### ISSUE TITLE
Memory block wrong used percentage

### ISSUE THREAD

**Issue by greshake** [greshake/i3status-rust#10]
The metric used to calculate memory used may be inaccurate/ non- intuitive. Htop shows 25% memory used, while the memory block shows 53%.

**Comment by jheyens** [comment]
It has not been "wrong", but https://github.com/greshake/i3status-rust/commit/b849e72c00d76250ade8194d133d9d9c82011b2d includes `{Mug},{Mum},{Mup}` values, mirroring htop's behaviour.
