### ISSUE TITLE
TOML can't be parsed

### ISSUE THREAD

**Issue by bigDaddyS1oth** [greshake/i3status-rust#100]
I'm not exactly sure what I'm doing wrong here, but I can't get i3 with i3status-rust to work for some reason.

Here's the error:

```

    {"version": 1, "click_events": true}
    [[{"background":"#000000","color":"#dc322f","full_text":" Configuration error: failed to parse TOML from file contents ","separator":false,"separator_block_width":0}]

    Configuration error: failed to parse TOML from file contents.
    Cause: failed to parse datetime for key `block.device`

```

[Here's](https://pastebin.com/sbEUBKSp) the status.toml file I have.

[Here's](https://pastebin.com/EbK6DgJV) my i3 config file.

**Comment by anthonynguyen** [comment]
On line 26, your `BAT1` should be in quotes

**Comment by bigDaddyS1oth** [comment]
God. Dammit.
