### ISSUE TITLE
sound: could not get sound info

### ISSUE THREAD

**Issue by CyanoKobalamyne** [greshake/i3status-rust#1003]
Starting today, I get an error message: `Error in block 'sound': could not get sound info`. I'm using the ALSA driver (`driver = "alsa"`) on Arch and have `alsa-utils` installed. The only relevant thing I can think about is that `libpulse` was updated from 14.1-1 to 14.1-2, but since I'm using ALSA, that shouldn't have had an effect. Oh, also, the kernel was updated from 5.10.6 to 5.10.7.

**Comment by ammgws** [comment]
Testing on the same updated Arch with the below config works for me:
```toml
[[block]]
block = "sound"
driver = "alsa"
```
All it's doing is calling `amixer -D default get Master`, so perhaps there is a problem with the output of that on your system. Can you check?

**Comment by CyanoKobalamyne** [comment]
Ah, sorry, it seems that another running app messed up my ALSA configuration and there was no default card.
