### ISSUE TITLE
Pacman Block: Add "on_click" option

### ISSUE THREAD

**Issue by boi4** [greshake/i3status-rust#1012]
Hello i3status-rust developers,
I'm a big fan of the status bar and wondered whether it was possible to add an `on_click` option to some more blocks (especially the `pacman` block).
A cool use-case would be something like this:
```
on_click: i3-sensible-terminal -e "sudo pacman -Syu"
```

to run the update command in a new terminal window when clicking on the status bar icon/text.

Cheers
Jan

**Comment by ram02z** [comment]
@boi4 Pull request #1006 just got merged. Implements on_click on all blocks. Thanks to @edwin0cheng and @ammgws  !

**Comment by ram02z** [comment]
Hmm actually after testing with the apt block, it seems that the on_click property doesn't work. It probably has got to do with the fact that the apt block has its own on_click functionality; updates its db. I think the same can be for the pacman block.

**Comment by edwin0cheng** [comment]
I forget to change the Widget name of some blocks such that the `base_block` missed some event, #1013 should fix it.
