### ISSUE TITLE
Sigma character in output

### ISSUE THREAD

**Issue by bkayes** [greshake/i3status-rust#1014]
```
# i3status-rs --version
i3status-rs 0.14.3 (commit 7a71a37 2021-01-26)
```

Here is a screenshot of the issue:
![i3bug](https://user-images.githubusercontent.com/34326788/106369871-ff685e80-6322-11eb-8221-1c30eb34c439.png)

I have verified that powerline fonts are properly installed as was mentioned in #255 and am using the default `config.toml` and default `bar {}` command

**Comment by bkayes** [comment]
```
# sudo apt-get install fonts-powerline
Reading package lists... Done
Building dependency tree       
Reading state information... Done
fonts-powerline is already the newest version (2.7-3).
```

**Comment by GladOSkar** [comment]
Did you also set one of the powerline capable fonts as your i3bar font?

**Comment by bkayes** [comment]
Yes, I used the default `bar {}` command - so it uses the following font:
````
    font pango:DejaVu Sans Mono, FontAwesome 12
```

**Comment by GladOSkar** [comment]
I'm not entirely sure but I think the Fontawesome version of a font does not necessarily include the Powerline characters. What you need is either just the Powerline font or, ideally, the [Nerd Font Version](https://www.nerdfonts.com/font-downloads) which includes almost all special icon sets (including FontAwesome, Powerline, and a bunch more.

**Comment by ammgws** [comment]
In any case all `i3status-rust` does is output JSON which is rendered by i3bar. Since we haven't changed any of our icons recently I strongly suspect GladOSkar is on the right track. I will close this issue but feel free to continue discussion.
