### ISSUE TITLE
networkmanager: When connected to VPN, wifi shows twice

### ISSUE THREAD

**Issue by xkonni** [greshake/i3status-rust#1016]
Hey everyone!

Just a slight issue I've experienced with the `networkmanager` block.
When connected to my wifi it looks like this:
![image](https://user-images.githubusercontent.com/218331/106855728-b5ce9980-66bd-11eb-9e62-5c40d866cca8.png)

However when I connect to a VPN, it shows the wifi status twice:
![image](https://user-images.githubusercontent.com/218331/106855845-e6163800-66bd-11eb-8531-f91b3d18d091.png)

I would rather think 1x wifi + 1x vpn should be sufficient, but maybe it's working as intended? 

Thank you for your time!

**Comment by ammgws** [comment]
Hmm, does it show up twice on DBus as well?

**Comment by xkonni** [comment]
Good question. My dbus experience is rather limited, trying to figure it out with this guide: http://cheesehead-techblog.blogspot.com/2012/09/dbus-tutorial-fun-with-network-manager.html

###when not connected to vpn

Active connections

```
$ dbus-send --system --print-reply --dest=org.freedesktop.NetworkManager /org/freedesktop/NetworkManager org.freedesktop.DBus.Properties.Get string:"org.freedesktop.NetworkManager" string:"ActiveConnections"
method return time=1612618162.825471 sender=:1.2 -> destination=:1.506 serial=23161 reply_serial=2
   variant       array [
         object path "/org/freedesktop/NetworkManager/ActiveConnection/10"
      ]
```

APNs
```
$ dbus-send --system --print-reply --dest=org.freedesktop.NetworkManager /org/freedesktop/NetworkManager/ActiveConnection/10 org.freedesktop.DBus.Properties.Get string:"org.freedesktop.NetworkManager.Connection.Active" string:"SpecificObject"
method return time=1612618447.422419 sender=:1.2 -> destination=:1.515 serial=23264 reply_serial=2
   variant       object path "/org/freedesktop/NetworkManager/AccessPoint/230"
```

APN name
```
$ dbus-send --system --print-reply --dest=org.freedesktop.NetworkManager /org/freedesktop/NetworkManager/AccessPoint/230 org.freedesktop.DBus.Properties.Get string:"org.freedesktop.NetworkManager.AccessPoint" string:"Ssid"
method return time=1612618535.957202 sender=:1.2 -> destination=:1.517 serial=23288 reply_serial=2
   variant       array of bytes "omnomnom"
```

### when connected to VPN

Active Connections

```
$ dbus-send --system --print-reply --dest=org.freedesktop.NetworkManager /org/freedesktop/NetworkManager org.freedesktop.DBus.Properties.Get string:"org.freedesktop.NetworkManager" string:"ActiveConnections"
method return time=1612618645.935493 sender=:1.2 -> destination=:1.524 serial=23729 reply_serial=2
   variant       array [
         object path "/org/freedesktop/NetworkManager/ActiveConnection/14"
         object path "/org/freedesktop/NetworkManager/ActiveConnection/13"
         object path "/org/freedesktop/NetworkManager/ActiveConnection/10"
      ]
```

APNs

```
$ for i in 10 13 14; do dbus-send --system --print-reply --dest=org.freedesktop.NetworkManager /org/freedesktop/NetworkManager/ActiveConnection/$i org.freedesktop.DBus.Properties.Get string:"org.freedesktop.NetworkManager.Connection.Active" string:"SpecificObject"; done
method return time=1612618721.525636 sender=:1.2 -> destination=:1.525 serial=23768 reply_serial=2
   variant       object path "/org/freedesktop/NetworkManager/AccessPoint/230"
method return time=1612618721.533609 sender=:1.2 -> destination=:1.526 serial=23769 reply_serial=2
   variant       object path "/org/freedesktop/NetworkManager/ActiveConnection/10"
method return time=1612618721.541261 sender=:1.2 -> destination=:1.527 serial=23770 reply_serial=2
   variant       object path "/"
```

APN name

```
$ for i in 10 230; do dbus-send --system --print-reply --dest=org.freedesktop.NetworkManager /org/freedesktop/NetworkManager/AccessPoint/230 org.freedesktop.DBus.Properties.Get string:"org.freedesktop.NetworkManager.AccessPoint" string:"Ssid"; done
method return time=1612618813.292882 sender=:1.2 -> destination=:1.528 serial=23807 reply_serial=2
   variant       array of bytes "omnomnom"
method return time=1612618813.300643 sender=:1.2 -> destination=:1.529 serial=23808 reply_serial=2
   variant       array of bytes "omnomnom"
```

So apparently, yes. Even though ActiveConnection/10 technically is not an APN, it does show the SSID.

**Comment by ammgws** [comment]
Hmm, not sure what we can do about it...

**Comment by xkonni** [comment]
they are different in the VPN case, one being an AccessPoint (230), the other an ActiveConnection (10). In the no-vpn-case it's an AccessPoint. Are there any cases where the ssid of an ActiveConnection should be shown?

**Comment by ammgws** [comment]
OK I think I understand what you mean: if SSID is only relevant for AccessPoint then we could solve this issue by ignoring it for ActiveConnections. If that is always true then it might be worth a shot?

Something else that might be worth checking out: is DeviceType mentioned anywhere?
You should be able to use something like `d-feet` to browse the tree easily.

**Comment by xkonni** [comment]
Right, that's what I meant. Can't be sure if it's needed for other connections though.
`d-feet` is rather helpful, thanks!

About the DeviceType, no, but there is Type. 

### Wifi connection:

![image](https://user-images.githubusercontent.com/218331/107221508-06bef480-6a14-11eb-9631-773b60426bff.png)

### VPN connection

![image](https://user-images.githubusercontent.com/218331/107221614-281fe080-6a14-11eb-9084-04cd31cd41ac.png)

### TUN connection

![image](https://user-images.githubusercontent.com/218331/107221724-4ab1f980-6a14-11eb-9932-0b74b5ae48f0.png)

**Comment by xkonni** [comment]
fixed in https://github.com/greshake/i3status-rust/pull/1099
