### ISSUE TITLE
cpu: per-core frequency

### ISSUE THREAD

**Issue by MaxVerevkin** [greshake/i3status-rust#1029]
At the moment it is not possible to show per-core frequency, even though documentation clearly has it:
> Display CPU frequencies and utilization per core.

This behavior was introduced in #688 as an attempt to solve incorrect *default* formatting. What I can see from this, is that no one actually use this feature if it was broken for almost a year.

Now, is it reasonable to try to fix it or just remove this feature and simplify the code?

**Comment by ammgws** [comment]
By remove do you mean update the docs? If so then I don't see why not.

**Comment by MaxVerevkin** [comment]
@ammgws I mean both from the docs and from the code. Update the docs to say: "per-core mode shows only utilization and cannot be customized". It totally describes the current situation, although it feels like a regression.
