### ISSUE TITLE
Any way to trigger the intervals early?

### ISSUE THREAD

**Issue by seqizz** [greshake/i3status-rust#1030]
Hi there :wave: 

First of all, thanks for this tool.

I'd like to show the current layout on status line and have the block set up.

My question is: It'd be a bit resource-consuming if I set the interval low (e.g. 1). Instead, is it possible to send a signal like HUP or USR1 to ping the application to reset the timers (and thus refresh the commands)?

Sorry if I've missed something obvious, couldn't find an easy way.

**Comment by GladOSkar** [comment]
Not sure if this is documented anywhere, but
```sh
pkill -SIGUSR1 i3status-rs
```
should immediately reload the bar (which is barely worse than updating a single block performance wise).

For `custom` blocks, you can also use a toml parameter like `signal = 4` and then use something like
```sh
pkill -SIGRTMIN+4 i3status-rs
```
to update a single block.

**Comment by ammgws** [comment]
Need to find somewhere to document that...

**Comment by seqizz** [comment]
Ah, I was confused a bit, but apparently my version was just old (0.14.1).

Since documentation is also [in place](https://github.com/greshake/i3status-rust/blob/master/blocks.md#custom) now, I am closing this one. Thanks :+1:
