### ISSUE TITLE
Focus mode

### ISSUE THREAD

**Issue by aparcar** [greshake/i3status-rust#104]
I really like the indication of cpu/ram usage with changing colors, however if I read a text this sometimes becomes a bit of a annoyance. Could you add a temporary mode where the bar stops blinking and stays in two colors only?

**Comment by greshake** [comment]
You can simply configure the color scheme yourself, or do some hotkey bindings in your i3 config that reload i3/bar with a new color scheme.

**Comment by greshake** [comment]
See https://github.com/greshake/i3status-rust/wiki/Theming-&-Icons
