### ISSUE TITLE
Blocks have some strange "lines?"

### ISSUE THREAD

**Issue by MSS00** [greshake/i3status-rust#1046]
No any other themes were applied.
https://imgur.com/ugyowpZ

**Comment by GladOSkar** [comment]
That looks like an issue with your font rendering and is nothing this Project can do anything about. Unfortunately happens some times. A bunch of people had success with fiddling with the fonts and font size though, so you could try that

**Comment by MSS00** [comment]
Thanks for help! Solved by setting font Source Code Pro 8
