### ISSUE TITLE
JSON parse error

### ISSUE THREAD

**Issue by crozbo** [greshake/i3status-rust#1047]
In 0.14.4 i got this message in my bar:
Error: Could not parse JSON (parse error: integer overflow)

Blocks which i use are:
`
[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "disk_space"
path = "/home/xyz"
alias = "~"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mug}GiB/{MAg}GiB"
format_swap = "{SUg}Gib/{SFg}GiB"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "temperature"
collapsed = false
interval = 10
format = "{min}° min, {max}° max, {average}° avg"

[[block]]
block = "nvidia_gpu"
show_clocks = true

[[block]]
block = "music"
player = "vlc"
buttons = ["play", "next"]

[[block]]
block = "sound"

[[block]]
block = "kdeconnect"
device_id = "42997e7a33960711"

[[block]]
block = "uptime"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"
`

**Comment by ammgws** [comment]
From a quick look the only block in there using json is the temperature block. Can you try with just that block? Does `sensors -j` return an error on your system?

**Comment by crozbo** [comment]
`sensors -j` work normally and return valid json

I try only temperature block and it worked.

I am on arch linux and I build package for myself from git, before 0.14.4 i am on 0.14.3 with most of the newest commits before 0.14.4 and everything work, so I think something happen in last couple of commits before 0.14.4

**Comment by ammgws** [comment]
How reproducible is it?

**Comment by MaxVerevkin** [comment]
Can you start with an empty config and add blocks one by one to find which one causes the error?

**Comment by crozbo** [comment]
@MaxVerevkin I do that.

The problem is there when I use nvida_gpu or music block (player=vlc). Other block works.

**Comment by MaxVerevkin** [comment]
Does the error shows immediately or after some time? Or maybe after a click on the bar?

**Comment by crozbo** [comment]
the error is immediately after i reload config

**Comment by MaxVerevkin** [comment]
Hmm, unfortunately I could not reproduce it. @ammgws can you?

**Comment by ammgws** [comment]
@crozbo Do you get more info if you run i3status-rust from a terminal? Like this: `RUST_BACKTRACE=full i3status-rs`

**Comment by crozbo** [comment]
@ammgws 
I try that only with music block and i get this:
1{"version": 1, "click_events": true}
[[{"background":null,"color":"#88c0d0","full_text":"","markup":"pango","separator":false,"separator_block_width":0},{"background":"#88c0d0","color":"#3b4252","full_text":"  ","markup":"pango","name":18446744073709551612,"separator":false,"separator_block_width":0}],`
I dont understand does this big number under "name" cause problem?

**Comment by ammgws** [comment]
Ohhhh this might be crashing i3/swaybar itself!

**Comment by crozbo** [comment]
and similar big number is under "name" with nvidia-gpu block

**Comment by ammgws** [comment]
Those are blocks using widgets which get assigned those large IDs so that makes sense.

**Comment by MaxVerevkin** [comment]
This big number should be `usize::MAX`. Maybe its trying to parse to signed integer?

**Comment by ammgws** [comment]
https://github.com/i3/i3/blob/9c7616cc98d27b8f3ea86c93f41699e4fd809b06/i3bar/src/child.c#L262

**Comment by MaxVerevkin** [comment]
@crozbo Do you use sway or i3?

**Comment by crozbo** [comment]
@ammgws I use i3-gaps

**Comment by MaxVerevkin** [comment]
Oh, I didn't test those IDs on i3(-gaps)

**Comment by MaxVerevkin** [comment]
Can you check if this change fixes the issue?
```diff
diff --git a/src/util.rs b/src/util.rs
index f40b930..22c1f66 100644
--- a/src/util.rs
+++ b/src/util.rs
@@ -20,7 +20,7 @@ use crate::errors::*;
 pub const USR_SHARE_PATH: &str = "/usr/share/i3status-rust";

 pub fn pseudo_uuid() -> usize {
-    static ID: AtomicUsize = AtomicUsize::new(usize::MAX);
+    static ID: AtomicUsize = AtomicUsize::new(isize::MAX as usize);
     ID.fetch_sub(1, Ordering::SeqCst)
 }
```

**Comment by ammgws** [comment]
Actually, why is our JSON output for `name` going out as an int instead of string?

**Comment by crozbo** [comment]
I don't know, that is what I get.

**Comment by MaxVerevkin** [comment]
Because id is usize:
```rust
"name": self.id,
```

**Comment by ammgws** [comment]
Yeah but we can't we just cast to string when rendering the JSON?

**Comment by MaxVerevkin** [comment]
Yeah, we can. Maybe that's the best way to do it.

**Comment by crozbo** [comment]
I hope my help is enough for solving this issue. I will check for new commits and make new build to check if problem is resolved. Until then I will not use problematic blocks.

**Comment by MaxVerevkin** [comment]
Did that work out?

**Comment by crozbo** [comment]
I build and issue is resolved.
