### ISSUE TITLE
Integer overflow in GPU Memory block

### ISSUE THREAD

**Issue by alcidesmig** [greshake/i3status-rust#1057]
```
[[block]]
block = "nvidia_gpu"
label = "GPU"
show_memory = true
show_clocks = false
interval = 5
```
Using ```show_memory = true``` I have as part of the output in terminal: `{"background":"#002b36","color":"#93a1a1","full_text":"193MB ","markup":"pango","name":18446744073709551615,"separator":false,"separator_block_width":0}`

In bar, otherwise, I got the message: `Errors: could not parse JSON (parse error: Integer overflow)`. What is probably referencing to `18446744073709551615`. With `show_memory = false` I got no errors.

**Comment by ammgws** [comment]
Sounds like #1047, #1052

Are you on 0.14.5 and above?

**Comment by alcidesmig** [comment]
Yes, I saw these issues after creating here, sorry.
Current package: `i3status-rust-0.14.4-1`
