### ISSUE TITLE
Sound block should open pavucontrol on left click.

### ISSUE THREAD

**Issue by that1communist** [greshake/i3status-rust#106]
Or make click actions configurable without recompiling.

**Comment by greshake** [comment]
Good idea. Maybe you can open a PR? I'm short on time for new features

**Comment by that1communist** [comment]
I don't really know anything about how that works. I'm sorry I can't be of more help, could you point me in the right direction?

**Comment by greshake** [comment]
Sure. Basically, you need to do the following to add a click handler/ application launch feature to block X:
1. Add a new configuration option for the application to launch (best provide some useful default)
2. Handle the Left Mouse click event in the click handler of block X and launch the program

**Comment by greshake** [comment]
If you're looking for examples, the custom block allows you to execute a command on left-click

**Comment by OneMoreByte** [comment]
Hey, can I try implementing this? I've been wanting to help the project out..

**Comment by greshake** [comment]
Sure, go ahead!

**Comment by atheriel** [comment]
Closed by #128.
