### ISSUE TITLE
 i3status-rust 0.14.6 does not compile on 32-bit architectures

### ISSUE THREAD

**Issue by mpolanski** [greshake/i3status-rust#1062]
Hello,
looks like the new version cannot compile on 32-bit architectures:
```
error: literal out of range for `usize`
   --> src/main.rs:113:64
    |
113 |         let error_widget = TextWidget::new(Default::default(), 9999999999)
    |                                                                ^^^^^^^^^^
    |
    = note: `#[deny(overflowing_literals)]` on by default
    = note: the literal `9999999999` does not fit into the type `usize` whose range is `0..=4294967295`
error: aborting due to previous error
error: could not compile `i3status-rs`
```
Full pipeline output on [armv7](https://gitlab.alpinelinux.org/mpolanski/aports/-/jobs/322302) and [x86](https://gitlab.alpinelinux.org/mpolanski/aports/-/jobs/322298).

**Comment by MaxVerevkin** [comment]
This is fixed on master branch, not sure when a new release is going to be.

**Comment by mpolanski** [comment]
Could you point out which commit fixed it? I can patch it manually.

**Comment by MaxVerevkin** [comment]
You can just change `9999999999` to `0`, there were no special meaning in that number.

**Comment by mpolanski** [comment]
Thanks! It did the job.
