### ISSUE TITLE
net block: remove `clickable` option

### ISSUE THREAD

**Issue by ammgws** [greshake/i3status-rust#1078]
```md
`clickable` | Whether to allow clicking on the block and swithching between `format` and `format_alt` | No | `false`
`format_alt` | The same as `format`. Shows when the block is toggled with a mouse click (if `clickable` is `true`). | No | `"{ssid}"`
```

Instead of `clickable`, just see if `format_alt` was specified in the config. If it was, then the user obviously wants the block to be clickable. If there's really some reason for disabling click events then it can be done once https://github.com/greshake/i3status-rust/issues/1038 is implemented by setting the on-click action to empty and overriding the block on-click handler.

**Comment by MaxVerevkin** [comment]
This would mean user would not be able to set `format_alt=""` (which would hide the block on click just like temperature block).

**Comment by ammgws** [comment]
I assume you mean collapse not hide? Otherwise you wouldn't be able to get the block to show again :laughing:

**Comment by MaxVerevkin** [comment]
Yeah, right.
