### ISSUE TITLE
brightness block: icon order is backwards

### ISSUE THREAD

**Issue by hacmorgan** [greshake/i3status-rust#1081]
On full brightness, the icon shown is of a black moon, while on min brightness the icon is a full moon. I'm not sure if this is intentional, but it seems backwards to me. 

icon set: awesome
OS: Arch Linux 
i3status-rust version: i3status-rs 0.14.5 (commit 1e40e8f 2021-02-15)

The screenshots below are after I reversed the order of the icons, so this is what I think it **should** look like:
![image](https://user-images.githubusercontent.com/19177940/108568932-1d901000-735f-11eb-92df-832eae16ec36.png)
![image](https://user-images.githubusercontent.com/19177940/108569013-46b0a080-735f-11eb-884e-5fb183ae4e91.png)

**Comment by ammgws** [comment]
See #845

**Comment by ammgws** [comment]
Though perhaps since this keeps coming up, maybe an option to flip out would be good?

**Comment by hacmorgan** [comment]
Oh sorry, I didn't check past issues, that was dumb. I will try to implement an option to flip them, I think that would be cool.
