### ISSUE TITLE
material icon set renders invalid icons

### ISSUE THREAD

**Issue by kgilmer** [greshake/i3status-rust#1086]
## Environment:

Ubuntu 20.04

i3-gaps
```
$ i3 --version
i3 version 4.19 (2020-11-15) © 2009 Michael Stapelberg and contributors
```

i3status-rs
```
$ ~/bin/i3status-rs --version
i3status-rs 0.15.0 (commit 4318a37 2021-02-21)
```

Material font installed:
```
$ apt list --installed | grep material
fonts-materialdesignicons-webfont/focal,now 1.6.50-3regolith3 amd64 [installed]
```

i3status-rs config:
```
theme = "native"
icons = "material"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"
```

## Steps to reproduce:
1. build i3status-rs from source, install as directed on wiki.

Expected behavior: material icons show on bar
Actual behavior: 
![image](https://user-images.githubusercontent.com/49683/108644673-e0ae4100-7464-11eb-9a6e-da1d2dbcf288.png)

FWIW the FontAwesome icon setting does not produce the "unknown unicode" charaters but also doesn't seem to map to the intended glyphs.

## Other notes

```bash
$ fc-list | grep -i material
/usr/share/fonts/truetype/materialdesignicons-webfont/materialdesignicons-webfont.ttf: Material Design Icons:style=Regular
```

FWIW I believe that the mappings from character code to icon have changed in the material design icon font in version 1.6 of that package ([debian](https://packages.debian.org/sid/fonts/fonts-materialdesignicons-webfont)).

I checked [this issue](https://github.com/greshake/i3status-rust/issues/744) but nothing there resulted in working behavior on my system

**Comment by GladOSkar** [comment]
I don't think your `materialdesignicons` font is FontAwesome/NerdFont compatible? Have you tried a FontAwesome or NerdFont font?

**Comment by MaxVerevkin** [comment]
I tried both FontAwesome and NerdFont but I get the same result as the author. Also I checked `src/icons.rs` and some icons are just missing.

**Comment by GladOSkar** [comment]
Interesting. I'm using the `FuraCode Nerd Font` and both `awesome` and `material` icon sets work fine with the clock icon:

![image](https://user-images.githubusercontent.com/9497832/108739868-597cce00-7535-11eb-9cb0-f6d0b4e2a71a.png)

But you're right that some of the networking icons are missing then, but that's another issue.

**Comment by MaxVerevkin** [comment]
With this font config:
```
    font pango:FuraCode Nerd Font 10
```
I get this 
![image](https://user-images.githubusercontent.com/34583604/108743322-5b4c8e80-7541-11eb-900c-2a6095b8d34c.png)

I use void linux and I have `nerd-fonts-2.1.0_3` installed.

**Comment by GladOSkar** [comment]
Weird. I just downloaded the latest version from the [official source](https://github.com/ryanoasis/nerd-fonts/blob/master/patched-fonts/FiraCode/Regular/complete/Fira%20Code%20Regular%20Nerd%20Font%20Complete.ttf) (which has been renamed back to Fira i think) and that works:

![image](https://user-images.githubusercontent.com/9497832/108768362-dcaf1b80-7557-11eb-82f7-34ce8d293eb1.png)

**Comment by MaxVerevkin** [comment]
Have you done any modifications to `fontconfig`? it still doesn't work for me.
```
❯ fc-list | grep -i fira
/usr/share/fonts/TTF/Fira Code Regular Nerd Font Complete.ttf: FiraCode Nerd Font:style=Regular
```

**Comment by MaxVerevkin** [comment]
This override works
```
cpu = " <span size='large' stretch='ultraexpanded' font_family='NotoSans Nerd Font'>\uf9c4</span> "
```

**Comment by GladOSkar** [comment]
> Have you done any modifications to `fontconfig`? it still doesn't work for me.
> 
> ```
> ❯ fc-list | grep -i fira
> /usr/share/fonts/TTF/Fira Code Regular Nerd Font Complete.ttf: FiraCode Nerd Font:style=Regular
> ```

Nope, just dropped the file in `.fonts` and that's it:

```
% fc-list | grep -i fira
/home/oskar/.fonts/Fira Code Regular Nerd Font Complete.ttf: FiraCode Nerd Font:style=Regular
```

**Comment by MaxVerevkin** [comment]
In `src/icons.rs` we have
```rust
        "time" => " \u{e192} ",
```
But https://www.nerdfonts.com/cheat-sheet doesnt give me that icon when I search for "clock"

**Comment by MaxVerevkin** [comment]
In fact, https://www.nerdfonts.com/cheat-sheet also works as a reverse search, and it can't find anything for "e192"

**Comment by GladOSkar** [comment]
Yeah i just saw the same thing. Gotta say i'm stumped

**Comment by MaxVerevkin** [comment]
From #57:
> Note: This requires a patched version of MaterialIcons-Regular.ttf as offered by Google to include \u{0020} (space), set a descent and lower all glyphs to properly align.

**Comment by GladOSkar** [comment]
Oh darn it i just realized i *do* have a material icons font installed -.-
```
$ fc-list | grep Material   
/home/oskar/.fonts/MaterialIcons-Regular-for-inline.ttf: Material Icons:style=Regular
```

**Comment by MaxVerevkin** [comment]
So... Maybe we should have two separate material icons set?

**Comment by GladOSkar** [comment]
I don't know, does NerdFont actually include them? If not then the current implementation is probably correct.

I presume @kgilmer 's issue is still that it's not the _right_ material font on their system. As stated in the [theming & icons documentation](https://github.com/greshake/i3status-rust/blob/master/themes.md) the `material` icon set requires a sepcific patched font that is available [here](https://gist.github.com/draoncc/3c20d8d4262892ccd2e227eefeafa8ef/raw/3e6e12c213fba1ec28aaa26430c3606874754c30/MaterialIcons-Regular-for-inline.ttf).

**Comment by MaxVerevkin** [comment]
> does NerdFont actually include them?

Their [home page](https://www.nerdfonts.com/) says yes.

**Comment by GladOSkar** [comment]
Interesting. I guess if we want to make use of them then we'd need another mapping, yes

**Comment by MaxVerevkin** [comment]
> issue is still that it's not the right material font on their system

Yeah, the patched font works. Sort of. Instead of memory icon i have a stormy cloud. And yes, many icons are just missing. But that's the other issue. I would consider adding a new icon set for "the other material" icons.

**Comment by ammgws** [comment]
Hmm I never noticed we are dependent on some random gist for the material icons... I wonder how many people are actually using it. 

I don't understand the reason why the official font can't be used (vertical spacing issues??), but if there's no actual problem then I feel like we should use the official font by default.

**Comment by MaxVerevkin** [comment]
> I don't understand the reason why the official font can't be used (vertical spacing issues??)

There are some horizontal spacing issues. But there is a solution: wrap each icon into pango's `span` like this:
```toml
music = " <span size='medium' font_family='NotoSans Nerd Font'>\uf886</span> "
```
And I think this could be a global configuration option:
```toml
icons_style = "size='medium' font_family='NotoSans Nerd Font'"
```

**Comment by MaxVerevkin** [comment]
```toml
cpu = " \uf9c4 "
```
gives
![image](https://user-images.githubusercontent.com/34583604/108957625-7b339d80-767a-11eb-9c5f-605723645355.png)
```toml
cpu = " <span size='medium' font_family='NotoSans Nerd Font'>\uf9c4</span> "
```
gives
![image](https://user-images.githubusercontent.com/34583604/108957632-7ff85180-767a-11eb-9235-103bd96189ae.png)

**Comment by ammgws** [comment]
Looks similar to what was proposed in #981

**Comment by MaxVerevkin** [comment]
> Looks similar to what was proposed in #981

Yeah, I see, that's exactly the same.

**Comment by kgilmer** [comment]
I didn't expect such a lively discussion, but happy to see it!  :smile: 

I was not using Nerd Fonts @GladOSkar and so I tried doing that by performing the following steps:
1. install Code New Roman Nerd Font from the NerdFonts patched-fonts directory into `~/.fonts/CodeNewRoman/` directory.  (I wanted to use a font not already installed on my system to avoid any potential conflicts)
2. Update the font cache with `fc-cache -f -v`  (also did w/ sudo mistakenly)
3. Verify the font name and installation with `fc-match`:
```
~$ fc-match "Code New Roman Nerd Font"
Code New Roman Nerd Font Complete.otf: "CodeNewRoman Nerd Font" "Book"
```
4. Update the font specification in my i3-gaps config file:
```
font  pango:DejaVu Sans Mono 13, Code New Roman Nerd Font 13
```
5. Reload i3 (then re-login after that didn't work)

Result: 
![image](https://user-images.githubusercontent.com/49683/109107792-3d209300-76e7-11eb-9ba0-8803d2b7f148.png)

Is there something I've missed or bungled here?  Any other tips or troubleshooting suggestions?

### Additional Info

```
$ fc-list | grep -i CodeNew
/home/kgilmer/.fonts/CodeNewRoman/Bold/complete/Code New Roman Bold Nerd Font Complete Mono Windows Compatible.otf: CodeNewRoman NF:style=Bold
/home/kgilmer/.fonts/CodeNewRoman/Italic/complete/Code New Roman Italic Nerd Font Complete.otf: CodeNewRoman Nerd Font:style=Italic
/home/kgilmer/.fonts/CodeNewRoman/Regular/complete/Code New Roman Nerd Font Complete Mono Windows Compatible.otf: CodeNewRoman NF:style=Book
/home/kgilmer/.fonts/CodeNewRoman/Regular/complete/Code New Roman Nerd Font Complete Windows Compatible.otf: CodeNewRoman NF:style=Book
/home/kgilmer/.fonts/CodeNewRoman/Regular/complete/Code New Roman Nerd Font Complete.otf: CodeNewRoman Nerd Font:style=Book
/home/kgilmer/.fonts/CodeNewRoman/Regular/complete/Code New Roman Nerd Font Complete Mono.otf: CodeNewRoman Nerd Font Mono:style=Book
/home/kgilmer/.fonts/CodeNewRoman/Italic/complete/Code New Roman Italic Nerd Font Complete Mono.otf: CodeNewRoman Nerd Font Mono:style=Italic
/home/kgilmer/.fonts/CodeNewRoman/Italic/complete/Code New Roman Italic Nerd Font Complete Mono Windows Compatible.otf: CodeNewRoman NF:style=Italic
/home/kgilmer/.fonts/CodeNewRoman/Bold/complete/Code New Roman Bold Nerd Font Complete Mono.otf: CodeNewRoman Nerd Font Mono:style=Bold
/home/kgilmer/.fonts/CodeNewRoman/Bold/complete/Code New Roman Bold Nerd Font Complete.otf: CodeNewRoman Nerd Font:style=Bold
/home/kgilmer/.fonts/CodeNewRoman/Bold/complete/Code New Roman Bold Nerd Font Complete Windows Compatible.otf: CodeNewRoman NF:style=Bold
/home/kgilmer/.fonts/CodeNewRoman/Italic/complete/Code New Roman Italic Nerd Font Complete Windows Compatible.otf: CodeNewRoman NF:style=Italic
```

**Comment by MaxVerevkin** [comment]
@kgilmer You don't need Nerd Fonts to use `material` icon set, but you need a [specific font](https://gist.github.com/draoncc/3c20d8d4262892ccd2e227eefeafa8ef/raw/3e6e12c213fba1ec28aaa26430c3606874754c30/MaterialIcons-Regular-for-inline.ttf).

#1095 Adds a new material icon set that should work with any font form Nerd Fonts.

**Comment by ammgws** [comment]
So to summarise, our "material" icon setting is useless when using the official Google Material font or the aggregated Nerd Fonts, and only works with that random patched font that's only available in that gist?

"works" meaning the mappings point to the intended icons

**Comment by GladOSkar** [comment]
I think so, yes. I don't know if that random patched font was based on some official mapping that we don't know about though.

**Comment by ammgws** [comment]
I am leaning towards replacing it with the official Google Material font.

Looks like that PR was made around 2017 so can check if the mappings changed between then and now.

**Comment by GladOSkar** [comment]
I wonder how many people are sing that feature since it would break for all of them in that case of course

**Comment by ammgws** [comment]
Yes it would, perhaps it could be left as "material-legacy" or something, but having it as the "main" one seems wrong. Even more so if the official font has undergone changes and the patched one has been left untouched this whole time.

**Comment by ammgws** [comment]
OK this is getting confusing so I want to try make a comparison table (might take a while to complete).

Google Material Design icons
https://github.com/google/material-design-icons
https://aur.archlinux.org/packages/ttf-material-design-icons/

Material Design icons by MaterialDesignIcons.com (annoyingly they don't seem to mention Google anywhere)
https://github.com/Templarian/MaterialDesign
https://aur.archlinux.org/packages/ttf-material-design-icons-extended/

Nerd Fonts which includes MaterialDesignIcons.com, possibly patched but codepoints the same?
https://github.com/ryanoasis/nerd-fonts/blob/master/readme.md
https://aur.archlinux.org/packages/nerd-fonts-complete/

"Patched" icons from that gist
https://gist.github.com/draoncc/3c20d8d4262892ccd2e227eefeafa8ef/raw/3e6e12c213fba1ec28aaa26430c3606874754c30/MaterialIcons-Regular-for-inline.ttf
 
  Icon | Patched | Google | MaterialDesignIcons.com | NerdFonts
--- | --- | --- | --- | --- |
backlight_empty | `\u{e1a3}` | `` | `` | `\u{e38d}` (nf-weather-moon_new) |
backlight_full | `` | `` | `` | `` |
backlight_1 | `` | `` | `` | `` |
backlight_2 | `` | `` | `` | `` |
backlight_3 | `` | `` | `` | `` |
backlight_4 | `` | `` | `` | `` |
backlight_5 | `` | `` | `` | `` |
backlight_6 | `` | `` | `` | `` |
backlight_7 | `` | `` | `` | `` |
backlight_8 | `` | `` | `` | `` |
backlight_9 | `` | `` | `` | `` |
backlight_10 | `` | `` | `` | `` |
backlight_11 | `` | `` | `` | `` |
backlight_12 | `` | `` | `` | `` |
backlight_13 | `` | `` | `` | `` |
bat | `` | `` | `` | `` |
bat_charging | `\u{e1a3}` | `` | `` | `\u{f57d}` |
bat_discharging | `` | `` | `` | `` |
bat_empty | `` | `` | `` | `` |
bat_full | `` | `` | `` | `` |
bat_half | `` | `` | `` | `` |
bat_not_available | `` | `` | `` | `` |
bat_quarter | `` | `` | `` | `` |
bat_three_quarters | `` | `` | `` | `` |
bell | `` | `` | `` | `` |
bell-slash | `` | `` | `` | `` |
bluetooth | `` | `` | `` | `` |
calendar | `` | `` | `` | `` |
cogs | `` | `` | `` | `` |
cpu | `` | `` | `` | `` |
disk_drive | `` | `` | `` | `` |
docker | `` | `` | `` | `` |
github | `` | `` | `` | `` |
gpu | `` | `` | `` | `` |
headphones | `` | `` | `` | `` |
joystick | `` | `` | `` | `` |
keyboard | `` | `` | `` | `` |
mail | `` | `` | `` | `` |
memory_mem | `` | `` | `` | `` |
memory_swap | `` | `` | `` | `` |
mouse | `` | `` | `` | `` |
music | `` | `` | `` | `` |
music_next | `` | `` | `` | `` |
music_pause | `` | `` | `` | `` |
music_play | `` | `` | `` | `` |
music_prev | `` | `` | `` | `` |
net_down | `` | `` | `` | `` |
net_loopback | `` | `` | `` | `` |
net_up | `` | `` | `` | `` |
net_vpn | `` | `` | `` | `` |
net_wired | `` | `` | `` | `` |
net_wireless | `` | `` | `` | `` |
notification | `` | `` | `` | `` |
phone | `` | `` | `` | `` |
phone_disconnected | `` | `` | `` | `` |
ping | `` | `` | `` | `` |
pomodoro | `` | `` | `` | `` |
resolution | `` | `` | `` | `` |
tasks | `` | `` | `` | `` |
thermometer | `` | `` | `` | `` |
time | `` | `` | `` | `` |
toggle_off | `` | `` | `` | `` |
toggle_on | `` | `` | `` | `` |
update | `` | `` | `` | `` |
uptime | `` | `` | `` | `` |
volume_empty | `` | `` | `` | `` |
volume_full | `` | `` | `` | `` |
volume_half | `` | `` | `` | `` |
volume_muted | `` | `` | `` | `` |
microphone_empty | `` | `` | `` | `` |
microphone_full | `` | `` | `` | `` |
microphone_half | `` | `` | `` | `` |
microphone_muted | `` | `` | `` | `` |
weather_clouds | `` | `` | `` | `` |
weather_default | `` | `` | `` | `` |
weather_rain | `` | `` | `` | `` |
weather_snow | `` | `` | `` | `` |
weather_sun | `` | `` | `` | `` |
weather_thunder | `` | `` | `` | `` |
xrandr | `` | `` | `` | `` |

**Comment by kgilmer** [comment]
I was able to resolve the issue with your help, thank you!

![image](https://user-images.githubusercontent.com/49683/109377223-c6b69900-787e-11eb-8b6b-397bfbf728b7.png)

I am using the JetBrains Mono font from NerdFonts.  I see that the icons are smaller than the text, is this expected?  From screenshots in the readme, I can see the fontawesome-based screenshots appear to have icon and text at roughly the same size...

In any case, thanks again and I won't close the issue as looks like there is work going on in here but you can consider my issue resolved.

**Comment by GladOSkar** [comment]
@kgilmer that might just be an issue with the jetbrains font. There are a bunch of issues about stuff like that here, like #238. Maybe one of them has something that works for you.

**Comment by MaxVerevkin** [comment]
@kgilmer You can try to add this in your config:
```toml
icons_format = " <span size='large'>{icon}</span> "
```

**Comment by ammgws** [comment]
So it turns out the codepoints we have for the `material` icon are the same for the "patched" font from the gist and the current Google Material font.

As for MDI, the codepoints are different to aggregated Nerd Fonts one. I mapped most of them int he table above, so if someone wants to add `materials_mdi` to go alongside `material_nf` then it could be used as a reference.
