### ISSUE TITLE
Latest `master` produces JSON error

### ISSUE THREAD

**Issue by GladOSkar** [greshake/i3status-rust#1089]
`rustc` says:
```
rustc 1.52.0-nightly (a15f484b9 2021-02-22)
```

`i3bar` says:
![image](https://user-images.githubusercontent.com/9497832/108836235-e5900380-75d0-11eb-8ae7-504ad6f57af8.png)

`i3status-rs` says:
```
% i3status-rs ~/.config/i3/status-rs-config.toml 
{"version": 1, "click_events": true}
[[{"full_text":"  Tue 2021-02-23 12:13 ","name":"0","instance":"0","markup":"pango",}],
```

Note the trailing comma in the object. That's not allowed in JSON.

**Comment by MaxVerevkin** [comment]
Hmm, it works fine with sway, Are you using `i3(-gaps)`?

**Comment by MaxVerevkin** [comment]
Hmm, it works fine with sway, Are you using `i3(-gaps)`?

**Comment by GladOSkar** [comment]
Regular `i3`, yep

**Comment by MaxVerevkin** [comment]
Does #1090 work?

**Comment by GladOSkar** [comment]
Yes that works. Thanks!
