### ISSUE TITLE
JSON Error after 10-50 minutes

### ISSUE THREAD

**Issue by GladOSkar** [greshake/i3status-rust#1091]
Another JSON Error:
![image](https://user-images.githubusercontent.com/9497832/108845441-ba5fe100-75dd-11eb-82c2-23fbf038508b.png)

Although for this one i have no idea how to debug it. It appeared twice, once 10 minutes after restart and once roughly 50 minutes after restart. No idea what triggers it.

**Comment by ammgws** [comment]
You could try `tee`ing the output to a file so you can check the JSON output at that time

**Comment by GladOSkar** [comment]
That's what i'm currently doing :+1:

**Comment by GladOSkar** [comment]
Now it hasn't happened for 2 hours. Still logging...

**Comment by GladOSkar** [comment]
I found the issue!

Quotes in text widgets aren't escaped properly anymore:
```json
{"full_text":"🎉 [Name] just shared: "LIVE" - [more text]","color":"#ffffff", ...}
```

The error occurred when i just opened an email in gmail that had quotes in its subject, which updated the window title and hence my `focused_window` block. That also explains the irregularity of the occurences

**Comment by MaxVerevkin** [comment]
Weird. This should be fixed with #1088.

**Comment by MaxVerevkin** [comment]
If you intentionally make a mistake in theme name in your config file, will the error message showed correctly?

**Comment by GladOSkar** [comment]
Ah darn it i was still on your `i3block_data_fix` branch from earlier which didn't have #1088... now I'm back on master and it works -.-
