### ISSUE TITLE
backlight block: add option to reverse icons for users using colour emojis

### ISSUE THREAD

**Issue by ammgws** [greshake/i3status-rust#1096]
This has come up time and time again:

https://github.com/greshake/i3status-rust/issues/183
https://github.com/greshake/i3status-rust/pull/452
https://github.com/greshake/i3status-rust/pull/573
https://github.com/greshake/i3status-rust/issues/845
https://github.com/greshake/i3status-rust/issues/1081

Although one could override the icons manually, given how often this comes up we might as well add an option to reverse the icons (with an explanation of why/when you would use it).

**Comment by MaxVerevkin** [comment]
Given that the implementation would be as trivial as
```diff
diff --git a/src/blocks/backlight.rs b/src/blocks/backlight.rs
index 4cadb2b..a3194f1 100644
--- a/src/blocks/backlight.rs
+++ b/src/blocks/backlight.rs
@@ -286,6 +286,9 @@ impl ConfigBlock for Backlight {
 impl Block for Backlight {
     fn update(&mut self) -> Result<Option<Update>> {
         let brightness = self.device.brightness()?;
+        if self.invert_icons {
+            brightness = 100 - brightness;
+        }
         self.output.set_text(format!("{}%", brightness));
         match brightness {
             0..=19 => self.output.set_icon("backlight_empty"),
```
a simple config option is not a bad idea.

**Comment by MaxVerevkin** [comment]
@ammgws By the way, what does "good first issue" label mean?

**Comment by GladOSkar** [comment]
It means if someone's new to the project or even new to rust this is an easy task for them to get started/involved/some experience.

**Comment by ammgws** [comment]
Meaning it could be trivially implemented by someone looking to make their first open source contribution. You can ignore the tag if you were planning on submitting a PR.
