### ISSUE TITLE
Memory block doesn't filter click events

### ISSUE THREAD

**Issue by greshake** [greshake/i3status-rust#11]
The click function is called on **every** click on any block. The memory module needs to assign a name/id to the displaying widget and match on that id when the event comes in. Otherwise, it doesn't matter where you click and the memory block switches states.

**Comment by robojeb** [comment]
I didn't know if I should file another issue but it looks like the Memory block also remains clickable even if you specify that clickable should be false.

**Comment by XYunknown** [comment]
@jheyens promised to fix the memory block today, I'll ensure the clickable thing is fixed too

**Comment by jheyens** [comment]
Fixed in https://github.com/greshake/i3status-rust/commit/b849e72c00d76250ade8194d133d9d9c82011b2d
