### ISSUE TITLE
Make `maildir` an optional dependency 

### ISSUE THREAD

**Issue by MaxVerevkin** [greshake/i3status-rust#1101]
`maildir` is used in maildir block only. Why not make it an optional dependency like `pulseaudio` and `notmuch`?

**Comment by ammgws** [comment]
How many dependencies will it reduce for a standard build?

**Comment by MaxVerevkin** [comment]
> How many dependencies will it reduce for a standard build?

`11`: from `134` to `123`

**Comment by ammgws** [comment]
Seems reasonable to put it behind a feature flag
