### ISSUE TITLE
Clock should refresh based on cron-like system.

### ISSUE THREAD

**Issue by Kommynct** [greshake/i3status-rust#111]
This would prevent poor timing, and it could possibly even allow the removal of the interval entirely.

sleep 60 whole true, sounds like it can resolve this, except that'd be problematic for seconds.

Maybe make the interval work on sleep whole true?

Maybe it already works like this and i'm actually dumb as hell. Thank you for your time, sorry if this is a waste of it, its just always bugged me that i have to set an interval for my clock, which reduces battery life inherently.

The same as all of the above can go with the battery. Best solution there i think is to use udev rules if the computer emits low battery ACPI events (i think this could be used for polling % but I could very easily be wrong, and even if it can be used for that, there's no guarantee that everyone has this, so, it might just be a bad idea.) 

Polling just seems like it's bad, but I could very well be wrong, i don't have the numbers infront of me.

**Comment by that1communist** [comment]
Okay, my issue with the clock interval in its most simple form is this

say the statusbar loads one second before a minute change, it will then be a minute early indefinitely.

Unless I misunderstand, is that not the behavior? If so, it should be attached to a cronjob which will adjust the load time.

If i'm wrong thats totally cool, if not, I have a cronjob thing that might be able to fix this.

**Comment by greshake** [comment]
1. Yes you are correct. While I have a system in place that mitigates clock skewing (an effect that would desynchronize multiple blocks updating in the same second with different update times) there is always a possibility of the clock being behind <1m (if interval is set to 60s). I once had fixed this but the solution seemed unwieldy and unelegant, especially when weighed against the (imho) negligible benefits. If you need a more accurate time, I guarantee that setting the interval to 1s will have negligible impact on your battery life (the whole operation uses no I/O and just a couple CPU cycles- only 'costly' operation is rendering the update through i3bar, but chances are your bar already renders every couple seconds).

**Comment by that1communist** [comment]
could this easily be fixed by making it poll once, then start polling every 60 seconds when the clock reads 01 on the seconds?

I intend to actually learn rust sooner or later, if this is possible, i'll handle it later.

Thank you so much duder, you're a great dev.

**Comment by greshake** [comment]
2. The cron system is not suitable here. It would implicate additional IPC (inter process communication), context switches and leave no room for internal optimization or control over the event mechanics. 

Uhm, the easiest fix would be to simply time the first updates to directly follow a second change (as you kind of pointed out). The clock skewing mitigation should ensure that the updates stay aligned. However, there are a few caveats, which make this feature, as I mentioned, unwieldy and unelegant:
1. Custom blocks that perform network operations or I/O are very slow, and might skew the alignment.

While trying to write the rest of my argument, I think I found a solution that is completely encapsulated in the time block, elegant and easy. I'll make a commit soon. And thanks for the compliment :)

**Comment by that1communist** [comment]
Cool, good to hear. I'm trying to learn rust as we speak, I'd really appreciate it if you explained exactly what your solution is, I understand if you don't have the time/want to, though.

I should be able to actually contribute in a couple weeks.

**Comment by greshake** [comment]
My idea is just to have the time block readjust the first update interval to align with minute/second changes

**Comment by that1communist** [comment]
Oh, cool, have you considered wake from suspend/hibernate? I would think that all the blocks should probably be refreshed.

**Comment by atheriel** [comment]
This is unlikely to be implemented for the time being, so I'm going to close this issue for now.

**Comment by tetraxile** [comment]
would changing this line
https://github.com/greshake/i3status-rust/blob/93c4a48bd0a29ff0a155d2e3f5c96c07df34ea74/src/wrappers.rs#L27
to use `tokio::time::MissedTickBehavior::Skip` break other things? if not i think this could fix this issue, couldn't it? (maybe with another bit of code to set the interval time to be at the start of the minute)
