### ISSUE TITLE
Adding times music block

### ISSUE THREAD

**Issue by KoO-303** [greshake/i3status-rust#1120]
Would it be possible to add song elapsed & length to the music block.
{mpd_elapsed} / {mpd_length}

**Comment by ammgws** [comment]
See #1050

**Comment by KoO-303** [comment]
ammgws Thanks but i'm not sure how to use it.

**Comment by ammgws** [comment]
I meant that this issue has already been raised via that PR. I don't believe the PR is finished yet.

**Comment by KoO-303** [comment]
I understood sorry will lookout for an update. Thanks
