### ISSUE TITLE
Music block : hide_when_empty not working with player="spotify"

### ISSUE THREAD

**Issue by adaigre** [greshake/i3status-rust#1121]
I have the following music block :
```
[[block]]
block = "music"
player = "spotify"
format = "{player}"
dynamic_width = true
buttons = ["play", "next"]
on_click = "i3-msg \"[class=Spotify] focus\""
hide_when_empty = true
```
When Chromium is launched it is registered as MPRIS. I think that if `player = "spotify"`, only `org.mpris.MediaPlayer2.spotify` should match.

**Comment by ammgws** [comment]
What's the output of



busctl --user list | grep "org.mpris.MediaPlayer2." | cut -d' ' -f1

?

**Comment by adaigre** [comment]
When Spotify is closed I only have chromium registered like I said :
```
  ~ busctl --user list | grep "org.mpris.MediaPlayer2." | cut -d' ' -f1
org.mpris.MediaPlayer2.chromium.instance5544
```

But I would like to display that block only if Spotify is open.

**Comment by ammgws** [comment]
Hmm, that's strange. I assume the bug doesn't only affect spotify. Will need to check it out later

**Comment by ammgws** [comment]
I can't reproduce on either v0.14.7 or master, however I don't have spotify so I'm testing with mpv.

With this config:

```toml
[[block]]
block = "music"
player = "mpv"
```

Starting i3status-rust with  `mpd` and `firefox` already on the bus gives an empty block, and when `mpv` is opened and starts playing a file, the block updates accordingly and goes back to a empty block once it's closed.

Not sure why it would make a difference with spotify, but I can't download the package at the moment so I can't test it yet.

**Comment by ammgws** [comment]
OK so this had nothing to do with the actual player being used and was just a logic error in the view code
