### ISSUE TITLE
Custom theme gives error

### ISSUE THREAD

**Issue by viper0825** [greshake/i3status-rust#1122]
[[block]]
block = "cpu"
icons_format = "{icon}" # Remove spaces aroud icons for this block.
[block.theme_overrides]
idle_bg = "#123456"
idle_fg = "#abcdef"

When I use the above in the config I get an error in the i3bar stating that block.theme_overrides fails with a failed to deserialize block config.

**Comment by MaxVerevkin** [comment]
It works for me. What version of `i3status-rust` are you using?

**Comment by viper0825** [comment]
community/i3status-rust 0.14.7-1

**Comment by ammgws** [comment]
In 0.14.7 it was `color_overrides`. It will change to `theme_overrides` in the next release.

**Comment by viper0825** [comment]
Thank you, thaorks.
