### ISSUE TITLE
Custom Block Throws Error

### ISSUE THREAD

**Issue by viper0825** [greshake/i3status-rust#1123]
When I do a custom block it throws a parsing error.

[[block]]
block = "custom"
command = "uname -r"

Updated to the current version 0.20

**Comment by MaxVerevkin** [comment]
Version 0.20 is not released yet so I assume you are on the `master` brunch.

Can you share the output when you run `i3status-rust` from the terminal? I have no issues with this config.

**Comment by viper0825** [comment]
Output below, I figured out what it was after running from the terminal.  When the command block is called I have a script that is called in the shell.  I commented that out and it is now working properly.

Thanks,

[{"full_text":"","color":"#212121","separator":false,"separator_block_width":0,"markup":"pango"},{"full_text":"BlueMail","color":"#56b6c2","background":"#212121","name":"0","instance":"0","separator":false,"separator_block_width":0,"markup":"pango"},{"full_text":"","color":"#212121","background":"#212121","separator":false,"separator_block_width":0,"markup":"pango"},{"full_text":"  23m 27s ","color":"#c678dd","background":"#212121","name":"1","instance":"0","separator":false,"separator_block_width":0,"markup":"pango"},{"full_text":"","color":"#212121","background":"#212121","separator":false,"separator_block_width":0,"markup":"pango"},{"full_text":" six
 ▒▒▒▒ ▒▒   ▒▒▒▒ ▒▒   ▒▒▒▒ ▒▒   ▒▒▒▒ ▒▒   ▒▒▒▒ ▒▒   ▒▒▒▒ ▒▒ 
 ▒▒ ■ ▒▒   ▒▒ ■ ▒▒   ▒▒ ■ ▒▒   ▒▒ ■ ▒▒   ▒▒ ■ ▒▒   ▒▒ ■ ▒▒  
 ▒▒ ▒▒▒▒   ▒▒ ▒▒▒▒   ▒▒ ▒▒▒▒   ▒▒ ▒▒▒▒   ▒▒ ▒▒▒▒   ▒▒ ▒▒▒▒  
5.11.7-arch1-1 ","color":"#abcdef","background":"#212121","name":"2","instance":"0","separator":false,"separator_block_width":0,"markup":"pango"},{"full_text":"","color":"#212121","background":"#212121","separator":false,"separator_block_width":0,"markup":"pango"},{"full_text":"   269.14 ","color":"#61afef","background":"#212121","name":"3","instance":"0","separator":false,"separator_block_width":0,"markup":"pango"},{"full_text":"","color":"#212121","background":"#212121","separator":false,"separator_block_width":0,"markup":"pango"},{"full_text":"  13.4G ","color":"#e5c07b","background":"#212121","name":"4","instance":"0","separator":false,"separator_block_width":0,"markup":"pango"},{"full_text":"","color":"#212121","background":"#212121","separator":false,"separator_block_width":0,"markup":"pango"},{"full_text":"  04% ","color":"#98c379","background":"#212121","name":"5","instance":"0","separator":false,"separator_block_width":0,"markup":"pango"},{"full_text":"","color":"#212121","background":"#212121","separator":false,"separator_block_width":0,"markup":"pango"},{"full_text":"  30° ","color":"#e06c75","background":"#212121","name":"6","instance":"0","separator":false,"separator_block_width":0,"markup":"pango"},{"full_text":"","color":"#212121","background":"#212121","separator":false,"separator_block_width":0,"markup":"pango"},{"full_text":"  0.24 ","color":"#abb2bf","background":"#212121","name":"7","instance":"0","separator":false,"separator_block_width":0,"markup":"pango"},{"full_text":"","color":"#212121","background":"#212121","separator":false,"separator_block_width":0,"markup":"pango"},{"full_text":"    0.00KB   0.00KB ","color":"#56b6c2","background":"#212121","name":"8","instance":"0","separator":false,"separator_block_width":0,"markup":"pango"},{"full_text":"","color":"#212121","background":"#212121","separator":false,"separator_block_width":0,"markup":"pango"},{"full_text":"  ","color":"#c678dd","background":"#212121","name":"9","instance":"18446744073709551612","separator":false,"separator_block_width":0,"markup":"pango"},{"full_text":"","color":"#212121","background":"#212121","separator":false,"separator_block_width":0,"markup":"pango"},{"full_text":"  65% ","color":"#61afef","background":"#212121","name":"10","instance":"0","separator":false,"separator_block_width":0,"markup":"pango"},{"full_text":"","color":"#212121","background":"#212121","separator":false,"separator_block_width":0,"markup":"pango"},{"full_text":"  9 updates available ","color":"#e5c07b","background":"#212121","name":"11","instance":"0","separator":false,"separator_block_width":0,"markup":"pango"},{"full_text":"","color":"#212121","background":"#212121","separator":false,"separator_block_width":0,"markup":"pango"},{"full_text":"  \"Clear\" 36°, 16.1 m/s N ","color":"#98c379","background":"#212121","name":"12","instance":"0","separator":false,"separator_block_width":0,"markup":"pango"},{"full_text":"","color":"#212121","background":"#212121","separator":false,"separator_block_width":0,"markup":"pango"},{"full_text":"  Fri March 19 13:56 ","color":"#e06c75","background":"#212121","name":"13","instance":"0","separator":false,"separator_block_width":0,"markup":"pango"}]
