### ISSUE TITLE
Discussion: use rustdoc for blocks' documentation

### ISSUE THREAD

**Issue by MaxVerevkin** [greshake/i3status-rust#1127]
In-code documentation is just easier to maintain.

The question is whether it is actually convenient for users. Here is an example of documentation (time block): https://maxverevkin.github.io/i3status-rust/doc/i3status_rs/blocks/time/index.html

**Comment by MaxVerevkin** [comment]
Oh, wow. I forgot that github pages is a thing:
* [main page](https://maxverevkin.github.io/i3status-rust/)
* [docs](https://maxverevkin.github.io/i3status-rust/doc/i3status_rs/)
* [docs for backlight](https://maxverevkin.github.io/i3status-rust/doc/i3status_rs/blocks/backlight/index.html)

**Comment by MaxVerevkin** [comment]
Now the question is whether it is actually convenient for users. Here is an example of config (time block): https://maxverevkin.github.io/i3status-rust/doc/i3status_rs/blocks/time/index.html

**Comment by ammgws** [comment]
I like the idea of increasing maintainability but going with rustdoc it ends up being a bit overwhelming for standard users. Is there a rustdoc option to hide all the struct declarations and such?

**Comment by MaxVerevkin** [comment]
Unfortunately, I don't think there in an option to hide trait `impl`s (it is possible to hide struct declarations).

I can imagine that if there was an option to output markdown, it would be easy to make the documentation cleaner for users.

From https://github.com/rust-lang/rust/issues/44136 I understand that there were plans to support other output formats but it will never be implemented.

**Comment by MaxVerevkin** [comment]
Even though per-field configuration is not user-friendly, just writing all block related documentation in the beginning of source code is both convenient to maintain (better than having one huge .md file) and user friendly (is it?):
![image](https://user-images.githubusercontent.com/34583604/116774819-c77acf80-aa67-11eb-92d1-9919693330b2.png)

**Comment by ammgws** [comment]
Actually that might not be too bad!

**Comment by ammgws** [comment]
Should we go ahead and do it?

**Comment by MaxVerevkin** [comment]
@ammgws If you like how https://maxverevkin.github.io/swaystatus/docs/swaystatus/blocks/index.html looks then I suppose.

**Comment by ammgws** [comment]
It's grown on me

**Comment by jyn514** [comment]
> From rust-lang/rust#44136 I understand that there were plans to support other output formats but it will never be implemented.

That issue was out of date, I updated it - there's an unstable JSON output format on nightly :) https://github.com/rust-lang/rust/issues/76578

**Comment by ammgws** [comment]
@MaxVerevkin Do the docs have to be checked into the repo like at swaystatus for this to be usable online?

**Comment by MaxVerevkin** [comment]
I think so, unless we publish the crate on crates.io

**Comment by ammgws** [comment]
Do others publish programs to crates.io? I always thought it was for libraries that other crates can then import. Wonder if there's another way..

**Comment by ammgws** [comment]
Do others publish programs to crates.io? I always thought it was for libraries that other crates can then import. Wonder if there's another way..

**Comment by MaxVerevkin** [comment]
Well, there are `ripgrep`, `alacritty` and `zbus_xmlgen`, but... it looks like docs are not generated for binary crates :disappointed:

**Comment by jyn514** [comment]
> docs are not generated for binary crates

https://github.com/rust-lang/docs.rs/issues/238

As a workaround, you could move your current binary to a library with a `main` function and have the actual binary just call `my_lib::main` and do nothing else.

**Comment by MaxVerevkin** [comment]
> As a workaround, you could move your current binary to a library with a main function and have the actual binary just call my_lib::main and do nothing else.

Will it work for a crate which is both a library and a binary?

>  Wonder if there's another way..

Yeah, publishing a new version after every change in documentation doesn't sound great.

**Comment by MaxVerevkin** [comment]
> As a workaround, you could move your current binary to a library with a main function and have the actual binary just call my_lib::main and do nothing else.

Will it work for a crate which is both a library and a binary?

>  Wonder if there's another way..

Yeah, publishing a new version after every change in documentation doesn't sound great.

**Comment by jyn514** [comment]
> Will it work for a crate which is both a library and a binary?

No, you'd have to make a new library if you want that to work. (or work on the docs.rs issue :wink:)

**Comment by ammgws** [comment]
> \> @MaxVerevkin Do the docs have to be checked into the repo like at swaystatus for this to be usable online?
> I think so, ~unless we publish the crate on crates.io~

Actually if we just keep the docs in a separate branch and have a github action to generate them then we can do this, e.g.: https://github.com/houqp/leptess

**Comment by MaxVerevkin** [comment]
> Actually if we just keep the docs in a separate branch and have a github action to generate them then we can do this, e.g.: https://github.com/houqp/leptess

Nice! Didn't know https://github.com/marketplace/actions/deploy-to-github-pages existed :)

**Comment by ammgws** [comment]
Closing now that async branch is merged into master. However we now need a way to generate manpages to replace our old script that parsed `blocks.md`...

**Comment by MaxVerevkin** [comment]
> However we now need a way to generate manpages to replace our old script that parsed blocks.md...

Well... A little script/program can be written to iterate through every file in `/src/blocks/` and extract the top-level comment. Those comments can then be concatenated and placed in one big `.md` file. And then we can convert this file to manpage.

**Comment by MaxVerevkin** [comment]
My attempt - eb22f911d822a2424943b6becad8392c56094e20

The result contains some `.RS 2` where it doesn't make sense, don't know why yet.

**Comment by ammgws** [comment]
BTW any idea what is going on here? Pretty sure the docs are up to date

![image](https://user-images.githubusercontent.com/20397027/175020518-7cd97f88-3fae-4c76-992e-f51e1384c9db.png)

![image](https://user-images.githubusercontent.com/20397027/175020566-6a6dc0dd-40d4-471f-8510-30589a734f28.png)

**Comment by MaxVerevkin** [comment]
> BTW any idea what is going on here? Pretty sure the docs are up to date but code block formatting broken in the Github pages.
> 
> ![image](https://user-images.githubusercontent.com/20397027/175020518-7cd97f88-3fae-4c76-992e-f51e1384c9db.png)
> 
> ![image](https://user-images.githubusercontent.com/20397027/175020566-6a6dc0dd-40d4-471f-8510-30589a734f28.png)
> 

Ahh, that's because markdown is weird and "|" gets parsed as a column separator. Some kind of special escape sequence must be used, like `&vert;` or something.

**Comment by MaxVerevkin** [comment]
> special escape sequence must be used, like `&vert;`

And to use this escape sequence you need `<code>...</code>` instead of \`...\` :angry:

**Comment by MaxVerevkin** [comment]
TIL that number of `-` in markdown tables matter (for manpages).

```
//! Placeholder        | Value
//! -------------------|----------------------------------------------------------------
```

renders as

![image](https://user-images.githubusercontent.com/34583604/175106941-a4a7acf8-381f-4469-b9b3-19d132428959.png)

while

```
//! Placeholder        | Value
//! -------------------|------
```

renders as

![image](https://user-images.githubusercontent.com/34583604/175107171-cf2db01a-db51-477c-8740-490c9baea142.png)
