### ISSUE TITLE
Uneven spacing memory block

### ISSUE THREAD

**Issue by ram02z** [greshake/i3status-rust#1134]
I have noticed that some (not all) format values that have percentages have uneven spacing(see below). I have tested all the format values that have percentages and the following have uneven spacing:

- `cached_percent`
- `mem_free_percents`
- `mem_total_used_percents`
- `mem_used_percents`
- `mem_avail_percents`
- `cached_percent`

<meta http-equiv="content-type" content="text/html; charset=utf-8"><img src="https://i.imgur.com/nJy2Dqf.png">

> sway version v1.5
> i3status-rs 0.20.0 (commit ef2e881 2021-03-23)

**Comment by MaxVerevkin** [comment]
It is intentional. Refer to the formatting section of `blocks.md`. In short, try `format = {<var-name>:2}`.
