### ISSUE TITLE
Notify block: error on click

### ISSUE THREAD

**Issue by marzzzello** [greshake/i3status-rust#1136]
Clicking on the notify block results in a bar error with `Internal error in context 'click handler': could not get required block`

i3status-rs 0.20.0 (commit ef2e881 2021-03-23)
dunst 1.6.1.r13.g3acffdb-1

**Comment by MaxVerevkin** [comment]
@marzzzello can you test #1138?

**Comment by marzzzello** [comment]
That was fast. Thanks it works now. #1137 is fixed too
