### ISSUE TITLE
NetworkManager Block shows same interface twice when connected to VPN

### ISSUE THREAD

**Issue by Alexeyan** [greshake/i3status-rust#1143]
Hi. 

I've noticed an issue when using the networkmanager block while connected to a VPN.
It shows the ethernet interface that the VPN is running over twice with the same IP. 
I have this in my config:
```
[[block]]
block = "networkmanager"
interface_name_include = ["enp*", "vpn*"]
```

The statusbar this looks like this (192.168.0.123 being my LAN IP):
```
192.168.0.123/24   $VPN_IP   192.168.0.123/24
```
I assume it is because the networkmanager block is getting all active connections and grabs the device for each one. https://github.com/greshake/i3status-rust/blob/ef2e881308486e58becdd4c264dc5191b65854cd/src/blocks/networkmanager.rs#L230 
and
https://github.com/greshake/i3status-rust/blob/ef2e881308486e58becdd4c264dc5191b65854cd/src/blocks/networkmanager.rs#L734

When using the networkmanager VPN feature, the VPN connection hast the same device, but a different type of connection 
```
$ nmcli con
NAME                     UUID     TYPE       Device
VPN                      $UUID    vpn        enp7s0
Wired Connection 1       $UUID    ethernet   enp7s0
vpn0                     $UUID    tun        vpn0
```
When setting interface_name_include to only "enp*", I still get the interface twice.

I'm not sure what the best approach here would be. Deduplication of the devices/IPs could be a workaround, but the more correct solution should be to get the devices instead of the connections.
```
$ nmcli dev
NAME    TYPE        STATE                  CONNECTION
enps0   ethernet    connected              Wired Connection 1
vpn0    tun         connected (externally) vpn0
```

**Comment by ammgws** [comment]
Is it a regression?

https://github.com/greshake/i3status-rust/pull/1099

**Comment by GladOSkar** [comment]
Releases are made quite occasionally. `master` is usually stable enough to run though

**Comment by ammgws** [comment]
> Oh hm. It seems like there hasn't been a release since 6 weeks and the fix hasn't landet yet.

How are you installing it? If on Arch Linux you can just switch over to the -git package if you can't wait.

> Any info on when another release is happening?

There have been some major changes recently so I'm not in a rush to cut a new release until any new bugs are fixed and docs are improved further. Any help would be welcome :)
