### ISSUE TITLE
Theme missing after update

### ISSUE THREAD

**Issue by GladOSkar** [greshake/i3status-rust#1145]
Hi!

Just updated to the lastest `master` and got this error:

```
i3status-rs ~/.config/i3/status-rs-config.toml
{"version": 1, "click_events": true}
[
[{"full_text":" Configuration error: failed to parse TOML from file contents.
Cause: Theme 'slick' not found. for key `theme` at line 103 column 1 ","name":"0","instance":"0","separator":false,"separator_block_width":0,"markup":"pango"}],


Configuration error: failed to parse TOML from file contents.
Cause: Theme 'slick' not found. for key `theme` at line 103 column 1
```

Also, btw, 
![image](https://user-images.githubusercontent.com/9497832/113199703-ba4fa280-9267-11eb-9f27-475e691b80a1.png)
is not a good error message. Could the above error message be displayed instead? I assume this has to do with the plaintext error message being printed to `stdout` instead of `stderr`.

**Comment by GladOSkar** [comment]
Oh after running `install.sh` it was fixed, i assume this will be listed as a breaking change? I usually would expect an update to keep working without having to read the README again to install new files. Maybe the binary could install the files automagically in a transition period?

**Comment by MaxVerevkin** [comment]
> Maybe the binary could install the files automagically in a transition period?

I don't know. How would you implement that?

**Comment by GladOSkar** [comment]
>  assume this has to do with the plaintext error message being printed to stdout instead of stderr.

Actually it might also be that `i3` doesn't like a newline within the json `full_text`. Not sure.

**Comment by MaxVerevkin** [comment]
> is not a good error message

Yeah, not informative at all. I'll see why its happening.

**Comment by MaxVerevkin** [comment]
> Actually it might also be that i3 doesn't like a newline within the json full_text. Not sure.

`sway`'s fine :eyes:

**Comment by GladOSkar** [comment]
I just checked with `i3` - it's the newline. If i remove it i get the full error message:

![image](https://user-images.githubusercontent.com/9497832/113202527-22ec4e80-926b-11eb-9891-ab1dafb4e491.png)
