### ISSUE TITLE
feature request: suspend on low battery

### ISSUE THREAD

**Issue by hboetes** [greshake/i3status-rust#1148]
I added this feature to my version of the battery script for i3block, but I like i3status-rust a lot, so I'd like to make this feature request:

It would be nice of i3status-rust can suspend the laptop once critical battery level is reached.

All that would be needed is an option where the suspend command is defined, with a default of empty, doing nothing.

And an example where it is defined as "systemctl suspend" which mortal users can call.

https://www.freedesktop.org/software/systemd/man/systemd-suspend.service.html

Perhaps even better would be to add a suspend-level and to send notifications once the critical level is reached.

What do you think?

**Comment by MaxVerevkin** [comment]
My personal opinion is that this kind of functionality is just too much for a status-line generator.

You can write a python script (or whatever you preferred language is) that look something like that
```python
import time
import os

while True:
    full = int(open("/sys/class/power_supply/BAT0/charge_full").read())
    now = int(open("/sys/class/power_supply/BAT0/charge_now").read())
    percentage = now / full * 100
    if percentage < 10:
        os.system("systemctl suspend")
    time.sleep(10)
```
and just run it in the background.

**Comment by hboetes** [comment]
OK, fair enough. I think I'll use that script I already have, strip it down a bit and run it in the BG.
