### ISSUE TITLE
config no longer parses

### ISSUE THREAD

**Issue by matthiaskrgr** [greshake/i3status-rust#1164]
Unfortunately I don't exactly know which was the last working version but as I restarted i3status-rust today, it no longer parses my config.

````
{"version": 1, "click_events": true}
[
[{"full_text":" Configuration error: failed to parse TOML from file contents.
Cause: Theme 'modern' not found. for key `theme` at line 1 column 9 ","name":"0","instance":"0","separator":false,"separator_block_width":0,"markup":"pango"}],


Configuration error: failed to parse TOML from file contents.
Cause: Theme 'modern' not found. for key `theme` at line 1 column 9
````

I have this in my toml
````
theme = "modern"
icons = "awesome"
````
which seems to cause problems now, if I comment out the two lines, the bar loads.
According to the docs this is supposed to work though..?
https://github.com/greshake/i3status-rust/blob/master/doc/themes.md

not even
````
theme = "plain"
icons = "none"
````
works.

**Comment by matthiaskrgr** [comment]
Hm, it seems that  https://github.com/greshake/i3status-rust/pull/1135 is the cause for this.

Previously I could just copy the i3status binary into $PATH and it would find everything out of the box.

**Comment by matthiaskrgr** [comment]
Solved the issue by pointing to the respective files of a copy of the git repo...
Would be nice if the error message had been a bit more helpful :)

**Comment by GladOSkar** [comment]
Agreed, it should be something along the lines of "<Theme/Icon> file not found"
