### ISSUE TITLE
Graphs wiggle in width depending on usage

### ISSUE THREAD

**Issue by nolanl** [greshake/i3status-rust#1168]
This causes every widget to the left of the CPU graph to move around distractingly as CPU usage changes.

I've screenshotted the cpu graph (on a 64 thread Threadripper), but the net ones behave similarly.

![2021-04-08-181739_755x26_scrot](https://user-images.githubusercontent.com/720974/114114965-c7d3e080-9896-11eb-9abf-85837e68fef1.png)
![2021-04-08-181843_694x29_scrot](https://user-images.githubusercontent.com/720974/114115026-e0dc9180-9896-11eb-93d3-c1e54f460e5e.png)

```
bar {
        font pango:Monospace, FontAwesome 8.5
```

```
$ fc-match Monospace
VeraMono.ttf: "Bitstream Vera Sans Mono" "Roman"
$ fc-match FontAwesome
FontAwesome.otf: "FontAwesome" "Regular"
```

This is on Debian Bullseye, with the repo's version of i3*, ttf-bitstream-vera and fonts-font-awesome. i3status-rust is built locally from 759602d85543edbec2a22e6522f41ee983517f95.

**Comment by ammgws** [comment]
const BOXCHARS: &[char] = &['▁', '▂', '▃', '▄', '▅', '▆', '▇', '█'

Quick guess is these characters not being equal width. Are you able to check?

**Comment by nolanl** [comment]
``` for i in '▁', '▂', '▃', '▄', '▅', '▆', '▇', '█'; do echo $i; done ```
![2021-04-08-183404_25x158_scrot](https://user-images.githubusercontent.com/720974/114116163-05396d80-9899-11eb-84e2-da658dcdbce2.png)

Looks like the 100% character is narrower for me. Strangely, in my browser (firefox installed from mozilla directly) it appears wider than the rest.

**Comment by ammgws** [comment]
Weird. The characters are hardcoded at the moment but if they were moved to the icon config then you could try overriding it and make the last two the same.

**Comment by nolanl** [comment]
I edited the source to that effect, and unsurprisingly, the wiggle is gone. Haven't tried it for the net block, but I have to imagine I'd get the same results...

**Comment by nolanl** [comment]
Made the same change in format_vec_to_bar_graph and that "fixed" the net graphs as well.

**Comment by nolanl** [comment]
Removing Bitstream Vera, so font-config matches DejaVu instead fixes it. Must be something wrong with Vera's monospace font.
