### ISSUE TITLE
Wrong font name for FontAwesome?

### ISSUE THREAD

**Issue by bennyyip** [greshake/i3status-rust#118]
I am using Arch Linux and have installed  `community/ttf-font-awesome`. 
I followed README to specify the bar font to `Icons 12` and enable `icon="awesome"` in the config file.
But, it turns out that the status bar displayed abnormally. I change the font from `Icons` to `FontAwesome` and then it works eventually. 
Maybe the font name of FontAwesome has changed? Should we update the README? 

FYI, the following shell output maybe helpful.
```zsh
22:14:21 ben @ alcohol ω ~  
λ fc-match Icons
NotoSansCJK-Regular.ttc: "Noto Sans CJK TC" "Regular"
22:14:22 ben @ alcohol ω ~
λ pacman -Ql ttf-font-awesome
ttf-font-awesome /usr/
ttf-font-awesome /usr/share/
ttf-font-awesome /usr/share/fonts/
ttf-font-awesome /usr/share/fonts/TTF/
ttf-font-awesome /usr/share/fonts/TTF/fontawesome-webfont.ttf
ttf-font-awesome /usr/share/licenses/
ttf-font-awesome /usr/share/licenses/ttf-font-awesome/
ttf-font-awesome /usr/share/licenses/ttf-font-awesome/OFL
22:14:36 ben @ alcohol ω ~
λ fc-match fontawesome
fontawesome-webfont.ttf: "FontAwesome" "Regular"
```

**Comment by greshake** [comment]
Still works for me

**Comment by atheriel** [comment]
I've added some info pertaining to this to the README. It should be clearer now.
