### ISSUE TITLE
pomodoro block libnotify option

### ISSUE THREAD

**Issue by lihkak** [greshake/i3status-rust#1181]
Hi,
This is a feature request. Can libnotify support be added for pomodoro block alongside i3-nagbar. I think [this](https://crates.io/crates/libnotify) crate would be of some help.
Thanks

**Comment by ammgws** [comment]
Might be easier to implement by using `notify-send` instead of adding a new crate.

**Comment by lihkak** [comment]
Hi,
By `notify-send` do you mean sending the notification using the binary installed by the package manager with the help of `std::process::Command`  or do you meaning something else?
Thanks

**Comment by ammgws** [comment]
Yes, instead of calling the i3nag binary. The command line arguments are different though so just need to figure it the best way to do it.
