### ISSUE TITLE
alert_absolute in disk space is not working correctly, when true

### ISSUE THREAD

**Issue by Crandel** [greshake/i3status-rust#1182]
I build latest master and use this config
```
[[block]]
block = "disk_space"
alert = 10.0
alert_absolute = true
format = "{path^2}{available;G}"
info_type = "available"
interval = 300
path = "/data"
unit = "GB"
warning = 50.0
```
Currently I have 34 GB available, but block stay the same color as it was before. If I change `alert_absolute` to false and use correct percentage for warning, the block styled as it should be styled for warning level. In my case I use dark-gruvbox theme and warning color is yellow

**Comment by ammgws** [comment]
Due to wrong units being compared (or supplied to) this function:
https://github.com/greshake/i3status-rust/blob/a66bc6dd645e0a8884e3374fa11139537e33fb7e/src/blocks/disk_space.rs#L102

e.g.
alert: 10, warning: 50, value: 1554784208465952800

**Comment by Crandel** [comment]
Yes, now it works correctly, thank you very much
