### ISSUE TITLE
Music block on_collapsed_click not working

### ISSUE THREAD

**Issue by ThreshMain** [greshake/i3status-rust#1185]
My config file https://pastebin.com/hUiXhvv5
My i3status-rust version is i3status-rs 0.14.7
I have tried config with starting other working applications (on_collapsed_click) and not even that works.
Thanks for any help.

**Comment by MaxVerevkin** [comment]
Duplicate of #1060 -- already fixed. I don't know when a new version is released, but you can try `aur/i3status-rust-git` if you use Arch.

**Comment by ThreshMain** [comment]
> Duplicate of #1060 -- already fixed. I don't know when a new version will be released, but you can try `aur/i3status-rust-git` if you use Arch.

Thanks the new version works just fine.

**Comment by ammgws** [comment]
> I don't know when a new version will be released

Once the remaining items in the milestone are done
