### ISSUE TITLE
Incorrect dispay: arrows gap

### ISSUE THREAD

**Issue by backuitist** [greshake/i3status-rust#119]
This is what I can see:
![selection_001](https://user-images.githubusercontent.com/1017537/33272803-91321a2a-d38b-11e7-9f37-3b87f8316637.png)
```
i3 --version
i3 version 4.14.1 (2017-09-24) © 2009 Michael Stapelberg and contributors
```

My i3 config has this:
```
bar {
	font pango:DejaVu Sans Mono, Icons 12
```
I have installed the powerline and awesome fonts, but I'm on NixOS so perhaps the wrong font got used?

**Comment by backuitist** [comment]
Using
```
font pango: DejaVu Sans Mono for Powerline 12
```
fixes the gap, but there are still top and bottom margins, which seem to be hardcoded into i3.

**Comment by GladOSkar** [comment]
i3 adds padding around the text, that is why the arrows don't take the full height.

If it is really important to you, you can recompile i3 with this patch (made by the infamous Airblader):
https://gist.github.com/Airblader/72d6a03d05c111d33ad4
