### ISSUE TITLE
QUESTION: Should the Weather block be removing quotes?

### ISSUE THREAD

**Issue by xxxserxxx** [greshake/i3status-rust#1191]
The wiki well documents escaping in custom blocks; is it possible to perform (custom) replacements in non-custom blocks? 

The weather block (openweather) returns the description as a quoted string for me, and the quotes are retained by the block s.t. the output is something like:

```
{"full_text":"  \"Clouds\" 42° ","color":"#1ebce8","background":"#000000","name":"1","instance":"0","separator":false,"separator_block_width":0,"markup":"pango"}
```

I'd like to remove the quotes around "Clouds".  I'm currently doing it in a trivial script that just does `i3status-rs | sed 's/\\"//g'`, but it'd be nice to be able to do a regexp replacement, or just have the Weather block remove quotes.

Because it seems odd that I'd be the only person to notice this, I wonder if I have something set incorrectly, or if I'm missing a way of transforming the string in a non-custom widget.

i3status-rust is from 2021-03-26 (d0caebc2d0a7b2608746bcfaf87a6bfc1edd6a32).

**Comment by ammgws** [comment]
It must be a regression since there are no quotes in v0.14.1. Probably something to do with the JSON deserialisation.

**Comment by xxxserxxx** [comment]
I just verified the behavior's the same in a more recent commit (4d55b1d94ee09cbdefd805841fb54a2a4a0663a4, Apr 18, 2021).

**Comment by ammgws** [comment]
It's due to something introduced in v0.14.4. Should be able to track it down

**Comment by xxxserxxx** [comment]
Confirmed, thanks!
