### ISSUE TITLE
Number of pacman packages

### ISSUE THREAD

**Issue by sivertjoe** [greshake/i3status-rust#1196]
Hello, 

I cloned the project a few months ago because I wanted to have a block displaying the number of pacman packages. Is this a feature you would be interested in having? I can create a PR for it if there is interest

**Comment by ammgws** [comment]
It already exists (for a couple of years now I think?). Check the block docs

**Comment by ammgws** [comment]
Oh did you mean the actual number of installed packages? You can use a custom block for that

**Comment by sivertjoe** [comment]
That works
