### ISSUE TITLE
Alternating color in Nord theme not working

### ISSUE THREAD

**Issue by etrigan63** [greshake/i3status-rust#1199]
I am using the `nord-dark` theme and the status bar looks like the native bar with nord colors. How can I get the background to alternate colors like a proper powerline?

**Comment by ammgws** [comment]
Did you try setting `alternating_tint_bg` and/or `alternating_tint_fg`? Like this: https://github.com/greshake/i3status-rust/blob/master/files/themes/slick.toml

**Comment by etrigan63** [comment]
Just tried `alternating_tint` in `[theme_overrides]` and no joy. I don't want to manually set the colors because if I add/remove a block, I have to edit every block.

**Comment by etrigan63** [comment]
I had to copy the source of `nord-dark.toml` locally and add the `alternating_tint` there.  Also you need some documentation explaining the mechanism behind `alternating_tint` as it is not obvious.

**Comment by ammgws** [comment]
> Also you need some documentation explaining the mechanism behind alternating_tint as it is not obvious.

Documentation does need to be improved overall. PRs welcome.

**Comment by MaxVerevkin** [comment]
Works for me with
```toml
[theme]
name = "nord-dark"
[theme.overrides]
alternating_tint_bg = "#111111"
alternating_tint_fg = "#111111"
```

**Comment by etrigan63** [comment]
Ah, it's `[theme.overrides]` not `[theme_overrides]`.

I would happily PR to update the documents, but that would be a case of "the blind leading the blind".
