### ISSUE TITLE
Clicks are sometimes only registered the second time

### ISSUE THREAD

**Issue by greshake** [greshake/i3status-rust#12]
This may be an issue with i3bar, further investigation is needed. Sometimes, clicks on the bar only get registered the second time... The issue was reproducable on multiple workstations.

**Comment by pitkley** [comment]
I have not verified this yet, but I am pretty certain that [this](https://github.com/greshake/i3status-rust/blob/45be014bf03cb13141297dfb9aba10743e7c09ae/src/input.rs#L24) might be the issue.

The first event on the first line probably does not start with a `,` and thus does not get processed.

This might work:

```diff
diff a/src/input.rs b/src/input.rs
--- a/src/input.rs
+++ b/src/input.rs
@@ -22,11 +22,11 @@ pub fn process_events(sender: Sender<I3barEvent>) {
         io::stdin().read_line(&mut input).unwrap();
 
         if input.starts_with(",") {
-            let input = input.split_off(1);
+            input = input.split_off(1);
+        }
 
-            let e: I3barEvent = serde_json::from_str(&input).unwrap();
- 
-            sender.send(e).unwrap();
-        }
+        let e: I3barEvent = serde_json::from_str(&input).unwrap();
+ 
+        sender.send(e).unwrap();
     });
 }
```
