### ISSUE TITLE
Minimal music player block

### ISSUE THREAD

**Issue by bluehood** [greshake/i3status-rust#120]
Hi,
I _love_ i3status-rust.
I started learning a bit of rust just to add my own blocks.

However I need to hear poeple's opinion on if and how to implement a minimal music player block. I don't use spotify or any gui app, I just usually fire up `mplayer -shuffle ~/music/*` in a terminal. It would be super nice to have a player run in the status bar, with a couple of useful buttons.

How would you go about implementing this? I could actually start and stop `mplayer` in the background but it would be difficult to extract the name of the current track. I looked around a bit but could not find something that looked like the right tool for the job.

Any kind of feedback on the idea would be appreciated.

P.S.
just found out that `mplayer -identify` prints out track information "in an easily parseable format" and that rust has `std::process:ChildIn` and `ChildOut`. It might be doable to wrap `mplayer` directly after all...

**Comment by greshake** [comment]
Thing is, I'd like to avoid a special block just for Mplayer. The music block currently supports all players that implement htis interface: https://specifications.freedesktop.org/mpris-spec/latest/Player_Interface.html

Maybe choose a cmdline player that supports this interface? It might be really hard and possibly circumventable to build a dedicated piece for Mplayer.

**Comment by bluehood** [comment]
It doesn't _have_ to be mplayer -- but I couldn't find a list of players implementing mediaPlayer2, and from my tests mplayer does not. I can try out alternatives, I'm open to suggestions 😄 

Regarding the feasibility of an mplayer block: with my zero knowledge of rust I put together a `struct` last night that starts mplayer as a child process and has control over its stdin and stdout -- so it seems quite doable after all.

If anyone has a suggestion for a cmdline player that is supported by the current music block please let me know :D

**Comment by greshake** [comment]
I just worry that this is kind of duplicate/ going to introduce a lot of duplication. How about this: Make a wrapper for the MediaPlayer2 interface for Mplayer :) Then users of Mplayer can enjoy all kinds of controls that suppport the interface.

**Comment by bluehood** [comment]
oh boy xD I would need to make an application that starts mplayer and steers it according to messages received from dbus, correct? and MediaPlayer2 specifies which messages do what.

**Comment by greshake** [comment]
Yup. But you can implement Dbus interfaces in Rust

**Comment by bluehood** [comment]
Ok you convinced me, but I might as well go with python at this point :)

Feel free to close the issue as the development will be separate from i3status-rust

**Comment by greshake** [comment]
Good luck, have fun :+1:
