### ISSUE TITLE
Upgrade from i3status-rust to i3status-rust-git broke my config file

### ISSUE THREAD

**Issue by epixinvites** [greshake/i3status-rust#1202]
```
theme = "gruvbox-dark"

[icons]
name = "awesome"

[[block]]
block = "uptime"

[[block]]
block = "taskwarrior"
interval = 1
format = "{count} pending tasks"
format_singular = "{count} pending tasks"
format_everything_done = "Tasks completed"
warning_threshold = 3
critical_threshold = 5

[[block]]
block = "pacman"
interval = 600
format = "{pacman}/{aur} pending updates"
format_singular = "{pacman}/{aur} pending update"
format_up_to_date = "Up to date"
aur_command = "yay -Qua"

[[block]]
block = "music"
player = "ncspot"
buttons = ["play", "next"]
max_width = 18
dynamic_width = true
marquee_interval = 5
marquee_speed = 0.5
hide_when_empty = true

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 1
warning = 20.0
alert = 10.0

[[block]]
block = "net"
device = "wlp1s0"
format = "{speed_down}"
interval = 1
use_bits = false

[[block]]
block = "memory"
interval = 1
display_type = "memory"
format_mem = "{MAm}MB"
format_swap = "{SFm}MB"

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "temperature"
collapsed = false
interval = 1
format = "{average}°"
chip = "coretemp-isa-0000"

[[block]]
block = "battery"
interval = 1
format = "{percentage}% {time}"

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 1
format = "%a %d/%m %R:%S"
```
I'm using Arch Linux. Here is my config file, I recently updated from i3status-rust (0.14.7) to i3status-rust-git (i3status-rs 0.20.0 commit fa15265 2021-04-25). After I refreshed my i3, I only get this error
```
{"version": 1, "click_events": true}
[
[{"full_text":" Configuration error: Failed to deserialize block config..
Cause: unknown field `use_bits`, expected one of `interval`, `format`, `format_alt`, `device`, `hide_inactive`, `hide_missing` ","color":"#dc322f","background":"#000000","name":"0","instance":"0","separator":false,"separator_block_width":0,"markup":"pango"}],


Configuration error: Failed to deserialize block config..
Cause: unknown field `use_bits`, expected one of `interval`, `format`, `format_alt`, `device`, `hide_inactive`, `hide_missing`
```

**Comment by ammgws** [comment]
Does https://github.com/greshake/i3status-rust/blob/master/NEWS.md help?
(it may need some further updates)

**Comment by epixinvites** [comment]
![image](https://user-images.githubusercontent.com/54717060/116489753-4802ca00-a8c8-11eb-9f08-06550084e5de.png)
here, my old disk block has shows me something like 137.8 GB now its 137GB how can I prevent it from rounding off.
Also, my Memory Block, even though I specifically added this line into my config `format_mem = "{mem_avail;M}"`, it still gave me output in GB. Same thing happens with the swap format, I did specify this `format_swap = "{swap_free;M}"`

**Comment by epixinvites** [comment]
![image](https://user-images.githubusercontent.com/54717060/116490222-661cfa00-a8c9-11eb-9e8f-d08c30704c61.png)
This thing here is also very ugly, I remember it being like 1.98 or 10.84 and not 9.9

**Comment by GladOSkar** [comment]
The unit is just the minimum SI prefix, i.e. `;M` will show `100K` as `0.1M` but if the the value is higher than `1G` it will still show `G` to be shorter.

To show more decimal places, use the `:` specifier to set the min width of the placeholder, like `{used:5}` for your disk space and `{1m:4}` for your load.

**Comment by epixinvites** [comment]
Thanks a lot, it worked.

**Comment by epixinvites** [comment]
```
[[block]]
block = "pacman"
interval = 600
format = "{pacman}/{aur} pending updates"
format_singular = "{pacman}/{aur} pending update"
format_up_to_date = "Up to date"
aur_command = "yay -Qua"
```
Here is the config for my Pacman block, while the output of them block looks like this:
![image](https://user-images.githubusercontent.com/54717060/116766180-c0e65b00-aa5b-11eb-8f66-f9c7435872d0.png)

Why is there a space after the '/'

**Comment by GladOSkar** [comment]
Because integers have a default min width of 2. Use `{pacman:1}/{aur:1}` if you don't care about the block with changing once more than 9 updates are available or `{pacman:02}/{aur:02}` if you'd rather keep it consistent but pad with zeroes so there aren't any gaps.

**Comment by epixinvites** [comment]
> Because integers have a default min width of 2. Use `{pacman:1}/{aur:1}` if you don't care about the block width changing once more than 9 updates are available or `{pacman:02}/{aur:02}` if you'd rather keep it at a consistent width but pad with zeroes so there aren't any gaps.

Well sometimes my updates can be a few hundred...

**Comment by GladOSkar** [comment]
It's the minimum width so you'll always see the total number. It's just a matter of personal preference whether you want to pad it and how much. If you want you can also set it to pad to at least 3 digits, your choice

**Comment by epixinvites** [comment]
Thank you all so much, I appreciate it.
