### ISSUE TITLE
Custom block doesn't handle json whose text field contains literal ampersand &

### ISSUE THREAD

**Issue by michaelmrose** [greshake/i3status-rust#1204]
Example block

[[block]]
block = "custom"
command = "mpd-status-line.clj"
interval = "once"
signal = 4
json = true
on_click = "mpc toggle"

{"state":"Info","text":"   Tom Petty & The Heartbreakers - Breakdown via http local"}

Took me a minute to understand because the block worked when mpd wasn't running as it would return the text none and unfortunately I queued up the same playlist whilst testing it.

**Comment by grvxs** [comment]
I have a json parsing error too on this block.
```rs
[[block]]
block = "custom"
interval = 999999
command = "echo '\uF011'"
on_click = "i3-nagbar -t warning -m 'What do you want to do?' -b 'Shutdown' 'shutdown now' -b 'Hibernate' 'systemctl hibernate' -b 'Reboot' 'reboot'"
```

**Comment by michaelmrose** [comment]
@grvxs oddly I get a parsing error when running i3status-rs in a terminal but it does work perfectly fine in practice. Of note you probably want to do interval = "once" I'm presuming that if you did leave your system up for 6 months you don't want it to ask you to log off.

**Comment by ammgws** [comment]
See here: https://github.com/greshake/i3status-rust/blob/master/doc/blocks.md#escaping-text

Perhaps there could be an option to disable Pango formatting

**Comment by michaelmrose** [comment]
@ammgws thanks I didn't notice that
