### ISSUE TITLE
Memory and htop

### ISSUE THREAD

**Issue by euri10** [greshake/i3status-rust#1216]
There is somtheing I dont get

i3status-rs tells me I have 50GB of ram used, htop tells me 18GB

![20210507_1441_1479x1083_1620391276](https://user-images.githubusercontent.com/1104190/117451860-5ba2d600-af43-11eb-89be-00196bf43d71.png)

```
 block = "memory"                                                                
 format_mem = "tot:{mem_total} free:{mem_free} used:{mem_used} avail:{mem_avail} cached:{cached}"
```

**Comment by GladOSkar** [comment]
Measuring used memory is hard because every utility has a different definition for what counts as actively used: allocations/free'd pages/pre-allocated pages/various caches/fs mappings etc. My guess would be there is some chunk of memory on your system that `/proc/meminfo` considers `used`, but `htop` doesn't on your system. That's quite hard to debug

**Comment by euri10** [comment]
I spent a few hours on this and I had no idea how "complicate" this would be. 
So when you said it's hard to debig, it's quite an understatement !
I was not able to pinpoint the discrepancies I'm seeing unfortunately.
I'll close for now as there's nothing actionable, the only thing I can say for sure is that glances, i3status-rust, node-exporter and htop all seem to "agree" on the memory usage right after boot.
But htop's calculations diverge over time on my system, while the other 3 seems to stay in the same ballpark.
The only thing that's running is docker and a shitload of containers, maybe something to explore.

**Comment by euri10** [comment]
I totally forgot I'm having a zfs pool, the discrepancy seems to be zfs arc cache size which by default sits at half the total RAM.
Would that be a potential "interesting" addition to the memory block @GladOSkar ?

**Comment by euri10** [comment]
> Seems reasonable. Can you tell me which line/title in `/proc/meminfo` shows the size of the ZFS arc cache? I only use ZFS on my FreeBSD machines which don't have `/proc/meminfo`.

I dont think that it is available on `/proc/meminfo`

the only place I know it can be read is in `/proc/spl/kstat/zfs/arcstats` and this is the size entry:
```
❯ awk '/^size/ { print $1 " " $3 }' < /proc/spl/kstat/zfs/arcstats
size 33751448000
```

there are other options to get the number as described better than what I could do [here](https://superuser.com/questions/1137416/how-can-i-determine-the-current-size-of-the-arc-in-zfs-and-how-does-the-arc-rel)

**Comment by GladOSkar** [comment]
Wanna try GladOSkar/memory-exclude-zfs-arc-cache? I don't have a way of testing this so i'll have to ask you to test for me.

**Comment by euri10** [comment]
> Wanna try [GladOSkar/memory-exclude-zfs-arc-cache](https://github.com/GladOSkar/i3status-rust/tree/memory-exclude-zfs-arc-cache)? I don't have a way of testing this so i'll have to ask you to test for me.

works fine bare a minor comment I made on your branch, THANKS !
