### ISSUE TITLE
[v0.20.0] invalid json generated for any block

### ISSUE THREAD

**Issue by jthomaschewski** [greshake/i3status-rust#1222]
### Config

```
[[block]]
block = "load"
interval = 120
format = "{5m}"
```
(Simple example config, can be reproduced with any config)

### Version

i3status-rust v0.20.0 and latest master.
Tried `i3status-rust v0.20.0-2` package from arch `community-testing` and `i3status-git` from AUR.

i3-gaps v4.19.1

### Expected behavior

Should write valid json to stdout and show bar in i3

```console
$ i3status-rs 
{"version": 1, "click_events": true}
[{"full_text":"","color":"#002b36","separator":false,"separator_block_width":0,"markup":"pango"},{"full_text":"  1.6 ","color":"#93a1a1","background":"#002b36","name":"0","instance":"0","separator":false,"separator_block_width":0,"markup":"pango"}],
```

### Actual behavor

Writes invalid open bracket in stdout.

```console
$ i3status-rs    // v0.20.0
{"version": 1, "click_events": true}
[
[{"full_text":"","color":"#002b36","separator":false,"separator_block_width":0,"markup":"pango"},{"full_text":"  1.6 ","color":"#93a1a1","background":"#002b36","name":"0","instance":"0","separator":false,"separator_block_width":0,"markup":"pango"}],
```

When downgrading to v0.14.7 and starting with the same config output is the following:

```console
$ i3status-rs   // v0.14.7
{"version": 1, "click_events": true}
[[{"background":null,"color":"#002b36","full_text":"","markup":"pango","separator":false,"separator_block_width":0},{"background":"#002b36","color":"#93a1a1","full_text":"  2.07 ","name":"0","separator":false,"separator_block_width":0}],
```

i3 reports:
`Could not parse JSON (lexical error: invalid character inside string.)`

Tried multiple theme/icon combinations and different block types.
Always the same result.

**Comment by jthomaschewski** [comment]
Uh... sorry I failed. I've set a different config file in my i3 config.
The additional opening bracket seems still weird to me and is new in v0.20.0
But i3 seems to ignore it.

Additional info if interested:

The bracket seems to be added during init. When ran with `--no-init` flag, it's not written to stdout:
```
i3status-rs --no-init                          
[{"full_text":"","color":"#002b36","separator":false,"separator_block_width":0,"markup":"pango"},{"full_text":"  1.6 ","color":"#93a1a1","background":"#002b36","name":"0","instance":"0","separator":false,"separator_block_width":0,"markup":"pango"}],
```

As this seems to be a non-issue in practice, I'll close this issue

**Comment by ammgws** [comment]
Wait so what was the config that was causing i3status-rust to produce broken JSON? That might be an issue in of itself

**Comment by jthomaschewski** [comment]
This extra line seems to be added in the protocol init function: https://github.com/greshake/i3status-rust/blob/master/src/protocol/mod.rs#L13

But now I checked closely, and the JSON it's actually not different from 0.14.x - the opening bracked has just moved to a separate line.

before:
```
[[ first block output ],
```
after:
```
[
[ first block output ],
```

So I think this is a false alarm

**Comment by ammgws** [comment]
You mentioned seeing this:

> i3 reports: Could not parse JSON (lexical error: invalid character inside string.)

Does that mean i3/i3bar was crashing due to the JSON? Or was it just displayed in stderr and the bar was still working?

**Comment by jthomaschewski** [comment]
i3 was just displaying the JSON parse error, the rest was still working (e.g systray, workspace indicator...)
![image](https://user-images.githubusercontent.com/682607/117846298-99746700-b281-11eb-9081-8a762bee289e.png)

This can be easily reproduced by just providing an invalid i3status config: 
```
// config.toml
BROKEN CONFIG
```

The stdout of i3status-rs is the following with this broken config:
```console
$ i3status-rs                                    
{"version": 1, "click_events": true}
[
[{"full_text":" Configuration error: failed to parse TOML from file contents.
Cause: expected an equals, found a newline at line 1 column 13 ","color":"#dc322f","background":"#000000","name":"0","instance":"0","separator":false,"separator_block_width":0,"markup":"pango"}],


Configuration error: failed to parse TOML from file contents.
Cause: expected an equals, found a newline at line 1 column 13
```

So it starts with valid json but later adds some invalid json which causes the error message not to be shown in the i3 bar.

Looks to me as if it's supposed to display "Configuration error: failed to parse TOML ..." in the i3bar instead, correct? This might be a bug
