### ISSUE TITLE
Nofity block not updating

### ISSUE THREAD

**Issue by 1ncend1ary** [greshake/i3status-rust#1225]
- version:  0.14.7, but tested on latest master version.

- `dunst` version: tested on latest (`1.6.x`) and on `1.5.0`

- `config.toml`:
  ```
  [[block]]
  block = "notify"
  ```

When I run `dunstctl set-paused toggle`, I then have to manually restart `i3status-rs` for the icon to be updated.

**Comment by ammgws** [comment]
I can't reproduce this at all:

i3status-rs 0.20.0
dunst 1.6.1 (1.6.0 or newer is required)

https://user-images.githubusercontent.com/20397027/117915078-8617d900-b31f-11eb-9d18-a5c63fde1e9c.mp4

**Comment by 1ncend1ary** [comment]
Hey,
this is my video of it happenning

I have to reload the i3wm (by pressing $mod+Shift+r) for the notification status to update

https://user-images.githubusercontent.com/45948348/117938180-6c6e9580-b30f-11eb-814c-002c9ca4d9f7.mp4

**Comment by GladOSkar** [comment]
Do you get output from
```sh
dbus-monitor destination=org.freedesktop.Notifications
```
when running the toggle command? It should print something like
```
method call time=1620809266.678865 sender=:1.164 -> destination=org.freedesktop.Notifications serial=2 path=/org/freedesktop/Notifications; interface=org.freedesktop.DBus.Properties; member=Set
   string "org.dunstproject.cmd0"
   string "paused"
   variant       boolean <false/true>
```

**Comment by 1ncend1ary** [comment]
Yes, I do; exactly this output.

I have decided to try to update all packages (`sudo pacman -Syu`), and suddenly I started getting exactly expected behavior. 

Sadly, I didn't see what was updated, so cannot post it here. 
The issue is resolved, sorry for taking up your time.

**Comment by ammgws** [comment]
OK no worries, keep an eye on it.
