### ISSUE TITLE
Memory block displays spaces sometimes before mem_xxx

### ISSUE THREAD

**Issue by euri10** [greshake/i3status-rust#1231]
this is my block:
```
  [[block]]                                                                       
  block = "memory"                                                                
  format_mem = "F:{mem_free} U:{mem_used} A:{mem_avail} C:{cached}"
```
and this is how it looks like:
![20210513_1553_595x40_1620913999](https://user-images.githubusercontent.com/1104190/118135455-5b06b580-b403-11eb-9f96-519e51bfb1f4.png)

so apparently there is undesired space before `mem_used`, `mem_avail` and `cached`

I didn't test others

**Comment by GladOSkar** [comment]
This was a breaking change introduces in `0.20`. Take a look at `NEWS.md` after updating to see what might have changed. In you case it's this:

`float` values are padded to 3 digits by default. To disable this, reduce the padding with (`min_width`), using for example:
```
format_mem = "F:{mem_free:1} U:{mem_used:1} A:{mem_avail:1} C:{cached:1}"
```
or, if you'd rather keep the with consistent at 3 digits, but replace the gaps with `0`s, use:
```
format_mem = "F:{mem_free:03} U:{mem_used:03} A:{mem_avail:03} C:{cached:03}"
```

**Comment by euri10** [comment]
I somehow missed this change thanks for the pointer @GladOSkar !
