### ISSUE TITLE
internal error in context 'get_icon()': icon 'bat_not_available' not found

### ISSUE THREAD

**Issue by adaigre** [greshake/i3status-rust#1235]
I'm using i3status-rust 0.20.1
I didn't have this issue before (0.20).

Using awesome5 icons from archlinux package (i3status-rust arch package too).

This is my 2 battery blocks :
```
[[block]]
block = "battery"
driver = "sysfs"
device = "BAT0"
format = "I {percentage}"
full_format = "I"
allow_missing = true
hide_missing = true

[[block]]
block = "battery"
driver = "sysfs"
device = "BAT1"
format = "E {percentage}"
full_format = "E"
allow_missing = true
hide_missing = true
```

Since `hide_missing = true`, it shouldn't try to load the icon in the first place?

**Comment by BonusPlay** [comment]
Same here, running on archlinux and latest package from [community repo](https://archlinux.org/packages/community/x86_64/i3status-rust/).

**Comment by ammgws** [comment]
Provisional fix: add the icon to the theme file (for some reason it's missing)

**Comment by hboetes** [comment]
Does it help if you update the files in ~/.local/share/i3status-rust with the latest version from the git repo?

**Comment by adaigre** [comment]
It doesn't. There is no `bat_not_available` in i3status-rust/files/icons/awesome5.toml repo file.
it works by adding it manually. However it seems that Font Awesome 5 don't provide a missing battery icon. I'm gonna using the same icon as bat_empty.

**Comment by hboetes** [comment]
OK, that fixed it for me.
