### ISSUE TITLE
Error in block 'battery': Power supply device does not exist

### ISSUE THREAD

**Issue by kflak** [greshake/i3status-rust#1236]
The battery module does not work on my Asus A15 running Arch Linux rt latest, giving me the error: `Error in block 'battery': Power supply device '/sys/class/power_supply/BAT0' does not exist`.

On my computer the power supply device is named BAT1 instead of BAT0.

Both the `i3status-rust` and `i3status-rust-git` packages from AUR have the same issue.

**Comment by ammgws** [comment]
https://github.com/greshake/i3status-rust/blob/master/doc/blocks.md#battery

Set `device = BAT1` since the default is BAT0. Perhaps it could be improved by defaulting to the first file found in `/sys/class/power_supply/` instead of being hardcoded to BAT0. PRs welcome for that.

**Comment by kflak** [comment]
Great, thanks a lot!

For some reason I just didn't notice the `device` parameter in the wiki. My bad.
