### ISSUE TITLE
pacman default string no longer valid

### ISSUE THREAD

**Issue by hellow554** [greshake/i3status-rust#1238]
My pacman block looks like this:

```
[[block]]
block = "pacman"
```

Now the following happens:

```
i3status-rs
{"version": 1, "click_events": true}
[
[{"full_text":" Internal error in context 'util': Unknown placeholder in format string: pacman ","color":"#dc322f","background":"#000000","name":"0","instance":"0","separator":false,"separator_block_width":0,"markup":"pango"}],


Internal error in context 'util': Unknown placeholder in format string: pacman
```

There seems to be an issue with the default string of the block. 

---

Version: i3status-rs 0.20.1 (commit 67238c5 2021-05-13)

**Comment by hellow554** [comment]
Seems to be introduced by #1220 @mpldr because 0.20.0 works perfectly fine

**Comment by ammgws** [comment]
This bisects to 67238c5859959e1dce074dbf2d3182c15e127376 which is the `short_text` support by @GladOSkar 

IIRC some stuff in the pacman block was refactored so that's probably where it went wrong

**Comment by GladOSkar** [comment]
`PacmanConfig::any_format_contains!("pacman")` for the default format ("{pacman}") returns `false` which results in an ampty map passed to `FormatTemplate::render()`. Debugging now.

**Comment by ammgws** [comment]
Yeah until it's fixed can work around it by manually specifying `format = "{pacman}"

**Comment by GladOSkar** [comment]
Ah yes `PacmanConfig::watched()` was using a version of the `FormatTemplate` that didn't include the default format. PR inbound:

**Comment by GladOSkar** [comment]
If one of y'all using `pacman` could test it that'd be appreciated

**Comment by Noah-Kennedy** [comment]
Seems like it is still happening on my system on 0.20.1.

**Comment by hellow554** [comment]
@Noah-Kennedy in my post I stated that my version is 0.20.1, so yeah ;)

**Comment by GladOSkar** [comment]
0.20.1 was released before this fix was introduced and therefore doesn't include it.

You'll either have to wait for the next release (@ammgws ?) or build it yourself from source. Sorry!
