### ISSUE TITLE
Formatting net block with consistent units and width

### ISSUE THREAD

**Issue by 12ian34** [greshake/i3status-rust#1243]
Hello. 

Perhaps I'm missing something, or I'm dense, or just having a bad day but I'm genuinely finding it difficult to understand how to use the new Formatting documentation, particularly in application to the net block. Here are my ideal requirements:
- Fix the block's width to avoid shifting the rest of my bar around every second as the download/upload speed length strings change.
- Have a space between the number and the units (see #1242) and ensure the units are "b", "kb", "Mb", "Gb".
- Scale between b, kb, Mb, Gb 

Here's where I'm at now: 
`format = "{speed_down:2;n*_b} b {speed_up:2;n*_b} b"`

Which leads to this:
![image](https://user-images.githubusercontent.com/9979944/118482999-66145b00-b70d-11eb-833a-0a0eebb7685a.png)

I appreciate that not all my requirements might be possible, but I'd really appreciate any help that could be provided further to the Formatting documentation. I'm not demanding any changes, I just feel like I might be missing something which could get me most of the way. 

Many thanks,

**Comment by GladOSkar** [comment]
Hi! Thanks for the issue. It's true that your use case is not covered by the new formatting (yet), mostly because of the space you want before the unit. All the other stuff works correctly, right?

@MaxVerevkin any idea if/how we could incorporate this? Maybe a `" "` modifier in the unit field, like `{var* b}`?

**Comment by GladOSkar** [comment]
Oh i see you want `k` for kilos instead of `K`. Is that important? I see it's correct according to SI/NIST but doesn't really make sense to me, i like the larger than 1 / lower than 1 separation using case.

**Comment by MaxVerevkin** [comment]
I also like `K` more. But having an option to override it would be neat (back to the old idea of "`x_overrides`").

**Comment by GladOSkar** [comment]
Yeah in that case it definitely makes sense to override it globally

**Comment by 12ian34** [comment]
Thanks for also looking into this one @GladOSkar / @MaxVerevkin ! Really appreciate the support and discussion from you two. 

On `k` vs `K`, indeed lowercase is correct but it's honestly not a big issue for me (and I presume most others). The annoyance for me is the width change. I increased the min width to 3 and got rid of the gap before the "b" (user error!) but the bar still jumps when the speed changes between a number in the order of bits and a number in the order of kilobits, because this change involves adding/removing a letter. For reference my current config is below:
`format = "{speed_down:3;n*_b}b {speed_up:3;n*_b}b" `

It seems that the min width only applies to the number, perhaps it should be expanded to also include any inherent denomination of the value (e.g. "K", "M", "G" for kilo/mega/giga). I think this would solve the jumping.

**Comment by MaxVerevkin** [comment]
> `format = "{speed_down:3;n*_b}b {speed_up:3;n*_b}b"`

You can force "K" prefix with the following config:

```toml
format = "{speed_down:3;K*_b}b {speed_up:3;K*_b}b"
```

**Comment by GladOSkar** [comment]
Ahhh interesting. I hadn't thought of that but yes that kind of makes sense

I only see 2 solutions: Either (as you suggest) count the unit width to the `min_width` (which i imagine might be pretty difficult algorithmically because then the unit formatting and the number formatting both require each other's before doing their own layout) or add a space after the unit if the prefix value is `1`, which is probably far easier and IMO good enough

**Comment by 12ian34** [comment]
@MaxVerevkin ah, ok, so I've implemented that (using "M" instead of "K" and a min width of 4). @GladOSkar It is indeed a bit of a workaround but I'm happy the jumping has stopped. Adding a space after the unit does seem like it could cause problems for other users.

I'm not sure on the algorithmic complexity of your first proposed solution, but I will say it does feel more elegant to account for a sometimes-present character in the min width parameter.

For now, my most pressing problem of width jumping is resolved as per the forced prefix option, we're dealing with space separately in #1242, and the forced prefix isn't a big problem for me. Perhaps it's pragmatic to park this for now and reconsider if any similar or wider requirements appear in the future. 

Meanwhile, perhaps my example above would be useful to add to the Formatting docs, since they currently lack real world examples consisting of multiple different formatting bits stitched together - this would have been helpful for me and I imagine other users.

**Comment by MaxVerevkin** [comment]
> `format = "{speed_down:3;K*_b}b {speed_up:3;K*_b}b"`

How is it different from
```toml
format = "{speed_down:3;K*b} {speed_up:3;K*b}"
```
?

> would be useful to add to the Formatting docs,

I think PRs extending the docs are always welcome :)

**Comment by 12ian34** [comment]
>... How is it different from ...
@MaxVerevkin ha... good point!

> I think PRs extending the docs are always welcome :)
Sure, happy to do this I'll get something in soon!
