### ISSUE TITLE
Discussion: home expansion for block paths

### ISSUE THREAD

**Issue by mplanchard** [greshake/i3status-rust#1246]
Hello!

I was wondering how y'all would feel about a PR to automatically expand paths in the various blocks to allow specification of paths like `~/mail/gmail/Inbox` or similar.

The use case for me personally is so that I can easily check my `i3status-rust/config.coml` into my git-tracked dotfiles and have it work on systems with a variety of usernames.

We could use something like [shellexpand](https://docs.rs/shellexpand/2.1.0/shellexpand/) to do the hard work, and we could potentially limit expansion to _just_ the tilde, rather than also interpolating in env vars, to keep things simple. Alternatively we could manually look for the `~` at the beginning of the path and use the existing `xdg_config_home()` utility function to replace it.

The implementation could either do the expansion at the point of the `ConfigBlock::new()` or the point of config deserialization using `deserialize_with`. The type could remain `String` for simplicity of integrating with any existing code, or we could turn it into a `Path` or some custom struct (with appropriate `From` impls) if desired to provide a semantic hint that it's not a normal string.

Let me know if there's interest here and if so what approach y'all would like to see, and I'd be happy to work on it.

**Comment by ammgws** [comment]
Which blocks would benefit from this apart from maildir?

**Comment by ammgws** [comment]
@mplanchard We now will soon include `shellexpand` once #1325 is merged, so you can start on this if you want.

**Comment by mplanchard** [comment]
Thanks a ton! Work's gotten pretty busy recently, so I can't guarantee
speedy progress, but I will work on it in fits and starts.

**Comment by ammgws** [comment]
Now that we depend on shellexpand and already have some blocks using it, we just need to go through the remaining blocks and add the functionality. (and add docs where necessary)

**Comment by MaxVerevkin** [comment]
Implemented in #1453
