### ISSUE TITLE
Improvements for Battery-Block

### ISSUE THREAD

**Issue by SebTM** [greshake/i3status-rust#1254]
I'm currently sed-patching `sed -i "s/{}:{:02}/ | {}:{:02}h/" src/blocks/battery.rs` while building with nix-overlays so I can have a separator and hour-unit after time which is only shown when there is something to show.

Besides this I'm experiencing issues with empty time on 99% and never turning 100% (on some not original ac-adapter | Thinpad T14s - AMD).

So my Ideas are:
- Adding support for seconds/minutes/hours in https://github.com/greshake/i3status-rust/blob/master/doc/blocks.md#formatting
- Maybe another formatting-option to be able to prepend a string only shown while the variable is not empty?
- Option for battery-block which makes an offset between full calculated and full shown possible?

**Comment by ammgws** [comment]
> I'm experiencing issues with empty time on 99% and never turning 100% (on some not original ac-adapter | Thinpad T14s - AMD).

Perhaps create another issue for this if you are implying it's an issue with our calculations. Or is it purely a hardware limitation that causes it to only show up to 99%?

>     * Option for battery-block which makes an offset between full calculated and full shown possible?

What do you mean by this? To set the full threshold to something less than 100%, e.g. I guess in your case you would set it to 99%?

>     * Adding support for seconds/minutes/hours in https://github.com/greshake/i3status-rust/blob/master/doc/blocks.md#formatting
>     * Maybe another formatting-option to be able to prepend a string only shown while the variable is not empty?

@MaxVerevkin What do you think about these?

**Comment by MaxVerevkin** [comment]
> Adding support for seconds/minutes/hours

How exactly do you expect it to work? Can you give some details?

**Comment by GladOSkar** [comment]
> To set the full threshold to something less than 100%, e.g. I guess in your case you would set it to 99%?

"Full" is currently not determined by percentage, but by `BAT0/status == 'Full'`. I recently also had to swap my battery for an aftermarket one and it now also doesn't set 'Full', but switches the `status` to `'Unknown'` once it stops charging, so i'm currently patching this as well:

```diff
diff --git a/src/blocks/battery.rs b/src/blocks/battery.rs
index 8b702f3..846e6c5 100644
--- a/src/blocks/battery.rs
+++ b/src/blocks/battery.rs
@@ -658,7 +658,7 @@ impl Block for Battery {
             },
         );
 
-        if status == "Full" || status == "Not charging" {
+        if status == "Full" || status == "Not charging" || status == "Unknown" {
             self.output.set_icon("bat_full")?;
             self.output.set_texts(self.full_format.render(&values)?);
             self.output.set_state(State::Good);
```

**Comment by SebTM** [comment]
@ammgws I don't thought there is something wrong with the calculation but I switched to upower for several reasons and there it works better and I get the 100%/Full like expected... So maybe? Yeah my thought was to say if it is 99% and connected show as full or if possible more precise like 0.X (what might be missing) ...

@MaxVerevkin I thought about something like [this](https://github.com/greshake/i3status-rust/blob/master/doc/blocks.md#_unit) for time would maybe possible but as I'm not into the code/rust I'm not sure that it is...

@GladOSkar Thanks, I will try "Not charging" this might be an alternative!

**Comment by GladOSkar** [comment]
Check `cat /sys/class/power_supply/*/status` to see what status your battery driver is actually reporting

**Comment by MaxVerevkin** [comment]
> I thought about something like [this](https://github.com/greshake/i3status-rust/blob/master/doc/blocks.md#_unit) for time would maybe possible but as I'm not into the code/rust I'm not sure that it is...

There is already a "seconds" unit, so we can add units like "hours", "days" etc. But to achieve formatting like "01:12" (I guess) we will have to also add "special" units like "time" and "date_time" or something like that.

For example, if placeholder `var` has a value of 1 hour 25 minutes, then
Formatting string | Result
-|-
`"{var*h}"` | `1.42h`
`"{var*m}"` | ` 85m`
`"{var*s}"` | `5100s`
`"{var*time}"` | `01:25`

Did I get you right?

**Comment by ammgws** [comment]
@GladOSkar since status seems so unreliable shouldn't we just add "|| percentage >= full_percentage" to the condition? Full_percentage could be configurable if need be (actually wasn't there someone who wanted that? They were running some battery management thing where it doesn't charge the battery to 100 but stops short or something like that)

**Comment by SebTM** [comment]
Yeah, that's it! if time could get some extensions like h/m based on value this would be nice, too - as this is my use case for battery showing the whole time with unit 👍🏻

**Comment by GladOSkar** [comment]
True, that was a usecase and is probably an easy fix. Can look into it tomorrow

**Comment by ammgws** [comment]
Moved formatting enhancement discussion to new issues.
