### ISSUE TITLE
[bluetooth block] force connect on click

### ISSUE THREAD

**Issue by BrendanBall** [greshake/i3status-rust#1256]
for bluetooth devices I sometimes have to force connect when it doesn't connect automatically (don't ask me why), e.g. for my galaxy buds. When this happens I currently open blueberry to force connect.
Does it make sense to allow the bluetooth block to be clickable and optionally force connect on click?

**Comment by ammgws** [comment]
Is force connecting it different to this:

> Right-clicking the block will attempt to connect (or disconnect) the device.
(from https://github.com/greshake/i3status-rust/blob/master/doc/blocks.md#bluetooth)

?

Also, if/once https://github.com/greshake/i3status-rust/issues/1038 is done then all blocks will become clickable.

**Comment by BrendanBall** [comment]
No it's not different, my apologies, I missed that. I'm pretty sure I also actually tried that before and it didn't seem to do anything, maybe I was only left clicking. It is working now that I tried again :)
