### ISSUE TITLE
Powerline - How can I get colored arrows to work.

### ISSUE THREAD

**Issue by robcohen** [greshake/i3status-rust#126]
Hello, and first of all fantastic work. I really think this project is very cool and I hope to make some contributions soon.

My problem is that I cannot seem to figure out how to get the colored arrows to work like in [the example](https://raw.githubusercontent.com/XYunknown/i3status-rust/master/img/example_bar.png).

I did run
```
pacman -S powerline-fonts
```

But  for the life of me I cannot figure out how to actually make the config.toml implement this. I think it may have something to do with tinting different themes, but I cannot figure it out.

Here are my relevant configs:

## ~/.config/i3status-rs/config.toml
```
theme = "solarized-dark"
icons = "awesome"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"
```

## ~/.config/sway/config [bar section only]
```
bar {
      font pango:DejaVu Sans Mono, Icons 12
      position bottom 
      status_command /usr/bin/i3status-rs ~/.config/i3status-rs/config.toml
      colors {
            separator #666666
            background #222222
            statusline #dddddd
            focused_workspace #0088CC #0088CC #ffffff
            active_workspace #333333 #333333 #ffffff
            inactive_workspace #333333 #333333 #888888
            urgent_workspace #2f343a #900000 #ffffff
      }
}
```

Any guidance would be appreciated.

**Comment by atheriel** [comment]
Just to help understand what you mean: The colours in the example are due to the actual states of the blocks -- light blue for "info", yellow for "warning" (because CPU usage is high), and red for "critical" (because load very high). Normally all of these colours are much more muted.

Or is the problem that your powerline arrows are not rendering at all? Or that they are a different colour from their adjacent blocks?

**Comment by robcohen** [comment]
I apologize, I thought the coloring was set manually. I understand a bit more after [reading this part of the wiki](https://github.com/greshake/i3status-rust/blob/master/blocks.md).

I am a little unclear still on how the thresholds are set.
For example, in the disk_space block below, how would I set a warning for the disk space available being ~10% or say 10GB?

Thank you in advance!

```
[[block]]
block = "disk_space"


path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
```

**Comment by atheriel** [comment]
Some blocks support setting the thresholds, some do not, and unfortunately the documentation is incomplete. In this case you can set the block to warn when disk space falls below 10GB with `warning = 10` (20 is the default). You can set the "critical" warning with `alert = 10` (default 5). At least, that's what the source code seems to say.

**Comment by robcohen** [comment]
Thank you for the explanation. I understand now where to check in the future, thank you.
Perhaps I can contribute by documenting the blocks a bit. Thank you for your help.
