### ISSUE TITLE
formatter: allow to enforce the unit suffix

### ISSUE THREAD

**Issue by regazzoj** [greshake/i3status-rust#1262]
Hello ! 

Thanks for this amazing status bar, I really enjoy to use it :D

I am here because I don't know how to show memory in megabytes instead of gigabytes.

My block looks like this: 
```
[[block]]
block = "memory"
format_mem = "{mem_used;M}/{mem_total;M}"
format_swap = "{swap_used;M}/{swap_total;M}"
display_type = "memory"
icons = true
clickable = true
interval = 5
warning_mem = 80
warning_swap = 80
critical_mem = 95
critical_swap = 95
```
My memory block looks like that :
![memory](https://user-images.githubusercontent.com/6738167/122081258-41400000-cdff-11eb-8e6f-6ec9645e0f7d.png)

I don't know if it's just me blind to see my mistake, or something else ?!

Thanks for reading me.

**Comment by GladOSkar** [comment]
The prefix you specify is just the minimum prefix, i.e. it will never show units smaller than a `GB` in your case, but it will scale up if the value is high enough. Until now we didn't see a usecase for setting a max/fixed prefix.

Can you explain why you'd prefer megabytes to gigabytes?

**Comment by MaxVerevkin** [comment]
From #1248:

>Future idea - we can add another modifier to "min prefix" config to force the prefix (i.e. actually set it to a specific value). This makes a ton of sense when using `_` modifier. For example, `"{key;+_G}"` may be used to _force_ the prefix to "G" and hide it.
>
>_Originally posted by @MaxVerevkin in https://github.com/greshake/i3status-rust/issues/1248#issuecomment-846374706_

**Comment by regazzoj** [comment]
@GladOSkar I'm pretty sure before the last release (0.20.1), my status bar was displaying my memory in MB.
I was using the format `{MTm}` at that moment, so after the update I changed it to `{mem_total;M}` like mentionned in the `Removed Format Keys` grid [here](https://github.com/greshake/i3status-rust/blob/master/doc/blocks.md#memory).

To answer your question, I prefer MB to GB because it is clearer for me than a float.
i.e. `2.3015GB` => `23015MB`
In fact, my problem was the rounded numbers, I used to have more precision so it was not what I was used to at first.

Then I tried what you wrote to get more decimals, and it is exactly what I wanted !
I didn't know about this before you told me.
I couldn't find anything in the doc on the memory block about precision, is it somewhere else ?

One last question, the number `:6` is how much digit at most will be displayed, am I right ? 

Thanks a lot, I really appreciate your help !

**Comment by GladOSkar** [comment]
It's documented in the [formatting section](https://github.com/greshake/i3status-rust/blob/master/doc/blocks.md#formatting) of the blocks documentation.

The number is not the digits but the characters of the number, so `1.23M` would be `:4` (3 digits + 1 decimal point)

**Comment by regazzoj** [comment]
Okay, I missed this section...
I am sorry for my mistake.

Thanks a lot for your answers and help ! :pray:

**Comment by ammgws** [comment]
All solved?

**Comment by MaxVerevkin** [comment]
> All solved?

Not really. We still don't have a way to set the prefix to a concrete value.

**Comment by ammgws** [comment]
This should be solved with the async branch that was just merged into master (still some work to do before a release is possible though).
