### ISSUE TITLE
low prio - question - theme selection gives error

### ISSUE THREAD

**Issue by ObiWahn** [greshake/i3status-rust#1263]
Hi,
I have upgraded i3status-rust after some time and now I get the following error when starting:

`{"full_text":" Configuration error: failed to parse TOML from file contents. Cause:  Theme 'plain' not found. for key `theme` at line 63 column 1 ","name":"0","instance":"0","separator":false,"separator_block_width":0,"markup":"pango"}],`

The configuration was working fine before and `plain` and `modern` (the theme I usually use) are still listed in available themes in the `themes.md` file. Maybe I made a mistake during installation or the configuration has changed. I really guess this is not really broken, but a problem on my side.

**Comment by ammgws** [comment]
See notes about copying theme files: https://github.com/greshake/i3status-rust/blob/master/NEWS.md
