### ISSUE TITLE
Future weather

### ISSUE THREAD

**Issue by frjonsen** [greshake/i3status-rust#1267]
The weather widget only supports fetching the current weather. It could be useful to add support for forecasts, something the openweathermap API seems to support as well.

Configuration wise this could simply be done as a single option, something like `forecast`, defaulting to `0` for the current weather, or taking a number in some time scale. The API has the [/onecall endpoint](https://openweathermap.org/api/one-call-api) returns forecasts for up to seven days, but I would guess most users are only interested in either the next few hours, or something more specific, such as "tomorrow afternoon".

The current implementation seems to be using the `/weather` endpoint, but that one does not support hourly forecasts in the free tier, unlike the `/onecall` endpoint. Switching to *only* use the `/onecall` endpoint would probably make the implementation easier, but it does reduce the number of daily calls. However, even for the free tier, it still allowed for 30,000 per month / 1,000 per day, which would probably be enough for most users even if they reuse the same API key on multiple computers.

The big difference between the two is that the `/onecall` endpoint does not support getting location by city id. It *only* accepts coordinates. As far as I could tell, they don't have an API for converting a city ID into coordinates. They do have a geocoding API, but that takes `{zip code},{country code}`. It would, regardless, be a breaking change, but that still seems preferable than supporting different config options for different endpoints, depending on whether the user wants forecasts or not.

If this sounds at all useful, I'd be happy to give implementing this a shot myself. If so I would also like to add support for showing UV Index, but since that's included in the data that's already being fetched I didn't feel like it warranted it's own issue.

**Comment by ammgws** [comment]
I started doing something like that a while ago but I was only interested in the forecast for the upcoming weekend and never got around to figuring out the details for how the format qualifier would work.

https://github.com/ammgws/i3status-rust/commit/862e9498086611ec5cd8d76577927e8a0138cabb

I think you can find a way to implement it without causing a breaking change, give it a go.

**Comment by frjonsen** [comment]
I think there are two alternatives for avoiding a breaking change:

1. Limit the feature to using the "3-hour Forecast 5 days". This also doesn't include UV index, but I suppose that was not the main point of this.
2. Make a single call to the `/weather` endpoint using the city id (either eagerly at launch or lazily at the first refresh). The result contains coordinates, which can be cached and used to call the `/onecall` endpoint instead, which offers better granularity and more data

**Comment by ammgws** [comment]
I think option 2 would be good since even with the extra API call I doubt anyone would get near 1000 hits a day (unless you set the interval below 3 or so minutes). Is the coordinates info always there? I think I may have looked into it before but found it unreliable.

**Comment by ammgws** [comment]
@frjonsen How did you go?

**Comment by frjonsen** [comment]
As always, time has been a constraint, but I have at least made some progress: https://github.com/frjonsen/i3status-rust/commits/master

**Comment by frjonsen** [comment]
Closing this as a cleanup measure, since it's been a long time since I worked on it and I'm no longer using i3

**Comment by bim9262** [comment]
I am working on implementing this now :)
