### ISSUE TITLE
Networkmanager block no longer updating with NetworkManager v1.32.0

### ISSUE THREAD

**Issue by auguste42** [greshake/i3status-rust#1269]
After upgrading to NetworkManager 1.32.0 from 1.30.4, the NetworkManager block no longer updates on connection changes. Downgrading to 1.30.4 fixes the issue so there must be some breaking change in the new version.

**Comment by ammgws** [comment]
https://github.com/NetworkManager/NetworkManager/blob/main/NEWS

Perhaps this?

> NetworkManager-1.32
> Overview of changes since NetworkManager-1.30
> * API CHANGE: D-Bus: remove long deprecated "PropertiesChanged" signal from D-Bus
>   API. They are replaced by standard "PropertiesChanged" signal on the
>   "org.freedesktop.DBus.Properties" interface. It is not expected that anybody
>   is still using this API.
