### ISSUE TITLE
Pango font rendering seemingly broken

### ISSUE THREAD

**Issue by starcraft66** [greshake/i3status-rust#1275]
After updating to 0.20.2, my status bar font started looking like this:

<img width="469" alt="image" src="https://user-images.githubusercontent.com/1858154/125208807-b538c100-e262-11eb-8264-99b77ca66081.png">

In my config, I have my font set to `pango:MesloLGS Nerd Font Mono`. If I change it to `MesloLGS Nerd Font Mono`, my font is displayed but the spacing is wrong:

<img width="459" alt="image" src="https://user-images.githubusercontent.com/1858154/125208792-a4884b00-e262-11eb-9315-42f91d68f541.png">

**Comment by ammgws** [comment]
What did it look like before? I think previously only certain widgets had pango enabled by default, but now all widgets do, so it could be that?

**Comment by Savanta** [comment]
Something definitely broke, some icons went missing others are displaying wrong symbols.
My i3config bar
`bar {
    font pango:"MesloLGS NF" 10 
    position top
    height 20
    status_command sleep  2 ; /usr/bin/i3status-rs ~/.config/i3status-rs/config.toml
    colors {
        separator #666666
        background #222222
        statusline #dddddd
        focused_workspace #0088CC #0088CC #ffffff
        active_workspace #333333 #333333 #ffffff
        inactive_workspace #333333 #333333 #888888
        urgent_workspace #2f343a #900000 #ffffff
    }`
My i3status-rust config
`theme = "gruvbox-dark"

[icons]
name = "awesome"
[icons.overrides]
phone_disconnected = ""
music = ""
volume-muted = ""

[[block]]
block = "music"
player = "spotify"
format = "{title}" 
buttons = ["prev", "play", "next"]
dynamic_width = true
max_width = 30
on_collapsed_click = "spotify"

[[block]]
block = "kdeconnect"
format = "{bat_charge} {notif_icon}{notif_count}"
format_disconnected = ""

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = "{icon} {available}"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used_percents}"
format_swap = "{swap_used_percents}"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "temperature"
collapsed = true
interval = 10
format = "{min} , {max} , {average}"
chip = "*-isa-*"

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "sound"

[[block]]
block = "backlight"
device = "acpi_video0"

[[block]]
block = "battery"
driver = "upower"
format = "{percentage} {time}"

[[block]]
block = "weather"
format = "{weather} {temp}"
service = { name = "openweathermap", api_key = "5459334c36f8e5453769936e08f54d8e", city_id = "3087584", units = "metric" }

[[block]]
block = "time"
interval = 5
format = "%a %d/%m %R"
`
Here how it looks like
![image](https://user-images.githubusercontent.com/13687101/132090440-5388da27-b55a-4b7f-9b89-9aa9203c447d.png)

**Comment by ammgws** [comment]
Is the JSON output correct if you run it in a terminal?

**Comment by Savanta** [comment]
Yes it is

**Comment by Savanta** [comment]
Additional info
![image](https://user-images.githubusercontent.com/13687101/132091761-e5679c82-af56-495a-82d2-1cc9d43f792d.png)

**Comment by ammgws** [comment]
If the JSON is correct then it's not i3status-rust. It would be i3bar or your installed fonts or perhaps something else

**Comment by starcraft66** [comment]
Sorry for opening this here, it turned out to be a NixOS issue in my case that was fixed here: https://github.com/NixOS/nixpkgs/issues/129724.

Closing.
