### ISSUE TITLE
No clear way to set transparent background ?

### ISSUE THREAD

**Issue by rambip** [greshake/i3status-rust#1276]
The color of my i3 bar depend on a variable in my Xressourses files.

So I wanted to override the background of the bar to none.

I tried `bg = none`, `bg = "none"`, `bg = "0", `bg= "#00000000"` but none of them worked.
How can I do that ?

**Comment by GladOSkar** [comment]
The background should be transparent if you just don't set it. See for example the `native` and `semi-native` themes.

An alternative way, if you have a compositor, is to use the alpha channel: `#00000000` - But I'm not sure how well that works currently.

Lastly, remember that if `i3status-rs` makes its blocks transparent, you will still see i3bar's color behind it, and i don't know if it's possible to make i3bar transparent.

**Comment by rambip** [comment]
That's not exactly what I asked (sorry if that wasn't clear)
I would like to use a theme, and "unset" a color by overriding it.
If I use the `material` theme and I just want to make the background transparent, I can't tell rust that I want this parameter to be unset, I have to start everything from scratch.
The better behaviour would be to make rust understand "unset" when someone write `bg="none"` in an override

**Comment by GladOSkar** [comment]
Ah okay i understand. That seems useful, maybe someone who knows `serde` better than me can say how easy it would be to implement.

Did you try the color code with the alpha channel set to `0`?

**Comment by GladOSkar** [comment]
After taking a quick glace at the code and TOML's documentation implementing a way to unset a color value appears to be harder than i thought.

TOML has no built-in `nil`/`none` value, so we'd have to use a specific value like `"none"`. But as far as i can see in the current code, color values are read and processed in multiple places and there is no (central) place that parses them, they're essentially directly passed to `i3`/`sway`. So this would require a bunch of changes i think.

@ammgws @MaxVerevkin thoughts?

**Comment by MaxVerevkin** [comment]
@GladOSkar I think adding a special case somewhere here is sufficient?  https://github.com/greshake/i3status-rust/blob/974212179519feeaadd3fd7a9672d7475694e306/src/themes.rs#L173-L178

**Comment by MaxVerevkin** [comment]
@GladOSkar Or we can write a custom serde deserializer for `Option<String>` that will parse `Some("none")` to `None`.

**Comment by MaxVerevkin** [comment]
Actually, I prefer second approach as we may want to extend color parsing in the future to allow, for example color names in config (IDK if anyone actually needs this).

**Comment by GladOSkar** [comment]
> https://github.com/greshake/i3status-rust/blob/974212179519feeaadd3fd7a9672d7475694e306/src/themes.rs#L173-L178

Pretty sure that doesn't cover block-level overrides? But yeah it's a start. We'd then need to do the same here i guess? Not entirely sure:

https://github.com/greshake/i3status-rust/blob/974212179519feeaadd3fd7a9672d7475694e306/src/config.rs#L35-L59

**Comment by GladOSkar** [comment]
I agree using a serde deserializer is probably the best way to do it

**Comment by MaxVerevkin** [comment]
By the way, it might be worth trying [`palette`](https://lib.rs/crates/palette) to partially address this TODO (it also supports string-to-color mapping)
https://github.com/greshake/i3status-rust/blob/974212179519feeaadd3fd7a9672d7475694e306/src/util.rs#L186

**Comment by MaxVerevkin** [comment]
I think https://github.com/MaxVerevkin/swaystatus/commit/1c2516abeee95a7c6f42cac59b1b186c9698fe68 should cover all cases. Both `color=""` and `color="none"` are supported. @GladOSkar will you have some time to port it? I'm not sure I will have.

**Comment by GladOSkar** [comment]
Looks very good at a glance, thanks!

Not sure if I'll have time this week and definitely not next week, we'll see. But I'll do it at some point

**Comment by GladOSkar** [comment]
Alright my port is at [GladOSkar/i3status-rust/theme-unset-colors@9bcc267](https://github.com/GladOSkar/i3status-rust/commit/9bcc267828fca2d8effe08040a96571a95b39f39).

Unfortunately it doesn't work and i wasn't able to fix it. Probably won't have time soon either. Problems are:

- [ ] Color values from theme/overrides seem to still be directly passed through to the i3bar protocol output
- [ ] Crashes immediately when using alternating tint

**Comment by MaxVerevkin** [comment]
@GladOSkar ...works for me? :eyes:

**Comment by MaxVerevkin** [comment]
There is a little issue with separator's background, but it's somewhere in my code, not your port. 
![image](https://user-images.githubusercontent.com/34583604/126082465-ae5fd6d7-4877-4dcb-9d13-5faea12483c0.png)

Config:
```toml
icons_format = " <span font_family='NotoSans Nerd Font'>{icon}</span> "

icons = "material-nf"
[theme]
name = "modern"
[theme.overrides]
alternating_tint_bg = "none"
alternating_tint_fg = "#AA1111"

[[block]]
block = "time"

[[block]]
block = "focused_window"
[block.theme_overrides]
idle_bg = "none"
```

**Comment by GladOSkar** [comment]
> @GladOSkar ...works for me? eyes

That's weird... I have this:

Test case 1:
```
icons = "awesome"

[theme]
name = "modern"
[theme.overrides]
idle_bg = "none"

...
```
produces:
```
env RUST_BACKTRACE=1 i3status-rs
{"version": 1, "click_events": true}
[
[{"full_text":"","color":"none","separator":false,"separator_block_width":0,"markup":"pango"},{"full_text":"...","color":"#CFD8DC","background":"none","name":"1","instance":"1","separator":false,"separator_block_width":0,"markup":"pango"},...
```
(note the `"background":"none"`)

Test case 2:
```
icons = "awesome"

[theme]
name = "slick"
[theme.overrides]
idle_bg = "none"

...
```
produces
```
env RUST_BACKTRACE=1 i3status-rs
{"version": 1, "click_events": true}
[
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ParseIntError { kind: InvalidDigit }', src/protocol/mod.rs:52:22
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/panicking.rs:92:14
   2: core::option::expect_none_failed
             at /rustc/9bc8c42bb2f19e745a63f3445f1ac248fb015e53/library/core/src/option.rs:1329:5
   3: i3status_rs::protocol::print_blocks::{{closure}}
   4: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
   5: i3status_rs::protocol::print_blocks
   6: i3status_rs::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by MaxVerevkin** [comment]
That's interesting because both testcases produces somewhat expected results for me:
### Test case 1
![image](https://user-images.githubusercontent.com/34583604/126083059-649c93e8-48d8-4edd-9c1c-25757b9a4210.png)
### Test case 2
![image](https://user-images.githubusercontent.com/34583604/126083069-00a703f2-5caf-48bf-9213-2d9b605e0eb5.png)

**Comment by GladOSkar** [comment]
That's... odd... The first might be a `sway` thing? What's your output? If there a `"background"` key in there?

The latter must be on rust's side. I'll update rust in a sec

**Comment by MaxVerevkin** [comment]
@GladOSkar silly question but are you sure you are running the correct build? `thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ParseIntError { kind: InvalidDigit }', src/protocol/mod.rs:52:22` suggests that you are running previous version that converts colors on every print and unwraps the result on line 52, but line 52 on your branch doesn't contain any unwraps().

**Comment by GladOSkar** [comment]
sh$^$(!"&*^% you're right

**Comment by GladOSkar** [comment]
I was wondering and wondering about that exact same thing, but totally forgot my `i3status-rs` symlink always goes to the release binary. I should go to bed lol

**Comment by MaxVerevkin** [comment]
Yeah, that happens :)

**Comment by GladOSkar** [comment]
> little issue with separator's background

I don't think that's fixable as the foreground of the separator would need to take on the background of the bar, which we don't know.

**Comment by GladOSkar** [comment]
@rambip does #1279 solve your problem? You should be able to use a config like this with it:

```
[theme]
name = "<your_theme>"
[theme.overrides]
idle_bg = "none"

<your_blocks>
```
