### ISSUE TITLE
Weird sign on the status bar

### ISSUE THREAD

**Issue by iliesh** [greshake/i3status-rust#1278]
There is a weird sign at the starting line of the status bar, anyone have an idea  why?
![image](https://user-images.githubusercontent.com/14953151/126037299-f14e637d-a755-4c25-8f30-b7f789496d81.png)

This is the configuration I'm using:

theme = "solarized-light"
[[block]]
block = "sound"

$ i3status-rs --version                                   
i3status-rs 0.20.2 (commit 00e8084 2021-06-28)

**Comment by GladOSkar** [comment]
Probably your font. Which one are you using? (It's specified in your i3/sway config)

**Comment by iliesh** [comment]
I was using this font:
font pango:DejaVu Sans Mono, FontAwesome 10

I changed it to:
font pango:DejaVu Sans Mono 8 

and no changes.

➜  ~ fc-list | grep -i 'awesome'
/usr/share/fonts/opentype/font-awesome/FontAwesome.otf: FontAwesome:style=Regular
/usr/share/fonts/truetype/font-awesome/fontawesome-webfont.ttf: FontAwesome:style=Regular

**Comment by GladOSkar** [comment]
In your confiiguration, do you have

```
[icons]
name = "awesome"
```

set? Or if you're using FontAwesome 5+ `name = "awesome5"`?

**Comment by GladOSkar** [comment]
Oh wait no the issue is probably that you're missing the powerline font extension.

You can either find a patched fonts [here](https://github.com/powerline/fonts) that you could then patch into your FontAwesome font, or, much easier, use NerdFonts as they have all icons from FontAwesome, Material and Powerline combined: https://www.nerdfonts.com/

**Comment by iliesh** [comment]
I installed NerdFonts as you suggested, but still no changes. 

➜  Downloads ls -l ~/.fonts
total 13896
-rw-rw-r-- 1 ubuntu ubuntu 1139916 Jan 26  2020 'DejaVu Sans Mono Bold Nerd Font Complete Mono.ttf'
-rw-rw-r-- 1 ubuntu ubuntu 1139944 Jan 26  2020 'DejaVu Sans Mono Bold Nerd Font Complete Mono Windows Compatible.ttf'
-rw-rw-r-- 1 ubuntu ubuntu 1165720 Jan 26  2020 'DejaVu Sans Mono Bold Nerd Font Complete.ttf'
-rw-rw-r-- 1 ubuntu ubuntu 1165780 Jan 26  2020 'DejaVu Sans Mono Bold Nerd Font Complete Windows Compatible.ttf'
-rw-rw-r-- 1 ubuntu ubuntu 1066760 Jan 26  2020 'DejaVu Sans Mono Bold Oblique Nerd Font Complete Mono.ttf'
-rw-rw-r-- 1 ubuntu ubuntu 1066764 Jan 26  2020 'DejaVu Sans Mono Bold Oblique Nerd Font Complete Mono Windows Compatible.ttf'
-rw-rw-r-- 1 ubuntu ubuntu 1092268 Jan 26  2020 'DejaVu Sans Mono Bold Oblique Nerd Font Complete.ttf'
-rw-rw-r-- 1 ubuntu ubuntu 1092304 Jan 26  2020 'DejaVu Sans Mono Bold Oblique Nerd Font Complete Windows Compatible.ttf'
-rw-rw-r-- 1 ubuntu ubuntu 1149180 Jan 26  2020 'DejaVu Sans Mono Nerd Font Complete Mono.ttf'
-rw-rw-r-- 1 ubuntu ubuntu 1149208 Jan 26  2020 'DejaVu Sans Mono Nerd Font Complete Mono Windows Compatible.ttf'
-rw-rw-r-- 1 ubuntu ubuntu 1175040 Jan 26  2020 'DejaVu Sans Mono Nerd Font Complete.ttf'
-rw-rw-r-- 1 ubuntu ubuntu 1175100 Jan 26  2020 'DejaVu Sans Mono Nerd Font Complete Windows Compatible.ttf'
-rw-rw-r-- 1 ubuntu ubuntu 1065500 Jan 26  2020 'DejaVu Sans Mono Oblique Nerd Font Complete Mono.ttf'
-rw-rw-r-- 1 ubuntu ubuntu 1065516 Jan 26  2020 'DejaVu Sans Mono Oblique Nerd Font Complete Mono Windows Compatible.ttf'
-rw-rw-r-- 1 ubuntu ubuntu 1091004 Jan 26  2020 'DejaVu Sans Mono Oblique Nerd Font Complete.ttf'
-rw-rw-r-- 1 ubuntu ubuntu 1091056 Jan 26  2020 'DejaVu Sans Mono Oblique Nerd Font Complete Windows Compatible.ttf'

fc-cache -fv 
fc-cache: succeeded

![image](https://user-images.githubusercontent.com/14953151/126075687-018d14d5-897b-43a8-9a8a-1d32d9a69d5d.png)

Yes, I do have: icons = "awesome" in i3status-rust config file. Running Ubuntu 21.04

One thing what I noticed here, if I'm using the Bold style for any font - then this sign is not there anymore

Using: 
```
font pango:DejaVu Sans Mono Bold 8
```
instead of:
```
font pango:DejaVu Sans Mono 8
```
getting this:
![image](https://user-images.githubusercontent.com/14953151/126075876-0f22c72b-a0a2-4c62-b12e-514495a91025.png)

**Comment by GladOSkar** [comment]
Oh that is indeed quite interesting. I have no idea why that would be.

But in your example it looks like you're not actually using the nerd font? Maybe specify it like this:
```
font pango:DejaVu Sans Mono Nerd Font 8
```

**Comment by iliesh** [comment]
Oh, yes you're right - by using 
```
font pango:DejaVu Sans Mono Nerd Font 8
```
I don't have anymore that sign and the bar looks awesome.
Thank you @GladOSkar  for your help.
