### ISSUE TITLE
NetworkManager Block not updating

### ISSUE THREAD

**Issue by helgehr** [greshake/i3status-rust#1285]
Since some verions the NetworkManager Block does not update when the connection breaks down / connects to another network.
I have to restart i3 (mod+shift+r) to see whether I am connected or not.
Does someone have an Idea why this happens?

**Comment by ammgws** [comment]
Caused by new version of networkmanager or i3status-rust? I recall some improvements made on our side a few months ago.

**Comment by helgehr** [comment]
I cannot say when it went that way exactly, there where a few upgrades of NetworkManger in the last time and I updated i3status-rust at the end of last month and the month before.
I am using the versions:
```
i3status-rust: 0.20.2
NetworkManager: 1.32.4
```

**Comment by ammgws** [comment]
Can you reproduce with git master?

**Comment by helgehr** [comment]
Ok, the version from master seems to be making no such problems.

**Comment by MaxVerevkin** [comment]
@ammgws time to create a bugfix release?

**Comment by ammgws** [comment]
Sure why not. The only change since the last release is where we dealt with the DBus deprecation issue, so I guess that was causing this issue. Otherwise will have to look into this again.
