### ISSUE TITLE
"focused_window" block needs proper escaping

### ISSUE THREAD

**Issue by dmitrodem** [greshake/i3status-rust#1288]
I'm using "focused_window" together with i3bar. When window title contains some control character (tab, newline, visual bell, etc), i3bar fails with message

`Error: Could not parse JSON (lexical error: invalid character inside string.)`

Simple Tcl/Tk program to test this:
```tcl
#!/usr/bin/env wish
wm title . "\n"
```

**Comment by ammgws** [comment]
Doesn't happen on `sway` which may explain why I haven't seen this before.

**Comment by GladOSkar** [comment]
Yeah `sway` handles newlines in some way while `i3` fails. We had the same thing with error messages at some point. But then again who has a newline in their window title?

Anyhow, should probably just be replaced with a space?

**Comment by dmitrodem** [comment]
> Anyhow, should probably just be replaced with a space?

You must be kidding, right? Communication between i3bar and i3status is performed via JSON, and it requires special symbols in strings to be escaped. Of course, newline is a very rare case. However, I've seen many pdf files with titles containing tab symbols.

**Comment by GladOSkar** [comment]
You're right, we could also escape them properly. But a newline or a tab character just don't make any sense in a status bar, so we may need to think about how it should actually be displayed as well

**Comment by ammgws** [comment]
@dmitrodem Can you check with the latest master?

Also what happens with other characters such as `tab`? I'm guessing those need to be escaped too...
