### ISSUE TITLE
crashes when clicking on cpu block

### ISSUE THREAD

**Issue by matthiaskrgr** [greshake/i3status-rust#129]
the i3 bar always crashes when I click on the cpu block. I tried getting some backtrace but it only prints "1" when running
````
status_command i3status-rs   example_config.toml |& tee /tmp/out.log
````
besides the normal i3status output.
Sometimes it also crashes randomly, at least the actual gui-bar, when I launch it via cmdline the output looks fine.

How can I debug this?

**Comment by atheriel** [comment]
To be honest I haven't got a clue why this could happen -- the CPU block doesn't have any code to respond to click actions at all. Does the CPU block actually work? Do other blocks cause this behaviour?

**Comment by matthiaskrgr** [comment]
Hmm installer i3status-rust from git now and also installed the required font and it seems to be stable right now.

I'll close this issue in a day or two if I can't find any more crashes.

**Comment by matthiaskrgr** [comment]
Well, looks ok to me now.
