### ISSUE TITLE
60 second interval on time causes minute change to lag by over 30 seconds with 50% chance

### ISSUE THREAD

**Issue by ekliptik** [greshake/i3status-rust#1292]
https://github.com/greshake/i3status-rust/blob/a0369f85ed1a80f1579847ba3b794155cf61b5e2/examples/config.toml#L34

I suggest setting the interval to 1, if faster asynchronous notification that the minute has changed isn't feasible

**Comment by ammgws** [comment]
Sure go ahead and submit a PR ;)
