### ISSUE TITLE
Can't get it installed.

### ISSUE THREAD

**Issue by ShydenPierce** [greshake/i3status-rust#1293]
I'm sorry if this isn't the right place to ask for help, but I cannot seem to get this installed no matter what I do. I copied the files word for word except when I needed to change them for file paths and whatnot, got all the dependencies I could find, and it still says "Error: status_command not found or is missing a library dependency (exit 127)" I'll upload all the configuration I believe might have something to do with it, if you need anymore then I will supply them. Again, sorry if this isn't the right place, new to github. Edit: first code block wont work, my apologies

`
theme = "slick"
icons = "awesome"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 10.0
alert = 5.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_total_used_percents}"
format_swap = "{swap_used_percents}"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m R"
`

`
bar {
    font pango:DejaVu Sans Mono, Font Awesome 5 Free
    position top
    status_command /usr/bin/i3status-rs /etc/i3status-rust/config.toml
    colors {
        separator #666666
        background #222222
        statusline #dddddd
        focused_workspace #0088CC #0088CC #ffffff
        active_workspace #333333 #333333 #ffffff
        inactive_workspace #333333 #333333 #888888
        urgent_workspace #2f343a #900000 #ffffff
    }
}
`

**Comment by greshake** [comment]
The error message comes from i3bar which is trying to call i3status-rust at `/usr/bin/i3status-rs`. Check if it is actually installed at that path. 
That's pretty much it, nothing more we can do here :)
