### ISSUE TITLE
Memory block has a format with extra spaces which are not inside the config

### ISSUE THREAD

**Issue by AkechiShiro** [greshake/i3status-rust#1297]
Hi, I just updated from the latest release on GitHub (0.20.5.r2170.g831006c-1), after having used a very old version (around 0.14.0) and I noticed something wrong with the memory block, it shows as this : 
![image](https://user-images.githubusercontent.com/14914796/131201030-ea7a3299-267a-4e6d-8c81-462060f2f1b6.png)
When the config of the block is the following : 
```
block = "memory"
display_type = "memory"
format_mem = "{mem_used;M}/{mem_total;M}({mem_used_percents})"
format_swap = "{swap_used;M}/{swap_total;M}({swap_used_percents})"
```

I do not know why there is some space that's being inserted ? Is there a way to fix this ?

**Comment by GladOSkar** [comment]
See #1231

**Comment by AkechiShiro** [comment]
Sorry I missed this in the history of NEWS.md, thanks for mentioning it.
