### ISSUE TITLE
Change default formatting?

### ISSUE THREAD

**Issue by ammgws** [greshake/i3status-rust#1304]
> Pretty sure this is also #1231 and was added with the new formatting system.
> 
> Have a look there to see the right way to format the value.
>
> @MaxVerevkin seems to me like the new behavior might not be a very good default, we might want to have a look at that. (See also #1272)

_Originally posted by @GladOSkar in https://github.com/greshake/i3status-rust/issues/1303#issuecomment-914619040_

> I have a few ideas:
> 
>     * We can just change the default "min-width" to 1, however those who relied on defaults might get confused.
> 
>     * We can also add "refer to (...) for more info" in the blocks' docs. And perhaps formatting docs can be rewritten in a more clear way?
> 
>     * (not an actual option) Maybe not provide the default value for "min-width" at all?

_Originally posted by @MaxVerevkin in https://github.com/greshake/i3status-rust/issues/1303

**Comment by GladOSkar** [comment]
Option 4 i see and my favorite solution would be to do what's asked in #1272 and allow a number format as discussed in #240 and implemented in #704 that can have a fixed width and still not show any gaps, even if it's sometimes a bit suboptimal in the number of significant digits shown.

That might be difficult to enable with the current placeholder syntax, but is probably possible. I'll propose something when i have time

**Comment by ram02z** [comment]
Not sure if this entirely relevant, however, blocks like the brightness block don't have a format key, which makes sense, but that means it can't make use of the formatting available in other blocks. Not sure if it worth adding the format key just so I can change the min_width of the brightness block to 3 though.

**Comment by MaxVerevkin** [comment]
> Not sure if it worth adding the format key just so I can change the min_width of the brightness block to 3 though.

I think it does.

**Comment by GladOSkar** [comment]
Yeah now that we have the universal logic that's not an issue. Plus it will provide additional options like showing the brightness as a bar. But i wouldn't consider that relevant to this issue, feel free to open another one :)

**Comment by GladOSkar** [comment]
> Option 4 i see and my favorite solution would be to do what's asked in (the second part of) #1272 and allow a number format as discussed in #240 and implemented in #704 that can have a fixed width and still not show any gaps, even if it's sometimes a bit suboptimal in the number of significant digits shown.
> 
> That might be difficult to enable with the current placeholder syntax, but is probably possible. Alternatively we could also just change the default. I'll propose something when i have time

I thought about this a bit again and realized it's only possible for value placeholders with a `min_width` of at least 4 characters, since without padding a value like `42000` can't really be displayed with 3 value characters in any nice way: `42.K` / `.04M` would be the only (ugly) solutions i can come up with.

Starting at 4 characters we can easily do something like what was discussed in the other issue:
```
4.20M
0.42M
42.0K
4.20K
0.42K
```

Now i'm not sure if it's worth the effort/complexity just for avoiding some ugly padding, but we probably could add this as a special case for `min_width >= 4` in the default behavior of the value formatter.

What do you think @MaxVerevkin?

**Comment by MaxVerevkin** [comment]
I still don't like when `420K` is displayed as `0.42M` but I can understand that it might not be the case for others.

> but we probably could add this as a special case for min_width >= 4 in the default behavior of the value formatter

No, I think setting `min_width` to, say 5, sould do what it does now. However, I think we can either add some kind of config option or just set your proposed solution as the default and disable it if `min_width` is set.

**Comment by GladOSkar** [comment]
> Still, displaying (width=5) 0.104M instead of 104.0K is weird, or is it just me laughing?

Yeah it is. But i don't see another option for some of the cases in the `fix` formatter.

> By the way, anyone wants to implement fix formatter?

Want, yeah, have the time? No. The version i wrote that was used in #704 isn't very nice though, but can probably be adapted though. I'll have a look if/when i have time

**Comment by MaxVerevkin** [comment]
> `"{<var>@str-rotating(<params>)}" # Rotating string (would be really cool to have such functionality)`

So I've got a working prototype :tada: : 

https://user-images.githubusercontent.com/34583604/139596969-42851f57-223e-4ca8-9a13-680c904df3c6.mp4

```toml
[[block]]
block = "sway_kbd"
format = "Layout \"$layout.rot-str(10,0.5)\""
```

**Comment by MaxVerevkin** [comment]
So, are three any comments on the proposed syntax?

**Comment by GladOSkar** [comment]
I like it, but i'm still not sure if it's worth breaking configs again. If we manage a graceful transition this time i'm in favor.

**Comment by ammgws** [comment]
Even with a graceful transition you'd still end up having to change your config in the future, right?

We can mention the future changes in the release notes for the next bug fix release, but apart from that there's not much we can do...

**Comment by ammgws** [comment]
@MaxVerevkin  Are there any breaking changes necessary for merging swaystatus' async here? If so then it could be done at the same timing.

**Comment by MaxVerevkin** [comment]
@ammgws I'm not sure what exactly do you mean, but I expect this formatting to be merged (if even merged) with swaystatus, so not so soon.

**Comment by MaxVerevkin** [comment]
> So, are three any comments on the proposed syntax?

Like, maybe we should provide default formatters? (`$layout` instead of `$layout.str()`) Or any other recommendations.

**Comment by MaxVerevkin** [comment]
Not sure if graceful transition is even possible:

> However I'm not sure if it even makes sense since the whole point of the new formatting system it to allow missing placeholders.

**Comment by MaxVerevkin** [comment]
> Oh yeah i had assumed there was a default

So... `eng` or `fix`? :laughing:

**Comment by GladOSkar** [comment]
`eng` for numbers, `str` for strings. `fix` seems to be a bit of a niche use case at this point ^^

**Comment by MaxVerevkin** [comment]
I just realized that the new formatting system can make use of something similar to if statements!

This can be used in pacman/dnf/apt block:
```text
$noupdates{...}|$single{...}|{...}
```
where `$noupdates` is an empty string which is presented only if there are no updates. Same for `$single`.

It is even possible to create `&&` and `||` structures!
```text
$a$b{then}|{else} // a&&b
{$a|$b}{then}|{else} // a||b
```

**Comment by GladOSkar** [comment]
Oh no. If you manage to get some sort of loop in there we're probably turing complete -.-

**Comment by MaxVerevkin** [comment]
I've tried to formalize what is available so far in https://maxverevkin.github.io/swaystatus/docs/swaystatus/formatting/index.html

**Comment by MaxVerevkin** [comment]
So... Any comments on this topic? I've been using my proposed formatting all this time and it seems fine to me.

**Comment by ammgws** [comment]
Closing as this is now the default on master.
