### ISSUE TITLE
docker block doesn't work for rootless-mode or other, non-standard socket locations

### ISSUE THREAD

**Issue by JTarasovic** [greshake/i3status-rust#1309]
Not really a bug. The socket path is hardcoded [here](../blob/master/src/blocks/docker.rs#L85) so anyone using non-standard paths can't really use the block.

I think it'd be reasonable (and reasonably straightforward?) to expose that path as part of the config (with `/var/run/docker.sock` being the default). I'd be happy to take a pass at it if there's interest.

**Comment by ammgws** [comment]
Sure, go for it
