### ISSUE TITLE
On_click option should be available for all blocks

### ISSUE THREAD

**Issue by Kommynct** [greshake/i3status-rust#131]
This is just kinda obviously an issue, but I was here to report another bug so i figured i might as well add it to the issues checklist.

**Comment by atheriel** [comment]
I don't think this is high on the list of priorities for maintainers, but I agree this would be a nice feature for blocks that do not otherwise have a natural on-click behaviour already. You are free to take a crack at it yourself, or propose which blocks need it most.

**Comment by lausek** [comment]
@atheriel Is there a reason why the default implementation doesn't automatically pass the command to the shell? I mean, if the block needs another behaviour in `click` it could just override the trait method, right?

**Comment by atheriel** [comment]
This is complicated by the fact that clicks are at the "widget" level, not the "block" level. This is why there's no default block clicking behaviour in the current implementation, although I'm not opposed to it.

**Comment by atheriel** [comment]
@boogy Note that several blocks have on click behaviour already. We couldn't introduce this for all blocks without breaking some existing features.

**Comment by mankinskin** [comment]
Why has this issue got closed?

**Comment by karthink** [comment]
Adding my vote to this request. on_click would be very useful on most modules that don't have them yet.
