### ISSUE TITLE
Discussion: Replace dbus with zbus?

### ISSUE THREAD

**Issue by Celti** [greshake/i3status-rust#1314]
[`zbus`](https://gitlab.freedesktop.org/dbus/zbus) is a first-class native Rust implementation of the D-Bus API. Replacing the `dbus` and `dbus-tree` crates with `zbus` would remove a foreign dependency and should simplify code.

Would a PR for this be accepted?

**Comment by ammgws** [comment]
Sure, go for it!

**Comment by Celti** [comment]
Then maybe this should be done against zbus, as part of the rewrite? Doing it twice (once for zbus1 here, once for zbus2 there) feels like unnecessary effort, especially when the dbus crate is currently working and accepted.

**Comment by zeenix** [comment]
Hi, zbus dev here. 👋 Just to let you know, zbus 2.0 was released a month ago and the new API is primarily async (with blocking wrappers provided).

**Comment by ammgws** [comment]
Closing as we are now using zbus.
