### ISSUE TITLE
Add support for wlsunset to hueshift

### ISSUE THREAD

**Issue by DerVerruckteFuchs** [greshake/i3status-rust#1316]
[wlsunset](https://git.sr.ht/~kennylevinsen/wlsunset) is a simple gamma shifter (like redshift, et al.) for wlroots based Wayland compositors. It would be nice to add support for it in the hueshift block. `wlsunset -T` sets the high color temperature, `wlsunset -t` sets the low color temperature, and `wlsunset -g` sets the gamma.

**Comment by ammgws** [comment]
@DerVerruckteFuchs Let us know if you need a hand with this

**Comment by DerVerruckteFuchs** [comment]
I created a pull request for this:  #1337.
