### ISSUE TITLE
add on_click for `focused_window`

### ISSUE THREAD

**Issue by c02y** [greshake/i3status-rust#1318]
How can I add a feature like right-clicking the title in the `focused_window` block will kill the window?

Originally I use bindings that need multiple keys or simply 
```
bindsym button3 kill
```
which clicks the window bar to kill the window just using the mouse, but most of the time there is no window bar such as for split layout or floating windows, and I personally don't need window bar since I just use `focused_window` block from i3status-rust instead.

So it would be much better to add such a feature to the `focued_window` block once for all?

**Comment by ammgws** [comment]
Async branch has now been merged into master (still some work to do before release is possible though), which allows for click actions to be set for any mouse button for any block.
