### ISSUE TITLE
Would it be ok to pull in i3-ipc dependency?

### ISSUE THREAD

**Issue by JohnDowson** [greshake/i3status-rust#1324]
This project depends on swayipc, but it is only partially compatible with i3wm, ie event subscription works, but `get_workspaces` and `get_tree` both panic.
It would make sense to pull in a library that actually has support for i3wm specifically as a mission statement, specifically [i3-ipc](https://github.com/leshow/tokio-i3ipc).
I must note however, that i3-ipc is slightly outdated, although it has an open PR (leshow/tokio-i3ipc#31) bringing it up to date with current i3 version.

**Comment by ammgws** [comment]
If I recall correctly we only subscribe to events, so there should be no panics. Are you trying to implement a new block or feature?

**Comment by JohnDowson** [comment]
> Are you trying to implement a new block or feature?

Yes, I've prototyped a block for showing current split layout, which requires `get_tree`.

**Comment by MaxVerevkin** [comment]
> > Are you trying to implement a new block or feature?
> 
> Yes, I've prototyped a block for showing current split layout, which requires `get_tree`.

That's nice, perhaps it can be integrated in `focused_window` block?

**Comment by MaxVerevkin** [comment]
By the way, does `swayipc-async` has the same problem? And is it just a bug or an unsolvable issue?

**Comment by MaxVerevkin** [comment]
`swayipc` should be compatible now: https://github.com/JayceFayne/swayipc-rs/pull/35

**Comment by MaxVerevkin** [comment]
> I've prototyped a block for showing current split layout

@JohnDowson May I ask you how did you monitor layout changes? It seems that `i3`/`sway` not have such an IPC event...

**Comment by GladOSkar** [comment]
@MaxVerevkin at least for `i3` i got `i3-msg` output on layout changes: #1433

**Comment by MaxVerevkin** [comment]
@GladOSkar Both via keybinding and `i3msg split toggle` or similar? I get nothing with `sway` :/

**Comment by GladOSkar** [comment]
Ohh sorry i got confused between "monitor layout changes" and "monitor monitor layout changes" lol. Ignore my comment please
