### ISSUE TITLE
Add test command for all blocks?

### ISSUE THREAD

**Issue by ammgws** [greshake/i3status-rust#1326]
Just used my laptop for the first time in ages and remembered the below discussion from a while back. I feel like it would be a pretty handy feature when you are sharing the same config between multiple machines:

> I'm also sharing the configuration between multiple computers and was bitten by this issue.
> 
> I have another suggestion, what do you think about adding a tag for all blocks for a test command? E.g.:
> 
> ```toml
> [[block]]
> block = "battery"
> if_command = "upower -e"
> ```
> 
> If the command `upower -e` exits with an error code, the block will not be rendered.
> 

_Originally posted by @jlesquembre in https://github.com/greshake/i3status-rust/issues/50#issuecomment-362104891_

**Comment by MaxVerevkin** [comment]
So the idea is to run a command once before block's initialization and skip it if the exit code is nonzero?

**Comment by ammgws** [comment]
Pretty much. What do you think?

**Comment by MaxVerevkin** [comment]
It's pretty easy to implement, so why not?
