### ISSUE TITLE
formatter: Adding support for seconds/minutes/hours 

### ISSUE THREAD

**Issue by ammgws** [greshake/i3status-rust#1332]
> Adding support for seconds/minutes/hours 

_Originally posted by @SebTM in https://github.com/greshake/i3status-rust/issues/1254

**Comment by littlesum** [comment]
You can mod by yourself

**Comment by ammgws** [comment]
Are you talking about this?


> There is already a "seconds" unit, so we can add units like "hours", "days" etc. But to achieve formatting like "01:12" (I guess) we will have to also add "special" units like "time" and "date_time" or something like that.
>
>For example, if placeholder `var` has a value of 1 hour 25 minutes, then
> Formatting string | Result
> -|-
> `"{var*h}"` | `1.42h`
> `"{var*m}"` | ` 85m`
> `"{var*s}"` | `5100s`
> `"{var*time}"` | `01:25`

_Originally posted by @MaxVerevkin in https://github.com/greshake/i3status-rust/issues/1254#issuecomment-860555516_
