### ISSUE TITLE
formatter: prepend string for when variable is empty

### ISSUE THREAD

**Issue by ammgws** [greshake/i3status-rust#1333]
> Maybe another formatting-option to be able to prepend a string only shown while the variable is not empty?

_Originally posted by @SebTM in https://github.com/greshake/i3status-rust/issues/1254

**Comment by MaxVerevkin** [comment]
#1304 probably covers this.

**Comment by ammgws** [comment]
Yeah I had a feeling I had actually seen it implemented as well but couldn't find it anywhere. Maybe it was swaystatus? 🍌

**Comment by MaxVerevkin** [comment]
I mean, it is implemented in `swaystatus` :laughing:

**Comment by ammgws** [comment]
Thought so. If it's mentioned in #1304 somewhere then I can close this.

**Comment by MaxVerevkin** [comment]
The original proposal is here https://github.com/greshake/i3status-rust/issues/1304#issuecomment-950191828

**Comment by ammgws** [comment]
Thanks!
