### ISSUE TITLE
Memory block not working in example configuration linked from README

### ISSUE THREAD

**Issue by georgeanderson** [greshake/i3status-rust#1336]
Not sure this is a valid issue so bringing it to the attention of others here to confirm. I followed the README documentation and downloaded the sample configuration from link https://raw.githubusercontent.com/greshake/i3status-rust/master/examples/config.toml. 

Lines 17 and 18 make the bar display their content instead of the memory information.

```toml
format_mem = "{mem_used_percents}"
format_swap = "{swap_used_percents}"
```
Once I comment the lines above the memory information is rendered correctly in the bar. It displays memory in the format of `[free]/[total]([free%])`.

i3 version: `Binary i3 version:  4.19.2 (2021-02-27) © 2009 Michael Stapelberg and contributors`
i3status-rs:
```
Name        : i3status-rs
Version     : 0.13.1
Release     : 6.fc35
Architecture: x86_64
Install Date: Sat 06 Nov 2021 09:15:45 PM CDT
Group       : Unspecified
Size        : 5682603
License     : GPLv3 and 0BSD and ASL 2.0 and ISC and MIT and BSD and Public Domain
Signature   : RSA/SHA256, Sun 25 Jul 2021 06:56:16 PM CDT, Key ID db4639719867c58f
Source RPM  : i3status-rs-0.13.1-6.fc35.src.rpm
Build Date  : Thu 22 Jul 2021 05:47:19 AM CDT
Build Host  : buildvm-x86-30.iad2.fedoraproject.org
Packager    : Fedora Project
Vendor      : Fedora Project
URL         : https://github.com/greshake/i3status-rust
Bug URL     : https://bugz.fedoraproject.org/i3status-rs
Summary     : Feature-rich and resource-friendly replacement for i3status, written in Rust
```

**Comment by MaxVerevkin** [comment]
Fedora's package is [more that a year old](https://bugzilla.redhat.com/show_bug.cgi?id=1797471). Since then the syntax to configure memory block had changed.

**Comment by georgeanderson** [comment]
> Fedora's package is [more than a year old](https://bugzilla.redhat.com/show_bug.cgi?id=1797471). Since then the syntax to configure memory block had changed.

True. I saw someone offering to help there but there is no answer. I will check with folks on the Fedora community. This package is too good to be this outdated.
