### ISSUE TITLE
Option to put focused_window to the left side of the bar

### ISSUE THREAD

**Issue by c02y** [greshake/i3status-rust#1339]
Is it possible to put the focused_window block to the left side of the bar, like, after the workspace name/icon?

**Comment by MaxVerevkin** [comment]
Unfortunately, [i3bar protocol](https://i3wm.org/docs/i3bar-protocol.html) doesn't support this.

**Comment by ammgws** [comment]
I think in the past i3 rejected a proposal to allow it. Maybe you can look that up and see if the decision is still the same?
