### ISSUE TITLE
use braille dots instead of bars for graphs

### ISSUE THREAD

**Issue by matthiaskrgr** [greshake/i3status-rust#134]
The net block could use this for example.

https://github.com/hishamhm/htop/blob/93b811a051387acf4b9c4ddb8c1ee8c59118f3cc/Meter.c#L314

![braille](https://user-images.githubusercontent.com/476013/34849360-6b5bc732-f722-11e7-9b2b-d3627ace40f2.png)

**Comment by atheriel** [comment]
I agree that this would be neat. Perhaps this could be accomplished by allowing for customization of the existing unicode characters (see [here](https://github.com/greshake/i3status-rust/blob/master/src/widgets/graph.rs#L51)) used to render the graphs, likely in the icons/theme configuration.

**Comment by ammgws** [comment]
I gave it a test run in #934 but need to check if the output is correct:
![image](https://user-images.githubusercontent.com/20397027/99260857-4a63f100-285f-11eb-8f9d-50e4d11ead46.png)

**Comment by ammgws** [comment]
Closing due to apparent lack of interest. Please re-open (and try out #934) otherwise!
