### ISSUE TITLE
Battery isn't displayed properly

### ISSUE THREAD

**Issue by onymaticc** [greshake/i3status-rust#1341]
I have a laptop with multiple batteries. My issue is that the battery applet only shows the first battery's percentage. The other one does not show at all.

**Comment by ammgws** [comment]
Is having setting up another battery block for the second one an acceptable solution?
Either one can be set to be hidden if it is not present in the system (in case you ever take one of the two out)

@GladOSkar What do you think? I have a feeling this has come up before too...

**Comment by GladOSkar** [comment]
@onymaticc you should be able to add multiple battery blocks specifying the different a `device` for each.

See [here](https://github.com/greshake/i3status-rust/blob/master/doc/blocks.md#options-2) for the documentation of that Option.

You can find your battery devices by running `ls /sys/class/power_supply/` in your shell

**Comment by onymaticc** [comment]
Thanks guys, seems to be working great now.
