### ISSUE TITLE
One pixel artifacts between blocks

### ISSUE THREAD

**Issue by benjaminBrownlee** [greshake/i3status-rust#1346]
os: archlinux
wm: i3-gaps 4.20.1-1
status: i3status-rust 0.20.6-1

I just upgraded to version 0.20.6 and noticed that the blocks seem to be misaligned by a pixel. As an example, my current status bar looks like this,

![image](https://user-images.githubusercontent.com/29786277/141482252-caa24066-d978-4a0b-ac70-9a5807ada892.png)

Looking closer you can see the one pixel difference which has an effect on both sides of the block,

![image](https://user-images.githubusercontent.com/29786277/141482527-31595542-da02-42cf-b081-bd101a11f9b8.png)

Naturally, we would expect something more like this,

![image](https://user-images.githubusercontent.com/29786277/141482655-e92bb90e-f24f-4b5b-a901-85af53b54ebe.png)
 
I know this is a small detail, so let me know if anyone else can reproduce this issue.

**Comment by MaxVerevkin** [comment]
Did you also update your font? As far as I know, none of the icons were changed.

**Comment by benjaminBrownlee** [comment]
Fair point. I'll search my logs and let you know if rolling back any font packages helps.

**Comment by ammgws** [comment]
Did you figure it out?

**Comment by benjaminBrownlee** [comment]
Oh, yes, sorry I forgot to come back and close this issue. Though it seemed to just fix itself after a few days; I never found the culprit.
