### ISSUE TITLE
Question: how get a value of key from env variable

### ISSUE THREAD

**Issue by pythops** [greshake/i3status-rust#1353]
For instance, for docker block, I want to get the value of `socket_path` from the env variable `$XDG_RUNTIME_DIR`
Is that possible ? 

Thanks

**Comment by ammgws** [comment]
Should be possible if someone implements the request in #1246

**Comment by ammgws** [comment]
@pythops Does #1355 work for you? (for docker anyway)

**Comment by pythops** [comment]
No it does not work :disappointed:

**Comment by ammgws** [comment]
Maybe you could try adding something like 

eprintln!("docker block path: {:#?}", socket_path);

in the update function to see what socket path it's actually trying to use?

**Comment by ammgws** [comment]
@pythops Do you need some guidance?

**Comment by pythops** [comment]
Yes please, 
How should I write the `socket_path` in the `config.toml` file ?
```
[[block]]
block = "docker"
interval = 2
format = "{running}/{total}"
socket_path = ????
```

**Comment by ammgws** [comment]
I don't use docker but I think like this: socket_path = "$XDG_RUNTIME_DIR/docker.sock"

**Comment by ammgws** [comment]
Closing this as it should be solved. Please re-open otherwise.
