### ISSUE TITLE
xrandr module and /var/log/Xorg.0.log "spam"

### ISSUE THREAD

**Issue by euri10** [greshake/i3status-rust#1364]
I was surprised to see after not logging out of my desktop for quite a while a 44Gb log file for `/var/log/Xorg.0.log`

So I google a little and found this [comment](https://forums.developer.nvidia.com/t/x-server-with-loaded-nvidia-driver-spams-log-files/147203/2) and I tried to find which program could trigger that : it appears it's the xrandr block.

I'm using a 2s as the example for the wiki and wondered if maybe there could be a note on it, there are links to issues but that could maybe be more explicit.

**Comment by ammgws** [comment]
Any improvements to the docs are always welcome
