### ISSUE TITLE
Error: status_command process exited unexpectedly (exit 138)

### ISSUE THREAD

**Issue by tarkh** [greshake/i3status-rust#1368]
Hi, thanx for cool app!
I'm getting **RANDOM** `i3status-rs` crash on login. Right after reboot/start and entering my password in login manager, `i3-wm` loads but with error in `i3bar` instead of `i3status-rs` content:
```
Error: status_command process exited unexpectedly (exit 138)
```
**My setup is:**
Arch Linux, Xorg, i3-gaps, lightdm, picom.
**Blocks using:**
networkmanager, battery, disk_space, cpu, memory, temperature
**Network**
Wi-Fi connection, managed by `networkmanager`

Most of the time everything starts normally, but in 5-10% of startups I'm getting this error. Maybe network or some other system stuff just not ready yet and `i3status-rs` crashes? Where to dig? Is there any way I can debug this?
Thank you!

**Comment by cfsmp3** [comment]
Build from source and use the debug build.

**Comment by MaxVerevkin** [comment]
> Build from source and use the debug build.

How is this going to help?

> Is there any way I can debug this?

You can redirect the stderr to a log file by setting your `status_command` to
```
status_command "path_to_binary 2>> /tmp/bar-log"
```

**Comment by cfsmp3** [comment]
> > Build from source and use the debug build.
> 
> How is this going to help?

Better info in any case of a crash?

**Comment by MaxVerevkin** [comment]
> Better info in any case of a crash?

If a crash is caused by a panic, release mode will print the message and the number of the line that panicked. In this case it should be enough, I hope.

**Comment by tarkh** [comment]
> > Build from source and use the debug build.
> 
> How is this going to help?
> 
> > Is there any way I can debug this?
> 
> You can redirect the stderr to a log file by setting your `status_command` to
> 
> ```
> status_command "path_to_binary 2>> /tmp/bar-log"
> ```
This is exactly what I did in first place. But for some reason log was empty...

**Comment by MaxVerevkin** [comment]
> But for some reason log was empty...

That's weird...

> Maybe network or some other system stuff just not ready yet and i3status-rs crashes?

You can verify this by adding a delay:
```
status_command "sleep 10; path_to_binary 2>> /tmp/bar-log"
```
