### ISSUE TITLE
Failable blocks / Improve error handling

### ISSUE THREAD

**Issue by MaxVerevkin** [greshake/i3status-rust#1371]
The use of `refresh_interval_failure` in #1366 made me wonder if it can be applied to other blocks in a generic way.

Here is a rough idea: when an error in a block occurs, the block's state will be set to `error_state` and the text will be set according to `error_format`. Then the block will be restarted after `error_interval`. Clicking on the block will show the full error message. Clicking again will hide the full error message.

There is a major issue though: some blocks spawn threads. The situation is better for async implementation, as those threads are at least abortable (edit: `spawn_blocking()` is not really abortable).

**Comment by MaxVerevkin** [comment]
Actually, it might be easier than I thought. There's no need to fully restart the blocks. Instead, each block can be composed of failable but recoverable parts.

As an example, here's a part of `github`'s block from my prototype:
```rust
let total = api.recoverable(|| get_total(&request), "Oh no!").await?;
```

That's it. Nothing else needed on the block's side. That's how it looks:

https://user-images.githubusercontent.com/34583604/146654531-c1364a64-0592-439c-bb10-f2ffb278d313.mp4

**Comment by ammgws** [comment]
Closing this as it's implemented in master now.
