### ISSUE TITLE
failure of `nvidia_gpu` block causes unavailability of entire statuses info

### ISSUE THREAD

**Issue by lo48576** [greshake/i3status-rust#1372]
## How to reproduce

1. Use i3status-rust from i3bar, and add `nvidia_gpu` block to the config.toml.
    * `bar` block in my .config/i3/config: `status_command i3status-rs ~/.config/i3status-rs/config.toml`
2. Update nvidia proprietary driver to the new and incompatible version
    * In my case in Gentoo Linux, I downgraded `x11-drivers/nvidia-drivers` from `495.44` to `470.94`.
3. Now i3bar reports `Error: status_command process exited unrepeatedly (exit 101)`.
    * This is the first symptom.
4. Restart i3.
5. Now i3bar reports another error: `Error in block 'gpu': Nvidia-smi produced a non-zero exit status.`.

## What happens (unexpectedly)

* When `nvidia_gpu` block started to fail (especially due to driver update), `i3bar` invoked from `i3status` seems to stop working without any retry.
    + I'm not sure where is the root cause. i3status-rust? i3bar? or i3wm?
* When i3status-rust is started under condition that `nvidia-smi` fails, it does not emit any useful outputs, even when other blocks are still available.
    + For example, I have `load` block', `time` block, and many other blocks along with `nvidia_gpu` block, but none of them are printed; just an error message appears.

## What I expected

* Even when `nvidia_gpu` block started to fail, i3status-rs, i3bar, and i3wm works, and status bar is updating constantly.
* Even when i3status-rust is started under condition that `nvidia-smi` fails, other blocks still works and emits information.

## Supplement

i3bar after nvidia driver update:
![screenshot-2021-12-17-204232+0900](https://user-images.githubusercontent.com/1246590/146592075-1a2bef95-280e-4a63-91e6-2d5c5e00096d.png)

i3bar restarted after driver update (but the machine is not rebooted yet):
![screenshot-2021-12-17-205247+0900](https://user-images.githubusercontent.com/1246590/146592123-7b14d2eb-c099-4fbe-a9bc-6a0d9fbfaac7.png)

`nvidia-smi` after driver update:
![screenshot-2021-12-17-204244+0900](https://user-images.githubusercontent.com/1246590/146592162-c1e4df0d-402a-4129-829e-8c44bacd4671.png)

**Comment by lo48576** [comment]
Possibly #568 and #978 might be related?
I, as a user, usually expect i3status-rust to emit normally working blocks, even if some of the blocks fails.

**Comment by MaxVerevkin** [comment]
> I, as a user, usually expect i3status-rust to emit results of the normally working blocks, even if some of the blocks fails.

This part is covered by #1371 :) Although there is a lot of work to be done and I wouldn't expect it to be solved in the _very_ near future.

**Comment by ammgws** [comment]
Are you using a very old version of i3status-rust? I remember changing that error code ("Nvidia-smi produced a non-zero exit status.") when adding a fix for a similar issue in the past: https://github.com/greshake/i3status-rust/commit/fcd466a16136557a070cb04bfaebe7c69dd8cdad#diff-5f00cd808aa791cf8d6dd184dc9ad4788eddf37408396ca0102d992bd3c3ed50. I'm not sure what the nvidia-smi exit code is for your situation where it says "Driver/library mismatch", but there's a chance that it wouldn't have errored out with the current version of i3status-rust.

The other points about block errors bringing down the whole bar still stand, though that's another issue.

**Comment by cfsmp3** [comment]
>  I'm not sure what the nvidia-smi exit code is for your situation where it says "Driver/library mismatch",

That's typically caused by CUDA being updated but not the kernel (i.e. a reboot is pending).

**Comment by lo48576** [comment]
> Are you using a very old version of i3status-rust?

I'm using i3status-rust 0.14.1 (built and installed at 2021-04-29).
I'm sorry I didn't checked with the latest version... I'll try later.

**Comment by lo48576** [comment]
I tried v0.20.7, and it keeps working after driver update.
I'm so sorry... I used system's package manager and the latest version is outdated.

I'm closing this, as generic case would be covered by #1371.
Thank you!
