### ISSUE TITLE
Enable allow_missing for batteries using the UPower driver

### ISSUE THREAD

**Issue by bim9262** [greshake/i3status-rust#1377]
I was thinking that it would be cool if we could allow UPower devices to be missing just like their sysfs counterparts.
Is there any technical reason not to do so?

I'll add my proposed changes to a PR shortly.

**Comment by bim9262** [comment]
https://github.com/greshake/i3status-rust/pull/1378

**Comment by ammgws** [comment]
> Is there any technical reason not to do so?

I don't think so. I had a quick look at the PR and it looks basically the same as what we do in the bluetooth block, so it should be OK.

**Comment by ammgws** [comment]
> This still fails on startup if the device isn't available at that time, so we will need some additional logic for that case..

**Comment by bim9262** [comment]
Looks  like there is a similar problem for apcaccess too. I'll take a look at both.

**Comment by bim9262** [comment]
@ammgws, please let me know if you run into any other issues.
