### ISSUE TITLE
Add a configuration option to customize time/percent display in the Battery block

### ISSUE THREAD

**Issue by atheriel** [greshake/i3status-rust#138]
As mentioned in #133. The easy option here is to have support for e.g. `percent = true` and `time = false` configuration options. The alternative is to implement a `format` configuration option for the block.

**Comment by atheriel** [comment]
I'm reopening this temporarily because I realize that the implementation in #139 changes default behaviour to show *both* percent and time, which is a breaking change to user configs. @greshake Does this change make sense to you, or should we change the default to `percent` from the current `both` to preserve the existing behaviour?

**Comment by matthiaskrgr** [comment]
#148 reverts the change back to the default settings.
