### ISSUE TITLE
Add ability to switch keyboard layout when clicking on `keyboard_layout` block

### ISSUE THREAD

**Issue by roguh** [greshake/i3status-rust#1385]
Pretty self explanatory. If users are using `setxkbmap` to manage their layout, this custom block uses the `xkb-switch` external tool to switch layouts on click:

```
# Use xkb-switch to query and switch layouts
# https://github.com/grwlf/xkb-switch
[[block]]
block = "custom"
command = "xkb-switch"
on_click = "xkb-switch -n "
interval = 1
```

**Comment by MaxVerevkin** [comment]
> `on_click = "xkb-switch -n "`

You can use this option with the `keyboard_layout` block as well.

**Comment by roguh** [comment]
Oh ok, I'll close this.

**Comment by ammgws** [comment]
Maybe it could be added in the example config

**Comment by roguh** [comment]
https://github.com/greshake/i3status-rust/pull/1387
