### ISSUE TITLE
docker: change default socket path

### ISSUE THREAD

**Issue by ammgws** [greshake/i3status-rust#1392]
I don't use docker but it seems like it should be `$XDG_RUNTIME_DIR/docker.sock`

**Comment by MaxVerevkin** [comment]
I don't use it either, but after a simple `sudo pacman -S docker` and `sudo systemctl start docker.service` I can find the socket at `/var/run/docker.sock` but not `$XDG_RUNTIME_DIR/docker.sock`.

**Comment by ammgws** [comment]
I think it's because I only ever used it in rootless mode: https://docs.docker.com/engine/security/rootless/

If that's not what the majority of docker users do then this can be closed.

**Comment by cfsmp3** [comment]
@ammgws IMHO it should be closed. As per

https://docs.docker.com/engine/reference/commandline/dockerd/

"""By default, a unix domain socket (or IPC socket) is created at /var/run/docker.sock, requiring either root permission, or docker group membership."""
