### ISSUE TITLE
Enable [Music] block to only show specified players

### ISSUE THREAD

**Issue by epixinvites** [greshake/i3status-rust#1396]
We're able to specify an array of players or regex of players we want to ignore, why not let us have an array of players we only want to show show up? 
Please correct me if I'm wrong, but as far as I've tried, I can't do something like `player = ["ncspot", "cmus"]`. It tells me the `player` variable only takes a string.
 
I know that maybe in some rare cases someone has two or more players on at the same time, so maybe letting us change the players with right-click would do the job?

**Comment by ammgws** [comment]
IIRC the only reason you cannot do it right now is because we didn't want to break configs by changing the config from taking a string to taking an array. Perhaps a breaking change such as this could be bundled along with the other changes that are upcoming in the v0.3 async release...

**Comment by epixinvites** [comment]
Can't you accept a string *or* an array? That way the current configs won't break, will it?

**Comment by epixinvites** [comment]
I don't have much experience in Rust, sorry
