### ISSUE TITLE
Per-block icons override

### ISSUE THREAD

**Issue by welcoMattic** [greshake/i3status-rust#1406]
I'd like to be able to define 2 or 3 music block with each one a different icon. But I can't find how to override the icon per-block. Is it even possible ?

Thanks

**Comment by MaxVerevkin** [comment]
It's not possible at the moment, but it would be nice to have this feature.

**Comment by MaxVerevkin** [comment]
Implemented in 97a66195f16469a4011a1521fb991bbe943196b6
