### ISSUE TITLE
Status of custom/replaced laptop batteries with capacity > 100% of design spec

### ISSUE THREAD

**Issue by tarkh** [greshake/i3status-rust#1410]
Hello! Thanx for this software!
I have little issue with displaying proper status of my replaced lapdop battery. By design it have `8880 mAh`:
```
cat /sys/class/power_supply/BAT0/charge_full_design 
8880000
```
but actually the capacity is `9877 mAh`:
```
cat /sys/class/power_supply/BAT0/charge_full
9877000
```
and `capacity` calculated by this values in the system, so it is around 110%:
```
cat /sys/class/power_supply/BAT0/capacity
111
```
this diff lead to situation that when I unplug power supply my i3status-rust panel still shows full charge for some time until actual capacity drops below `8880000`. So question is it worth to introduce additional logic for `Battery` module to compare `charge_full_design` and `charge_full` and if second have greater value, then take it as 100% of total possible charge.

This issue pretty common with third party batteries that was placed in laptops instead of original ones.

Additionally, i'm on `Arch` and have `acpi` package installed, and it shows proper information about battery:
**With AC plugged in**
```
acpi -ba
Battery 0: Full, 100%
Adapter 0: on-line
```
**Immediately after unplug**
```
acpi -ba
Battery 0: Discharging, 99%, 06:42:52 remaining
Adapter 0: off-line
```

**Comment by ammgws** [comment]
`acpi` does seem to use "last_full_capacity" by default so perhaps we should be looking at it, though there are some voices against here: https://github.com/i3/i3status/issues/187

Should it be configurable then?

**Comment by tarkh** [comment]
Yes, I've seen these tickets.. So as an option it could be configurable to use either `acpi` or `kernel`... Another option, as I can briefly see in battery module [somewhere at this lines](https://github.com/greshake/i3status-rust/blob/ef840e0395fe91d4225aa4f021d986186fad6ac7/src/blocks/battery.rs#L141), is to add simple logic to check if `charge_full_design` and `charge_full` exist, then compare them and if second is greater - use it as 100% capacity. But I'm not in the details of how everything works, so this is just superficial suggestion...

**Comment by ammgws** [comment]
By the way does `upower` display the correct info?

**Comment by tarkh** [comment]
> By the way does `upower` display the correct info?

Seems like it shows correct information (just unplugged power cable from fully charged laptop):
```
Device: /org/freedesktop/UPower/devices/battery_BAT0
  native-path:          BAT0
  vendor:               wepro
  model:                A1494
  power supply:         yes
  updated:              Sun 30 Jan 2022 12:55:11 PM MSK (4 seconds ago)
  has history:          yes
  has statistics:       yes
  battery
    present:             yes
    rechargeable:        yes
    state:               discharging
    warning-level:       none
    energy:              110.235 Wh
    energy-empty:        0 Wh
    energy-full:         111.215 Wh
    energy-full-design:  99.9888 Wh
    energy-rate:         22.2498 W
    voltage:             12.399 V
    time to empty:       5.0 hours
    percentage:          99.1192%
    temperature:         24.7 degrees C
    capacity:            100%
    technology:          lithium-ion
    icon-name:          'battery-full-symbolic'
```

**Comment by ammgws** [comment]
@tarkh Can this be closed now?

**Comment by tarkh** [comment]
> @tarkh Can this be closed now?

Yes, thank you! Now everything seems to work fine. My final configuration of `battery` block:
```
[[block]]
driver = "upower"
block = "battery"
hide_missing = true
interval = 30
format = "{percentage} {time}"
```
I'm using `upower` as driver, so it must be installed additionally.
