### ISSUE TITLE
`spawn_child_async()` should detach the child instead of spawning a new thread

### ISSUE THREAD

**Issue by MaxVerevkin** [greshake/i3status-rust#1413]
I think `subprocess::spawn_child_async()` should just detach the child:
```rust
pub fn spawn_child_async(name: &str, args: &[&str]) -> io::Result<()> {
    use std::os::unix::process::CommandExt;
    let mut cmd = Command::new(name);
    cmd.args(args);
    // Safety: libc::daemon() is async-signal-safe
    unsafe {
        cmd.pre_exec(|| match libc::daemon(0, 0) {
            -1 => Err(io::Error::new(io::ErrorKind::Other, "Failed to detach new process")),
            _ => Ok(()),
        });
    }
    cmd.spawn()?.wait()?;
    Ok(())
}
```

I've opened this issue because I'm not sure why the current approach is to to spawn a new thread. Is there a particular reason to do so?

**Comment by ammgws** [comment]
Seems like it was just a hack to make it non-blocking?

**Comment by ammgws** [comment]
@MaxVerevkin Did we ever get to the bottom of this?

**Comment by MaxVerevkin** [comment]
I use the proposed implementation (on async branch) and it works fine.

**Comment by ammgws** [comment]
Just merged the async branch so closing this as done.
