### ISSUE TITLE
[bug][net block] ERROR @wl_dev_intvar_get  @wl_cfg80211_get_tx_power  in dmesg

### ISSUE THREAD

**Issue by tkit1994** [greshake/i3status-rust#1414]
How to get rid of this error in dmesg output
```bash
sudo dmesg | grep -i error | tail

[    0.258156] acpi PNP0A08:00: _OSC: platform retains control of PCIe feat
ures (AE_ERROR)
[    0.584832] RAS: Correctable Errors collector initialized.
[  101.415119] ERROR @wl_dev_intvar_get :
[  101.415127] error (-1)
[  101.415132] ERROR @wl_cfg80211_get_tx_power :
[  101.415133] error (-1)h

```
I found out that these lines are causing the problem if run as non-root user, but I do not know how to fix it:
https://github.com/greshake/i3status-rust/blob/0f935120073cb9cd23e57249d52540b164ad009a/src/blocks/net.rs#L163-L166

**Comment by cfsmp3** [comment]
@tkit1994 You seem to be hitting this bug - https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=987159
