### ISSUE TITLE
Battery: add `not_charging_format` config option

### ISSUE THREAD

**Issue by ram02z** [greshake/i3status-rust#1416]
Battery config
```toml
[[block]]
block = "battery"
format = "{percentage:2}"
device = "BAT0"
allow_missing = true
```

i3status-rust version: `0.21.2`
Linux kernel version: `5.15.17`

![image](https://user-images.githubusercontent.com/59267627/151661818-57b93424-c9ca-4d53-b1f4-6faa977490cb.png)

This is all I see
![image](https://user-images.githubusercontent.com/59267627/151661940-bfe9f2db-d7d3-4775-abf6-d4e9d21045ca.png)

Using `upower` also has the same behaviour.

Let me know if there anything I can do to debug this issue.

**Comment by MaxVerevkin** [comment]
Can you check whether it works on the `async` branch?

**Comment by ram02z** [comment]
@MaxVerevkin 

Im getting the following compile error:
```
error: linking with `cc` failed: exit status: 1
...
  = note: /usr/bin/ld: cannot find -lnotmuch
          /usr/bin/ld: cannot find -lsensors
          collect2: error: ld returned 1 exit status
```

I am using rust 1.57 and cargo 0.58.0

**Comment by MaxVerevkin** [comment]
If you use debian-based distro, run `sudo apt-get install libsensors-dev libnotmuch-dev`.

> Did the dependencies change?

`libsensors-dev` is a new dependency,  `libnotmuch-dev` will soon be optional.

**Comment by ram02z** [comment]
> Can you check whether it works on the [`async` branch](https://github.com/greshake/i3status-rust/tree/async) (you'll need to adapt your format a little)?

Using the following config and the async branch
```toml
[[block]]
block = "battery"
```

The same behaviour is exhibited.

![image](https://user-images.githubusercontent.com/59267627/151663130-d1710f04-3765-421a-9adb-a79cde7d2fb3.png)

**Comment by MaxVerevkin** [comment]
Apparently the battery block treats "Not charging" as "Full": https://github.com/greshake/i3status-rust/blob/0cccc595b5c9bac940687dbe7a9e6ab6d42f0006/src/blocks/battery.rs#L857

**Comment by MaxVerevkin** [comment]
@ram02z What's the output of `cat /sys/class/power_supply/BAT0/current_now`?

**Comment by ram02z** [comment]
> Apparently the battery block treats "Not charging" as "Full":
> 
> https://github.com/greshake/i3status-rust/blob/0cccc595b5c9bac940687dbe7a9e6ab6d42f0006/src/blocks/battery.rs#L857

I can confirm that when I disconnect the AC, the percentage is shown. Note that I am using a battery charging threshold, so it never reaches 100%.

>
> @ram02z What's the output of cat /sys/class/power_supply/BAT0/current_now?

`current_now` doesn't exist for me.

**Comment by MaxVerevkin** [comment]
> I can confirm that when I disconnect the AC, the percentage is shown. Note that I am using a battery charging threshold, so it never reaches 100%.

Well, then the current output _is_ correct?

**Comment by ram02z** [comment]
> > I can confirm that when I disconnect the AC, the percentage is shown. Note that I am using a battery charging threshold, so it never reaches 100%.
> 
> Well, then the current output _is_ correct?

Not really, because if I plug it when its above the charging threshold but below the full capacity, e.g. 70%, it will not show the percentage.

**Comment by MaxVerevkin** [comment]
> i3status-rust version: 0.21.2

Was it different in the previous versions?

**Comment by ram02z** [comment]
>
> Was it different in the previous versions?

I did try `0.20.7` and `0.20.4` again to check, but the behaviour is the same, however, I am pretty sure this behaviour is new since I have always seen the percentage. I did update my Linux kernel yesterday, so that might be it.

Anyway, I set `full_format = "{percentage}"` and it shows now (According to the docs, this should the default behaviour, but I have had to set it explicitly). I still think the behaviour is weird, because the battery is flagged as full when in its in the range charge_control_start_thresh_hold < x <= charge_control_end_threshold and plugged in.

**Comment by MaxVerevkin** [comment]
So, in your case, battery should be considered full then it's 85% and above, discharging if it's between 60% and 85%, and charging if's below 60% and connected?

>  I did update my Linux kernel yesterday, so that might be it.

Most likely.

**Comment by ram02z** [comment]
> So, in your case, battery should be considered full then it's 85% and above, discharging if it's between 60% and 85%, and charging if's below 60% and connected?

Yeah, I think the issue is that when my AC is plugged in and my battery level is between 60% and 85%, it doesn't charge, but it doesn't discharge; remains at the original battery level when it was plugged in. 

![image](https://user-images.githubusercontent.com/59267627/151664218-8e941316-edb4-4cf7-929b-0a1545e22d74.png)

**Comment by MaxVerevkin** [comment]
Just to be sure, when the percentage drops to 60%, does the status change to "Charging"?

**Comment by ram02z** [comment]
> Just to be sure, when the percentage drops to 60%, does the status change to "Charging"?

I think so, since I remember the icon changing to have the charging symbol. I am currently discharging my battery, I'll update you when it is < 60%.

**Comment by ram02z** [comment]
Also, it turns out that it was because of Linux 5.15.17.
https://github.com/torvalds/linux/commit/dd7c1a93025284d244bb5b00108b7417df00e1df

**Comment by MaxVerevkin** [comment]
> I think so, since I remember the icon changing to have the charging symbol. I am currently discharging my battery, I'll update you when it is < 60%.

Okay, if this is the case, then I think the block should just set status to "Discharging" if `charge_control_start_thresh_hold < x <= charge_control_end_threshold && status == "Not charging"` ?

**Comment by MaxVerevkin** [comment]
By the way, how does `UPower` handle this case?

**Comment by ram02z** [comment]
> > I think so, since I remember the icon changing to have the charging symbol. I am currently discharging my battery, I'll update you when it is < 60%.
> 
> Okay, if this is the case, then I think the block should just set status to "Discharging" if `charge_control_start_thresh_hold < x <= charge_control_end_threshold && status == "Not charging"` ?

Hmm, that would be better than "Full`, but just "Not Charging" would be accurate.

> By the way, how does UPower handle this case?

![image](https://user-images.githubusercontent.com/59267627/151664822-292c624b-3466-41de-878d-20cc80355ac9.png)
![image](https://user-images.githubusercontent.com/59267627/151664841-661ec11c-6d9d-4142-880d-23f34d437e96.png)

**Comment by MaxVerevkin** [comment]
> Hmm, that would be better than "Full", but just "Not Charging" would be accurate.

Like `not_charging_format` config option?

**Comment by ram02z** [comment]
> > Hmm, that would be better than "Full", but just "Not Charging" would be accurate.
> 
> Like `not_charging_format` config option?

Yeah I can see that being useful.

**Comment by ram02z** [comment]
> Just to be sure, when the percentage drops to 60%, does the status change to "Charging"?

Yeah it does, when it is plugged in.

![image](https://user-images.githubusercontent.com/59267627/151666409-07d0b82c-259d-4b81-b92f-8caa452570b5.png)
