### ISSUE TITLE
workspace underline

### ISSUE THREAD

**Issue by iliesh** [greshake/i3status-rust#1418]
Is there a way to add a underline to the workspace number like polybar have?

<img width="121" alt="image" src="https://user-images.githubusercontent.com/14953151/151724135-3876467e-122f-42b5-abf7-a30fde4015eb.png">

**Comment by ammgws** [comment]
All we do is provide JSON to i3/sway to parse and render blocks of information in i3bar/swaybar. The workspace numbers and tray icon part of the bar are not affected by this.

However, there is a WIP protocol that will allow scripts like i3status-rs to customise the workspace buttons too: https://github.com/i3/i3/issues/3818. I imagine that what you propose should be possible using pango markup once that is merged.
