### ISSUE TITLE
Battery block: better default value for upower device

### ISSUE THREAD

**Issue by ammgws** [greshake/i3status-rust#1419]
With sysfs, we default to the first device that starts with "BAT", or otherwise default to "BAT0".

With upower, we currently default to "BAT0". However, we can be smarter and either default to DisplayDevice or the first device in the enumerated list that starts with "BAT", like what we do with sysfs.

**Comment by MaxVerevkin** [comment]
> default to DisplayDevice

That sounds reasonable.

> With sysfs, we default to the first device that starts with "BAT"

That can be improved too (see https://github.com/MaxVerevkin/swaystatus/issues/4#issuecomment-864609003)

**Comment by ammgws** [comment]
Sounds good to me

**Comment by ammgws** [comment]
Closing via c6824727020090bf6eb59cd3bf6f4de0f10179fa
