### ISSUE TITLE
Support FontAwesome v6?

### ISSUE THREAD

**Issue by ammgws** [greshake/i3status-rust#1428]
https://github.com/FortAwesome/Font-Awesome/releases/tag/6.0.0

Perhaps worth looking into if we need to make any changes (either in docs or code), or even introduce a new icon set.

**Comment by codicodi** [comment]
https://github.com/greshake/i3status-rust/blob/master/files/icons/awesome5.toml seems to work fine with Font Awesome 6

Here are the icons rendered with FA5:
![image](https://user-images.githubusercontent.com/22731198/153063534-bb99f34d-7fa1-4769-ba8c-6da2826a53a0.png)
and with FA6:
![image](https://user-images.githubusercontent.com/22731198/153063573-6fc18b84-461a-4e89-af5f-810795e6d79f.png)
Actually one of the icons is broken with FA5 but not with FA6

**Comment by ammgws** [comment]
So I'm guessing that broken one is `resolution = "\uf096" # fa-square-o`?

It shows up in v4: https://fontawesome.com/v4/icon/square-o

But I can't even that codepoint in v5, perhaps it was replaced by: https://fontawesome.com/v5/icons/square?s=regular ?

Also can't find it in v6, apart from: https://fontawesome.com/icons/square?s=regular

**Comment by Pixelnarium** [comment]
ArchLinux updated FontAwesome to version 6 yesterday and now my status line looks like this:
![2022-02-09T07:44:19,859190871+01:00](https://user-images.githubusercontent.com/30435935/153136431-91f5cdb8-26a6-495b-a7a3-5223d945ba19.png)

Volumne, Brightness, Battery, Wireless, Toggle, Clock
```
icons = "awesome5"

[theme]
name = "native"

[theme.overrides]
separator = ""

[[block]]
block = "sound"

[[block]]
block = "backlight"

[[block]]
block = "battery"
interval = 60
format = "{percentage}"

[[block]]
block = "networkmanager"
interface_name_include = ["wlo1"]
ap_format = "{strength}"
device_format = "{icon}{ap}"

[[block]]
block = "toggle"
text = "Nachtmodus"
command_state = "systemctl --user is-active --quiet gammastep | echo 'isactive'"
command_on = "systemctl --user restart gammastep"
command_off = "systemctl --user stop gammastep"

[[block]]
block = "time"
interval = 10
locale="de_DE"
format = "%a, %d.%m.%Y %H:%M:%S"
```

Is there a way to fix this via configuration?

**Comment by codicodi** [comment]
@Pixelnarium do you have `Font Awesome 5 Free` or something like that in your bar configuration?

**Comment by codicodi** [comment]
@ammgws I can't see it documented either, but according to https://mathew-kurian.github.io/CharacterMap/ the square glyph is available via codepoints 25A0, 25FB, 25FC, F096 and F0C8.

**Comment by Pixelnarium** [comment]
> @Pixelnarium do you have `Font Awesome 5 Free` or something like that in your bar configuration?

Ah yes, thanks for the hint. Forgot that it is set there. It works now.

**Comment by 12ian34** [comment]
Thanks @codicodi updating that to `Font Awesome 6 Free` worked for me too.

**Comment by ammgws** [comment]
OK so the conclusion is that since all the icons we currently use in the `awesome5` Font Awesome 5 icon set still work/haven't changed in Font Awesome 6 we do not need to introduce another icon set (`awesome6`)?

**Comment by regazzoj** [comment]
@ammgws `awesome5` set still work with `Font Awesome 6 Free` so I think it's okay.
It's just a little weird to have `Font Awesome 6 Free` in`config` file and `awesome5` in `config.toml` file.
But that my point of view and as long as it works like that, I'm fine with it (:

**Comment by ammgws** [comment]
I guess it would have been better if we defaulted to the latest supported version for `awesome` and then created `awesome4`, `awesome5` for the older versions but it's too late now..

**Comment by emersion** [comment]
https://github.com/greshake/i3status-rust/commit/25bf1a32504046a5f42c0207e4603ee265837c23 adds `awesome6`.
