### ISSUE TITLE
Issue with Battery Block after update to newest release

### ISSUE THREAD

**Issue by cyberoma** [greshake/i3status-rust#1430]
Hi together,
I have a problem with the Battery Block after the update. Instead of using BAT0, it tries to read the battery information of my Bluetooth Keyboard. My config:

```
icons = "awesome5"

[theme]
name = "semi-native"
[theme-override]
seperator_bg = "#000000"
seperator_fg = "#000000"

[[block]]
block = "music"
hide_when_empty = true
player = "spotify"
buttons = ["play", "next"]
format = "Spotify"
max_width = 7

[[block]]
block = "net"
device = "wlp3s0"
format = "{signal_strength} {ssid^10}"
interval = 10


[[block]]
block = "disk_space"
path = "/"
format = "{icon} {used} /{total}"
[[block]]
block = "memory"
format_mem = "{mem_used} /{mem_total} ({mem_used_percents})"
display_type = "memory"
icons = true
clickable = true
interval = 5
clickable = false

[[block]]
block = "cpu"
interval = 1
format = "{utilization} {frequency}"

[[block]]
block = "sound"
[[block]]
block = "battery"
format = "{percentage} {time}"

[[block]]
block = "time"
interval = 5
format = "%a %d.%m %R"
locale="de_DE"
```

Error Message:
![image](https://user-images.githubusercontent.com/27788629/153469739-99276d8f-c45e-4be2-9052-d3eea2a88113.png)

Version: i3status-rs 0.21.4
Kernel: 5.15.19-1-MANJARO

EDIT:

I think it is similar to #1416.
I add `device = "BAT0"` and it shows know the full charged icon. I also use battery thresholds to stop charging after a specific percentage. 
Now if I add also the line `full_format = {"percentage"}` I get the percentage:
![image](https://user-images.githubusercontent.com/27788629/153479632-41c9a574-e30d-414f-840f-581509d5d9ca.png)

**Comment by ammgws** [comment]
Perhaps we should prefer batteries starting with "BAT" when there are multiple to choose from

**Comment by cyberoma** [comment]
Yeah that would be better I think. Maybe add an "not charging" format setting and make a difference between full charged and not charging while using thresholds. For example say that if percentage = 100 and not charging, then is full else not. 
This would be usefull, because of the coloring. Actually the coloring is like full charged.

**Comment by ammgws** [comment]
3db119a5a2dd12a65a499377cf849d418bfee308 should deal with the default battery part
