### ISSUE TITLE
CPU utilization moving all due font is not fixed

### ISSUE THREAD

**Issue by daviddgm** [greshake/i3status-rust#1432]
Hi!

Have any way to prevent the moving of i3status-rust text every time that CPU utilization change his value? Is it possible to use fixed font only for {utilization}?

**Comment by MaxVerevkin** [comment]
Yes, you can change the font for a portion of a format using `pango` . Here is an example of how I change the font for icons:
```toml
icons_format = " <span font_family='NotoSans Nerd Font'>{icon}</span> "
```

See `pango` docs [here](https://docs.gtk.org/Pango/pango_markup.html).
