### ISSUE TITLE
Async branch progress

### ISSUE THREAD

**Issue by ammgws** [greshake/i3status-rust#1440]
Fully compatible   :heavy_check_mark:
 Not implemented   :x:
 Partially implemented   :clock3:
 Complete but incompatible  :large_blue_circle:

 Block  | State  | Notes
------|---------|-----------
 apt  | :heavy_check_mark:  | 
 backlight  | :heavy_check_mark:  | 
 battery  | :clock3:  | [greshake/i3status-rust#1383](https://github.com/greshake/i3status-rust/pull/1383) [greshake/i3status-rust#1378](https://github.com/greshake/i3status-rust/pull/1378)
 bluetooth  | :heavy_check_mark:  | Use format flags instead of different format strings
 cpu  | :heavy_check_mark:  | 
 custom  | :heavy_check_mark:  | 
 custom_dbus  | :large_blue_circle:  | The original protocol couldn't handle multiple blocks at once
 disk_space  | :heavy_check_mark:  | 
 dnf  | :heavy_check_mark:  | 
 docker  | :heavy_check_mark:  | 
 external_ip  | :heavy_check_mark:  | 
 focused_window  | :large_blue_circle:  | More advanced formatting
 github  | :heavy_check_mark:  | 
 hueshift  | :heavy_check_mark:  | Docs are incomplete
 ibus  | :x:  | deprecate
 kdeconnect  | :clock3:  | Doesn't support old version
 keyboard_layout  | :clock3:  | Everything except `kbdd` (unable to get it work on my machine), [greshake/i3status-rust#1386](https://github.com/greshake/i3status-rust/pull/1386)
 load  | :heavy_check_mark:  | 
 maildir  | :heavy_check_mark:  | 
 memory  | :heavy_check_mark:  | 
 music  | :large_blue_circle:  |  No `smart_trim`
 net  | :clock3:  | no `ip(6)`, `bitrate` and `hide_(missing/inactive)`
 networkmanager  | :x:  | 
 notify  | :heavy_check_mark:  | 
 notmuch  | :heavy_check_mark:  | 
 nvidia_gpu  | :heavy_check_mark:  | Not tested (at all)
 pacman  | :heavy_check_mark:  | 
 pomodoro  | :large_blue_circle:  | Interactive configuration
 rofication  | :heavy_check_mark:  | 
 sound  | :heavy_check_mark:  | 
 speedtest  | :heavy_check_mark:  | 
 taskwarrior  | :heavy_check_mark:  | Experimentally use format flags instead of `format`, `format_singular` and `format_everything_done`
 temperature  | :heavy_check_mark:  | 
 time  | :heavy_check_mark:  | 
 toggle  | :heavy_check_mark:  | 
 uptime  | :heavy_check_mark:  | 
 watson  | :heavy_check_mark:  | 
 weather  | :heavy_check_mark:  | 
 xrandr  | :heavy_check_mark:

Other issues that will be solved once async branch is merged:
#430
#557
#1015
#1024
#1038
#1127
#1262
#1304
#1314
#1318
#1334
#1371 (partially)
#1442

**Comment by ammgws** [comment]
> Need to split format templates into widgets

Is this the only non-block specific thing left to implement?

**Comment by MaxVerevkin** [comment]
> > Need to split format templates into widgets
> 
> Is this the only non-block specific thing left to implement?

I think so. But I already mentioned that this particular solution is probably not the best one - it doesn't allow for "short formats".

**Comment by ammgws** [comment]
> Well only if they have a short version set, right? So if widget A hasn't and widget B has a short text (set as icon only or empty) it should only show widget A in short mode, right?

_Originally posted by @GladOSkar in https://github.com/MaxVerevkin/swaystatus/issues/4#issuecomment-1038086376_

Doesn't it work out with the above suggestion?

**Comment by MaxVerevkin** [comment]
Consider a block with the following format:

```toml
[block.format]
full = "two buttons: $btn1 $btn2"
short = "one button: $btn1"
```

The full format expands into something like
```json
[
    {"full_text": "two_buttons "},
    {"full_text": "<btn1 label> ", "instance": "btn1"},
    {"full_text": "<btn2 label>", "instance": "btn2"},
]
```

How should the short version integrate into this?

**Comment by GladOSkar** [comment]
I don't see why
```
[
    {"full_text": "two buttons ", "short_text": "one button"},
    {"full_text": "<btn1 label>", "short_text": "<btn1 label>", "instance": "btn1"},
    {"full_text": "<btn2 label>", "short_text": "",  "instance": "btn2"},
]
```
wouldn't work?

**Comment by GladOSkar** [comment]
Yeah true there i'm stumped :D I would probably try to prohibit this in some way unless there's a good reason for it

**Comment by MaxVerevkin** [comment]
Well, telling users that both of their formats should contain buttons in the same order is kinda weird.

And BTW, when/if https://github.com/i3/i3/issues/4113 is implemented, the whole idea of splitting stuff into widgets will be broken.

**Comment by GladOSkar** [comment]
Also true :(

**Comment by MaxVerevkin** [comment]
Actually, something like this might work :laughing: (haven't tried it yet)

```toml
[block.format]
full = "two buttons: $btn1 $btn2"
short = "$btn2 $btn1" # buttons are swapped
```

```json
[
    {"full_text": "two_buttons ", "short_text": ""},
    {"full_text": "<btn1 label> ", "short_text": "", "instance": "btn1"},
    {"full_text": "<btn2 label>", "short_text": "", "instance": "btn2"},
    {"short_text": "<btn2 label> ", "full_text": "", "instance": "btn2"},
    {"short_text": "<btn1 label>", "full_text": "", "instance": "btn1"},
]
```

**Comment by GladOSkar** [comment]
Oh no... As if a lot of all this wasn't already hacky enough -.-

**Comment by MaxVerevkin** [comment]
> As if a lot of all this wasn't already hacky enough

There's more.

Setting full text to `""` completely disables the block. Setting short text to `""` disables the short text. But we can use `"<span/>"` (or something similar) instead and it works.

**Comment by MaxVerevkin** [comment]
https://github.com/greshake/i3status-rust/commit/b42df75559f4029de2c888e26c73049683d5b1b5. For now I've implemented only clickable placeholders, i.e buttons.

Now, configs like this are possible

```toml
[[block]]
block = "music"
[block.format]
full = "$title_artist.rot-str(20) $prev $play $next|"
short = "$title_artist.rot-str(15) $play|"
```

> And BTW, when/if https://github.com/i3/i3/issues/4113 is implemented, the whole idea of splitting stuff into widgets will be broken.

Actually, this (given that something like this will be accepted) can be easily fixed - `i3bar`/`swaybar` should group the blocks by their `name` and treat them as a single "block" while choosing whether to use short or full text.

**Comment by MaxVerevkin** [comment]
If anyone has an nvidia gpu, please test this block: https://greshake.github.io/i3status-rust/i3status_rs/blocks/nvidia_gpu/index.html.

**Comment by MaxVerevkin** [comment]
Music block: `smart_trim` isn't... implementable. Unless a new type "string pair" and a specialized formatter "rot-str-smart-trim" are introduced in the formatting system. Is it worth it?

**Comment by MaxVerevkin** [comment]
About the networkmanager block: is it really necessary to display multiple widgets at once? Perhaps an approach identical to the music block is sufficient?

**Comment by MaxVerevkin** [comment]
> Actually, this (given that something like this will be accepted) can be easily fixed - i3bar/swaybar should group the blocks by their name and treat them as a single "block" while choosing whether to use short or full text.

I've implemented this in [my port of `i3bar`](https://github.com/MaxVerevkin/i3bar-river) and this seems like a good solution (no modifications needed in `i3status-rs`).

**Comment by MaxVerevkin** [comment]
[Yet another async design](https://github.com/greshake/i3status-rust/tree/yet_another_async)

<details>
<summary>Startup time comparison with the same config</summary>

#### Master

https://user-images.githubusercontent.com/34583604/169406185-8c0db7d7-e82b-4da2-a5a8-4eb9c40c9156.mp4

#### That branch

https://user-images.githubusercontent.com/34583604/169406243-870c4188-e3b7-4c02-862b-aded03fc2e33.mp4

</details>

**Comment by ammgws** [comment]
I can't find the post but I remember seeing you write that the second design would make it easier to port existing blocks. Do you think that's the way to go for now in order to switch master over to async ASAP?

**Comment by MaxVerevkin** [comment]
> I can't find the post

https://github.com/greshake/i3status-rust/issues/430#issuecomment-1133078817

> Do you think that's the way to go for now in order to switch master over to async ASAP?

IDK :) Porting complex blocks (net / music / dbus in general) is still painful.

**Comment by MaxVerevkin** [comment]
> and everything except networkmanager is already ported to "the first async".

And just to clarify, networkmanager is over-complicated and I neither understand nor use all of it's features, so don't expect me to port it

**Comment by ammgws** [comment]
Yeah it's basically untouched from the time it was contributed. I'm in favour of dropping it for now since there's no one available to maintain it anyway.

**Comment by ammgws** [comment]
Closing this since async branch has been merged. Create separate issues if required.
