### ISSUE TITLE
Use logind API to control backlight

### ISSUE THREAD

**Issue by eternal-sorrow** [greshake/i3status-rust#1442]
This allows to control brightness without udev rules. For reference you can see how it's done in [brightnessctl](https://github.com/Hummer12007/brightnessctl).

**Comment by MaxVerevkin** [comment]
Correct me if I'm wrong, but this how backlight block is implemented in `async` branch, right?

**Comment by ammgws** [comment]
Async branch has now been merged into master (still some work to do before release is possible though).
