### ISSUE TITLE
Material icons missing backlight icons

### ISSUE THREAD

**Issue by eternal-sorrow** [greshake/i3status-rust#1443]
`backlight_*`  icons are completely missing from the material icon theme.

**Comment by ammgws** [comment]
Got any icon suggestions?

**Comment by bim9262** [comment]
Looks like this was added https://github.com/greshake/i3status-rust/blob/master/files/icons/material.toml#L5-L17, but this issue was left open.

**Comment by eternal-sorrow** [comment]
It's not in any release yet...

**Comment by ammgws** [comment]
Need help with one remaining issue before we can make a release: https://github.com/greshake/i3status-rust/milestone/2

**Comment by MaxVerevkin** [comment]
> It's not in any release yet...

v0.30 is released.
