### ISSUE TITLE
When AC plugged in, battery block shows only battery icon 

### ISSUE THREAD

**Issue by eternal-sorrow** [greshake/i3status-rust#1444]
It ignores all the `format*` options and shows only the icon. Is there any way to control what is shown when AC is plugged?

**Comment by MaxVerevkin** [comment]
What does `cat /sys/class/power_supply/BAT0/status` output for you when AC is plugged in?

**Comment by eternal-sorrow** [comment]
`Full`

**Comment by eternal-sorrow** [comment]
Okay, this works.  The only thing that is wrong is the [documentation](https://github.com/greshake/i3status-rust/blob/master/doc/blocks.md#battery) saying that default for `full_format` is `"{percentage}"`. When I manually set it to `"{percentage}"`, it worked, but by default it was empty.

**Comment by MaxVerevkin** [comment]
> The only thing that is wrong is the [documentation](https://github.com/greshake/i3status-rust/blob/master/doc/blocks.md#battery)

Thanks for pointing this out, fixed.
