### ISSUE TITLE
Error in block 'battery': failed to load file /sys/class/power_supply/apple_mfi_fastcharge/status

### ISSUE THREAD

**Issue by tarkh** [greshake/i3status-rust#1445]
As topic says, after last update on `Arch Linux` I'm getting this error instead of i3status-rust panel:
```
Error in block 'battery': failed to load file /sys/class/power_supply/apple_mfi_fastcharge/status
```
My config block looks like this:
```
[[block]]
driver = "sysfs"
block = "battery"
allow_missing = true
hide_missing = true
interval = 30
format = "{percentage} {time}"
```
Also tried without `driver = "sysfs"` - same effect.
**This is desktop setup, so machine does not have any battery**, but for this reason my config contains `allow_missing = true` and `hide_missing = true`, which worked OK before.
If I set `driver = "upower"`, panel starts to work, but shows RED battery icon and 0%, which is not a valid behavior in this case.

**Comment by MaxVerevkin** [comment]
@tarkh Can you please check if the last commit actually fixed this for you?

**Comment by tarkh** [comment]
Yes, installed `i3status-rust-git ` package with latest upstream version and now error is gone.
