### ISSUE TITLE
Issues with FontAwesome 6 Pro

### ISSUE THREAD

**Issue by mpldr** [greshake/i3status-rust#1446]
My statusline currently looks like this:
![2022-03-17-09-56-24](https://user-images.githubusercontent.com/33086936/158773503-3a83f6a0-d494-4e56-b38b-fb10b7f5b1bf.png)

This is since updating FontAwesome Pro from v5 to v6. (using it's AUR package [ttf-font-awesome-pro](https://aur.archlinux.org/packages/ttf-font-awesome-pro))

The blocks are (in order):
- load
- pacman
- net
- cpu
- sound 
- time

The Separator has not been changed.

**Comment by ammgws** [comment]
Did you update your sway/i3bar config?

**Comment by mpldr** [comment]
No font has been specified there, so no.

**Comment by ammgws** [comment]
Not sure how it was working for you before (sway/i3bar just happened to fallback to font awesome on you system?), but you need to specify the font there

**Comment by mpldr** [comment]
Interesting… it works now. No clue how it could work before.
