### ISSUE TITLE
Some awesome icons are missing

### ISSUE THREAD

**Issue by Skycader** [greshake/i3status-rust#1447]
Today I installed SwayWM on a new machine. Installed font awesome (ttf-font-awesome 5.9.0-1) and set 
font pango: JetBrainsMono, Font Awesome 5 Free 13. 
RAM, Sound, battery, cpu are shown, however, brightness and flags are not shown. 
What can I do to fix this? Thank you.

**Comment by Skycader** [comment]
https://ibb.co/BZj77xS

**Comment by MaxVerevkin** [comment]
Can you please share the output of `fc-list | grep 'Font Awesome'`

**Comment by Skycader** [comment]
The problem was due to lacking of noto-fonts-emoji.

**Comment by ammgws** [comment]
> The problem was due to lacking of noto-fonts-emoji.

Yeah I just reinstalled arch and forgot about this too. Perhaps we need to document it if there are no font awesome icons we can use intead
