### ISSUE TITLE
No CPU usage icon after update to `ttf-font-awesome` 6.1.0

### ISSUE THREAD

**Issue by mvforell** [greshake/i3status-rust#1448]
Today I upgraded my Arch Linux system from `ttf-font-awesome` 6.0.0 to 6.1.0. Now the CPU usage icon is missing in `i3status-rust`, but all other icons still work (see screenshot below). Downgrading back to 6.0.0 fixes the problem. The `i3status-rust` version is 0.21.8.

This issue seems to be independent of the font used for the bar. I've tried it with "JetBrainsMono Nerd Font" (from the `nerd-fonts-complete` AUR package) as well as with "Font Awesome 6 Free" and the icon is missing in both cases.

![image](https://user-images.githubusercontent.com/16070060/159379136-a904b292-bb18-47d0-962a-486cbf53667a.png)

**Comment by sonderlab** [comment]
I have the same issue, after upgrading from ttf-font-awesome 6.0.0 to 6.1.0. All other icons are well.
![icon_issue](https://user-images.githubusercontent.com/99246478/159911451-6926ba98-8b4f-48d5-9099-bb012766c589.png)

**Comment by MaxVerevkin** [comment]
Does this fix it? (And does this work with v5?)

```toml
[icons]
name = "awesome5"
[icons.overrides]
cpu = "\uf2db"
```

**Comment by okhsunrog** [comment]
> Does this fix it? (And does this work with v5?)
> 
> ```toml
> [icons]
> name = "awesome5"
> [icons.overrides]
> cpu = "\uf2db"
> ```

yes, it does fix it (tested only with v6)

**Comment by MaxVerevkin** [comment]
https://github.com/greshake/i3status-rust/commit/8a3d2c3d8544ab6ae1f4e1169c4aa0a16910d9f4

Haven't tested with v5, but according to their web cite, it should work.

**Comment by ammgws** [comment]
So what was the actual issue in the end? The icon we were using was gone? Or we were using a non-existent FA icon this whole time?

**Comment by MaxVerevkin** [comment]
> So what was the actual issue in the end? The icon we were using was gone? Or we were using a non-existent FA icon this whole time?

We used a v5-only icon (https://fontawesome.com/v5/icons/tachometer-alt?s=solid)

The new once should work with both versions (https://fontawesome.com/icons/gauge?s=solid)
