### ISSUE TITLE
Create a meta-issue to track breaking changes?

### ISSUE THREAD

**Issue by MaxVerevkin** [greshake/i3status-rust#1462]
`nvim-cmp` has an issue which tracks breaking changes: https://github.com/hrsh7th/nvim-cmp/issues/231. I think something like this could be a good idea for `i3status-rust` too, as users can subscribe to such an issue to receive notifications.

**Comment by GladOSkar** [comment]
Interesting idea. Are there any good alternatives? An RSS file in the repo?

If we do this let's wait for issue #1500 :D

**Comment by AkechiShiro** [comment]
I believe breaking changes should be extensively documented, as in the documentation for the block being updated with a breaking change must have it's wiki documentation uodated as well, it would be nice I got heavily confused by a recent breaking change in the battery block, and the documentation is still out of date. I had to look at the commit history to see the breaking change and fix my i3status-rust config.

**Comment by GladOSkar** [comment]
> the documentation is still out of date

wdym? @MaxVerevkin's PR removed the option from the documentation as intended. Would you have preferred a removal notice in its place instead?

**Comment by AkechiShiro** [comment]
You are correct @GladOSkar I wrongfully believed the option was still there, I probably mistook the `hide_missing` with `allow_missing`, if that has been done this way then this is correct I believe. Maybe a removal notice during the update of the package would've been nice, like a red printed message stating breaking changes, but that would be very, very smooth to be able to know which breaking changes are going to happen and which aren't, and I'm not sure that's simple to put in place, maybe using a diff of the `NEWS.md` file ?

**Comment by GladOSkar** [comment]
Since we don't own/maintain the packages in the distros, that's difficult to do. For now, users just have to look at `NEWS.md` after updating, but @MaxVerevkin is currently testing a runtime notification for deprecated options.

**Comment by AkechiShiro** [comment]
Got it @GladOSkar 
Indeed such a notification would be neat, thanks for working on it @MaxVerevkin !

**Comment by MaxVerevkin** [comment]
> Usually I just subscribe to new releases and check the release notes/changelog/NEWS.md etc. I have a feeling that the users who don't check our NEWS.md also wouldn't follow the proposed issue so not sure if it would help overall with awareness.

Yes, `NEWS.ms` work for those who use released versions. However, it doesn't quite work for those who use latest master. 

Another good example of such a "meta-issue" is https://github.com/neovim/neovim/issues/14090.

**Comment by AkechiShiro** [comment]
Just for reference to anyone who might get here or is subscribed, the meta-issue to track breaking created by @MaxVerevkin is #1641
