### ISSUE TITLE
Lemonbar and i3status-rust

### ISSUE THREAD

**Issue by developer1105** [greshake/i3status-rust#1463]
Is it possible to use i3status-rust with lemonbar?

if so, is it possible to use it in another window manager (other than i3), like herbstluftwm?

Are there any tutorials or scripts about this?

**Comment by MaxVerevkin** [comment]
> Is it possible to use i3status-rust with lemonbar?

`i3status-rust` relies on [i3bar protocol](https://i3wm.org/docs/i3bar-protocol.html), so no, it will not work with `lemonbar` ([this one](https://github.com/LemonBoy/bar), I assume).

> is it possible to use it in another window manager (other than i3)

The only bars that implement i3bar protocol that I'm aware of are: `i3bar`, `swaybar` and `i3bar-river`. The last one is [my project](https://github.com/MaxVerevkin/i3bar-river), which I wrote to bring `i3status-rust` to river, but it runs on any wlr-based compositor.
