### ISSUE TITLE
i3status-rust not working

### ISSUE THREAD

**Issue by arnavgr** [greshake/i3status-rust#1464]
Im new to i3 so i will explain step by step what i did 

i installed i3status rust on my arch linux using `sudo pacman -Syu i3status-rust`
then i made a config file in my _.config_ called _i3status-rust_ and copied the _config.toml_ file from 
`/usr/share/doc/i3status-rust/examples/config.toml ` to `/home/user/.config/i3status-rust/`
then i edited the config.toml (i will paste it below)
```
`theme = "plain"
icons = "none"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used_percents}"
format_swap = "{swap_used_percents}"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 5
format = "%a %d/%m %R"

[[block]]
block = "battery"
if_command = "test -e /sys/class/power_supply/BAT0"
```

then i added this to my i3config file
```
bar {
    font pango:monospace 8
    position top
    status_command path/to/i3status-rs path/to/your/config.toml
    colors {
        separator #666666
        background #222222
        statusline #dddddd
        focused_workspace #0088CC #0088CC #ffffff
        active_workspace #333333 #333333 #ffffff
        inactive_workspace #333333 #333333 #888888
        urgent_workspace #2f343a #900000 #ffffff
    }
}
```
(i did replace the path to i3status-rs and config.toml with there repective paths)
my i3status bar doesnt show at all after restarting. where did i go wrong
(i dont have custom themes ,icons or fonts so i used what i did)

**Comment by GladOSkar** [comment]
Try running `i3status-rs` in a terminal. What does it output?

**Comment by ferdinandschober** [comment]
Did you fix your issue?
The config as provided is working for me.

**Comment by ferdinandschober** [comment]
Also just 
```
status_command i3status-rs
```
in your sway config should be enough.
