### ISSUE TITLE
Crash when pomodoro notifier is not found

### ISSUE THREAD

**Issue by notramo** [greshake/i3status-rust#1466]
The bar breaks when the pomodoro timer notifier program is not installed.
E.g. `i3-nag` isn't installed, but it's set as pomodoro notifier. When the timer ends, the bar crashes.

For easier debugging:
- don't output error to bar, but to STDERR
- display error in bar format so it's visible in bar
- don't output error at all, simply don't notify

**Comment by ammgws** [comment]
Perhaps output error to STDERR and simply don't notify?

**Comment by ammgws** [comment]
The thought was to avoid crashing the bar or erroring out the block since pomodoro should still function fine without notifications, but we can just `.block_error` it as you mentioned since this error should only really occur once in most cases.

**Comment by notramo** [comment]
> The thought was to avoid erroring out the block where possible since pomodoro should still function fine without notifications, but we can just `.block_error` it as you mentioned since this error should only really occur once in most cases.

There is no point in letting it functioning without it. It's probably a config error, which has to be fixed. Erroring out the block can help debugging, and probably the user fixes it immediately.
If the user don't want notifications, then the value can be set to `/bin/false`.

**Comment by ammgws** [comment]
Patches welcome

**Comment by MaxVerevkin** [comment]
@notramo should be fixed in #1473
