### ISSUE TITLE
.xsession-errors log: Icon bat_10 not found

### ISSUE THREAD

**Issue by tarkh** [greshake/i3status-rust#1467]
Hi! Everything works ok, but I'm getting warning/error in my `.xsession-errors` log:
```
Icon bat_10 not found in your icons file. Please check NEWS.md
```
My battery config part:
```
[[block]]
driver = "sysfs"
block = "battery"
allow_missing = true
hide_missing = true
interval = 30
format = "{percentage} {time}"
```
My battery icon config part:
```
bat_charging = ""
bat_not_available = ""
bat_empty = ""
bat_quarter = ""
bat_half = ""
bat_three_quarters = ""
bat_full = ""
```

**Comment by ammgws** [comment]
I guess the error message should be more specific - it's referring to this: https://github.com/greshake/i3status-rust/blob/master/NEWS.md#bug-fixes-and-improvements-12

Do you have a custom icons config? If not then how are you installing i3status-rust?

**Comment by tarkh** [comment]
Thanks! Yes, I do have custom icons on system. And maybe it's lacking of `bat_10` icon, which is kind of failsafe according to [this part of code](https://github.com/greshake/i3status-rust/blob/fb292c0e6563edb73f691ed1bbd76784befc5e6e/src/blocks/battery.rs#L830).
Anyway, just solved it by adding `bat_10 = "<img>"` to my icon config file.
