### ISSUE TITLE
Failing to compile v0.21.10

### ISSUE THREAD

**Issue by GoodGuyPat** [greshake/i3status-rust#1475]
When trying to perform an installation on a new system running on 5.13.0-41-generic, an error is thrown:

Compiling neli-wifi v0.3.1
error: there is no argument named `unknown`
   --> src/blocks.rs:166:78
    |
166 |                               unknown => Err(E::custom(format!("Unknown block '{unknown}'")))
    |                                                                                ^^^^^^^^^
...
179 | / define_blocks!(
180 | |     apt::Apt,
181 | |     backlight::Backlight,
182 | |     battery::Battery,
...   |
220 | |     xrandr::Xrandr,
221 | | );
    | |_- in this macro invocation
    |
    = note: this error originates in the macro `define_blocks` (in Nightly builds, run with -Z macro-backtrace for more info)

I finished the install by reviewing the git log and checking out a relatively recent commit (b7e4ff2a47031be023c785768041c057a42fac4c), so the issue (if any) was produced somewhere in between that commit and the one on HEAD at the time (c8a20b7cc91c86314d648b65bc092ba89b842252).

**Comment by MaxVerevkin** [comment]
Which version of rust are you using? You need at least 1.58.0 (2022-01-13) (current latest stable is 1.60).

**Comment by GoodGuyPat** [comment]
Yeah, apparently the one in the ubuntu repos is still 1.57.0. Thanks!
