### ISSUE TITLE
Icons have suddenly become small

### ISSUE THREAD

**Issue by arnavgr** [greshake/i3status-rust#1477]
![Mon May 9 01 43 21 AM IST 2022](https://user-images.githubusercontent.com/103447227/168535121-ea51325d-23b3-4e90-a407-141d99787ec8.jpg)
![Mon May 16 12:19:23 PM IST 2022](https://user-images.githubusercontent.com/103447227/168535277-19c07f4c-5ca1-40cd-b347-9055292718ef.jpg)

i was playing around with i3status-rs config and it changed the icons from large to small. i dont know how this hapened as there was no block for icon size or anything .Now even if i change config back to its original one , the icons remain small. Is there any way i can return the icons to their normal size?

This is my config.toml

```
theme = "dracula"
icons = "awesome"
 
[[block]]
block = "pacman"
interval = 600
format = "{pacman} + {aur} = {both} updates available"
format_singular = "{both} update available"
format_up_to_date = "system up to date"
critical_updates_regex = "(linux|linux-lts|linux-zen)"
aur_command = "yay -Qua"
 
[[block]]
block = "music"
player = "spotify"
buttons = ["play", "next"]
 
[[block]]
block = "networkmanager"
on_click = "urxvt -e nmtui"
interface_name_exclude = ["br\\-[0-9a-f]{12}", "docker\\d+"]
interface_name_include = []
 
[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used_percents}"
format_swap = "{swap_used_percents}"
 
[[block]]
block = "cpu"
interval = 1
 
[[block]]
block = "load"
interval = 1
format = "{1m}"
 
[[block]]
block = "sound"
 
[[block]]
block = "time"
interval = 5
format = "%a %d/%m %R"
 
[[block]]
block = "battery"
if_command = "test -e /sys/class/power_supply/BAT0"
```

**Comment by MaxVerevkin** [comment]
By the way, which font do you use?

**Comment by arnavgr** [comment]
i use the default config font which is DejaVu Sans Mono, FontAwesome 12
