### ISSUE TITLE
Music block bug reports

### ISSUE THREAD

**Issue by littlesum** [greshake/i3status-rust#1481]
If music file has no id info, such as aritst, title. Music block will never show play next …. button.
So i think if add new verb,  info about file name, music block will be show button normally.

Is there have any possible to add the new var :
“File name” ? For music block

**Comment by ammgws** [comment]
Sounds OK to me. IIRC with the formatter in the async branch it could be added as a fallback?

**Comment by MaxVerevkin** [comment]
> IIRC with the formatter in the async branch it could be added as a fallback?

Yeah, there is no such problem because while `$combo` is optional and can be missing, buttons are always available (if there is at least one player). Thus this will work just fine:

```toml
format = "{$combo.rot-str(25, 0.5)|}$prev$play$next|"
```

**Comment by littlesum** [comment]
```
[[block]]
block = "music"
player = "mpd"
buttons = ["play", "next"]
dynamic_width = true
format = "{combo}"
```


this is my config!
When some file no id buttons will not show!

**Comment by littlesum** [comment]
> > IIRC with the formatter in the async branch it could be added as a fallback?
> 
> Yeah, there is no such problem because while `$combo` is optional and can be missing, buttons are always available (if there is at least one player). Thus this will work just fine:
> 
> ```toml
> format = "{$combo.rot-str(25, 0.5)|}$prev$play$next|"
> ```

i set as combo! But when mpd play,not all music will show button! Some music will not show buttons!

**Comment by MaxVerevkin** [comment]
> i set as combo! But when mpd play,not all music will show button! Some music will not show buttons!

It's only relevant for this branch: https://github.com/greshake/i3status-rust/tree/async

**Comment by littlesum** [comment]
![97367D95-688F-4108-B22A-C6E52F4205AF](https://user-images.githubusercontent.com/22040751/169704792-f9486e48-ce16-4bfa-b1ab-d88392770232.jpeg)
![BE1179AD-32FA-452E-8947-16CA7C6A3FD5](https://user-images.githubusercontent.com/22040751/169704796-99da247f-b9d0-4ad6-9f84-3792915ba8dd.jpeg)
![44C013A4-0690-410C-BAF9-8BCC550E8FB2](https://user-images.githubusercontent.com/22040751/169704799-b08bdb71-ddd9-4d9a-81bf-975adb6c4659.jpeg)

**Comment by ammgws** [comment]
I believe this should be solved with the new formatter in master (release might be a little while a way though)
