### ISSUE TITLE
i3status-rust lagging behind when clicking on nvidia_gpu block

### ISSUE THREAD

**Issue by TheBlackBeans** [greshake/i3status-rust#1489]
I have a time block with `interval=1` rendering seconds, so basically it should change every second. And it works fine. I also have a `nvidia_gpu` block with `show_memory=true` (by default), and when I click on it, it effectively toggles between max memory and current usage. However, when I click on it once, the whole bar starts lagging behind, refreshing (according to my time block) at most once every three seconds. Not only this is a bit annoying when reading time, but it really feels laggy because there is a lot of delay between clicking on a block, and the bar showing a difference (for instance, it takes three seconds to toggle between max memory and current usage). Strangely enough, this only occurs with the `nvidia_gpu` block: my `sound` block works perfectly, ie. right-clicking it (which toggles mute) works instantly, and does not cause the rest of the bar to start lagging. My bar is `swaybar`.

In `.config/i3status-rust/config.toml`:
<details>

```text
icons_format = "<span font_family='Font Awesome 6 Free'>{icon}</span> "

[icons]
name = "awesome6"
[icons.overrides]
time = ""
cpu = ""
[theme]
name = "solarized-dark"
[theme.overrides]
separator = "<span font_family='FiraCode Nerd Font'>\ue0b2</span>"

[[block]]
block = "focused_window"
max_width = 60
[[block]]
block = "net"
format = "{ssid}"
on_click = "wifi toggle"
[[block]]
block = "sound"
[[block]]
block = "cpu"
interval = 0.5
[[block]]
block = "nvidia_gpu"
label = ""
[[block]]
block = "time"
format = "<span font_family='Font Awesome 6 Free'></span> %H:%M:%S"
interval = 1
[[block]]
block = "time"
format = "<span font_family='Font Awesome 6 Free'></span> %d/%m"
interval = 3600
```
</details>

**Comment by ammgws** [comment]
Could you please try the async branch? Although the nvidia block hasn't been tested there yet, I suspect your issues would probably be gone.

**Comment by ammgws** [comment]
FYI Async branch was merged into master.

Perhaps look at where the current nix package sources i3status-rs and change it to source git master instead?

**Comment by ammgws** [comment]
v0.22 isn't async

Can you test like this?

```sh
>cd /tmp/
>git clone https://github.com/greshake/i3status-rust
>cd i3status-rust
>cargo build
```
then edit your i3bar/swaybar config to point to the binary that was built (`/tmp/i3status-rust/target/debug/i3status-rs`)

Note that there were breaking changes to the config file in v0.3 (master) so you need to resolve those too

**Comment by ammgws** [comment]
> clicking on the memory usage no longer switches between current usage and total available memory

That's probably something missed in the port to async that we need to look into

> It also doesn't seem to trigger any lag whatsoever

Awesome

**Comment by MaxVerevkin** [comment]
> That's probably something missed in the port to async that we need to look into

It _is_ implemented, just not tested because I don't have an nvidia card.

**Comment by ammgws** [comment]
Yeah I don't have one either. In the past I made a bash script that output lines based on example output I found on the internet but it wasn't ideal.

**Comment by MaxVerevkin** [comment]
Oh that's why :laughing: https://github.com/greshake/i3status-rust/blob/2d31e182257f598843a3e96b2127bbd7abc465ec/src/blocks/nvidia_gpu.rs#L230

**Comment by MaxVerevkin** [comment]
@TheBlackBeans can you try now?
