### ISSUE TITLE
App can't find the theme file 

### ISSUE THREAD

**Issue by jwtiyar** [greshake/i3status-rust#1491]
hey this is first time trying i3status-rust, this is my config 👍🏼 

```
[theme]
# file = "/home/jwty/.config/i3status-rust/themes/dracula.toml"

file = "dracula.toml"
# icons = "none"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used_percents}"
format_swap = "{swap_used_percents}"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 5
format = "%a %d/%m %R"

[[block]]
block = "battery"
if_command = "test -e /sys/class/power_supply/BAT0"
```

As you can see i tried both ways none of them found by the app, copied my theme file to three different places as mentioned in wiki, none of them working. 
This is the theme config:

```
[theme]
idle_bg = "#282a36"
idle_fg = "#f8f8f2"
info_bg = "#8be9fd"
info_fg = "#282a36"
good_bg = "#50fa7b"
good_fg = "#282a36"
warning_bg = "#f1fa8c"
warning_fg = "#282a36"
critical_bg = "#ff5555"
critical_fg = "#282a36"
separator = "\ue0b2"
separator_bg = "auto"
separator_fg = "auto"
[theme]
```

I Added same theme file inside ~/.local/share/i3status-rust/themes & home directroy/i3status-rust/themes & ~/.config/i3status-rust/themes

Wha iam missing?

**Comment by MaxVerevkin** [comment]
Is your `$HOME` variable set properly? What's the output of `echo $HOME`?

**Comment by jwtiyar** [comment]
> Is your `$HOME` variable set properly? What's the output of `echo $HOME`?

It's /home/jwty

**Comment by MaxVerevkin** [comment]
@jwtiyar which error message do you get?

**Comment by MaxVerevkin** [comment]
@jwtiyar also, how did you install `i3status-rust`? If you installed from your distro's repository, then you don't need to do anything because `dracula` theme should be already included. If you installed from source, then you should run [`this install script`](https://github.com/greshake/i3status-rust/blob/master/install.sh).

**Comment by jwtiyar** [comment]
> @jwtiyar also, how did you install `i3status-rust`? If you installed from your distro's repository, then you don't need to do anything because `dracula` theme should be already included. If you installed from source, then you should run [`this install script`](https://github.com/greshake/i3status-rust/blob/master/install.sh).
It shows that:
`error:Failed to parse TOML from file contents, Cause:Theme 'dracula.toml' not found. for key 'theme' at line41 column 1`

I installed for gentoo through guru overlay.

**Comment by jwtiyar** [comment]
it solved guys, I was creating the dracula.tom file, Inside the file  was suppose to not include colors inside [theme] block (As its shown in my config above), Just removed [theme] tag and problem solved. thank you again.

**Comment by MaxVerevkin** [comment]
Glad you found a solution. The error message should be improved though.

**Comment by MaxVerevkin** [comment]
And can you check if `/usr/share/i3status-rust/themes` is present on your system?

**Comment by jwtiyar** [comment]
> And can you check if `/usr/share/i3status-rust/themes` is present on your system?

No it was not available.

**Comment by MaxVerevkin** [comment]
Then the package is incomplete. By the way, how do you use icons? Did you copy them from github? They should also be automatically installed.

**Comment by jwtiyar** [comment]
> Then the package is incomplete. By the way, how do you use icons? Did you copy them from github? They should also be automatically installed.

I Re-installed it again, No folder or file created under /usr/share for i3status-rs.
Yes, cloned the project then move them to ~/.config folder.
