### ISSUE TITLE
Add SI unit prefixes to formatter (base 10; MB, GB, TB)

### ISSUE THREAD

**Issue by Mynacol** [greshake/i3status-rust#1493]
Hi, I recently added the disk_usage block to my config. My drive has quite exactly 1TB (1000GB, 10**12 Byte) storage. In base-10 this is 1TB, in base-2 this is 931GB.

The formatter seems to use base-2 calculations, while I would like to use base-10 for disk space. It just seems "prettier" for me seeing 1TB instead of 931GB.

Please add new Prefixes for base-10 calculations.

And btw. using "GB", "TB", etc. for base-2 is _legacy_ usage, and should be used for base-10 calculations. The proper names for base-2 nomenclature are "KiB", "MiB", "GiB", "TiB", etc., stemming from e.g. Kibibyte. You expect 1 _Kilo_-meter to be 1000 meters, as an example. The [SI prefixes](https://en.wikipedia.org/wiki/Metric_prefix) require Kilo to be 1000, Mega 1000*1000, etc.. See [Wikipedia](https://en.wikipedia.org/wiki/Byte#Multiple-byte_units) for more info.

Switching GB to base-10 and using GiB for base-2 would be a breaking change, but fixes it for good.

**Comment by c02y** [comment]
Is it already using 1000 based unit for disk_space block? I use 1024 based or binary unit for all my Linux unties such as `df` or `exa` or `dua`, when I use `df -h` (1024), it shows I have 94G disk space out of 938G available, `df -H` (1000) shows I have 101G out of 1.1T available but in disk_space block of i3status-rust, it shows I have 100 GB.

I came here to ask for a feature to add 1024 based unit for disk_space block.

**Comment by MaxVerevkin** [comment]
v0.30 accidentally changed this

Any suggestions on how this should be configured?

**Comment by c02y** [comment]
Maybe add a unit filed such as `unit: 10 or unit: 2`, or simply use `G` for 10-based, `Gi` for 2-based. 

For example, `exa -l`(1000) show `G` for a file's size, `exa -lb` (1024) shows `Gi`

**Comment by MaxVerevkin** [comment]
@Mynacol @c02y see #1604
