### ISSUE TITLE
Various regressions after updating to v0.30

### ISSUE THREAD

**Issue by GladOSkar** [greshake/i3status-rust#1498]
Just jotting this down here because i don't have more time currently. I can separate into multiple issues later if desired.

## ~~1. `custom` with `cycle` cycles automatically every 10 seconds~~

~~`custom` does not have an interval set. `10` is the lowest interval used in any block.~~

Block:
```
[[block]]
block = "custom"
shell = "sh"
cycle = ["echo '🐑'", "cat /etc/hostname"]
[[block.click]]
button = "left"
cmd = "<command>"
```

## 2. `battery` does not display

No idea why, i checked the updated config options.

MOVED TO #1504

Block:
```
[[block]]
block = "battery"
interval = 30
full_threshold = 98
[block.format]
full = "$percentage $time ($power)"
short = "$percentage"
```

```
$ ls /sys/class/power_supply/BAT0/
alarm           charge_full         current_now  hwmon0/       power/         status      type                voltage_now
capacity        charge_full_design  cycle_count  manufacturer  present        subsystem@  uevent
capacity_level  charge_now          device@      model_name    serial_number  technology  voltage_min_design
```

## ~~3. Can't hide inactive `net` blocks~~

~~I used to have `hide_inactive = true` set on my ethernet NICs to only show the blocks when a link was established. I don't see a way to do that anymore.~~

Screenshot:
![image](https://user-images.githubusercontent.com/9497832/174586063-1f34e45a-cad8-4859-9624-4b3301ed1684.png)

## 4. `kdeconnect` shows `"Failed to read charge"`.

I think reading the battery charge from `kdeconnect` never worked for me, i had the battery display disabled and only showed notifications. That doesn't seem possible anymore because i can't get the error message to disappear.

MOVED IN FAVOR OF #1499

Block:
```
[[block]]
block = "kdeconnect"
device_id = "7814dd5c9a77a7b2"
format = "$notif_count"
bat_info = 0
bat_good = 0
bat_warning = 0
bat_critical = 0
```

Screenshot:
![image](https://user-images.githubusercontent.com/9497832/174585586-ea526935-9d14-458d-a6cd-ec43fef8ba86.png)

## 5. `music` block's `hide_when_empty = true` doesn't work

I still see the music icon if no player is open.

MOVED TO #1505

Block:
```
[[block]]
block = "music"
hide_when_empty = true
```

Screenshot:
![image](https://user-images.githubusercontent.com/9497832/174586300-4a6d3d2e-23ca-4d4b-8583-6667ad62566e.png)

That's it for now. Thanks! And awesome work on getting `async` merged @ammgws @MaxVerevkin! :)

**Comment by ammgws** [comment]
It's all thanks to Max. Now hopefully we can all pick up the slack and work out these remaining bugs together!

Thanks for mentioning the battery one, I started to doubt my sanity :laughing: 

Times like this kinda make we wish we had a `--debug` flag to print certain helpful data points to stderr...

**Comment by MaxVerevkin** [comment]
> 1. custom with cycle cycles automatically every 10 seconds

Should be fixed in #1501

**Comment by MaxVerevkin** [comment]
> Times like this kinda make we wish we had a --debug flag to print certain helpful data points to stderr...

Or we can use `log` + `env_logger`. Then we could just do

```
$ RUST_LOG=<block_name>=debug cargo r
```

to debug a specific block.

**Comment by ammgws** [comment]
I see, that could be helpful in reducing noise. Either way we still need to add the debug prints. I'll add an issue for implementing that!

**Comment by MaxVerevkin** [comment]
@GladOSkar can you test #1506?

**Comment by GladOSkar** [comment]
> @GladOSkar can you test #1506?

Works perfectly
