### ISSUE TITLE
When using pipewire, the sound module causes delays in status bar loading

### ISSUE THREAD

**Issue by invader-zimm** [greshake/i3status-rust#1502]
I'm on Artix Linux, using pipewire instead of pulseaudio. If I add a sound block to the status bar and I start i3wm, 9 times out of 10, i3status_rust takes about 3-4 seconds to load/display. The block seems to function as expected, the only issue I see is the noticeable delay in loading the status bar.
If I remove the sound block, the status bar loads almost instantaneously. Before switching to pipewire, loading was also very fast. 

I have installed these packages
`pipewire pipewire-alsa pipewire-pulse`
and in .xinitrc I have
```
/usr/bin/pipewire&
/usr/bin/pipewire-pulse&
/usr/bin/wireplumber&
exec i3
```
The block setup in config.toml is pretty basic:
```
[[block]]
block = "sound"
driver = "pulseaudio"
on_click = "pavucontrol"
headphones_indicator = true
```

Can anyone else reproduce this issue? Any idea what exactly causes that delay?
Thanks.

**Comment by MaxVerevkin** [comment]
Which version do you use? (`i3status-rs -V`)

**Comment by ammgws** [comment]
If you comment out those lines in xinitrc (other than i3), and instead start them up each in a separate terminal without backgrounding them, can you still reproduce the issue (I guess you will have to kill i3bar bar first)? If so then there might be some interesting info in the terminal running pipewire-pulse

**Comment by invader-zimm** [comment]
I am using i3status-rs 0.22.0.

If I do this:
1. edit .xinitrc to contain only "exec i3"
2. start i3 and kill i3bar
3. from separate terminals, start pipewire, pipewire-pulse and wireplumber
4. start i3bar 

then I don't really see the delay, or at least it's not noticeable. I don't see any errors regarding pipewire in the terminals, everything seems to initialize and start without problems.

**Comment by GladOSkar** [comment]
> Using i3status-rs from git requires compilation, right?

Yes it does, but with rust it's not that hard :) check out https://rustup.rs/ to install the toolchain and then run `cargo build` in the repo :)

**Comment by MaxVerevkin** [comment]
I'm pretty sure this is fixed on master.
