### ISSUE TITLE
v0.30: music block's hide_when_empty = true doesn't work

### ISSUE THREAD

**Issue by ammgws** [greshake/i3status-rust#1505]
As mentioned in #1498 . Splitting into separate issue to make it easier to track.

**Comment by MaxVerevkin** [comment]
eae07262ed5a4eb5747756b0c6caf5e3361b1bc1 adds logging. Run with `RUST_LOG=music=debug cargo r >/dev/null` to see music's debug messages. Currently it prints the list of available players.

So, can you check which players are available when you expect the block to be hidden?

**Comment by MaxVerevkin** [comment]
eae07262ed5a4eb5747756b0c6caf5e3361b1bc1 also breaks compilation on stable rustc :(

**Comment by GladOSkar** [comment]
Actually since a bit after writing #1498 this issue hasn't occurred again for me, did one of you replicate?

**Comment by ammgws** [comment]
I can't reproduce it

**Comment by GladOSkar** [comment]
I guess it was some rogue player then and we can close this
