### ISSUE TITLE
v0.30: pulaseaudio bindings are no longer optional

### ISSUE THREAD

**Issue by ammgws** [greshake/i3status-rust#1507]
v0.22:
`libpulse-binding = { optional = true, version = "2.0", default-features = false }`

v0.30:
`libpulse-binding = { version = "2.0", default-features = false }`

@MaxVerevkin Is there a reason why it was changed?

**Comment by MaxVerevkin** [comment]
It was just easier to develop it this way. Now it can be made optional again.
