### ISSUE TITLE
v0.30: Re-implement apcupsd driver for battery block

### ISSUE THREAD

**Issue by ammgws** [greshake/i3status-rust#1510]
Added late last year and present in v0.21 onwards, see https://github.com/greshake/i3status-rust/issues/1379 and https://github.com/greshake/i3status-rust/pull/1383

Setting a tentative milestone of v0.30, but I think this driver is likely niche enough that we could probably release v0.30 first and leave re-implementation for a later version. @bim9262 What do you think?

**Comment by bim9262** [comment]
@ammgws, is v0.30.0 the implementation what's currently being written in the async branch?
I may be the only person who uses the apcupsd driver, so if it went missing, it's not the end of the world.

**Comment by ammgws** [comment]
The async branch was merged into master a few days ago.

If it holds back the release of v0.30 then I will leave it for the future

**Comment by bim9262** [comment]
Cool. I'm happy to take a look at the reimplantation. Do you have any pointers on doing TCP connection asynchronously?

**Comment by MaxVerevkin** [comment]
> Do you have any pointers on doing TCP connection asynchronously?

[`tokio` docs](https://docs.rs/tokio/latest/tokio/net/struct.TcpStream.html)

[A simple example of `UnixStream` used in one of the blocks](https://github.com/greshake/i3status-rust/blob/master/src/blocks/rofication.rs#L83-L109)

[Http-over-socket example](https://github.com/greshake/i3status-rust/blob/2aca056dafe58693009d353ecbdd010291803dbf/src/blocks/docker.rs#L88-L110)

**Comment by bim9262** [comment]
Thanks for pointing me towards tokio. It took me a while to figure out everything out, but it seems to work well!

Did the behavior of disconnecting a battery change in 0.30? I see an error, but as far as I can tell it doesn't attempt to reconnect. I attempted to test the behavior using the upower driver, but I get an error that the UPower device could not be found.

**Comment by MaxVerevkin** [comment]
Missing batteries don't work with `upower` yet (see  #1495). It does work with `sysfs` though.
