### ISSUE TITLE
v0.30: Reimplement xkbswitch driver for keyboardlayout block

### ISSUE THREAD

**Issue by ammgws** [greshake/i3status-rust#1512]
First appeared in v0.21.0: https://github.com/greshake/i3status-rust/pull/1386

@roguh This may end up out of v0.30 for the time being

**Comment by aloner-pro** [comment]
Hi
Is this still an important issue. Can I work on this?

**Comment by ammgws** [comment]
Please do!

**Comment by aloner-pro** [comment]
> Please do!

Can you give me a head start regarding this. It would be helpful !

**Comment by ammgws** [comment]
SetXkbMap should be similar enough

**Comment by tusharxoxoxo** [comment]
I am on it #1813
