### ISSUE TITLE
docs: quotes inside <code> blocks get transformed into different char

### ISSUE THREAD

**Issue by ammgws** [greshake/i3status-rust#1522]
I guess we have to specify the quotes inside <code> flags differently 

kdeconnect docs - incorrect quote marks:

![image](https://user-images.githubusercontent.com/20397027/175209068-98cc9b5e-f6bb-41a8-9082-72f4d012d7b7.png)

cpu docs - correct quote marks: 

![image](https://user-images.githubusercontent.com/20397027/175209097-5f686958-c9f0-4c38-ad4c-70894511b2e4.png)

**Comment by bim9262** [comment]
Resolved by #2021
