### ISSUE TITLE
doc clarification regarding placeholder flags

### ISSUE THREAD

**Issue by ammgws** [greshake/i3status-rust#1528]
In the `kdeconnect` docs the default format string is apparently `“$name $bat_icon $bat_charge{ $notif_icon|}”` and `$bat_charge` is explained as "Battery charge level (only when connected)". It implies that any placeholder that can be missing (e.g. bat_charge that is only available when phone is connected) can be used as a Flag despite its inherent Type actually being something else. If true then we need a way to document that since I dont think I saw that in the formatter docs (it only mentioned flags).

**Comment by MaxVerevkin** [comment]
I think [this](https://greshake.github.io/i3status-rust/i3status_rs/formatting/index.html#handling-missing-placeholders-and-incorrect-types) section of the docs explain this behavior. Basically, `|` is a "try again" operator, scoped in `{...}`. 

> `“$name $bat_icon $bat_charge{ $notif_icon|}”`
>
> (e.g. bat_charge that is only available when phone is connected) can be used as a Flag

In this example `$notif_icon` is the one that's used as a "Flag".
