### ISSUE TITLE
v0.30: Re-add shell expansion for path handling in all relevant blocks

### ISSUE THREAD

**Issue by ammgws** [greshake/i3status-rust#1531]
See https://github.com/greshake/i3status-rust/pull/1453

**Comment by MaxVerevkin** [comment]
064913c42b2d6c30a3321e16946d0956b29ec841

**Comment by ammgws** [comment]
I think we are still missing rofication and watson from the original PR

**Comment by MaxVerevkin** [comment]
https://github.com/greshake/i3status-rust/blob/570cf62c4bfcb6abc246fd235ec52b8dbc6a3cb0/src/blocks/watson.rs#L51

https://github.com/greshake/i3status-rust/blob/570cf62c4bfcb6abc246fd235ec52b8dbc6a3cb0/src/blocks/rofication.rs#L51

I haven't tested it, so IDK. It didn't work for you?

**Comment by ammgws** [comment]
I don't use either of those blocks, but I don't see why it shouldn't work. Was just a failed grep by me.
