### ISSUE TITLE
v0.30: re-add get_bss_info for wifi in net block

### ISSUE THREAD

**Issue by ammgws** [greshake/i3status-rust#1534]
introduced in 0.21.7: https://github.com/greshake/i3status-rust/commit/4f11d68b1d5147fe2b5285d68653e7091f44f628

**Comment by MaxVerevkin** [comment]
IIRC this fallback was needed because of a bug in `neli-wifi`. I don't think it's necessary anymore.

**Comment by ammgws** [comment]
OK we can re-open if someone can repro

**Comment by MaxVerevkin** [comment]
Apparently it is still needed: https://github.com/greshake/i3status-rust/issues/1583
