### ISSUE TITLE
Clock Icon not working

### ISSUE THREAD

**Issue by dreyses11** [greshake/i3status-rust#154]
Since I've updated `i3status-rust`, the icons weren't working ,so I've installed `ttf-font-awesome-4`  from the AUR and now all icons are working, except the time icon. 
![image](https://user-images.githubusercontent.com/33466028/36102647-361aa22e-100d-11e8-89a7-7d02b3c43211.png)
What can I do to fix it?

**Comment by atheriel** [comment]
I can't reproduce, is anyone else experiencing this issue?

In the meantime, you can change the icons directly in your configuration file. Check if that solves your problem.

**Comment by bemeurer** [comment]
I've tried, and failed to reproduce this on my Arch machine. I'll try to do it from a VM with a clean install, maybe it's a missing dependency.

**Comment by mmetak** [comment]
This happens (at least to me) when I specify `Regular` style for `FontAwesome` and `Semibold` for an example to second font style. Like this:

``
font pango:FontAwesome Regular, SF Compact Display Semibold 11
``

Setting just `FontAwesome` without `Regular` style for it shows all icons.
