### ISSUE TITLE
Confuse on format string

### ISSUE THREAD

**Issue by superdinogirl** [greshake/i3status-rust#1540]
Sorry because english not the first language and first time post issue

In formatter how she can behave with more or less argument?

Exemple - how can set only max-width or min-width?
Set max-width only: `$combo.str(21)`
Set min-width and max-width: `$combo.str(5, 21)`
Set min-width only: `$combo.str(5)` but look same max-width option

Exemple - how can set only width and prefix?
`$swap_used_percents.eng(4, k)` cannot know which one I mean?

**Comment by MaxVerevkin** [comment]
> Exemple - how can set only max-width or min-width?

1. To set only `min_width` just set only the first argument: `$combo.str(5)`.
2. To set only `max_width` you need to set `min_width` to zero: `$combo.str(0, 21)`.

**Comment by ammgws** [comment]
I guess this is kinda covered by #1542
