### ISSUE TITLE
Formatting: fix examples configs which use `.str(<width>)`

### ISSUE THREAD

**Issue by MaxVerevkin** [greshake/i3status-rust#1542]
Currently the order of arguments is `.str(<min_width>, <max_width>)`. However, example configs only ever set `min_width`, which isn't quite right. Also the order of parameters can be reconsidered.

**Comment by ammgws** [comment]
> However, example configs only ever set `min_width`, which isn't quite right

Do you mean the example configs are intending to set `max_width` so they should be `.str(0, max_width)`, but they are currently only doing `.str(max_width)` which sets min_width instead?

**Comment by MaxVerevkin** [comment]
> Do you mean the example configs are intending to set max_width so they should be .str(0, max_width), but they are currently only doing .str(max_width) which sets min_width instead?

Yes, and I feel like the `.str(0, width)` pattern is so common that the arguments can be swapped, but I'm not sure.
