### ISSUE TITLE
Download source link from "archive"

### ISSUE THREAD

**Issue by lumarogit** [greshake/i3status-rust#1546]
Hi,

The new version v0.22.0 report this message when try download from "archive", appear this:
https://github.com/greshake/i3status-rust/archive/v0.22.0.tar.gz
_the given path has multiple possibilities: #<Git::Ref:0x00007fca29037668>, #<Git::Ref:0x00007fca29035e80>_

The  previous version download without problem:
https://github.com/greshake/i3status-rust/archive/v0.21.4.tar.gz

Any idea? Thanks.

**Comment by MaxVerevkin** [comment]
This one should work: https://github.com/greshake/i3status-rust/archive/refs/tags/v0.22.0.tar.gz

**Comment by lumarogit** [comment]
Thanks, this URL works fine, this URL works fine. I wanted to avoid "refs/tags" in the link but I see that it is not possible. Thank you very much !!!
