### ISSUE TITLE
v0.30: `battery` uses wrong battery

### ISSUE THREAD

**Issue by GladOSkar** [greshake/i3status-rust#1547]
Some more `battery` issues...

My format is `$percentage $time ($power.str(1))`.

After resetting i3status-rust, the block displays like this for 30s:
![image](https://user-images.githubusercontent.com/9497832/175832821-98d4e689-9969-4c74-8fed-d3519a17b971.png)

Then, after those 30s (on the first update, it switches to:
![image](https://user-images.githubusercontent.com/9497832/175832843-0f1d0736-b36f-400c-b8da-f564a7888e0a.png)
with the detailed explanation:
![image](https://user-images.githubusercontent.com/9497832/175832873-2d55edad-690b-4063-9106-41b5421d2610.png)
even though, AFAIK, `$time` very much is a valid placeholder according to [the docs](https://greshake.github.io/i3status-rust/i3status_rs/blocks/battery/index.html) and worked before.

The first display is also not correct and varies, but never correlates to the current battery charge level (here 100%)

This is my block config:
```
[[block]]
block = "battery"
interval = 30
full_threshold = 98
[block.format]
full = "$percentage $time ($power.str(1))"
short = "$percentage"
```

Any ideas? Thanks!

**Comment by MaxVerevkin** [comment]
Firstly, you probably want `full = "$percentage {$time |}($power.eng(1))"` or `full = "$percentage{ $time ($power.eng(1))|}"` because
1. `$time` is available only when charging/discharging.
2. `$power` is a number and can't be formatted with `.str()`.

Secondly, the 30 seconds delay was fixed in a recent commit.

**Comment by GladOSkar** [comment]
Ah that helped. it was trying to use my mouse's battery instead of my laptops. That also explains why it worked sometimes - whenever my mouse wasn't connected.

The old block never did that. I think it should prefer `BAT*` devices to `hidpp*` ones, don't you think?

**Comment by MaxVerevkin** [comment]
Hm, indeed, v0.22 has some code to handle this. Ported in the latest commit.

**Comment by GladOSkar** [comment]
Yes, that works! But now the block uses the normal format even when full?

![image](https://user-images.githubusercontent.com/9497832/176016405-9e7aa091-bce3-4751-ab90-81a3760355b4.png)

**Comment by GladOSkar** [comment]
Might have been `0a9d2e5` even though i feel like it worked after that commit

**Comment by GladOSkar** [comment]
Wait yes it uses `full_format` if i have `device = "BAT0"`, but not if i don't have it set (but it still uses the correct battery). Weird

**Comment by GladOSkar** [comment]
Log says
```
[2022-06-27T19:10:58Z DEBUG battery] status = Some(Full)
[2022-06-27T19:10:58Z DEBUG battery] capacity_level = Some(Full)
[2022-06-27T19:10:58Z DEBUG battery] capacity= Some(100.0)
```
either way though

**Comment by GladOSkar** [comment]
Ah sorry i was using an old build, i always forget to switch my bar between the `release` and the `debug` binary. Sorry!
