### ISSUE TITLE
Backlight block is always one update behind

### ISSUE THREAD

**Issue by jasyip** [greshake/i3status-rust#1549]
Let's say I boot up my computer or reload the bar. The value from `/sys/class/backlight/intel_backlight/brightness` matches the bar's value. Then I change the brightness (using `brightnessctl`). Displayed value doesn't change, but `cat /sys/class/backlight/intel_backlight/brightness` and `cat /sys/class/backlight/intel_backlight/actual_brightness` and `brightnessctl info` still give the actual value. Then I change it to a new value, displayed value changes to what it was right before the change. It did update, but not correctly. I'm not sure if when it receives the signal, it reads the value too quickly.

I'm using Sway on ArchLinux, my i3status-rust version is 22.0.

**Comment by MaxVerevkin** [comment]
Can you please check the master branch?
