### ISSUE TITLE
Custom `format` values doesn't work

### ISSUE THREAD

**Issue by XiNiHa** [greshake/i3status-rust#1550]
Although the default `format` values work flawlessly, almost every `format` value I've specified just gets printed as a plain string.
The only exception was `time`'s one, and I guess it's because it has a completely different mechanism for formatting (`chrono`'s).
It's even reproducible with the default config file provided. (since it uses custom formatting on `disk_space` block and `memory` block)

**Comment by ammgws** [comment]
v0.22 or v0.3? Current docs are for 0.3

**Comment by XiNiHa** [comment]
That was the problem ;D Fixed by installing `i3status-rust-git`
