### ISSUE TITLE
v0.30 : Brightness block errors out and disappears when brightness goes under 10%

### ISSUE THREAD

**Issue by AkechiShiro** [greshake/i3status-rust#1552]
I've tried the 0.30 and right now, the brightness block when at the lowest percentage disappears from the bar (status command exited with an error code 101 I think then if you restart the i3status bar, you see the brightness block disappeared), you can't tweak it back unless you run a command in a terminal or using media Fn keys (if you binded them)

Normally working bar: 
![image](https://user-images.githubusercontent.com/14914796/177051593-aaa61579-d2ab-4ff1-bcc9-469fbb529244.png)

See error : 
![image](https://user-images.githubusercontent.com/14914796/177051564-0f46248b-e92a-48af-b01a-b31a0326f516.png)

Restarting i3 (Brightness block disappears, reappears only if brightness is tweaked up and i3 restarted again): 
![image](https://user-images.githubusercontent.com/14914796/177051587-8a64fae5-f7c7-4103-8ba9-0b81240f2e67.png)

**Comment by MaxVerevkin** [comment]
1. What's the output of `cat /sys/class/backlight/*/brightness` when this happens?
2. If your run `i3status-rs` in terminal and trigger this bug, what gets displayed?

**Comment by MaxVerevkin** [comment]
Should be fixed in 586e1f60ec355947d7ae42f3386967c826874cd7

**Comment by AkechiShiro** [comment]
It is fixed yep, thanks !
