### ISSUE TITLE
Add option to hide blocks when format string is empty

### ISSUE THREAD

**Issue by gregdan3** [greshake/i3status-rust#1554]
i3status is capable of hiding `disk` information when they are not within a threshold, usually by percentage of free space or number of gigabytes of free space. The same goes for `memory` information.

The current behavior of i3status-rust is to fail with ENOENT when a target disk is not mounted, and to always show the format string under all conditions otherwise, even if it is empty.

Example configuration in i3status:
```
disk "/" {
    prefix_type = "decimal"
    format = ""
    format_below_threshold = "/ %avail"
    format_not_mounted = ""
    low_threshold = 10
    threshold_type = "percentage_free"
}

disk "/home/" {
    prefix_type = "decimal"
    format = ""
    format_below_threshold = "⌂ %avail"
    format_not_mounted = ""
    low_threshold = 10
    threshold_type = "percentage_free"
}
memory {
    format = ""
    format_degraded = " %available"
    threshold_degraded = "30%"
}
```

This is one of the few things keeping me from switching to i3status-rust; the ability to hide blocks with empty format strings, and controlling the format string conditionally. This is possible for some blocks, but as far as I can find in the docs, not many of them.

**Comment by ammgws** [comment]
So basically making the `custom` block's `hide_when_empty` a universal option?

**Comment by gregdan3** [comment]
Yup, exactly that @ammgws

**Comment by MaxVerevkin** [comment]
I think #1582 will cover this because if icons and spacing are handled manually by format strings, there will be no other meaning to `format = ""` other than "hide this block".
