### ISSUE TITLE
Music block crashes i3status while trying to display katakana/kanji characters

### ISSUE THREAD

**Issue by Savuth-S** [greshake/i3status-rust#1556]
As the title says whenever I try to play this video: https://www.youtube.com/watch?v=G5hScSFkib4
which contains katana and kanji characters on its title it crashes the status bar [Error: status_command process exited unexpectedly (exit 101)] with the following message showing on the terminal if I try to manually start it again:
```
{"version": 1, "click_events": true}
[
thread 'main' panicked at 'assertion failed: self.is_char_boundary(new_len)', /rustc/1.61.0/library/alloc/src/string.rs:1202:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I'm not entirely sure wether this happens because of an error while trying to display the characters or an issue with the title trimming functionality. This is my block configuration on my config.toml:
```
[[block]]
block = "music"
max_width = 25
dynamic_width = true
smart_trim = true
hide_when_empty = true
buttons = ["prev","play", "next"]
# player = "cmus"
interface_name_exclude = ["firefox", "mpd"]
```

**Comment by MaxVerevkin** [comment]
1. This video works for me on master branch (the width is not calculated correctly though, I suppose this is because some characters consist of multiple utf8 code points).
2. Run `i3status-rs` with this env variable: `RUST_BACKTRACE=1`. This will help understand which part of the codebase panics.

**Comment by Savuth-S** [comment]
Its empty
```
{"version": 1, "click_events": true}
[
thread 'main' panicked at 'assertion failed: self.is_char_boundary(new_len)', /rustc/1.61.0/library/alloc/src/string.rs:1202:13
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

With full:
```
{"version": 1, "click_events": true}
[
thread 'main' panicked at 'assertion failed: self.is_char_boundary(new_len)', /rustc/1.61.0/library/alloc/src/string.rs:1202:13
stack backtrace:
   0:     0x55f98166f7dc - <unknown>
   1:     0x55f9816969ec - <unknown>
   2:     0x55f981668fe1 - <unknown>
   3:     0x55f981671425 - <unknown>
   4:     0x55f9816710c8 - <unknown>
   5:     0x55f981671983 - <unknown>
   6:     0x55f981671829 - <unknown>
   7:     0x55f98166fc74 - <unknown>
   8:     0x55f981671589 - <unknown>
   9:     0x55f9812d76d3 - <unknown>
  10:     0x55f9812d759d - <unknown>
  11:     0x55f981339271 - <unknown>
  12:     0x55f9813d3932 - <unknown>
  13:     0x55f98136917b - <unknown>
  14:     0x55f98144def3 - <unknown>
  15:     0x55f98146c7f9 - <unknown>
  16:     0x55f981662d3e - <unknown>
  17:     0x55f98136d812 - main
  18:     0x7f3866629290 - <unknown>
  19:     0x7f386662934a - __libc_start_main
  20:     0x55f9812d79c5 - <unknown>
  21:                0x0 - <unknown>
```

I'm using the latest arch release which is version 0.22.0-1 according to pacman, I'll try compiling from source instead

**Comment by Savuth-S** [comment]
It is fixed on the latest git version as expected, however it seems a lot has changed from the release in the Arch repository. A little of topic but what happened to the networkmanager block and how can I recreate the function it had?
