### ISSUE TITLE
v0.30: rename `invert_scrolling` back to `scrolling`

### ISSUE THREAD

**Issue by MaxVerevkin** [greshake/i3status-rust#1559]
It was renamed my me while rewriting async: I found it confusing that `scrolling` accepts two values: `"inverted"` - the default, in which case Up means Up and Down means Down, i.e. we are not actually reversing anything, and `"natural"` - the directions are inverted.

Also, this functionality should really be a part of `i3bar`/`swaybar`/... because a status line generator doesn't know which device was used for scrolling, but this setting should apply only for touchpads.

**Comment by MaxVerevkin** [comment]
Bar-side implementation is surprisingly easy btw: https://github.com/MaxVerevkin/i3bar-river/pull/1/commits/a68c55c3462fa9c716a4d286a11cc451ac917800

**Comment by ammgws** [comment]
Have you tried discussing this with i3 as well?

**Comment by MaxVerevkin** [comment]
> Have you tried discussing this with i3 as well?

No, not yet. Will send a feature request if no one does it before me when I'll have time.

**Comment by ammgws** [comment]
If it's really that confusing then we could just leave the new name as-is?

**Comment by MaxVerevkin** [comment]
> If it's really that confusing then we could just leave the new name as-is?

I'm okay with that. Will just need to update the README and NEWS.
