### ISSUE TITLE
nvidia_gpu: add spaces around values for more consistent hightlighting

### ISSUE THREAD

**Issue by MaxVerevkin** [greshake/i3status-rust#1560]
v0.22: ![image](https://user-images.githubusercontent.com/34583604/178115665-3e1f5685-f10c-4f2a-807c-ee217b644fe8.png) ![image](https://user-images.githubusercontent.com/34583604/178115664-ccf5d1cf-8185-4949-87cf-c4836d22717c.png)

v0.30: ![image](https://user-images.githubusercontent.com/34583604/178115332-5b7742a4-7963-4ac9-882b-bbf1779fdf30.png) ![image](https://user-images.githubusercontent.com/34583604/178115346-1a97b5a9-e305-495e-afa3-c28e9831e129.png)

**Comment by ammgws** [comment]
Did you end up simulating `nvidia-smi`?

**Comment by MaxVerevkin** [comment]
Yes, on v0.30 it's easier than on v0.22 because query is constant: 

```sh
#!/bin/sh

while [[ true ]]; do
    echo MyName, 100, 50, 10, 56, 100, 10, 0
    sleep 10
done
```

**Comment by MaxVerevkin** [comment]
Another option is to drop background coloring (it will make spacing way to complicated) and instead
1. For temperature, set the color of the entire block, not just temperature part.
2. For fan control indication, underline the relevant part of the text. Or make it italic. Or bold.
