### ISSUE TITLE
v0.30 muting the volume sound causes `"Failed to render full text"` for volume block

### ISSUE THREAD

**Issue by AkechiShiro** [greshake/i3status-rust#1562]
Muting causes "Failed to render full text", unmuting fixes the error.

**Comment by MaxVerevkin** [comment]
- You can click on the block to see the full error message.
- [Docs](https://greshake.github.io/i3status-rust/i3status_rs/blocks/sound/index.html) say: `volume` - Current volume. Missing if muted.

So you need a `|` to handle this manually (see the default format & examples). Or you can set `show_volume_when_muted = true`.

**Comment by AkechiShiro** [comment]
Thanks then this issue is not really a problem then
