### ISSUE TITLE
Bugs I found when using the i3status-rs 0.30.0

### ISSUE THREAD

**Issue by c02y** [greshake/i3status-rust#1564]
Recently because of the [pacman block issue](https://github.com/greshake/i3status-rust/issues/1561), I decided to use the latest version of i3status-rust (i3status-rs 0.30.0 (commit 6e2799ad 2022-07-13)), so basically the old config.toml is broken I have to read the doc of v0.30(links are in the README) to fix those breaks.

I found several bugs and typos in the process, since it's been a spiritually exhausting last few days for me because of some work I'm doing, I don't have time to fix these erros right now, here is the list I found, someone can fix it if interested:

- [x] **`disk_space` block:** **OLD CODE:** The `format = "$icon.str() $available.eng(2)"` in [Example for disk_space block](https://greshake.github.io/i3status-rust/i3status_rs/blocks/disk_space/index.html#example) is wrong, `Failed to render full text` on the block, click on it, it shows `Error in disk_space: Failed to render full text. (Cause: Placeholder with name 'icon' not found)`, simply `format = "$available.eng(3)"` works fine, icon will be displayed, **SOLUTION**: simply removing icon part in the source code's comment should be fine.
- [ ] #1568
- [ ] **`music` block:** **BUG:** when you play a new instance of your player, the block displays `Failed to render full text`, click on it, it shows: `Error in music: Failed to render full text. (Cause: Placeholder with name 'title' not found)`, but when you reload your i3status-rust manually, title is displayed fine.
- [x] **`pacman` block:** **OLD CODE**: `on_click` line in [Example for pacman block](https://greshake.github.io/i3status-rust/i3status_rs/blocks/pacman/index.html#examples) is wrong, on_click is replaced by `[[block.click]]`, doc is old, **SOLUTION:** simply deleting that part in source code's comment should be fine.
- [ ] #1565
- [x] **`uptime` block:** **TYPO:** `interval = "3600"` in [Example for uptime block](https://greshake.github.io/i3status-rust/i3status_rs/blocks/uptime/index.html#example) is wrong, it should be `interval = 3600` which is integer instead of string, **SOLUTION:** simply deleting the double quote in the source code's comment part should be fine.
- [x] **`temperature` block:** **TYPO:** The `format = "{min} min, {max} max, {average} avg|"` in [Example for temperature block](https://greshake.github.io/i3status-rust/i3status_rs/blocks/temperature/index.html#example) is wrong, **SOLUTION:** changing that part in the source code's comment part into `format = "{$min} min, {$max} max, {$average} avg|"` is OK.
- [x] **`notify` block:** **TYPO:** The `[block]` in [Example for notify block](https://greshake.github.io/i3status-rust/i3status_rs/blocks/notify/index.html#examples) is wrong, **SOLUTION:**: simply changing it to `[[block]]` in the source code's comment part is OK

I haven't tried all the blocks, but those are the bugs/typos I found so far.

**Comment by ammgws** [comment]
Thanks for the write-up and so sorry about the issues! We are still in the process of fixing documentation as well so any help is much appreciated.

**Comment by ammgws** [comment]
> * **`bluetooth` block:** **BUG:** the color of the bluetooth's icon is not updated when your bluetooth device is disconnected, after manually refresh the i3status-rus bar, color is OK

Yes I noticed this too and added some debug statements a while back but haven't had time to go through it yet.

**Comment by ammgws** [comment]
> music block: BUG: when you play a new instance of your player, the block displays Failed to render full text, click on it, it shows: Error in music: Failed to render full text. (Cause: Placeholder with name 'title' not found), but when you reload your i3status-rust manually, title is displayed fine.

Can you provide a reproducer for this? e.g. mpv is playing a file, you open another mpv and then the block errors?

**Comment by ammgws** [comment]
> But using the following line from the Example in the doc

Yeah all the examples in the music block use `|` because placeholders like title can be missing, though if you're not familiar with the formatter than it is easy to overlook: https://greshake.github.io/i3status-rust/i3status_rs/formatting/index.html#handling-missing-placeholders-and-incorrect-types

Perhaps we need to bring more attention to this in the docs, e.g. in the music block docs placeholder table, mention which placeholders have a possibility of being missing etc

Apart from this and the other 2 issues which I spun out into their own threads, I think this thread has played its course. Please let us know if there is anything else (feel free to create a new issue)

**Comment by c02y** [comment]
> > But using the following line from the Example in the doc
> 
> Yeah all the examples in the music block use `|` because placeholders like title can be missing, though if you're not familiar with the formatter than it is easy to overlook: https://greshake.github.io/i3status-rust/i3status_rs/formatting/index.html#handling-missing-placeholders-and-incorrect-types
> 
> Perhaps we need to bring more attention to this in the docs, e.g. in the music block docs placeholder table, mention which placeholders have a possibility of being missing etc
> 
> Apart from this and the other 2 issues which I spun out into their own threads, I think this thread has played its course. Please let us know if there is anything else (feel free to create a new issue)

Oh, `|` seems important in this case, I added it and now `title` is working fine, I thought it is just a separator. Thanks.

doc says `Some blocks allow missing placeholders, for example [bluetooth](https://greshake.github.io/i3status-rust/i3status_rs/blocks/bluetooth/index.html)’s “percentage” may be absent if the device is not supported. To handle such cases it is possible to queue multiple formats together by using | symbol: <something that can fail>|<otherwise try this>|<or this>.` 

but `title` in format of music block shouldn't be missing or failed, is `title` here a bug or just working like this?

**Comment by c02y** [comment]
Also, 20 `format = "$title.str(20)|"` for `focused_window` doesn't work, `format = "$title.rot-str(20)|"` works fine.

**Comment by c02y** [comment]
I think I misunderstand the number in `.str(20)`, take `focused_window` for example, it means it will display at least 20 characters, if the title is shorter than 20, it will fill the right with spaces to 20 characters in the `focused_window` title, it will display the full title if it is longer than 20. Old version of `i3status-rust` has a filed called `max_width` which is completely opposite.
