### ISSUE TITLE
bluetooth: block color not updated when device is disconnected

### ISSUE THREAD

**Issue by ammgws** [greshake/i3status-rust#1565]
> the color of the bluetooth's icon is not updated when your bluetooth device is disconnected, after manually refresh the i3status-rus bar, color is OK

**Comment by MaxVerevkin** [comment]
Is this fixed by #1695? Can you still reproduce it?

**Comment by MaxVerevkin** [comment]
Oh... Apparently when some process disconnects a device, everyone receive "PropertiesChanged" _except_ that process... For some reason.

I assume this issue was discovered by clicking the block and not by turning off the device. I never used this feature so I never noticed.

**Comment by MaxVerevkin** [comment]
Fixed in fbb586e5bb5a57750bcdc46dcf293a36fa6afbc1
