### ISSUE TITLE
Uptime block has weird positioning

### ISSUE THREAD

**Issue by bemeurer** [greshake/i3status-rust#157]
Upon enabling the uptime block, I see the time string shifter higher than one would expect it to be. Here's a screenshot of what I mean 
![screenshot from 2018-03-04 15-17-04](https://user-images.githubusercontent.com/7243783/36952020-2aa61c04-1fbf-11e8-94e9-3418b19e27d7.png)
Shouldn't that string be at the same height as all other blocks?

**Comment by bemeurer** [comment]
Now it broke, and shows the uptime as just `0`, but the text got centered right!
![screenshot from 2018-03-04 22-04-27](https://user-images.githubusercontent.com/7243783/36959663-079f38f6-1ff8-11e8-82fe-3d584379627d.png)

**Comment by bemeurer** [comment]
Now it randomly started working again! And the text shifted back up
![screenshot from 2018-03-04 22-42-12](https://user-images.githubusercontent.com/7243783/36960745-3f53841e-1ffd-11e8-9594-a9b965f01d3f.png)

**Comment by atheriel** [comment]
I looks like the second issue -- showing "0" -- is related to some incorrect parsing of the `/proc/uptime` file, so the [default text](https://github.com/greshake/i3status-rust/blob/master/src/blocks/uptime.rs#L93) is shown instead. Not sure of the cause yet.

**Comment by bemeurer** [comment]
Confirming #160 fixes this.
