### ISSUE TITLE
i3status-rust master sending signal to i3status-rs no longer causes blocks with interval = "once"  to update

### ISSUE THREAD

**Issue by michaelmrose** [greshake/i3status-rust#1574]
System is void linux running kernel 5.18.11 with i3wm version 4.20.1
i3status-rs = i3status-rs 0.30.0 (commit 73667ae 2022-07-22)

i3 is not configured to hide i3bar but i3status-rs is run with --never-pause anyway

Consider a simple test config consisting of the text

```
block = "custom"
interval = "once"
command = "date"
signal = 4
```

I restart i3 to enable the most recent version of the config which is run by directly referencing the path of the binary installed via cargo /usr/home/michael/.cargo/bin/i3status-rs

As expected the bar contains the current date and time

running pkill -SIGRTMIN+4 i3status-rs unfortunately has no effect it is only updated when i3status-rust is restarted by restarting the bar. Other testing which included clickable blocks revealed the same problem however the command intended to be run WAS run indicating it was running correctly just not updating.

Likewise running it with an interval works as expected the time updates on each tick with an interval of one for example.

0.22 still works fine even if it lacks the new features so I will revert but I'm happy to test any updated version or submit any information you think useful. Thanks for the good work.

**Comment by ammgws** [comment]
>  i3status-rs is run with --never-pause anyway

Do you mean that you are running it with `--never-pause` or that i3status-rs is acting like the flag was supplied when it wasn't? Since I can't reproduce that:

```sh
>i3status-rs
{"version": 1, "click_events": true}
...
```

```sh
>i3status-rs --never-pause
{"version": 1, "click_events": true, "stop_signal": 0}
```

**Comment by michaelmrose** [comment]
I passed --never-pause to test because I felt like things might simply be stuck although this seems not to be so. The result is the same either way.

**Comment by MaxVerevkin** [comment]
Is this only applicable to `custom` block or are other blocks affected too?

**Comment by MaxVerevkin** [comment]
@michaelmrose can you verify that the latest commit fixes the issue for you?

**Comment by michaelmrose** [comment]
I can verify that signals now cause blocks to update thanks.
