### ISSUE TITLE
`double_click_delay`: change the default + document

### ISSUE THREAD

**Issue by MaxVerevkin** [greshake/i3status-rust#1576]
Global option `double_click_delay` defines the maximum duration between two consequent clicks that can be considered as a double click. This needs to be documented.

Currently the default is 200ms. Setting it to zero makes the bar (way) more responsive. Obviously, it disables the double click feature.

**Comment by ammgws** [comment]
Is double click stable/usable enough to document it? Otherwise if it's still being evaluated we could leave it undocumented for now (and change the default to 0)

**Comment by MaxVerevkin** [comment]
> Is double click stable/usable enough to document it?

I think so.
