### ISSUE TITLE
Problem with one module crashes entire bar

### ISSUE THREAD

**Issue by madhur** [greshake/i3status-rust#1581]
I faced a problem with pulse audio service in my system. It was getting crashed or not started.

As a result of that, instead of just the sound module being unavailable, the entire bar disappeared with just the text

`Error in block 'sound': could not get sound info`

I believe this should be handled better. The problem in one module should not cause the entire bar to be unavailable.

My sound block configuration

```
[[block]]
block = "sound"
format = "{volume}"
```

Using i3status-rs 0.21.6 (commit ea215f5 2022-02-13)

**Comment by GladOSkar** [comment]
The new `async` implementation that is currently in `master` and set so be released as `0.30` addresses this already

**Comment by madhur** [comment]
Upgraded
