### ISSUE TITLE
Wifi connection is detected as wired

### ISSUE THREAD

**Issue by madhur** [greshake/i3status-rust#1583]
I have upgraded to latest master branch and it works great.

However, I am facing issue with `net` block. My wifi connection is detected as wired.

I am using USB wifi device
Such as this 
https://www.reliancedigital.in/tp-link-archer-t2u-plus-ac600-high-gain-wireless-dual-band-usb-adapter/p/491998222?gclid=Cj0KCQjw0JiXBhCFARIsAOSAKqDqGRjivRV_TgpGxsEYt4ouhjAiuSSySy5FaiXtK28o2boxMsCiNR4aAobpEALw_wcB

I am using wifi drivers from this repo

https://github.com/aircrack-ng/rtl8812au

The output I get is 
`Wired connection via wlp1s0f0u1`

Format: 
`format = "{$signal_strength $ssid $frequency|Wired connection} via $device"`

i3status-rs 0.30.0 (commit e203adef 2022-07-28)

Worth mentioning that it was working fine in older version.

**Comment by madhur** [comment]
Quick update,  problem with variable `$signal_strength`. `$ssid` is shown correctly.

**Comment by MaxVerevkin** [comment]
Thanks for reporting this, this should be fixed by implementing #1534
