### ISSUE TITLE
Error in temperature: Failed to create chip iterator. (Cause: libsensors error: Unknown error)

### ISSUE THREAD

**Issue by madhur** [greshake/i3status-rust#1587]
I am getting this error while adding chip information in `temperature` block. Using i3status-rs 0.30.0 (commit c56a570a 2022-08-01)

```
[[block]]
block = "temperature"
format = "$max|"
interval = 5
collapsed=false
chip="*-k10-*"
```

Sensors output: 

```
k10temp-pci-00c3
Adapter: PCI adapter
Tctl:         +32.8°C
Tccd1:        +32.2°C

nvme-pci-0100
Adapter: PCI adapter
Composite:    +53.9°C  (low  =  -0.1°C, high = +79.8°C)
                       (crit = +81.8°C)
Sensor 1:     +53.9°C  (low  = -273.1°C, high = +65261.8°C)

acpitz-acpi-0
Adapter: ACPI interface
temp1:        +16.8°C  (crit = +20.8°C)

gigabyte_wmi-virtual-0
Adapter: Virtual device
temp1:        +30.0°C
temp2:        +38.0°C
temp3:        +32.0°C
temp4:        +23.0°C
temp5:        +34.0°C
temp6:        +45.0°C

nvme-pci-0400
Adapter: PCI adapter
Composite:    +36.9°C  (low  = -273.1°C, high = +84.8°C)
                       (crit = +84.8°C)
Sensor 1:     +36.9°C  (low  = -273.1°C, high = +65261.8°C)
Sensor 2:     +37.9°C  (low  = -273.1°C, high = +65261.8°C)
```

**Comment by ammgws** [comment]
Does the `sensors` command have any errors when you run it in a terminal?

**Comment by madhur** [comment]
> Does the `sensors` command have any errors when you run it in a terminal?

No. That was the complete output.

**Comment by MaxVerevkin** [comment]
From `sensors -h`:

```
Example chip names:
	lm78-i2c-0-2d	*-i2c-0-2d
	lm78-i2c-0-*	*-i2c-0-*
	lm78-i2c-*-2d	*-i2c-*-2d
	lm78-i2c-*-*	*-i2c-*-*
	lm78-isa-0290	*-isa-0290
	lm78-isa-*	*-isa-*
	lm78-*
```

(This should be in the docs though.)

So you probably want

```toml
chip="k10temp-*"
```

**Comment by madhur** [comment]
> From `sensors -h`:
> 
> ```
> Example chip names:
> 	lm78-i2c-0-2d	*-i2c-0-2d
> 	lm78-i2c-0-*	*-i2c-0-*
> 	lm78-i2c-*-2d	*-i2c-*-2d
> 	lm78-i2c-*-*	*-i2c-*-*
> 	lm78-isa-0290	*-isa-0290
> 	lm78-isa-*	*-isa-*
> 	lm78-*
> ```
> 
> (This should be in the docs though.)
> 
> So you probably want
> 
> ```toml
> chip="k10temp-*"
> ```

Working. Thanks.

**Comment by ammgws** [comment]
> From `sensors -h`:
> (This should be in the docs though.)

This might be handy: `sensors -j | jq 'keys'`
