### ISSUE TITLE
`net` incorrect default interface

### ISSUE THREAD

**Issue by Alextopher** [greshake/i3status-rust#1595]
I believe I discovered a bug after installing docker my net block no longer rendered.

```
$ ip route list
default via 192.168.1.1 dev wlp166s0 proto dhcp src 192.168.1.50 metric 600
172.17.0.0/16 dev docker0 proto kernel scope link src 172.17.0.1 linkdown
192.168.1.0/24 dev wlp166s0 proto kernel scope link src 192.168.1.50 metric 600
```

`fn default_interface()` in `netlink.rs` returns `Some("docker0")`. I expected it would return `Some("wlp166s0")` as it is the interface of my _default_ route. 

Reading the source it seems to me `default_interface()` returns whatever netlink returned as the ~~"first"~~ "last"? interface. I can't tell if there is any guarantee this should be the default interface. Not sure if this is intended but it seems like odd behavior. 

Maybe this is related to #1515? #1515 is help wanted, I could look more into this.

**Comment by MaxVerevkin** [comment]
Dose [this script](https://gist.github.com/MaxVerevkin/6419a79ecb8b85d9e0ec90a48c856d02) display the correct info?

**Comment by Alextopher** [comment]
No that script fails.

> ```  2 thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: TryFromSliceError(())', src/main.rs:71:64 ```

`stats.len()` is 200 while `std::mem::size_of::<RtnlLinkStats64>` is 192.

**Comment by Alextopher** [comment]
stats:
```
[254, 0, 0, 0, 0, 0, 0, 0, 254, 0, 0, 0, 0, 0, 0, 0, 88, 90, 0, 0, 0, 0, 0, 0, 88, 90, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
```

**Comment by Alextopher** [comment]
But removing that bad code yes this works

**Comment by MaxVerevkin** [comment]
Apparently `linux 5.19` changed the size of `RtnlLinkStats64` (I hope not the order of fields). Will find a way not to depend on it. Probably convert to `&[u64]` instead of `&RtnlLinkStats64`.

**Comment by MaxVerevkin** [comment]
Can you please verify the latest version of that script (which eventually will be integrated into `net`)?

**Comment by Alextopher** [comment]
Works!
```
[src/main.rs:23] get_interfaces().unwrap() = [
    Interface {
        index: 1,
        is_default: false,
        is_up: true,
        name: "lo",
        rx_bytes: 23128,
        tx_bytes: 23128,
        ip: Some(
            127.0.0.1,
        ),
        ipv6: Some(
            ::1,
        ),
    },
    Interface {
        index: 2,
        is_default: true,
        is_up: true,
        name: "wlp166s0",
        rx_bytes: 152915111,
        tx_bytes: 31260804,
        ip: Some(
            192.168.1.50,
        ),
        ipv6: Some(
            fe80::6886:cfc5:97c4:643c,
        ),
    },
    Interface {
        index: 3,
        is_default: false,
        is_up: true,
        name: "docker0",
        rx_bytes: 0,
        tx_bytes: 0,
        ip: Some(
            172.17.0.1,
        ),
        ipv6: None,
    },
]
```

**Comment by MaxVerevkin** [comment]
> I could look more into this.

Some testing needs to be done to integrate that script and thus fix this bug. See #1069. Any help in this direction would be appreciated.

**Comment by MaxVerevkin** [comment]
@Alextopher see #1598
