### ISSUE TITLE
lemonbar tags - color formatting

### ISSUE THREAD

**Issue by fhill2** [greshake/i3status-rust#1596]
Before `wayland+i3status-rust` I used a custom script module in polybar that printed the current workspace layout.

I could color the focused window/container in a different color as [polybar supports lemonbar tag formatting](https://github.com/polybar/polybar/wiki/Formatting#format-tags).
 
![status](https://user-images.githubusercontent.com/16906982/185901737-c74189ad-1a7d-4d70-b65e-24b18e3f218e.png)

Is there a feature to color part of the text shown in the block a different color? 
I have only found a way to change color for the whole block.

**Comment by MaxVerevkin** [comment]
> Is there a feature to color part of the text shown in the block a different color?

Not a feature of `i3status-rs`, but you can use `pango` markup in all the blocks. For example,

```
<span color='#fabd3f'>...</span>
```

**Comment by fhill2** [comment]
This is exactly what I'm trying to do. Thanks for this info.
