### ISSUE TITLE
bluetooth: can't read $percentage for the first run

### ISSUE THREAD

**Issue by YHNdnzj** [greshake/i3status-rust#1599]
For the first run (by sway) on each startup, after the device gets connected, the `bluetooth` block always reports "placeholder with name percentage not found". Reloading sway or running another `i3status-rs` manually in a terminal seem to be fine.

I'm using the latest master (16c28bd11587eea03dcc2da26efc34db795cdd00) and have tried reverting e4503bc099c0301ed7715735f26e44b631c5e55a, but that actually made the situation worse (not working even after reloading).

**Comment by MaxVerevkin** [comment]
Try replacing `$percentage` with `{$percentage|}` or `{$percentage|placeholder text}` in your format string.

**Comment by YHNdnzj** [comment]
> Try replacing `$percentage` with `{$percentage|}` or `{$percentage|placeholder text}` in your format string.

This fixed the problem for me. Thanks for the quick reply :)
