### ISSUE TITLE
Failed to install on ubuntu

### ISSUE THREAD

**Issue by xahmad7** [greshake/i3status-rust#1606]
Hello
Failed to install on ubuntu i cloned the repository and can't find i3status-rs , 
I got Error: status_command is not executable

**Comment by infomehdi** [comment]
Did you install it like mentionned here ?
https://github.com/greshake/i3status-rust/blob/master/doc/dev.md

**Comment by xahmad7** [comment]
I got this error:
error: failed to select a version for the requirement `phf = "^0.11"`
candidate versions found which didn't match: 0.10.1, 0.10.0, 0.9.0, ...
location searched: crates.io index
required by package `chrono-tz v0.6.3`
    ... which satisfies dependency `chrono-tz = "^0.6"` (locked to 0.6.3) of package `i3status-rs v0.30.0

**Comment by infomehdi** [comment]
first check your rustc version
`rustc --version`

then try upgrading with (as mentionned in the documentation)
`curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh`

(do not forget to `source "$HOME/.cargo/env"`)
