### ISSUE TITLE
Rendering problem

### ISSUE THREAD

**Issue by hm1rafael** [greshake/i3status-rust#161]
I'm having a small rendering problem that I can't seem to figure out why. The arrows on the blocks are not "connected" to the body as shown in the image below.
![1521073459-898x181](https://user-images.githubusercontent.com/3649436/37438026-fc4d01a2-27ce-11e8-9194-a88cc4c023f3.png)

What I'm doing wrong?

**Comment by lausek** [comment]
Hi @hm1rafael, have you checked issue #119?

**Comment by atheriel** [comment]
@hm1rafael Does @lausek's suggestion resolve your issue? If not, what i3/i3-gaps/sway version are you running? And can you paste your font configuration?

**Comment by ZJaume** [comment]
I'm having similar problem, arrows are not showed correctly on Sway 0.15.2
![screenshot](https://user-images.githubusercontent.com/11339330/41849826-e921ce98-7871-11e8-9d50-c68384b67afe.png)
