### ISSUE TITLE
kdeconnect: choose first available device

### ISSUE THREAD

**Issue by marzzzello** [greshake/i3status-rust#1612]
When I don't specify a `device_id` in the kdeconnect block it doesn't choose the first device paired and reachable. 

`kdeconnect-cli --list-available` shows one device. When I use the id from there and set it as `device_id` it works.

`kdeconnect-cli --list-devices` shows 7 paired devices but only the 5. device is paired and reachable

**Comment by MaxVerevkin** [comment]
>  it doesn't choose the first device paired and reachable.

Yes it chooses the first device, connected or not. But so does `v0.22`, so I don't think this issue is `v0.30` specific.

**Comment by marzzzello** [comment]
In v0.22 it was also buggy but sometimes it worked. I didn't look more into it.
But it would be nice if in the future the first available device is chosen instead of some other paired device

**Comment by ammgws** [comment]
Patches welcome :)

**Comment by MaxVerevkin** [comment]
Not sure if this is a "good first issue" though xD. I'd imagine property implementing this being as hard as implementing missing battery support for UPower...

By "property" I mean: handle the case when there are no connected devices (only paired), wait until some device becomes reachable, rescan when the current device becomes disconnected, etc. Although maybe I'm overthinking this.

**Comment by ammgws** [comment]
I actually wasn't thinking that far ahead :laughing:
