### ISSUE TITLE
Backlight icon missing

### ISSUE THREAD

**Issue by Pixelnarium** [greshake/i3status-rust#1615]
Hello,

it is probably caused by some ArchLinux update but my brightness icon is not displayed anymore. I tried to downgrade ttf-font-awesone and i3status-rust but without any luck.

Do you have any idea what is wrong here?

Installed versions:
i3status-rust 0.22.0-1
ttf-font-awesome 6.1.2-1

sway config:
```
bar {
    position top

    status_command i3status-rs
    status_padding 0

    colors {
        separator #666666
        background #222222
        statusline #dddddd
        focused_workspace #0088CC #0088CC #ffffff
        active_workspace #333333 #333333 #ffffff
        inactive_workspace #333333 #333333 #888888
        urgent_workspace #2f343a #900000 #ffffff
    }

    font pango:DejaVu Sans Mono, Font Awesome 6 Free 16
}
```

i3status-config
```
icons = "awesome6"

[theme]
name = "native"

[theme.overrides]
separator = ""

[[block]]
block = "sound"

[[block]]
block = "backlight"

[[block]]
block = "battery"
interval = 60
format = "{percentage}"

[[block]]
block = "networkmanager"
interface_name_include = ["wlo1"]
ap_format = "{strength}"
device_format = "{icon}{ap}"

[[block]]
block = "time"
interval = 10
locale="de_DE"
format = "%a, %d.%m.%Y %H:%M:%S"

```
![2022-09-06T20:10:37,047896367+02:00](https://user-images.githubusercontent.com/30435935/188708314-2998801a-1d3f-4635-82e2-91f743d9c3cf.png)

Thank you

**Comment by MaxVerevkin** [comment]
Can you see the icon when you run `i3status-rs` in your terminal?

**Comment by Pixelnarium** [comment]
No. I can't see it in the Terminal. But if I copy&paste the output here into this message box here I see it. When I open LibreOffice Writer, set it to DejaVu Sans Mono and copy&paste it there I see it there too. 

 🌑 100%
 🌒 85% 

![2022-09-07T09:24:19,029702987+02:00](https://user-images.githubusercontent.com/30435935/188815487-91193f95-50b1-4d49-a54c-bb901485144a.png)

**Comment by MaxVerevkin** [comment]
Can you share the output of `fc-list | grep -i dejavu`?

**Comment by Pixelnarium** [comment]
Had some time digging into this and found out it that this was an issue with fonts on my side. I had ttf-google-fonts-git from AUR installed and this caused the issue here for whatever reason.
