### ISSUE TITLE
formatting: document binary SI prefixes

### ISSUE THREAD

**Issue by MaxVerevkin** [greshake/i3status-rust#1620]
Document changes made in #1604

**Comment by ammgws** [comment]
Prefixes are already documented here: https://greshake.github.io/i3status-rust/i3status_rs/formatting/prefix/enum.Prefix.html, which is linked on the formatting docs page.

Just added a comment about `1i` - i think that was all that was needed?
22702358c31b9dd6b572479023a3130795848140

**Comment by c02y** [comment]
Sorry, how to config the disk_space to use 1024 based again? Since I just notice the size in i3status-rust bar is different from other tools I use, for reference: https://github.com/greshake/i3status-rust/issues/1493

**Comment by MaxVerevkin** [comment]
I use `format = " $icon $available.eng(w:5, prefix:1i) "` to display in GiB. Alert units a 1000 based though, but 1024 units can be added.

**Comment by c02y** [comment]
Thanks, so it is a little weird that the `format` and `warning/alert` cannot synchronize based on the same unit.
