### ISSUE TITLE
Follow-up work based on discussion in #1618

### ISSUE THREAD

**Issue by MaxVerevkin** [greshake/i3status-rust#1629]
Adding top lvl comment about follow-up work based on discussion in this PR, might get easily lost from resolved threads

  - flags vs format options - https://github.com/greshake/i3status-rust/pull/1618#discussion_r969907006 (looks like a potential breaking change, 0.30 milestone?)
  - hiding short block - https://github.com/greshake/i3status-rust/pull/1618#discussion_r968688067 (shouldn't be a breaking)
  - Improve time block - drop parsing format in the inner loop, maybe add datetime Value with formatter https://github.com/greshake/i3status-rust/pull/1618#discussion_r980158956

_Originally posted by @arathunku in https://github.com/greshake/i3status-rust/issues/1618#issuecomment-1249491109_

**Comment by ammgws** [comment]
https://github.com/greshake/i3status-rust/issues/1708

https://github.com/greshake/i3status-rust/issues/1709

Breaking into separate issues to track separately.
