### ISSUE TITLE
Temperature Block, bad default and example

### ISSUE THREAD

**Issue by aaronchall** [greshake/i3status-rust#1631]
The Temperature block's default and example don't work. Here's the syntax from https://greshake.github.io/i3status-rust/i3status_rs/blocks/temperature/index.html:

Default entry:
```
“ $icon{ $average avg, $max max|} “
```
Example entry:
```
format = " $icon {$min min, $max max, $average avg |}"
```

Instead, it requires syntax like this (like I'm currently using):
```
format = "{average} avg, {max} max"
```

Additionally, the icon seems to be hardcoded outside of the formatting, but the icon seems to be missing, instead I have a unicode block standing in for the icon with the characters "F2C8" in it. I am using NixOS, not sure if this matters.

**Comment by ammgws** [comment]
The docs you're looking at are for the master branch, which documents the yet to be released v0.3.

The link to the older docs is still listed here:
https://github.com/greshake/i3status-rust/blob/master/README.md#further-documentation
