### ISSUE TITLE
Many missing icons

### ISSUE THREAD

**Issue by epixinvites** [greshake/i3status-rust#1632]
![20220930-102727](https://user-images.githubusercontent.com/54717060/193177028-03ff78dd-7d16-4b50-9661-f347336f83f1.png)

Icons just went missing. Some icons are there, some icons are gone
i3 config -> https://termbin.com/pzd8
i3status-rs config -> https://termbin.com/9rri

**Comment by matthiaskrgr** [comment]
I'm just another user but from what I understand, icons now need to be set via `format` https://github.com/greshake/i3status-rust/pull/1618

**Comment by MaxVerevkin** [comment]
> I'm just another user but from what I understand, icons now need to be set via `format` #1618

Yes, this is correct.

Hopefully #1462 will help with the situation with breaking changes.
