### ISSUE TITLE
Output variable value to notify-send

### ISSUE THREAD

**Issue by madhur** [greshake/i3status-rust#1635]
In the net block, I want to popup the current IP address on click, instead of displaying it in block all the time since it consumes real estate.

I tried following but its not working. I tried escaping `$ip` as well. The plain notify send works without any variable interpolation. Is there any solution to this?

Running i3status-rs 0.30.0 (commit 51fd9e5d 2022-10-02)

```
[[block]]
block = "net"
device = "enp5s0"
format = "$icon {$ssid |}{$ip ^icon_net_up $speed_up.eng(3,B,K) ^icon_net_down $speed_down.eng(3,B,K)|Wired connection} "
interval = 5
[[block.click]]
button="left"
cmd = "notify-send -u low -t 5000 $ip"
```

**Comment by MaxVerevkin** [comment]
> I want to popup the current IP address on click

Currently it is not possible to access placeholders such as `$ip` inside of `cmd`.

> instead of displaying it in block all the time since it consumes real estate.

An alternative solution for this usecase might be to set `format_alt = " $icon $ip "`.

**Comment by madhur** [comment]
Got it. That really helps.
I was trying to apply the same `format_alt` to `disk` and `memory` blocks. It seems they are not supported in those blocks.
![image](https://user-images.githubusercontent.com/509431/194713055-7de56663-2a41-4f19-9ccd-03a64a2e591e.png)

Any reason why? Should it not be consistent across the blocks.

**Comment by MaxVerevkin** [comment]
> It seems they are not supported in those blocks. Any reason why?

No one implemented it yet :) If you wish, you can send a PR.

**Comment by MaxVerevkin** [comment]
For the `memory` block: it already has `format_mem` and `format_swap`, so IDK how `format_alt` would fit in.

**Comment by madhur** [comment]
For `disk_space` , raised the PR https://github.com/greshake/i3status-rust/pull/1636

**Comment by MaxVerevkin** [comment]
About the memory block: `format_mem` and `format_swap` already behave as `format` and `format_alt`. So you can have

```toml
[[block]]
block = "memory"
format_mem = " ^icon_memory_mem $mem_used_percents.eng(1) "
format_swap = " ^icon_memory_mem $mem_used / $mem_total "
```

What we can do is just rename `format_mem` -> `format` and `format_swap` -> `format_alt` and drop `clickable`. But then either we should have two `$icon` placeholders (e.g. `$icon_mem` and `$icon_swap`) or just drop `$icon` and let users use the `^icon_` syntax.

**Comment by MaxVerevkin** [comment]
@madhur if each (or most) blocks had `format_alt`, the original issue would not be relevant anymore, right? I have a thew ideas how to solve it, but I'd like to avoid this for now.

**Comment by madhur** [comment]
> @madhur if each (or most) blocks had `format_alt`, the original issue would not be relevant anymore, right? I have a thew ideas how to solve it, but I'd like to avoid this for now.

Yes
