### ISSUE TITLE
Pacman updates no longer working?

### ISSUE THREAD

**Issue by yawpitch** [greshake/i3status-rust#164]
Cannot see any recent changes to the code, but after a recent upgrade of i3status-rust the pacman block is no longer showing updates, though pacman itself finds them fine.

Tried downgrading package, but to no avail. Not really sure how to diagnose any further, but haven't seen anyone else mentioning a similar issue.

**Comment by matthiaskrgr** [comment]
Hi, I tried to make a simpler implementation of the pacman block as pacman2 block.
Pull request here: https://github.com/greshake/i3status-rust/pull/181

I wonder if this also accidentally fixes your issue?

**Comment by yawpitch** [comment]
Not at my machine for two days, but I did notice that after updating to the latest release on AUR the issue seems to have resolved itself, though I can't see anything that clearly explains why.

I think this issue can be closed, though it'd be nice to have a better explanation.

M

**Comment by yawpitch** [comment]
No explanation found, but seems to have fixed in later pacman releases.
