### ISSUE TITLE
Issue on Ubuntu 22.04

### ISSUE THREAD

**Issue by xahmad7** [greshake/i3status-rust#1649]
Hllo
When i try to install it on Ubuntu 22.04
after $ cargo install --path . --locked
I got this:

`   Compiling i3status-rs v0.30.0 (/home/zero/Downloads/i3status-rust)
error[E0658]: use of unstable library feature 'bool_to_option'
   --> src/blocks/nvidia_gpu.rs:145:77
    |
145 | ...                   set_fan_speed(config.gpu_id, fan_controlled.then_some(info.fan_speed)).await?;
    |                                                                   ^^^^^^^^^
    |
    = note: see issue #80967 <https://github.com/rust-lang/rust/issues/80967> for more information

For more information about this error, try `rustc --explain E0658`.
error: could not compile `i3status-rs` due to previous error

`
Any idea ?

**Comment by ammgws** [comment]
https://github.com/greshake/i3status-rust/blob/master/doc/dev.md

The first sentence should help

**Comment by ammgws** [comment]
Huh I swear your post said ssl at first

**Comment by ammgws** [comment]
What's your rustc version?

**Comment by xahmad7** [comment]
❯ rustc --version
rustc 1.61.0

**Comment by xahmad7** [comment]
Now i got this error:
  = note: /usr/bin/ld: cannot find -lsensors: No such file or directory
          collect2: error: ld returned 1 exit status

**Comment by MaxVerevkin** [comment]
> Now i got this error:
>   = note: /usr/bin/ld: cannot find -lsensors: No such file or directory
>           collect2: error: ld returned 1 exit status
> 

I think you need `libsensors-dev`.

**Comment by MaxVerevkin** [comment]
We should mention this in dev.md

**Comment by xahmad7** [comment]
Installed succsefully
but the problem it looks like this:
![image](https://user-images.githubusercontent.com/87617666/198819068-acc3bf28-6d56-4273-a29a-c309a7a786a6.png)

**Comment by MaxVerevkin** [comment]
See #1014

**Comment by twosaturdayscode** [comment]
Probably newbie note, but if someone else stumble upon this while trying to manually install this package on ubuntu, using simply `rust` from `sudo apt install rust` won't work, you'll need to install rust using the following:
```shell
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
```
then follow the guide as is.
