### ISSUE TITLE
Add custom ending character (re. tray icons)

### ISSUE THREAD

**Issue by REALERvolker1** [greshake/i3status-rust#1650]
Hello all, I love this bar generator!

The only problem I haven't been able to address is the sharp cutoff at the system tray. (See screenshot below)

![image](https://user-images.githubusercontent.com/73304952/198715955-9f63715c-cc7c-414e-9358-ab559d717a28.png)

My proposed solution is to add a powerline solid arrow character () pointing right at the very end, with the same color as whatever the last module is (For example, if my battery changed its status and color, it would change the character's color to my battery module's current color.)

![image](https://user-images.githubusercontent.com/73304952/198717469-ecd252b5-afa7-4933-955f-35fff1abdf8f.png)
![image](https://user-images.githubusercontent.com/73304952/198718692-08815d7f-d3cd-4ea9-a5c1-dc11e55d43f9.png)

Is this possible? I checked out the code but my Rust skill isn't really at this level yet.

**Comment by REALERvolker1** [comment]
Just an update, it would also be nice to have the option to add padding spaces on the end (so the end of the arrow would not look weird on monitors without trays)

**Comment by GladOSkar** [comment]
Have a look at #1653 , does that work for you?

**Comment by REALERvolker1** [comment]
That works! There is a tiny little line but that's probably just because of i3bar
![image](https://user-images.githubusercontent.com/73304952/199283977-0f6a2c34-8074-4f9a-8ec4-bf34cce44e64.png)
Adding spaces to the end works as well, tysm
