### ISSUE TITLE
pango escaping on by default?

### ISSUE THREAD

**Issue by ammgws** [greshake/i3status-rust#1655]
At some point recently it seems like escaping pango characters has been added to format strings by default, but as far as I can tell it breaks being able to use pango formatting in the first place.

e.g. a custom block that outputs `"<span color='red'>my custom text here</span>"` is pango escaped so displays literally in the bar without being rendered by pango
```json
{"full_text":"","color":"#424242FF","separator":false,"separator_block_width":0,"markup":"pango"},{"full_text":" &lt;span color=&#39;red&#39;&gt;my custom text here&lt;/span&gt; ","color":"#FFFFFFFF","background":"#424242FF","name":"0","separator":false,"separator_block_width":0,"markup":"pango"}],
```

**Comment by MaxVerevkin** [comment]
I think it happened in #1618. We can either make `$text` and `$short_text` not escaped (like any `$icon`), or if we go with #1605, an argument can be added to `str` formatter to control escaping. Something like `" $text.str(escape:false) "` or `" $text.str(escape:no) "`.

**Comment by MaxVerevkin** [comment]
Or `" $text.str(pango:true) "`.

**Comment by ammgws** [comment]
For now, I guess we should just do this:

> We can either make $text and $short_text not escaped (like any $icon)

and also find and re-add all the places we were explicitly escaping in other blocks (like SSID etc)
