### ISSUE TITLE
memory block: update ZFS arc calculation

### ISSUE THREAD

**Issue by ammgws** [greshake/i3status-rust#1656]
Match htop: https://github.com/htop-dev/htop/pull/1003

@GladOSkar FYI

**Comment by ammgws** [comment]
Removing from v0.30.0 milestone as it's not a breaking change/regression

**Comment by GladOSkar** [comment]
It's on my todo list but it'll likely still take a bit of time, have a lot of exams coming up

**Comment by okhsunrog** [comment]
What's the status on this issue? I use ZFS on my desktop too

**Comment by GladOSkar** [comment]
I'll likely only get to it in late March/early April. Feel free to take the lead and send a PR if you need it urgently.

**Comment by ammgws** [comment]
@okhsunrog fda86433ae668c86ef1d8ddda604a4860a8d78d2 should hopefully suffice for now. To get it to match htop 100% we need to get the value of `zfs_arc_min` as well, but I can't find a way to grab it.

**Comment by cfsmp3** [comment]
> @okhsunrog [fda8643](https://github.com/greshake/i3status-rust/commit/fda86433ae668c86ef1d8ddda604a4860a8d78d2) should hopefully suffice for now. To get it to match htop 100% we need to get the value of `zfs_arc_min` as well, but I can't find a way to grab it.

It _should_ be here

`/sys/module/zfs/parameters/zfs_arc_min
`

**Comment by ammgws** [comment]
Indeed it is. Not sure what to make of the "Min size" displayed by arc_summary though;

```sh
>cat /sys/module/zfs/parameters/zfs_arc_min
0
>cat /sys/module/zfs/parameters/zfs_arc_max
0
>arc_summary

------------------------------------------------------------------------
ZFS Subsystem Report                            Sun Feb 26 11:13:56 2023
Linux 5.15.35-1-pve                                           2.1.4-pve1
Machine: ammgwsserver (x86_64)                             2.1.4-pve1

ARC status:                                                      HEALTHY
        Memory throttle count:                                         0

ARC size (current):                                    88.7 %   27.8 GiB
        Target size (adaptive):                        88.9 %   27.9 GiB
        Min size (hard limit):                          6.2 %    2.0 GiB
        Max size (high water):                           16:1   31.3 GiB
        Most Frequently Used (MFU) cache size:         96.8 %   24.5 GiB
        Most Recently Used (MRU) cache size:            3.2 %  841.6 MiB
        Metadata cache size (hard limit):              75.0 %   23.5 GiB
        Metadata cache size (current):                 20.0 %    4.7 GiB
        Dnode cache size (hard limit):                 10.0 %    2.4 GiB
        Dnode cache size (current):                    56.1 %    1.3 GiB
```

**Comment by cfsmp3** [comment]
> Indeed it is. Not sure what to make of the "Min size" displayed by arc_summary though;

Fortunately arc_summary is a trivial Python script :-)

https://github.com/openzfs/zfs/blob/master/cmd/arc_summary

I don't use ZFS, but I looked at it for a bit and it seems straightforward if you want to get the exact same results.

**Comment by ammgws** [comment]
Ah looks like it is in `/proc/spl/kstat/zfs/arcstats` after-all, as `c_min`

**Comment by ammgws** [comment]
Updated in d2f68d332c52d4824cff2581f0815b698c316dc9
