### ISSUE TITLE
Cycle through timezones in "time" block on click

### ISSUE THREAD

**Issue by llyyr** [greshake/i3status-rust#1658]
Unless I didn't read through the docs close enough, this currently isn't possible

**Comment by omkar-mohanty** [comment]
Hi if this issue is still open can I take it?

**Comment by ammgws** [comment]
I'm not aware of anyone working on it

**Comment by omkar-mohanty** [comment]
> I'm not aware of anyone working on it

Oh. I worked out how to implement this. If no one's working on this can I open a PR?

**Comment by ammgws** [comment]
Feel free to do so for anything, anytime
