### ISSUE TITLE
weather: possible bug in parsing near-zero temperatures?

### ISSUE THREAD

**Issue by martinpelikan** [greshake/i3status-rust#1659]
The weather block appears to render some strange values when parsing near-zero temperatures. It looks like negative numbers aren't the cause, as substituting a city ID with far below zero temperatures renders correctly. I've attached a screenshot of the block and the corresponding API response segment, as well as relevant config. To reproduce, you will likely have to find a city with a approximately zero temperatures.

![image](https://user-images.githubusercontent.com/3248296/200504518-14edfb64-3beb-4a26-a72b-a203b0265822.png)

`{"temp":-0.08,"feels_like":-0.08,"temp_min":-1.54,"temp_max":1.68,"pressure":1012,"humidity":91}`

```
[[block]]
block = "weather"
format = "$icon $temp"
autolocate = true
[block.service]
name = "openweathermap"
<snip>
```

**Comment by MaxVerevkin** [comment]
Looks like it's applying engineering notation to degrees. We already have [an exception for percents](https://github.com/greshake/i3status-rust/blob/1bc06eab8a30ef4c59be5ab95b3f0db194e1b9ee/src/formatting/unit.rs#L76), so fixing this should be easy.
