### ISSUE TITLE
The document of nvidia_gpu bock is out of date!

### ISSUE THREAD

**Issue by otakutyrant** [greshake/i3status-rust#1660]
I found out that this [document](https://github.com/greshake/i3status-rust/blob/v0.22.0/doc/blocks.md#options-25) does not match the [code](https://github.com/greshake/i3status-rust/blob/master/src/blocks/nvidia_gpu.rs#L15).

**Comment by ammgws** [comment]
That's because you're looking at the wrong code: https://github.com/greshake/i3status-rust/blob/v0.22.0/src/blocks/nvidia_gpu.rs
