### ISSUE TITLE
Music block fails to hide when player closes

### ISSUE THREAD

**Issue by Deedasmi** [greshake/i3status-rust#1661]
OS - Arch
WM - i3 4.21.1
i3status-rs - Git (via AUR)
Player - firefox (twitch)

Block config:
```
[[block]]
block = "music"
hide_when_empty = true
format = " $icon $combo $play $next"
```

Hides correctly when no player

With player:

![image](https://user-images.githubusercontent.com/5093293/200929206-1c629836-8875-47b5-942f-2483aaf946dc.png)

Ctrl+w firefox tab to close player:

![image](https://user-images.githubusercontent.com/5093293/200929280-5f21ad50-b293-461e-9016-fb1dbd76b09c.png)

Happens with just $title as well.

**Comment by MaxVerevkin** [comment]
Can you share the debug messages? It should list available players. To enable them, run with `RUST_LOG=music=debug` env variable (e.g. `RUST_LOG=music=debug cargo r >/dev/null`).

**Comment by ammgws** [comment]
$combo and $title are fallible so you need to use `|` with them, right? The default format string for the music block already handles that IIRC

**Comment by ammgws** [comment]
The music block docs say "Note: All placeholders can be absent. See the examples below to learn how to handle this." but the examples aren't very obvious

**Comment by MaxVerevkin** [comment]
Do we even need `hide_when_empty`? I think it only confuses people.

**Comment by ammgws** [comment]
I guess not needed after #1618 , just need to give an example format string that replicates the behaviour
