### ISSUE TITLE
Weather forecast

### ISSUE THREAD

**Issue by aloispichler** [greshake/i3status-rust#1663]
* Would be nice if the weather block would provide the format key `{forecast}`  in addition for the temperature in 3 hours, provided by openweathermaps.org.
The call is
`api.openweathermap.org/data/2.5/forecast?lat={lat}&lon={lon}&appid={API key}` (cf. https://openweathermap.org/forecast5).
* Openweather delivers icons on the fly: https://openweathermap.org/weather-conditions#Icon-list.
The following should be used: 
     "Unknown": "✨",
        "01d": "☀️",
        "01n": "🌕",
        "02d": "🌤️",
        "02n": "☁️",
        "03d": "🌥️",
        "03n": "☁️",
        "04d": "☁️",
        "04n": "☁️",
        "09d": "🌧️",
        "09n": "🌧️",
        "10d": "⛈",
        "10n": "⛈",
        "11d": "🌩",
        "11n": "🌩",
        "13d": "❄️",
        "13n": "❄️",
        "50d": "🌫",
        "50n": "🌫",
taken from here: https://docs.qtile.org/en/latest/_modules/libqtile/widget/open_weather.html
Thanks.

**Comment by bim9262** [comment]
Resolved by #1944
