### ISSUE TITLE
Space issue of bluetooth block

### ISSUE THREAD

**Issue by c02y** [greshake/i3status-rust#1669]
Put only one space after `$icon` the format for bluetooth block:
```
[[block]]
block = "sound"
format = "$icon $volume "
max_vol = 150
show_volume_when_muted = true
headphones_indicator = true

[[block]]
block = "bluetooth"
format = "$icon "
disconnected_format = "$icon "
mac = "xxx"

[[block]]
block = "time"
format = "$icon %m/%d %a %H:%M"
interval = 10
```
![image](https://user-images.githubusercontent.com/2135996/203277167-78ffa20e-51e6-4293-8dc2-34eaa312c9de.png)

Put two spaces after `$icon` in the format of bluetooth block:
```
[[block]]
block = "bluetooth"
format = "$icon  "
disconnected_format = "$icon  "
mac = "xxx"
```
![image](https://user-images.githubusercontent.com/2135996/203277636-006b63cc-cccc-46d4-b904-cef968004363.png)

It seems the one space after the `$icon` in format of bluetooth block is only half of the one space in the format of other blocks.

**Comment by MaxVerevkin** [comment]
Which icon set and font do you use?

**Comment by c02y** [comment]
`awesome6`

**Comment by MaxVerevkin** [comment]
Closing because it is a font/bar issue and we can't do much about it.

**Comment by c02y** [comment]
I'm sorry, I tried the old config which is `awesome5` and `Font Awesome 5 Pro 12.4`, but this issue is not gone either.

And `awesome6`, `Font Awesome 6 12.4` is the same either.

Since old version of i3status-rust is working fine, could you please be more specific about the `font/bar` issue?

Or if the space in your i3status-rust is working fine, could you please share your font config of i3/i3status-rust?

**Comment by MaxVerevkin** [comment]
> Since old version of i3status-rust is working fine

Oh, you didn't mention that. TBH I don't understand how this can be the case because icons weren't changed since v0.20. Are you absolutely sure?

> Or if the space in your i3status-rust is working fine, could you please share your font config of i3/i3status-rust?

I personally use `icons = "material-nf"` with `JetBrainsMono Nerd Font 10` and I've never had any issues with it. I did have (spacing and size) issues with `awesome` and I used to use pango markup to fix it (there is an example in the README how to use `icons_format` for this purpose) but eventually just switched.

**Comment by c02y** [comment]
Don't know why, if I use `icons = "material-nf"` in i3status-rust config and `font pango:JetBrainsMono Nerd Font 12` in i3-config bar, the icons in the i3status-rust bar is messed up. (JetBrainsMono Nerd Font is from `nerd-fonts-jetbrains-mono` archlinux package)


![image](https://user-images.githubusercontent.com/2135996/212208332-04ba4a8c-82db-45f7-9430-47f4b77f160e.png)





----------------------------------
Anyway, `icons_format = "<span font_family='Font Awesome 6 Pro'>{icon}</span>"` fixes all the space issue here.

Thank you.

**Comment by MaxVerevkin** [comment]
Fonts are weird :weary:
