### ISSUE TITLE
alt block could not parse JSON

### ISSUE THREAD

**Issue by euri10** [greshake/i3status-rust#1673]
I have a issue with the apt block, I removed everything else and just have that
```
[[block]]
block = "alt"
```
to my status bar under a recent compiled version using git, I get `Error: Could not parse JSON (lexical error: invalid char in json text/)` , see screenshot

```
❯ i3status-rs --version
i3status-rs 0.30.0 (commit e477d2b3 2022-11-17)
```

![20221201_0908_1150x122_1669882106](https://user-images.githubusercontent.com/1104190/204999403-b86bedfc-1c0d-4424-ae18-4919a570844a.png)

but when I start it cli way it gives me no error
```
❯ /usr/bin/i3status-rs /home/lotso/.config/i3/statustop.toml
{"version": 1, "click_events": true}
[
Hit:1 http://security.debian.org/debian-security bullseye-security InRelease
Reading package lists... Done
Building dependency tree... Done
All packages are up to date.
[{"full_text":"0","name":"0","markup":"pango"}],
```

with debug enabled: 
```
❯ RUST_LOG=block=apt /usr/bin/i3status-rs /home/lotso/.config/i3/statustop.toml
warning: invalid logging spec 'apt', ignoring it
{"version": 1, "click_events": true}
[
Hit:1 http://security.debian.org/debian-security bullseye-security InRelease
Fetched 6,751 B in 1s (6,703 B/s)
Reading package lists... Done
Building dependency tree... Done
All packages are up to date.
[{"full_text":"0","name":"0","markup":"pango"}],
```

**Comment by ammgws** [comment]
The error is from i3bar/swaybar because i3status-rust is producing invalid JSON

For some reason apt output is not being captured

**Comment by euri10** [comment]
> I don't have a distro to test this, but [3a2f7ca](https://github.com/greshake/i3status-rust/commit/3a2f7ca03c3cc70f966035716631bea7d3008f05) should fix it.

I can confirm this solved it, thanks
