### ISSUE TITLE
Mouse wheel on music block

### ISSUE THREAD

**Issue by euri10** [greshake/i3status-rust#1675]
When using the wheel on the music block I get this, see screenshot, alternatively a red `seek() failed` message, and another error I can't really read well unfortunately, the 2 errors dont disappear should I play music, or stop it, I have to reload the entire bar.

Also I cant find a way to reproduce  just launching the cli in a terminal since it requires the use of the mouse, but I'd be more than happy to provide more info if guidance is provided !

![20221202_1022_448x39_1669972955](https://user-images.githubusercontent.com/1104190/205260493-5ed8842d-8d60-43a6-9e3b-1199af39b1e9.png)
![20221202_1022_2015x47_1669972962](https://user-images.githubusercontent.com/1104190/205260512-87918656-5df8-4144-b648-d2093377aa15.png)

my music block, nothing fancy, I'm using Plexamp 4.6.0
```
[[block]]
block = "music"
```

```
❯ i3status-rs --version
i3status-rs 0.30.0 (commit 26763bc0 2022-12-01)
  ~ ❯            
```

**Comment by ammgws** [comment]
Can you show the output of the command below, replacing the "org.mpris.MediaPlayer2.firefox.instance705831" with your player that you set in your config?

```sh
>busctl --user call org.mpris.MediaPlayer2.firefox.instance705831 /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player Seek x 100
Call failed: Method /org/mpris/MediaPlayer2.org.mpris.MediaPlayer2.Player.Seek not supported

>busctl --user call org.mpris.MediaPlayer2.playerctld /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player Seek x 100
# no error
```

**Comment by euri10** [comment]
how/where can I get that `org.mpris.MediaPlayer2.firefox.instance705831` @ammgws  please ? My config is like the one I showed above, really minimal I didnt set a particular player

**Comment by euri10** [comment]
found it : `busctl --user list|grep -i plex`

**Comment by ammgws** [comment]
...and I just found out that it's closed source so I don't think we can really help any further.

Maybe you could override the WheelUp and WheelDown for the block to no-op? Unless you use it with other players too, in that case try file a bug with Plex.

**Comment by euri10** [comment]
> ...and I just found out that it's closed source so I don't think we can really help any further.
> 
> Maybe you could override the WheelUp and WheelDown for the block to no-op? Unless you use it with other players too, in that case try file a bug with Plex.

ok will try filing a bug there, I need it for other players ! thanks for the kind help
