### ISSUE TITLE
Configuration Example Not Working

### ISSUE THREAD

**Issue by Shimori77** [greshake/i3status-rust#1676]
The default configuration and docs don't work on 0.22.0 for some reason.
Using i3-gaps v4.21.1 on Arch Linux. The i3status-rust binary was fetched from the community repository.

Example of error reported by i3:

`Error: failed to parse TOML from file contents (Cause: unknown field 'theme', expected one of 'name', 'file', 'overrides' for key 'theme'at line 41 column 1)`

Full error report:

```
{
  "version": 1, "click_events": true
}

[
  [
    {
      "full_text":" Error: failed to parse TOML from file contents (Cause: unknown field `theme`, expected one of `name`, `file`, `overrides` for key `theme` at line 41 column 1)", 
      "color": "#DC322FFF",
      "background": "#000000FF", 
      "name": "0",
      "instance": "0",
      "separator": false,
      "separator_block_width": 0,
      "markup": "pango"
    }
  ],


Wrapped("failed to parse TOML from file contents", Error { inner: ErrorInner { kind: Custom, line: Some(40), col: 0, at: Some(646), message: "unknown field `theme`, expected one of `name`, `file`, `overrides`", key: ["theme"] } })
```

**Comment by MaxVerevkin** [comment]
This example config is for master branch and it doesn't work because there's been a lot of breaking changes since last release. I've updated the example to mention this and point to an older example.

**Comment by Zagrebelin** [comment]
Here is a direct link to the working configuration for 0.22.0 version
https://github.com/greshake/i3status-rust/blob/v0.22.0/examples/config.toml
