### ISSUE TITLE
i3status-rust fails to build unless libpulse is installed

### ISSUE THREAD

**Issue by akdjka** [greshake/i3status-rust#1677]
I just wanted to install i3status on my system. Linking failed with
```
  = note: ld.lld: error: unable to find library -l:libpulse.so.0
          clang-15: error: linker command failed with exit code 1 (use -v to see invocation)
```
Fine, I don't have libpulse installed. And I don't want to.
But this requirement is not documented in https://github.com/greshake/i3status-rust/blob/master/doc/dev.md and I think it should be.

Also, making libpulse dependency optional would also be welcome.

**Comment by MaxVerevkin** [comment]
> Also, making libpulse dependency optional would also be welcome.

It is, but it's on by default. Did you compile with `--no-default-features`?

> But this requirement is not documented

Fixed

**Comment by akdjka** [comment]
With this switch it builds fine. :)
