### ISSUE TITLE
Error when bluetooth is disabled

### ISSUE THREAD

**Issue by MDingas** [greshake/i3status-rust#1682]
I'm using the bluetooth block. I don't always want to have bluetooth turned on, but disabling its systemd service results in the following i3status-rust error:

``` failed to get managed objects from org.bluez (Cause: Unit dbus-org.bluez.service not found) ```

Shouldn't the status bar gracefully proceed if bluetooth is turned off?

**Comment by ammgws** [comment]
Can you try with the master branch?

**Comment by MDingas** [comment]
On the master branch, it works fine with bluetooth on, but I get the error "Failed to get the list of devices" when bluetooth is off. It would be ideal if it could fail silently.

**Comment by MaxVerevkin** [comment]
@MDingas what is the full error message? (you can get it by clicking on the failed block)

**Comment by MDingas** [comment]
The error is as follows:

```Error in bluetooth: Failed to get the list of devices. (Cause: org.freedesktop.zbus.Error: Unit dbus-org.bluez.service not found)``` (Same error as in the stable version)

**Comment by MaxVerevkin** [comment]
@MDingas can you test with #1691?

**Comment by MDingas** [comment]
On that branch, when I have a bluetooth device connected and recognized, after performing ```systemctl stop bluetooth```, the bluetooth device remain on the task bar, requiring a manual ```i3-msg restart``` for it to go away.

**Comment by MaxVerevkin** [comment]
Okay, I understand the issue and I guess I know how to fix it (listen to `NameOwnerChanged`, as we do in `music`). But for some reason I cannot reproduce it because no mater what I do, I can't get rid of `org.bluez` service. Something keeps restarting `bluez`.

**Comment by ammgws** [comment]
Try disabling the Bluetooth kernel module

**Comment by MaxVerevkin** [comment]
@MDingas does #1695 fix it?

**Comment by MDingas** [comment]
It seems to be working perfectly now! I did notice something else. I get "Placeholder 'percentage' not found' upon starting bluetooth for the first time, requiring a manual ```i3-msg restart``` to get the value to show up.

**Comment by MaxVerevkin** [comment]
`percentage` is an optional placeholder and your `format` should handle the case when it's not available. For example `" $icon $name{ $percentage|} "`

**Comment by MDingas** [comment]
Thank you all for your work!
