### ISSUE TITLE
Can't find how to add microphone block

### ISSUE THREAD

**Issue by unavoidable0100** [greshake/i3status-rust#1692]
Hi there,

I can't find how to add microphone block on the bar, can someone guide me to this?

Right now I only have the block for sound but for my understanding I have to make a custom block for the microphone?
My bar right now:
![image](https://user-images.githubusercontent.com/77761282/210135716-22a1f5ff-0b3b-4f01-ab68-401c4bff0de5.png)

For example in bumblebee you can show the mic and sound like this:
![image](https://user-images.githubusercontent.com/77761282/210135790-32a5c77a-66da-4f13-b66a-b27962b59db5.png)

I know the implementation it may be obvious but I'm struggling the last 3 days now.
Any help would be appreciated, cheers !

**Comment by MaxVerevkin** [comment]
Do you use pulseaudio/pipewire? If so, just set `device_kind = "source"`. If this helps, you can submit a PR to improve the docs.

**Comment by unavoidable0100** [comment]
Hi !
thanks for your quick answer,

I'm not sure I follow you though,
I found my input source but I'm not sure I understand the implementation of block.
Should it be a custom block or a sound block? 
from what I've searched custom blocks don't allow the device_kind field.

This is what I've done so far but I am sure it's not correct
![image](https://user-images.githubusercontent.com/77761282/210139850-d5d415c0-9412-4495-a949-76cc1eedd285.png)


Also the output from pactl:
![image](https://user-images.githubusercontent.com/77761282/210139860-ca3379be-7b9d-4db0-bee9-953fa8876146.png)

**Comment by MaxVerevkin** [comment]
No need for custom blocks.

I have something like this in my config:

```toml
[[block]]
block = "sound"
driver = "pulseaudio"
device_kind = "sink"

[[block]]
block = "sound"
driver = "pulseaudio"
device_kind = "source"
```

**Comment by unavoidable0100** [comment]
This makes sense.

Seems like I hadn't understood the terminology of `sink` and `source`

I will leave this open to close it with a PR to update the docs for this asap

Thank you for your time, cheers

**Comment by unavoidable0100** [comment]
@MaxVerevkin I've updated the docs, let me know if something is wrong
