### ISSUE TITLE
Question: reload individual modules from shell?

### ISSUE THREAD

**Issue by fritzrehde** [greshake/i3status-rust#1699]
Hi, i'm currently using polybar, but thinking of maybe switching to i3status-rust. A big frustration in polybar is that I can't reload a module (usually I just have shell scripts that periodically run every few seconds and output to stdout) from an external shell command (e.g. i3status-rust reload module "module-name" or similar). Is this possible with i3status-rust?

**Comment by madhur** [comment]
You can use custom block to run shell scripts
https://greshake.github.io/i3status-rust/i3status_rs/blocks/custom/index.html

If the shell script is updated, the output will automatically update once it runs next. No need to reload the bar / module.

**Comment by fritzrehde** [comment]
I am talking about manually reloading a module. Let's say it updates every 10 seconds, but i want to manually reload it now. Is that possible?

**Comment by ammgws** [comment]
Not sure if you are purposely interchanging "update" and "reload", but just in case you meant "update", does the below cover your need?

```sh
[[block]]
block = "custom"
command = "fritzrehde's command"
interval = 10
signal = 4
```

Force update via shell: `pkill -SIGRTMIN+4 i3status-rs`

**Comment by fritzrehde** [comment]
I'm not sure if it does what I want, since I haven't used this application yet and don't know the config syntax yet. However, this does look promising. Am I right in assuming the `signal = 4` means that a `-SIGRTMIN+4` will only reload/update (not sure on the difference between the two terms, I mean basically rerunning the command to get new output) that certain module/block? That would be the exact feature I am looking for! How many possible `signal` values are there?

**Comment by ammgws** [comment]
Sounds like it is exactly want you're looking for.

Look up SIGRTMAX for your system to see how many you have.
