### ISSUE TITLE
Proposal: Change update interval consistently to milliseconds

### ISSUE THREAD

**Issue by jheyens** [greshake/i3status-rust#17]
I would like to discuss a proposed change of consistently switching to milliseconds from seconds in our update interval configurations.
I know that any block implementation can handle this on its own, but I would prefer to have it consistently for all blocks.
Some blocks would benefit from a more fine-grained update interval, f.e. I would CPU utilization to 250 or 500 ms. 
Opinions?

**Comment by greshake** [comment]
We could just parse the interval in the config as floating point numbers. That way existing configs don't need to be changed, and we set everything from seconds to nanoseconds. Just add a macro that translates f64 to a Duration.

**Comment by greshake** [comment]
@jheyens is on vacation, but I think #48 covers it :)
