### ISSUE TITLE
[Bug Report] "Failed to get connected state" from bluetooth block after wakeuping from hibernation

### ISSUE THREAD

**Issue by c02y** [greshake/i3status-rust#1702]
Every time after I wake up from hibernation, the bluetooth block is 
```
Failed to get connected state
```

Config is:
```
[[block]]
block = "bluetooth"
format = "$icon "
disconnected_format = "$icon "
mac = "xxx"
```

After I reload i3status-rust bar, it works normally.

FYI:
i3status-rs 0.30.0 (commit fbb586e5 2023-01-11)
i3 version 4.22 (2023-01-02)

**Comment by MaxVerevkin** [comment]
Does 74da5133f7c5a92e5c44c50458ea4f33af6c79b9 fix it?

**Comment by c02y** [comment]
Yep, it seems fixed. Thank you.
