### ISSUE TITLE
Change block on click

### ISSUE THREAD

**Issue by Llamach** [greshake/i3status-rust#1705]
Is there way to expand/change/modify the blocks on click?
For example I click the clock block it changes the format? I apologize if I have missed any certain part in the documentation.

Thanks in advance

**Comment by GladOSkar** [comment]
This is most easily done (imo) with `custom` blocks and `cycle` which allows you to cycle through multiple custom commands.

See https://greshake.github.io/i3status-rust/i3status_rs/blocks/custom/index.html

Or, an example from my config:
```
[[block]]
block = "custom"
shell = "sh"
cycle = ["echo '🐑'", "cat /etc/hostname"]
[[block.click]]
button = "left"
cmd = "<command>"
```

**Comment by MaxVerevkin** [comment]
Also some blocks (cpu, disk space, memory...) have the `format_alt` option which does exactly what you want. Time block doesn't have it, but only because it wasn't implemented by anyone yet.

**Comment by Llamach** [comment]
Thanks for the info.
Closing the issue. Have a good day :)
