### ISSUE TITLE
cpu: option to show max frequency instead of avg

### ISSUE THREAD

**Issue by matthiaskrgr** [greshake/i3status-rust#1732]
When I can see in the bar chart, that only one core is running/turboing, displaying the average frequency is kinda pointless because it will not reflect the frequency of that one core :upside_down_face: 
Might be nice to have an option to actually show "highest core frequency" instead of average. :)

**Comment by MaxVerevkin** [comment]
Done in c3fc0f0d50871089c6718d335c1234533cd4ecbd :)
