### ISSUE TITLE
Example config broken

### ISSUE THREAD

**Issue by T4varo** [greshake/i3status-rust#1734]
The example config in example/config.toml is broken. When trying to use the config I get the following error:

`
[{"full_text":"Failed to deserialize TOML file /home/<user>/.config/i3status-rust/config.toml at line 25: Incorrect format template. (Cause: expected &#39;:&#39;, got &#39;)&#39;)","border":"#ff0000","instance":"0:","separator":false,"separator_block_width":0,"markup":"pango"}],

Failed to deserialize TOML file /home/<user>/.config/i3status-rust/config.toml at line 25: Incorrect format template. (Cause: expected ':', got ')')

[src/main.rs:114] error = Error {
    kind: Other,
    message: Some(
        "Failed to deserialize TOML file /home/<user>
	/.config/i3status-rust/config.toml at line 25: Incorrect format template. (Cause: expected ':', got ')')",
    ),
    cause: None,
    block: None,
}`

**Comment by MaxVerevkin** [comment]
fixed 17238ac
