### ISSUE TITLE
`load` block shows no info

### ISSUE THREAD

**Issue by freswa** [greshake/i3status-rust#1743]
Since 0.30 the load block is pretty silent. It either shows `0 0 1` or `0 0 0` when started.
At the same time htop shows `0.41 0.62 0.78`.

Config:
```
[[block]]
block = "load"
format = " $icon $1m $5m $15m "
interval = 1
```

**Comment by MaxVerevkin** [comment]
> At the same time htop shows 0.41 0.62 0.78

To get this kind of precision set `format = " $icon $1m.eng(w:4) $5m.eng(w:4) $15m.eng(w:4) "`. The default width of 2 is pretty useless for this block, so I updated the docs and default `format`.

Although it would be nice if `$1m` defaulted to a reasonable width.
