### ISSUE TITLE
`music` block fails to show Firefox instances (v0.30)

### ISSUE THREAD

**Issue by LRitzdorf** [greshake/i3status-rust#1745]
I've just received the v0.30 update via the Arch repos, and have reworked my config file in response. While testing, I discovered that certain media players (Firefox, in my testing) failed to appear in the `music` block, while others (Spotify and VLC) do show up properly.

In addition, I've confirmed that Firefox does seem to be broadcasting its presence correctly — `playerctl -l` does list the Firefox instance, along with Spotify, when both programs are open. It's worth noting that Firefox does name its interfaces with a dot (for example, `firefox.instance9822`), in case that might be throwing off your parsing (?).

Is there any further testing I can perform to help troubleshoot this issue?

**Comment by cfsmp3** [comment]
The music block has debugging logging, so you can give it a try. Just create a trivial config that only contains that block. 

This is what I get with firefox and ytmp:

```
✦ ❯ busctl  --list  --user |grep -i mpri
org.mpris.MediaPlayer2.firefox.instance6808         6808 firefox         cfsmp3 :1.125        user@1000.service -       -
org.mpris.MediaPlayer2.playerctld                   6589 playerctld      cfsmp3 :1.84         user@1000.service -       -
org.mpris.MediaPlayer2.youtube-music-desktop-app    6797 youtube-music-d cfsmp3 :1.250        session-c2.scope  c2      -
```

```
✦ ❯ playerctl -l
youtube-music-desktop-app
firefox.instance6808
```
However:
```
✦ ❯ RUST_LOG=music=debug /home/cfsmp3/codebase/i3status-rust/target/release/i3status-rs /tmp/music.toml
{"version": 1, "click_events": true}
[
[],
[2023-02-22T05:57:47Z DEBUG music] available players:
[2023-02-22T05:57:47Z DEBUG music] org.mpris.MediaPlayer2.youtube-music-desktop-app
[{"full_text":"","color":"#458588FF","separator":false,"separator_block_width":0,"markup":"pango"},{"full_text":"Baby Missiles - The War On Drugs                                           ","color":"#EBDBB2FF","background":"#458588FF","name":"0","instance":"0:","separator":false,"separator_block_width":0,"markup":"pango"}],
```

**Comment by bim9262** [comment]
It's failing to get the volume.
```
> busctl --user get-property org.mpris.MediaPlayer2.firefox.instance952358 /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player Volume
Failed to get property Volume on interface org.mpris.MediaPlayer2.Player: /org/mpris/MediaPlayer2.org.mpris.MediaPlayer2.Player Volume is not supported
```
Firefox bug report: https://bugzilla.mozilla.org/show_bug.cgi?id=1674654

We should probably make it so that volume can be optional (even though it is part of the spec: https://specifications.freedesktop.org/mpris-spec/latest/Player_Interface.html#Simple-Type:Volume)

**Comment by LRitzdorf** [comment]
Well, that was fast. Thanks for the fix!
