### ISSUE TITLE
docs: mention mouse buttons up, down in [[block.click]] section of README.md

### ISSUE THREAD

**Issue by w-jablonski** [greshake/i3status-rust#1753]
README.md line 72

Currently it's misleading as the linked content https://greshake.github.io/i3status-rust/i3status_rs/click/enum.MouseButton.html seems to suggest `wheel_up wheel_down` as the mouse wheel actions. While the correct names for these are `up down`. Let's just mention these.

**Comment by MaxVerevkin** [comment]
Fixed in 3eea7e0
