### ISSUE TITLE
Net block in v0.30.2 wrong IPv{46} address 

### ISSUE THREAD

**Issue by kagaroth** [greshake/i3status-rust#1756]
Hello,

Just updated i3status-rust to v0.30.2 and I found that the net block does not work correctly. For IPv4 it shows the default GW as the address and for IPv6 just picks the link local address instead the global one: 
>{"full_text":"10.0.0.1 fe80::67a:91f5:9d9a:1b08   0Kb   0Kb ","color":"#C1C1C1FF","background":"#06060FFF","name":"0","instance":"0:","separator":false,"separator_block_width":0,"markup":"pango"}

I don't know what checks are done and how those IPs are selected but the process should be revised because those who use this block are interested in their real IP addresses not in some random values. 

The way net block selects the addresses now makes it useless and without it the same goes for i3status-rust. 

PS: This block also uses a measurement for download / upload speeds that does not exist. Bytes per second and its multiples (power  of 2 or power of 10) is not a measure of speed. For speed the only measurement is bps (bits per second) and its multiples (power of 10).

**Comment by KloudJack** [comment]
I was just about to report this, though the behavior for me is slightly different:

- IPv4 address displayed is the host's private 192.168.x.x address as expected (not the gateway address)
- IPv6 address displayed is the link-local fe80:: address as mentioned by @kagaroth kagaroth

**Comment by MaxVerevkin** [comment]
> This block also uses a measurement for download / upload speeds that does not exist

Who decides what exists and what doesn't? Does Firefox / qBittorrent use a non-existing measurement? In any case, just set the unit to whatever you want.

> those who use this block are interested in their real IP addresses not in some random values.

No need to get passive aggressive. Instead you could provide what `ip -json -family inet6 address show <dev>` and `ip -json -family inet6 address show <dev>` show on your system, because for me the behavior of v0.22 and v0.30 match.

Also, patches welcomed.

**Comment by kagaroth** [comment]
Bellow is the output of ip -j -f inet add sh ppp0:
>[{"ifindex":5,"ifname":"ppp0","flags":["POINTOPOINT","MULTICAST","NOARP","UP","LOWER_UP"],"mtu":1492,"qdisc":"fq_codel","operstate":"UNKNOWN","group":"default","txqlen":3,"addr_info":[{"family":"inet","local":"188.27.0.92","address":"10.0.0.1","prefixlen":32,"scope":"global","label":"ppp0","valid_life_time":4294967295,"preferred_life_time":4294967295}]}]
As you can see on point to point over ethernet interfaces there is a public IP address and a private one. The json key local is of interest in this case not the key address.

Same command as above but for v6:
>[{"ifindex":5,"ifname":"ppp0","flags":["POINTOPOINT","MULTICAST","NOARP","UP","LOWER_UP"],"mtu":1492,"qdisc":"fq_codel","operstate":"UNKNOWN","group":"default","txqlen":3,"addr_info":[{"family":"inet6","local":"2a02:2f0f:b0ff:ffff::bc1b:5c","prefixlen":128,"scope":"global","noprefixroute":true,"valid_life_time":4294967295,"preferred_life_time":4294967295},{"family":"inet6","local":"fe80::bc1b:5c","address":"fe80::1","prefixlen":64,"scope":"link","noprefixroute":true,"valid_life_time":4294967295,"preferred_life_time":4294967295},{"family":"inet6","local":"fe80::67a:91f5:9d9a:1b08","prefixlen":64,"scope":"link","noprefixroute":true,"valid_life_time":4294967295,"preferred_life_time":4294967295}]}]
The first key named local is the public global IPv6 and that is what I would like to see because that is what is used to communicate via v6. 

Just a little off-topic:
> 
> Who decides what exists and what doesn't? Does Firefox / qBittorrent use a non-existing measurement? In any case, just set the unit to whatever you want.
> 
Yes, all software products use a wrong measurement unit for bandwidth / throughput / download / upload speed. Or almost all, some of them respect the standards and use bit and its multiples (powers of 10). RFCs, ISO, standards  decides what measurement unit is used for what purpose. 

PS: I'm not getting passive aggressive or whatnot, it just irks me when I have to reconfigure stuff and the end result is not the one I was expecting. If I were a developer / programmer with knowledge of rust maybe, just maybe, I would have been able to write a patch or something. Unfortunately my area of expertise is totally different.

**Comment by cfsmp3** [comment]
> it just irks me when I have to reconfigure stuff

You don't have to. If the previous version was working well for you just keep using it. That's what I did until I had some time to get back to bleeding edge :-)

**Comment by kagaroth** [comment]
Unfortunately it never crossed my mind to go back to the previous version of i3status-rust. And after deleting the old configs and doing the new ones I kind of what for this t work instead of repeating the steps, delete new config, create old config, install old i3status-rust from ALA or local cache if the package is still there :(

**Comment by cfsmp3** [comment]
> > [{"ifindex":5,"ifname":"ppp0","flags":["POINTOPOINT","MULTICAST","NOARP","UP","LOWER_UP"],"mtu":1492,"qdisc":"fq_codel","operstate":"UNKNOWN","group":"default","txqlen":3,"addr_info":[{"family":"inet","local":"188.27.0.92","address":"10.0.0.1","prefixlen":32,"scope":"global","label":"ppp0","valid_life_time":4294967295,"preferred_life_time":4294967295}]}]
> > As you can see on point to point over ethernet interfaces there is a public IP address and a private one. The json key local is of interest in this case not the key address.

Isn't 10.0.0.1 the one that you said on your original post that belonged to the gateway?

What IP were you expected to see on the bar?

**Comment by MaxVerevkin** [comment]
@kagaroth try 8fc1ef4

**Comment by kagaroth** [comment]
@cfsmp3 Yes 10.0.0.1 is the GW, I was expecting to see 188.27.0.92 because that is my machine IP. 
@MaxVerevkin 10x I'll try it.

**Comment by KloudJack** [comment]
@MaxVerevkin I've tested https://github.com/greshake/i3status-rust/commit/8fc1ef47d8b69447af9f80e9898f93c788ff95cc

For me it now behaves as expected and displays the interface's primary IPv4 and global IPv6 address.

![20230222_220027](https://user-images.githubusercontent.com/6822406/220759307-630dea00-3133-4525-8d65-4bc9131cf89f.png)

```toml
[[block]]
block = "net"
device = "^en*"
format = " $icon $ip [$ipv6] "
```
