### ISSUE TITLE
Music block: "Failed to render full text" error

### ISSUE THREAD

**Issue by The-Corrupted** [greshake/i3status-rust#1757]
Since the latest update I've started running into issues with the music block throwing a "Failed to render full text" error.
The given cause is "Placeholder 'combo' not found"
This happens if a music player isn't present or temporarily goes away.

```
[[block]]
block = "music"
format = " $icon $volume_icon $prev $play $next {$combo.str(max_w:40,rot_interval:0.5)} "
```

**Comment by MaxVerevkin** [comment]
v0.30 allows optional placeholders.

From [docs](https://greshake.github.io/i3status-rust/i3status_rs/blocks/music/index.html):

> Note: All placeholders except icon can be absent. See the examples below to learn how to handle this.

By the way, not all players implement `volume` (Firefox doesn't), so you might want to handle this case too.

**Comment by The-Corrupted** [comment]
Thanks for the reply.
I wasn't aware the placeholders were optional and needed to be handled.
I took a look at the documentation. It wasn't immediately obvious how optionals are being handled. Seems to be the | character? Regardless, inserting the vertical bar character at the end of combo fixed this issue for me. Will keep this in mind for the other blocks as well.
Closing since this was a result of user error.

**Comment by MaxVerevkin** [comment]
More relevant docs: https://greshake.github.io/i3status-rust/i3status_rs/formatting/index.html

Feel free to ask any questions and point to the parts of the docs that could be improved :)

**Comment by CarterSnich** [comment]
> "Failed to render full text"

I get the same error when there's no player available. Is there a alternative format to show if no player is available?

> By the way, not all players implement volume (Firefox doesn't), so you might want to handle this case too.

 How to handle this? The error also shows up when media is playing on Firefox. I don't know what to do. I omitted `$volume` for the meantime.

```
[[block]]
block = "music"
format = " $icon {$title.str(max_w:25,rot_interval:0.5)} $prev $play $next "
[block.theme_overrides]
info_bg = "#285577"
info_fg = "#abcdef"
[block.icons_overrides]
music = "󰎇"
music_play = "󰐊"
music_pause = "󰏤"
music_next = "󰒭"
music_prev = "󰒮"
volume = " "
volume_muted = "󰝟 "
[[block.click]]
button = "left"
action = "next_player"
[[block.click]]
button = "up"
action = "volume_up"
[[block.click]]
button = "down"
action = "volume_down"
```
