### ISSUE TITLE
brightness: fix support for systems without `org.freedesktop.login1`

### ISSUE THREAD

**Issue by ptrcnull** [greshake/i3status-rust#1760]
currently on systems that don't implement `org.freedesktop.login1` brightness is completely broken - any action results in `Failed to send D-Bus message (Cause: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.login1 was not provided by any .service files)`

however, the following config doesn't seem to do anything:
```
[[block]]
block = "backlight"
format = " $brightness "
[[block.click]]
button = "left"
cmd = "brightnessctl set 100%"
[[block.click]]
button = "right"
cmd = "brightnessctl set 10%"
[[block.click]]
button = "wheel_up"
cmd = "brightnessctl set 10+%"
[[block.click]]
button = "wheel_down"
cmd = "brightnessctl set 10-%"
```

**Comment by MaxVerevkin** [comment]
> currently on systems that don't implement org.freedesktop.login1 brightness is completely broken

This needs to be fixed.

> cannot override mouse actions

Fixed in 6e0a8d2

> however, the following config doesn't seem to do anything:

Also the docs were a bit out of date (now updated), the correct names are "up" and "down" instead of "wheel_up" and "wheel_down".

**Comment by bim9262** [comment]
Looking at https://github.com/stephaneyfx/brightness, they use the following aproach:

>Setting brightness is attempted using D-Bus and logind, which requires [systemd 243 or newer](https://github.com/systemd/systemd/blob/877aa0bdcc2900712b02dac90856f181b93c4e40/NEWS#L262). If this fails because the method is not available, the desired brightness is written to /sys/class/backlight/$DEVICE/brightness, which requires permission (udev rules can help with that).

**Comment by MaxVerevkin** [comment]
>  right now it just doesn't display at all for me on my notebook

Hm, this issue if about setting the brightness, not reading it. Did it work on v0.22?

**Comment by TimB87** [comment]
With v0.22 it worked perfectely fine for me

**Comment by TimB87** [comment]
sorry, ignore me, for some reason, it wouldn't properly load my config.toml on that device. I can now see the brightness block and reproduce the problem with missing `org.freedesktop.login1` missing as well.
