### ISSUE TITLE
net: block fails to render after system resumes from sleep

### ISSUE THREAD

**Issue by KloudJack** [greshake/i3status-rust#1766]
## Issue description

When resuming my system from sleep, the net block displays an error where prior to sleep the configured network interface's IPv4 and v6 address were visible:

```json
{
  "full_text": "Failed to render full text ",
  "color": "#1F1F28FF",
  "background": "#C34043FF",
  "name": "1",
  "instance": "1:",
  "separator": false,
  "separator_block_width": 0,
  "markup": "pango"
},
```

Expanding the error message in the block shows the full error:
`Error in net:  Failed to render full text. (Cause: Placeholder 'ip' not found)`

Watching the output of `ip -json address show enp39s0` during sleep and resume shows that only the IPv6 link-local address is available shortly after resume:

```json
{
  "ifindex": 2,
  "ifname": "enp39s0",
  "flags": [
    "BROADCAST",
    "MULTICAST",
    "UP",
    "LOWER_UP"
  ],
  "mtu": 1500,
  "qdisc": "fq_codel",
  "operstate": "UP",
  "group": "default",
  "txqlen": 1000,
  "link_type": "ether",
  "address": "00:xx:xx:xx:xx:xx",
  "broadcast": "ff:ff:ff:ff:ff:ff",
  "addr_info": [
    {
      "family": "inet6",
      "local": "fe80::xxxx:xxxx:xxxx:xxxx",
      "prefixlen": 64,
      "scope": "link",
      "tentative": true,
      "valid_life_time": 4294967295,
      "preferred_life_time": 4294967295
    }
  ]
}
```

It takes a few moments for the interface to successfully repopulate its local IPv4 and global IPv6 address, unfortunately i3status-rust doesn't update the block when this occurs and displays the error until it is restarted manually.

I think it would be appropriate behavior for the net block to fall back to the `missing_format` output should the `ip` variables fail to be resolved.

## Environment

**i3status-rust version:** 0.30.3
**kernel:** 6.1.12-1-lts
**arch:** x86_64

## Relevant configuration

```toml
[[block]]
block = "net"
device = "^en*"
format = " $icon $ip [$ipv6]"
format_alt = " $icon $speed_down $graph_down $speed_up $graph_up "
interval = 5
missing_format = ""
```

**Comment by MaxVerevkin** [comment]
You may handle this case in any way you want. For example

```toml
format = " $icon {$ip [$ipv6]|No IP}"
```

Or if you want the block to hide

```toml
format = " $icon $ip [$ipv6]|"
```

**Comment by KloudJack** [comment]
Ah I see this syntax in the [formatting documentation](https://greshake.github.io/i3status-rust/i3status_rs/formatting/index.html) now.

Thanks for the hint and for your dedication to this project :smiley:
