### ISSUE TITLE
sound: don't look up icons when not needed

### ISSUE THREAD

**Issue by ptrcnull** [greshake/i3status-rust#1774]
with the following config:
```
[[block]]
block = "sound"
format = " $output_name($volume) "
step_width = 5
```

sometimes i get `Icon 'volume_muted' not found`, despite the icon not being used in the format at all

**Comment by MaxVerevkin** [comment]
This particular error was fixed in #1785. As for not looking up unused icons, this might be implemented as an optimization in the future.
