### ISSUE TITLE
net block does not update after suspend on swaywm

### ISSUE THREAD

**Issue by equalis3r** [greshake/i3status-rust#1778]
I have tried the net blocks for both wifi and ethernet (default interval is 2 seconds). When wake up from sleep, the block fails to update and ends up with: "Failed to render full text". A manual reload of swaywm gets the block to render correctly.

**Comment by equalis3r** [comment]
```
[[block]]
block = "net"
device = "wlan0"
format = " $icon $ip "
format_alt = " $icon $ip "
missing_format = ""

[[block]]
block = "net"
device = "eno1"
format = " $icon $ip "
missing_format = ""
```
On my laptop `wlan0` is the active interface and it seems to be dropped after wake up from suspend, causing "Failed to render full text". `eno1` still gets matched correctly and shows correct missing format.

Meanwhile on my PC, it's the other way around. `eno1` is the active interface and gets dropped after wake up from suspend.

**Comment by MaxVerevkin** [comment]
See #1766
