### ISSUE TITLE
Bluetooth device status

### ISSUE THREAD

**Issue by srid** [greshake/i3status-rust#178]
Would be nice to glance at

- connected bluetooth devices
- their battery level (if available)

Or is it outside the scope of this project?

**Comment by lausek** [comment]
I think this is a very special task for a toolbar. What about implementing it with a `Custom` block?

**Comment by atheriel** [comment]
I like the idea of having a block that shows the status of a single (configurable) Bluetooth device, which I think is sufficiently general to find a home in this project.

I'm guessing that the use case here is checking whether one's wireless mouse/keyboard is connected.

**Comment by atheriel** [comment]
Don't mean to necro this thread, but for any prospective implementers, the best approach would be to make use of the [bluez D-Bus API](https://git.kernel.org/pub/scm/bluetooth/bluez.git/tree/doc/device-api.txt) in order to get a fully asynchronous and low-resource block.
