### ISSUE TITLE
disk_space block loses significant figures in 0.30

### ISSUE THREAD

**Issue by dantho281** [greshake/i3status-rust#1783]
In 0.22, my `disk_space` block correctly showed 1.73TB total space, and 1.72TB available space.
In 0.30.3, both of these blocks are now losing their significant figures and simply showing 1TB.

Looking in the documentation, I see no way to format this item to bring this data back, and as it stands, totally incorrect values are being shown.

Block config:
```
 [[block]]
 block = "disk_space"
 path = "/"
 info_type = "used"
 format = "$icon ROOT: $used/$total ($available free)"
 alert = 80
 warning = 60
```

**Comment by bim9262** [comment]
Try this out:

```
[[block]]
block = "disk_space"
path = "/"
info_type = "used"
format = " $icon ROOT: $used.eng(w:4)/$total.eng(w:4) ($available.eng(w:4) free) "
alert = 80
warning = 60
```
