### ISSUE TITLE
Segmentation fault in `sound` and `temperature`

### ISSUE THREAD

**Issue by GladOSkar** [greshake/i3status-rust#1786]
After updating to current master (`i3status-rs 0.30.2 (commit 76e19f29 2023-02-22)`) and fixing up my config, i got:

```sh
$ i3status-rs
{"version": 1, "click_events": true}
[
fish: Job 1, 'i3status-rs' terminated by signal SIGSEGV (Address boundary error)
```
sometimes also:
```sh
$ i3status-rs
{"version": 1, "click_events": true}
[
[],
fish: Job 1, 'i3status-rs' terminated by signal SIGSEGV (Address boundary error)
```

Minimal configs to reproduce:
```toml
[[block]]
block = "sound"
```
and
```toml
[[block]]
block = "temperature"
```
both create the segfault, most other blocks don't.

This happens both when compiling in `debug` and in `release` mode.

I attached the LLVM debugger and got this stack trace (`sound` block config):

https://gist.github.com/GladOSkar/3352afe39d26f052d4ba6610a369a5a9#file-i3status-rs_segfault-L139
(Segfault in Thread 3, Line 139 ff.)

Looks like a read from `0x0`. Going further is a bit beyond me, especially with all that threading and stuff, help would be appreciated.

My system:
- Distribution: Void
- Kernel: `Linux [...] 6.1.12_1 #1 SMP PREEMPT_DYNAMIC [...] x86_64 GNU/Linux`
- libc: musl
- DE: sway
- rustc: `1.67.1 (d5a82bbd2 2023-02-07)`
- cargo: `1.67.1 (8ecd4f20a 2023-01-10)`

**Comment by MaxVerevkin** [comment]
Can you try https://github.com/greshake/i3status-rust/issues/401#issuecomment-812456518?

**Comment by ammgws** [comment]
> libc: musl

worked before with this?>

**Comment by GladOSkar** [comment]
@MaxVerevkin that works!

@ammgws yes never was a problem

**Comment by GladOSkar** [comment]
Ohh i just remembered another thing i changed. I switched from void's `rust` package to `rustup` (because void's package is [stuck on 1.64.0](https://github.com/void-linux/void-packages/issues/40805)).

And they apply [patches](https://github.com/void-linux/void-packages/tree/master/srcpkgs/rust/patches) to `rustc` to make it work better with `musl` (e.g. [0002](https://github.com/void-linux/void-packages/blob/master/srcpkgs/rust/patches/0002-Remove-nostdlib-and-musl_root-from-musl-targets.patch) and [0010](https://github.com/void-linux/void-packages/blob/master/srcpkgs/rust/patches/0010-Fix-dynamic-linkage-of-musl-libc-for-the-libc-crate.patch)). So that's probably what was missing.

And `sound` and `temperature` might be the blocks (of those that i use) that link to `libc` somewhere eventually? I thought this wasn't an issue with rust, but if they link into `C` code it might of course be.

**Comment by GladOSkar** [comment]
Guess I'll put a note on this into the install docs
