### ISSUE TITLE
Battery: Filter by model

### ISSUE THREAD

**Issue by cfsmp3** [greshake/i3status-rust#1797]
I'm going to do this myself but before getting into it I want to make sure this is not dumb :-) (or already possible)

My wireless mouse has a battery (obviously) and I can get its charge with upower:

```
Device: /org/freedesktop/UPower/devices/battery_hidpp_battery_15
  native-path:          hidpp_battery_15
  model:                MX Ergo Multi-Device Trackball
  serial:               406f-3b-a5-54-8c
  power supply:         no
  updated:              Mon 27 Feb 2023 02:45:53 PM PST (20 seconds ago)
  has history:          yes
  has statistics:       yes
  mouse
    present:             yes
    rechargeable:        yes
    state:               discharging
    warning-level:       none
    battery-level:       normal
    percentage:          55% (should be ignored)
    icon-name:          'battery-low-symbolic'
```

The actual device name (path) changes often (the mouse is connected to a KVM and each time I switch between computers it gets a new one, for example now is hidpp_battery_15 but before it was hidpp_battery_11).

Anyway, an easy solution is to allow filter by model name, i.e. just find "MX Ergo Multi-Device Trackball" and use that device.

I took a look at the block source and upower module and it doesn't seem too complex. 

Is this already possible or indeed I should just implement it myself?

**Comment by GladOSkar** [comment]
I think this is not currently possible and would be a nice feature

**Comment by MaxVerevkin** [comment]
> I assume this is not possible with the sysfs driver?

There is `/sys/class/power_supply/BAT0/model_name` on my machine (which reads "Primary"), so maybe it is possible?

**Comment by GladOSkar** [comment]
```
cat /sys/class/power_supply/BAT1/model_name
Framewo
```
```
 upower --dump | grep model
  model:                Framewo
```
It does match. So i guess yes
