### ISSUE TITLE
DevOps: Pls create a workflow to deploy new Releases to Cargo

### ISSUE THREAD

**Issue by mindflay3r** [greshake/i3status-rust#1799]
Hi team. there's a bit of drift between what's going on in this repo vs what's going on in the Cargo crate [[x](https://crates.io/crates/i3status-rs)]

Want some help with that? I can make a Github workflow to deploy Releases, but you're going to need to add some things on your end

**Comment by GladOSkar** [comment]
@cfsmp3 i think that was your thing?
