### ISSUE TITLE
Pacman Block not updating package lists

### ISSUE THREAD

**Issue by greshake** [greshake/i3status-rust#18]
Seems like pacman -Sup isn't enough after all, we need to use the method I suggested earlier to @keeslinp:
Look at the guys from bumblebee-status: https://github.com/tobi-wan-kenobi/bumblebee-status/blob/master/bumblebee/modules/pacman.py

They use a bash script and fakeroot:
```
#!/usr/bin/bash

if ! type -P fakeroot >/dev/null; then
error 'Cannot find the fakeroot binary.'
exit 1
fi

if [[ -z $CHECKUPDATES_DB ]]; then
CHECKUPDATES_DB="${TMPDIR:-/tmp}/checkup-db-${USER}/"
fi

trap 'rm -f $CHECKUPDATES_DB/db.lck' INT TERM EXIT

DBPath="${DBPath:-/var/lib/pacman/}"
eval $(awk -F' *= *' '$1 ~ /DBPath/ { print $1 "=" $2 }' /etc/pacman.conf)

mkdir -p "$CHECKUPDATES_DB"
ln -s "${DBPath}/local" "$CHECKUPDATES_DB" &> /dev/null
fakeroot -- pacman -Sy --dbpath "$CHECKUPDATES_DB" --logfile /dev/null &> /dev/null
fakeroot pacman -Su -p --dbpath "$CHECKUPDATES_DB"

exit 0
```

**Comment by keeslinp** [comment]
Ah yeah, you're absolutely right. I'll make the switch :). Do you know of a good way to include the bash script? I'll do some research to see if it's possible to bundle it in somehow. Otherwise I guess I'll just have to convert it to a weird combo of rust/commands.

**Comment by keeslinp** [comment]
I've got it working, I just need to figure out all the of the error checking and validation that goes on in that bash file.
