### ISSUE TITLE
Disable Battery 'time to full' while charging

### ISSUE THREAD

**Issue by JulianOestreich90** [greshake/i3status-rust#1804]
When my Battery turns into charging state, it is still showing the time_to_full. How can i disable it in charging state?
Or is there a way to access a variable to determine if the battery is in charging or emptying state and show a string like "remaining" or "until charged" depending on that?

![image](https://user-images.githubusercontent.com/19915127/222169520-615b1609-0e1e-4988-848d-0337f604f6ef.png)

`upower -d ` output:
![image](https://user-images.githubusercontent.com/19915127/222169852-93d42d15-0b7f-45dd-ac8a-7cf21fbbbd54.png)

`i3status-rust/config.toml`:
![image](https://user-images.githubusercontent.com/19915127/222170183-0da0958f-539a-42c5-9b67-ef5aa3595cda.png)

**Comment by MaxVerevkin** [comment]
> How can i disable it in charging state?

Unfortunately, right now you can't. This would require us to split `format` into `charging_format` and `discharging_format`.

**Comment by MaxVerevkin** [comment]
implemented in 9f41778d
