### ISSUE TITLE
Battery: Incorrect metric to determine icons

### ISSUE THREAD

**Issue by cfsmp3** [greshake/i3status-rust#1809]
On the battery block, the icon is selected based on the battery capacity 

```
                      if status == BatteryStatus::Charging {
                            State::Good
                        } else if capacity <= config.critical {
                            State::Critical
                        } else if capacity <= config.warning {
                            State::Warning
                        } else if capacity <= config.info {
                            State::Info
                        } else if capacity > config.good {
                            State::Good
```

This seems incorrect - capacity is not charge. It's a number that starts at 100% and decreases with battery age (as per https://upower.freedesktop.org/docs/Device.html )

We probably want to use Percentage. And not always, specifically for some batteries upower says

```
  mouse
    present:             yes
    rechargeable:        yes
    state:               discharging
    warning-level:       none
    battery-level:       normal
    percentage:          55% (should be ignored)
    icon-name:          'battery-low-symbolic'
```

Where the "should be ignored" is the important part. It means that it's unreliable, and that we should either icon-name (convert as needed) or warning-level, which has 4 or 5 possible states.

**Comment by MaxVerevkin** [comment]
We do read percentage: https://github.com/greshake/i3status-rust/blob/2f0ab146aba2123370fe7a80702d1587ef22bf79/src/blocks/battery/upower.rs#L127

**Comment by cfsmp3** [comment]
> We do read percentage:
> 
> https://github.com/greshake/i3status-rust/blob/2f0ab146aba2123370fe7a80702d1587ef22bf79/src/blocks/battery/upower.rs#L127

Yes but is it used for the icon based on the code I referenced?

**Comment by MaxVerevkin** [comment]
Yes. The wording is a bit confusing though. And it is used since at least v0.10: https://github.com/greshake/i3status-rust/blob/ede8ac79b0095550f2f882469eea4524be66a778/src/blocks/battery.rs#L33-L34

**Comment by MaxVerevkin** [comment]
Did you actually experience incorrect icons?

**Comment by cfsmp3** [comment]
> Did you actually experience incorrect icons?

I don't know. The laptop is always charging so that one is always full.

The mouse however probably yes but I'm waiting for the battery to cross a threshold. In theory, the icon being based on percentage is incorrect which is why it explicitly says "should be ignored". 

For starters, it's been at 55% for some days :-)

**Comment by MaxVerevkin** [comment]
> `(should be ignored)`

Is this info available via dbus?

**Comment by MaxVerevkin** [comment]
@cfsmp3 can you share the `busctl introspect` of your mouse?

**Comment by cfsmp3** [comment]
> @cfsmp3 can you share the `busctl introspect` of your mouse?

```
✦ ❯ busctl introspect org.freedesktop.UPower /org/freedesktop/UPower/devices/battery_hidpp_battery_6
NAME                                TYPE      SIGNATURE RESULT/VALUE                     FLAGS
org.freedesktop.DBus.Introspectable interface -         -                                -
.Introspect                         method    -         s                                -
org.freedesktop.DBus.Peer           interface -         -                                -
.GetMachineId                       method    -         s                                -
.Ping                               method    -         -                                -
org.freedesktop.DBus.Properties     interface -         -                                -
.Get                                method    ss        v                                -
.GetAll                             method    s         a{sv}                            -
.Set                                method    ssv       -                                -
.PropertiesChanged                  signal    sa{sv}as  -                                -
org.freedesktop.UPower.Device       interface -         -                                -
.GetHistory                         method    suu       a(udu)                           -
.GetStatistics                      method    s         a(dd)                            -
.Refresh                            method    -         -                                -
.BatteryLevel                       property  u         6                                emits-change
.Capacity                           property  d         0                                emits-change
.ChargeCycles                       property  i         -1                               emits-change
.Energy                             property  d         0                                emits-change
.EnergyEmpty                        property  d         0                                emits-change
.EnergyFull                         property  d         0                                emits-change
.EnergyFullDesign                   property  d         0                                emits-change
.EnergyRate                         property  d         0                                emits-change
.HasHistory                         property  b         true                             emits-change
.HasStatistics                      property  b         true                             emits-change
.IconName                           property  s         "battery-low-symbolic"           emits-change
.IsPresent                          property  b         true                             emits-change
.IsRechargeable                     property  b         true                             emits-change
.Luminosity                         property  d         0                                emits-change
.Model                              property  s         "MX Ergo Multi-Device Trackball" emits-change
.NativePath                         property  s         "hidpp_battery_6"                emits-change
.Online                             property  b         false                            emits-change
.Percentage                         property  d         55                               emits-change
.PowerSupply                        property  b         false                            emits-change
.Serial                             property  s         "406f-3b-a5-54-8c"               emits-change
.State                              property  u         2                                emits-change
.Technology                         property  u         0                                emits-change
.Temperature                        property  d         0                                emits-change
.TimeToEmpty                        property  x         0                                emits-change
.TimeToFull                         property  x         0                                emits-change
.Type                               property  u         5                                emits-change
.UpdateTime                         property  t         1677921305                       emits-change
.Vendor                             property  s         ""                               emits-change
.Voltage                            property  d         0                                emits-change
.WarningLevel                       property  u         1                                emits-change
```

**Comment by cfsmp3** [comment]
This is interesting: https://gitlab.freedesktop.org/upower/upower/-/issues/85

**Comment by MaxVerevkin** [comment]
I guess `(should be ignored)` comes from the fact that `BatteryLevel` is not `1` (None).

**Comment by MaxVerevkin** [comment]
But I don't understand why `IconName` is `"battery-low-symbolic"` when `BatteryLevel` is `6` (Normal).

**Comment by cfsmp3** [comment]
> I guess `(should be ignored)` comes from the fact that `BatteryLevel` is not `1` (None).

That seems to be the case

https://gitlab.freedesktop.org/upower/upower/-/blob/master/libupower-glib/up-device.c#L375

**Comment by cfsmp3** [comment]
> But I don't understand why `IconName` is `"battery-low-symbolic"` when `BatteryLevel` is `6` (Normal).

https://gitlab.freedesktop.org/upower/upower/-/blob/master/src/up-daemon.c#L795

So normal is low, high is good.

We're not the only ones with confusing enums

**Comment by MaxVerevkin** [comment]
I still don't quite understand this issue and what #1810 solves. Some devices report "battery level" instead of exact percentages. Upower exposes the reported level via `BatteryLevel` property, but for backwards compatibility it estimates the percentage (I assume it does, didn't look into the code though). What can we do?

**Comment by cfsmp3** [comment]
> I still don't quite understand this issue and what #1810 solves. Some devices report "battery level" instead of exact percentages. Upower exposes the reported level via `BatteryLevel` property, but for backwards compatibility it estimates the percentage (I assume it does, didn't look into the code though). What can we do?

Well, they explicitly say "should be ignored". It doesn't say "approximate value" or anything like that. For what is worth it still says 55% on my trackball.

I'm trying to match our icon to their icon which is based on load (and I believe it's not something the user can configure with thresholds).

Maybe it's not worth the effort, I don't know. What I do know is that we have now it's not very useful to me.

**Comment by MaxVerevkin** [comment]
> For what is worth it still says 55% on my trackball.

I assume the `BatteryLevel` didn't change either? In that case it is a device issue.

> Well, they explicitly say "should be ignored". It doesn't say "approximate value" or anything like that

If you mean that we should ignore `Percentage` and use `BatteryLevel` instead, we can do that. In fact we do that for `sysfs`: https://github.com/greshake/i3status-rust/blob/8596e1be913b7e6cc70cf18c39d2dcc96d31cb1a/src/blocks/battery/sysfs.rs#L42-L53

> What I do know is that we have now it's not very useful to me

Since both `sysfs` and `upower` have a notion of "battery level", we can extend the code above to be configurable. I.e. 

```toml
[[block]]
block = "battery"
[[block.level_mapping]]
low = { state = "critical", percentage = 10 }
# and so on
```

This is just a draft, but you get the idea. What do you think?

**Comment by MaxVerevkin** [comment]
By the way, what is the value of your `/sys/class/power_supply/hidpp_battery_6/capacity_level`?

**Comment by cfsmp3** [comment]
> By the way, what is the value of your `/sys/class/power_supply/hidpp_battery_6/capacity_level`?

✦ ❯ cat /sys/class/power_supply/hidpp_battery_19/capacity_level
Normal

**Comment by cfsmp3** [comment]
> I assume the `BatteryLevel` didn't change either? In that case it is a device issue.

Correct. I'm monitoring the situation as it develops though :-) I want to see what's the next level down and if everything changes at the same time. If it does, then obviously no point in continuing this exercise.

> Since both `sysfs` and `upower` have a notion of "battery level", we can extend the code above to be configurable. I.e.

As long as we can reproduce the behavior of upower (i.e. show the same icons it does for a given charge), works for me.
Also, I don't know if its internal thresholds are per device (or even if it's the device itself reporting some battery level and battery max). 
Anyway I was trying to get it to match upower but if it's a lot of work or controversial I can live without it, the trackball requires charging every 3 weeks or so, I'm not a slave to its charge :-)

**Comment by cfsmp3** [comment]
Next state:

```
Device: /org/freedesktop/UPower/devices/battery_hidpp_battery_45
  native-path:          hidpp_battery_45
  model:                MX Ergo Multi-Device Trackball
  serial:               406f-3b-a5-54-8c
  power supply:         no
  updated:              Wed 15 Mar 2023 07:36:20 PM PDT (24 seconds ago)
  has history:          yes
  has statistics:       yes
  mouse
    present:             yes
    rechargeable:        yes
    state:               discharging
    warning-level:       low
    battery-level:       low
    percentage:          10% (should be ignored)
    icon-name:          'battery-caution-symbolic'
```

**Comment by cfsmp3** [comment]
When charging (at a distance, probably outside reception)

```
Device: /org/freedesktop/UPower/devices/battery_hidpp_battery_45
  native-path:          hidpp_battery_45
  model:                MX Ergo Multi-Device Trackball
  serial:               406f-3b-a5-54-8c
  power supply:         no
  updated:              Wed 15 Mar 2023 10:16:20 PM PDT (14 seconds ago)
  has history:          yes
  has statistics:       yes
  mouse
    present:             yes
    rechargeable:        yes
    state:               unknown
    warning-level:       none
    battery-level:       unknown
    percentage:          50% (should be ignored)
    icon-name:          'battery-missing-symbolic'
```

After charging
```

Device: /org/freedesktop/UPower/devices/battery_hidpp_battery_45
  native-path:          hidpp_battery_45
  model:                MX Ergo Multi-Device Trackball
  serial:               406f-3b-a5-54-8c
  power supply:         no
  updated:              Wed 15 Mar 2023 10:17:28 PM PDT (7 seconds ago)
  has history:          yes
  has statistics:       yes
  mouse
    present:             yes
    rechargeable:        yes
    state:               fully-charged
    warning-level:       none
    battery-level:       full
    percentage:          100% (should be ignored)
    icon-name:          'battery-full-charged-symbolic'
  History (charge):
    1678943830	100.000	fully-charged
    1678943829	50.000	discharging
```

**Comment by MaxVerevkin** [comment]
So, everything as expected?

**Comment by cfsmp3** [comment]
> So, everything as expected?

I'm not totally convinced (particularly with the thresholds and the different levels) but I'm not going to obsess over it.
Closing.
