### ISSUE TITLE
i3status-rs uses a file in the current directory by default instead of the fallbacks specified in the man page

### ISSUE THREAD

**Issue by hw0lff** [greshake/i3status-rust#1811]
### Initial problem with config.toml

The man page for the `CONFIGFILE` argument states the following:
```
CONFIGFILE
    Read the configuration from this file. Otherwise, we fall back on $XDG_CONFIG_HOME/i3status-rust/config.toml.
```
But i3status-rs does more than that.
1. It sets a [default path for the config file](https://github.com/greshake/i3status-rust/blob/master/src/main.rs#L67) parameter in the struct with the command line arguments.
2. Then it passes the path to the [`util::find_file` function](https://github.com/greshake/i3status-rust/blob/master/src/main.rs#L95)
2a. … which [checks in several locations](https://github.com/greshake/i3status-rust/blob/master/src/util.rs#L19-L55).

The default path and [the very first check in `util::find_file`](https://github.com/greshake/i3status-rust/blob/master/src/util.rs#L19-L21) resulted for me in the following problem:
When i3status-rs is started with my $HOME as its current working directory[^1], it uses the `config.toml` which just happens to be lying around in my home. This toml file does not even contain any keys that could be interpreted by i3status-rs. i3status-rs just accepts it and displays nothing.

I propose the following solutions to this problem:
1. Do not set a default value for the `config` parameter and only use fallback file name for the `$XDG_CONFIG_HOME` directory (e.g. `$XGD_CONFIG_HOME/i3status-rust/config.toml`).
2. Fully and correctly document the `util::find_file`-behavior in the man page.
3. Add debug logging to indicate which (config) file has failed to load and which has actually been loaded.

### Additional results of the `util::find_file`-behavior
While debugging I found out that the problem with the `util::find_file`-behavior from above applies for the theme and icons file paths, too.
The man pages states:
```
where <file> can be either a filename or a full path and will be checked in this order:
1. If full path given, then use it as is: /home/foo/custom_theme.toml
2. If filename given, e.g. “custom_theme.toml”, then first check $XDG_CONFIG_HOME/i3status-rust/themes
3. […]
```
Actually it does not check `$XDG_CONFIG_HOME/i3status-rust/themes` at first.
If <file> is not a full path (e.g. `foo-theme.toml`) then the current directory is checked first and only if that fails will the `$XDG_CONFIG_HOME/i3status-rust/themes` directory be checked.

#### Example
My shell is currently in `/tmp` and the following files exist:
```
/tmp/config.toml
/home/user/.config/i3status-rust/themes/foo-theme.toml
```

The `/tmp/config.toml` contains:
```toml
[theme]
theme = "foo-theme.toml"
```

Starting i3status-rs under strace with no arguments
```sh
$ strace i3status
```

… results in this strace output (shortened to highlight the important parts):
```
[…]
statx(AT_FDCWD, "foo-theme.toml", […]) = -1 ENOENT (No such file or directory)
statx(AT_FDCWD, "/home/user/.config/i3status-rust/themes/foo-theme.toml", […]) = 0
openat(AT_FDCWD, "/home/user/.config/i3status-rust/themes/foo-theme.toml", […]) = 9
[…]
```
Now if I create a `foo-theme.toml` in `/tmp` and restart the `strace i3status-rs`:
```
statx(AT_FDCWD, "foo-theme.toml", […]) = 0
openat(AT_FDCWD, "foo-theme.toml", […]) = 9
```

i3status-rs uses the `foo-theme.toml` file in its current directory.

[^1]: This is done most of the time by my window manager. The CWD is just inherited.

**Comment by MaxVerevkin** [comment]
Yes, the manpage is outdated (#1794).

I think it is reasonable to change

```rust
    if file.exists() {
        return Some(file);
    }
```

to 

```rust
    if file.is_absolute() && file.exists() {
        return Some(file);
    }
```

And this should be documented in the manpage and in `i3status-rs --help` (we need to find a way to automatically generate manpage from `--help` page, I think `clap` has some tools for that).
