### ISSUE TITLE
net block: display ssid only when on wifi

### ISSUE THREAD

**Issue by matthewarmand** [greshake/i3status-rust#1815]
This is maybe a bug but more likely just a formatting question that could maybe be better documented.

In setting up a `net` block, I'm trying to display the `ssid` when my laptop is connected to WiFi, but not when connected to Ethernet (because that doesn't seem to work or be valid).

I've tried a few things, including wrapping the variable in curly braces because that seems to work elsewhere (battery percentage and time for example), but so far I can only get it to work when on WiFi, but when on ethernet the block displays the "Failed to render full text" message.

Format is currently as follows:

`format = " $icon {$ssid} ^icon_net_down $speed_down.eng(prefix:K) ^icon_net_up $speed_up.eng(prefix:K) "`

Is there a standard way to display a variable if it exists or is applicable, and to ignore it otherwise? Is this a bug with `ssid`? Is there anything else I can do to help debug this behavior?

**Comment by MaxVerevkin** [comment]
> Is there a standard way to display a variable if it exists or is applicable, and to ignore it otherwise?

Yes, see [here](https://greshake.github.io/i3status-rust/i3status_rs/formatting/index.html#handling-missing-placeholders-and-incorrect-types).

You probably want

```toml
format = " $icon {$ssid |}^icon_net_down $speed_down.eng(prefix:K) ^icon_net_up $speed_up.eng(prefix:K) "
```

**Comment by matthewarmand** [comment]
Ah, yep that did it. Thanks for the docs pointer, hadn't found that before.

Thanks for the super quick response!
