### ISSUE TITLE
Native theme

### ISSUE THREAD

**Issue by xzfc** [greshake/i3status-rust#182]
In other words no theme at all.
Let i3bar itself choose the default colors and draw separator.

I.e. do not produce `color`, `background` values and use native i3bar separators instead of `"| "` blocks.

**Comment by lausek** [comment]
Doesn't [theme.overrides](https://github.com/greshake/i3status-rust/wiki/Theming-&-Icons#user-content-overwriting-themes-and-icon-sets) solve your problem?

**Comment by xzfc** [comment]
No. I can modify colors and separators using overrides, but I can't disable them at all.

----

The following config:
```
[[block]]
block = "cpu"

[[block]]
block = "load"

[[block]]
block = "time"
```
Produces the following output:
`[{"background":"#000000","color":"#a9a9a9","full_text":"| ","separator":false,"separator_block_width":0},{"background":"#000000","color":"#93a1a1","full_text":" CPU 23% ","separator":false,"separator_block_width":0},{"background":"#000000","color":"#a9a9a9","full_text":"| ","separator":false,"separator_block_width":0},{"background":"#000000","color":"#93A1A1","full_text":" LOAD 0.26 ","separator":false,"separator_block_width":0},{"background":"#000000","color":"#a9a9a9","full_text":"| ","separator":false,"separator_block_width":0},{"background":"#000000","color":"#93a1a1","full_text":" Fri 04/05 00:19 ","name":"2f921bd715b74529945f341478714217","separator":false,"separator_block_width":0}]`

But what I want is:
`[{"full_text":" CPU 23% "},{"full_text":" LOAD 0.26 "},{"full_text":" Fri 04/05 00:19 ","name":"2f921bd715b74529945f341478714217"}]`

**Comment by atheriel** [comment]
This is currently a limitation of how the implementation works, so it's not simple to change by any measure. But I am sympathetic to the general aim, so I will leave it open. What would need to change is composition of fields on the block object we are serializing to JSON.

**Comment by nvllsvm** [comment]
fwiw - passing a value of `null` a given color is valid results in the desired "native" behavior.

**Comment by ammgws** [comment]
@nvllsvm Does that result in i3 using default values for those colours or just have no colour at all?

**Comment by GladOSkar** [comment]
Afaik it's "default" which means transparent background (= bar color) and white text.

**Comment by ammgws** [comment]
In that case we can't use that since my interpretation of the OP is that they want it to use the colours specified in their i3bar config

**Comment by GladOSkar** [comment]
Yes this is definitely something that would require a bunch of work. Since it's quite an old issue - is there still demand for this?

@xzfc @nvllsvm

**Comment by nvllsvm** [comment]
Yes - this was a blocker for me to use i3status-rust.

**Comment by GladOSkar** [comment]
I just had another look at the code and while it's gonna be nasty it's probably manageable. I'll see what i can do tomorrow.

**Comment by ammgws** [comment]
Dealing with the theme config might be a pain unless the current theme info is available at the place where we print the blocks. Then we can just special case it.

**Comment by GladOSkar** [comment]
See #938 for an implementation suggestion. @nvllsvm @xzfc testing and feedback would be appreciated

**Comment by nvllsvm** [comment]
Works great - thanks!
