### ISSUE TITLE
Versioned online docs

### ISSUE THREAD

**Issue by MaxVerevkin** [greshake/i3status-rust#1821]
After switching to `rustdoc` we no longer have versioned docs hosted (they can be build locally).

We can turn `i3status-rs` crate into lib+bin crate and let docs.rs host the versioned docs for us.

There is an open issue about turning this into a library + a binary (#1328), and this can be the first step. The lib crate doesn't have to be configurable in the beginning, (it can just provide a `run()` function), since the goal is to host docs. Later, if there will be interest, it can be made more configurable.

**Comment by bim9262** [comment]
@MaxVerevkin I just messed around with generating docs with feature flag notes: https://github.com/bim9262/calibright/commit/f3cea7bff3c59c8701fe3071cdc00c1b90e55fdf

This might be helpful for maildir/notmuch/pulseaudio

You can test it locally with `RUSTDOCFLAGS="--cfg docsrs" cargo +nightly doc --no-deps --all-features`

**Comment by MaxVerevkin** [comment]
Nice idea! We can enable this for our gh-pages docs too.

**Comment by MaxVerevkin** [comment]
lib+bin split done in #1822. Now we just need to (perhaps automatically) publish the crate. cc @cfsmp3

**Comment by cfsmp3** [comment]
> lib+bin split done in #1822. Now we just need to (perhaps automatically) publish the crate. cc @cfsmp3

Remind me how I am involved in this? :-)

**Comment by MaxVerevkin** [comment]
> > lib+bin split done in #1822. Now we just need to (perhaps automatically) publish the crate. cc @cfsmp3
> 
> Remind me how I am involved in this? :-)

You own the crate :eyes:

**Comment by cfsmp3** [comment]
> > > lib+bin split done in #1822. Now we just need to (perhaps automatically) publish the crate. cc @cfsmp3
> > 
> > 
> > Remind me how I am involved in this? :-)
> 
> You own the crate eyes

Ah :-) I don't want to be a bottleneck and much less not being able to die because the crate would be unmaintained. I'll happily add you as an owner, what's your crates.io username?

**Comment by MaxVerevkin** [comment]
@cfsmp3 https://crates.io/users/MaxVerevkin

**Comment by MaxVerevkin** [comment]
> @MaxVerevkin I just messed around with generating docs with feature flag notes: [bim9262/calibright@f3cea7b](https://github.com/bim9262/calibright/commit/f3cea7bff3c59c8701fe3071cdc00c1b90e55fdf)
> 
> This might be helpful for maildir/notmuch/pulseaudio
> 
> You can test it locally with `RUSTDOCFLAGS="--cfg docsrs" cargo +nightly doc --no-deps --all-features`

Done in 2b01d38
