### ISSUE TITLE
The custom_dbus block uses invalid default format strings

### ISSUE THREAD

**Issue by frazerk** [greshake/i3status-rust#1825]
The `custom_dbus` block specifies the following default format strings:
- `{ $icon|}{ $text.str(pango:true)|} `
- `{ $icon|} $short_text.str(pango:true) | `

The `pango:true` argument is not recognized, and this causes the block to fail at runtime with "Incorrect format template", regardless of whether a correct format string is supplied.

The following block config produces the following block:
```toml
[[block]]
block = "custom_dbus"
path = "/test"
```

![image](https://user-images.githubusercontent.com/16587706/224391963-3d2cc50c-2afb-493d-bc02-7602dd101eda.png)

**Comment by MaxVerevkin** [comment]
Thanks for reporting! Should be fixed in c441d33
