### ISSUE TITLE
block uptime default icon

### ISSUE THREAD

**Issue by euri10** [greshake/i3status-rust#1828]
I think there might be a "missing" glyph, here's the relevant part of my config:

```
[icons]
icons = "awesome6"
[[block]]
block = "uptime"
```

![20230314_0933_173x52_1678782784](https://user-images.githubusercontent.com/1104190/224942200-0c182273-4c0b-4a15-854b-29b170f5d831.png)

with awesome4 I have the default icon, not with awesome5 or 6
maybe I have not those fonts installed, but all other icons are ok

edit: just checked https://fontawesome.com/v6/icons/clock?s=regular&f=classic and uptime should be f017 imho

**Comment by MaxVerevkin** [comment]
f2f2 is a stopwatch and is part of both v5 and v6 - https://fontawesome.com/v6/icons/stopwatch?s=solid&f=classic

**Comment by euri10** [comment]
sorry for the noise, my fc-list revealed I use 4 version !
