### ISSUE TITLE
Brightness: Emoji disambiguity

### ISSUE THREAD

**Issue by GladOSkar** [greshake/i3status-rust#183]
Hi there, long time fan of the project.

My distribution recently introduced color emoji, which is very cool.

This led to a discovery though: The brightness-emoji (moon?) i3status-rs uses is actually used the other way around:

![image](https://user-images.githubusercontent.com/9497832/39660923-5e73f9a6-5049-11e8-8776-cbc22ea38861.png)

![image](https://user-images.githubusercontent.com/9497832/39660925-72d9c6aa-5049-11e8-8109-b619c9c09e81.png)

I know it would not make sense to invert this for everyone since it does make sense in black and white, but maybe an option to invert would be good?

Thank you!

(I'm learning rust currently, so if nobody wants to do it i may)

**Comment by matthiaskrgr** [comment]
For the record, in black and white mode it looks like this:

![brightness2](https://user-images.githubusercontent.com/476013/39665995-e52958c6-509c-11e8-9f22-7268e647aee4.png)
![brightness1](https://user-images.githubusercontent.com/476013/39665996-e54713f2-509c-11e8-800e-8a2c17040a5e.png)

**Comment by atheriel** [comment]
You can actually do this already! The `icon.overrides` section in your configuration allows you to set whatever icons you'd like. In this case, set `"backlight_empty"`, `"backlight_partial1"`, `"backlight_partial2"`, `"backlight_partial3"`, and `"backlight_full"` to the appropriate characters for your font.

**Comment by GladOSkar** [comment]
Cool! Thank you :)

**Comment by atheriel** [comment]
Glad to be of help.

**Comment by Kabouik** [comment]
> For the record, in black and white mode it looks like this:
> 
> ![brightness2](https://user-images.githubusercontent.com/476013/39665995-e52958c6-509c-11e8-9f22-7268e647aee4.png) ![brightness1](https://user-images.githubusercontent.com/476013/39665996-e54713f2-509c-11e8-800e-8a2c17040a5e.png)

I'm sorry for asking that question 4 years later, but how do you enable black and white mode? I'd really like do use that for that block.

**Comment by GladOSkar** [comment]
I think you have to choose a font or font system that doesn't include color emoji, but I'm not sure. Sometimes you can also just uninstall your distro's color emoji package. But that's something you'll have to look up for your distro yourself, it's nothing `i3status-rust` can control
