### ISSUE TITLE
Some keywords seems to not work anymore in example

### ISSUE THREAD

**Issue by gustafbstrom** [greshake/i3status-rust#1831]
See https://github.com/greshake/i3status-rust/blob/a4b46d7a113cacfeba64898ebc6398e31e87c914/examples/config.toml#L7

Keywords such as `alias` and `unit` seems to not be parsed properly anymore since upgrade to 0.30. Could someone point me to what happened to these keywords? Thank you.

**Comment by MaxVerevkin** [comment]
Up-to-date example: https://github.com/greshake/i3status-rust/blob/master/examples/config.toml

Some options were removed because you can use `format` to customize the block.
