### ISSUE TITLE
Sample config broken

### ISSUE THREAD

**Issue by brianmay** [greshake/i3status-rust#1834]
The sample config at https://github.com/greshake/i3status-rust/blob/master/examples/config.toml generates errors and generally seems to be broken.

**Comment by bim9262** [comment]
What version of i3status-rs are you using? What are the errors?
That config will only work with v0.30.0+

**Comment by brianmay** [comment]
The latest version in nix. Which is 0.22.

Version 0.30??? There doesn't appear to be any tags for that release in git...

**Comment by bim9262** [comment]
Does the new version fix #1835 too?

**Comment by brianmay** [comment]
Arrgh. Got the config working with what I thought was the latest version. Now it doesn't work with the latest version. Time to redo it again I guess... :-)

**Comment by brianmay** [comment]
Hmmm. Sample config has a reference to `$icon_swap` that i3status-rs version 0.30.4 seems to object to...

**Comment by brianmay** [comment]
Sorry, that was my fault. Got the memory format in the time block somehow by mistake. Obviously that is not going to work.
