### ISSUE TITLE
available disk space reported is wrong

### ISSUE THREAD

**Issue by brianmay** [greshake/i3status-rust#1835]
For example:

```
[[block]]
alert = 10
block = "disk_space"
format = "/home {free}/{total}"
interval = 5
path = "/home"
warning = 20
```

Says "/home 24GB/350GB", but df says:

```
$ df -h /home
Filesystem                Size  Used Avail Use% Mounted on
/dev/mapper/canidae-home  350G  326G  8.6G  98% /home
```

**Comment by brianmay** [comment]
I am going to close this for now because I was on old version. Will reopen if the problem occurs once I upgrade.

**Comment by brianmay** [comment]
Hmmm. That filesystem is now correct. But / is slightly out:

```
[[block]]
alert = 10
alert_unit = "GB"
block = "disk_space"
format = " $icon root: $available.eng(w:2) "
info_type = "available"
interval = 5
path = "/"
warning = 20
```

Reports 86GB free. But df reports:

```
$ df -h /
Filesystem                Size  Used Avail Use% Mounted on
/dev/mapper/canidae-root  216G  125G   81G  61% /
```

Maybe there is a good reason for it being 5GB out. But seems wrong to me.

**Comment by ammgws** [comment]
Can you post the output of `df -Th /` too?

**Comment by ammgws** [comment]
I think `df` reports in Gibibytes

`$available.eng(w:2,prefix:Gi)` should make it the same or closer depending on rounding

**Comment by brianmay** [comment]
```
Filesystem               Type  Size  Used Avail Use% Mounted on
/dev/mapper/canidae-root ext4  216G  125G   81G  61% /
```

Hmmm. Just noticed df has a `-H` option too:

>        -h, --human-readable
>              print sizes in powers of 1024 (e.g., 1023M)

>       -H, --si
>              print sizes in powers of 1000 (e.g., 1.1G)

```
Filesystem               Type  Size  Used Avail Use% Mounted on
/dev/mapper/canidae-root ext4  232G  134G   87G  61% /
```

That looks pretty close to the 86GB that is reported. Assuming the difference is due to different rounding used.

Thanks for your help. Closing.
