### ISSUE TITLE
[Compile Error] Error with `dbus`

### ISSUE THREAD

**Issue by Pk13055** [greshake/i3status-rust#184]
![image](https://user-images.githubusercontent.com/13479308/39784858-0aab163a-532b-11e8-9769-6ca9df0d771c.png)
There seems to be an issue with `dbus` but I have double checked everything.
System:
Linux pk-pc 4.15.0-20-generic #21-Ubuntu SMP Tue Apr 24 06:16:15 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
OS: Ubuntu 18.04 LTS 
i3: i3 version 4.14.1 (2017-09-24) © 2009 Michael Stapelberg and contributors

**Comment by greshake** [comment]
Is dbus correctly installed? The dbus package is a requirement to build the Rust package for it. As the error says: No package dbus-1 found

**Comment by greshake** [comment]
The package is probably called libdbus. You will have to check that with your distro

**Comment by atheriel** [comment]
Closed for inactivity.
