### ISSUE TITLE
backlight: Add missing_format

### ISSUE THREAD

**Issue by shazow** [greshake/i3status-rust#1842]
I noticed the `backlight` module lacks a `missing_format` option.

I use the same config on my laptop (where there is backlight control) and on my desktop (where there is not), and I'm getting a "Failed to read default device file" error block on my desktop.

Would be great if the ubiquitous `missing_format` option existed in this module too.

(If nobody beats me to it, I might have some time to add this if there's not a particular reason why it wouldn't work here)

**Comment by MaxVerevkin** [comment]
This is covered by #1802

**Comment by shazow** [comment]
Ah perfect, thank you! Feel free to close this issue (otherwise I'll leave it to autoclose).

**Comment by ammgws** [comment]
You can use "if_command" for this too
