### ISSUE TITLE
Documentation formatting issue in battery.rs

### ISSUE THREAD

**Issue by nishanthjayram** [greshake/i3status-rust#1844]
There is a minor formatting issue in `src/blocks/battery.rs`. Apologies if this is the wrong place to submit this issue.

Looking at the [ArchWiki page](https://man.archlinux.org/man/community/i3status-rust/i3status-rs.1.en#battery), it looks like the configuration table is missing some newlines characters, which is causing the `values` column entries to overflow from `interval` onwards. My understanding is that this documentation is generated from the comments within this codebase.

Thus, my guess is that any entries where the default value is an integer should have that default value enclosed in double quotes (e.g.,  \`"60"\` instead of \`60\`), and that this should fix the issue.

**Comment by MaxVerevkin** [comment]
Thanks for reporting! There were a few extra (or missing) \`, fixed in b54138dab2a1730b9eb7c7a8e04e947febab9d36.
