### ISSUE TITLE
Breaking changes?

### ISSUE THREAD

**Issue by SathOkh** [greshake/i3status-rust#1849]
After recent changes, the config file stopped working (many parsing errors instead of displaying the bar). How many breaking changes have occurred in the last 1-2 releases (I'm not sure which version I had before)?

```
$ i3status-rs --version
i3status-rs 0.30.6
```
![image](https://user-images.githubusercontent.com/2511493/229340483-ca65b3f3-6f62-4528-91e0-e849e76ac6d3.png)
After removing `alias`:
![image](https://user-images.githubusercontent.com/2511493/229340510-7a00ebdf-7d40-4948-8655-13137f5006cf.png)
after removing whole disc block:
![image](https://user-images.githubusercontent.com/2511493/229340535-ed9a425d-2b57-4c82-a107-3e7ecc1ea0e1.png)

etc

Applying example config (https://github.com/greshake/i3status-rust/blob/master/examples/config.toml) makes it work again, but of course get rid of all of my changes.

**Comment by ammgws** [comment]
You were probably on v0.22

Breaking changes were in v0.30: https://github.com/greshake/i3status-rust/blob/master/NEWS.md#i3status-rust-0300
