### ISSUE TITLE
Equal numbers (eng.) can appear both with a decimal separator and w/o: 10 / 10.0

### ISSUE THREAD

**Issue by dorsiflexion** [greshake/i3status-rust#1857]
**Steps to reproduce**:
Use net block config (see below) and watch the net block for some time.

**Expected behavior**:
10 will always be shown as 10.

**Actual Behavior**:
10 is sometimes displayed as 10 and sometimes as 10.0.

**Additional Info**:
It is not wrong per se but it is unexpected and weird to look at. It gets annoying if you "allocate" 3 characters for a number (i. e. width  3 and pad with spaces or `.eng(w:3)`) which is enough in every single case, as far as i observed, except for this one number – 10.0. If it happens and 10.0 is displayed, the entire bar left of it is moved one character to the left, which distracts a lot, because this movement is much more salient than just white numbers changing in one place.

The alternative right now is wasting one character for every number where this can happen which is not great either.

I guess it might has something to do with rounding: 10.0–10.49 is 10 and 9.995–9.9999999… is 10.0?
Or maybe it's something else and 10.0 is just 10.0 and ≥10.1 is 10

**Config (net block)**:
```
[[block]]
block = "net"
device = "enp5s0"
format = " ^icon_net_down $speed_down.eng(prefix:K, w:3) ^icon_net_up $speed_up.eng(prefix:K, w:3) "
interval = 5
```

**Pics or it didn't happen**:
![10](https://user-images.githubusercontent.com/52240714/230784955-e1762ce6-9d25-4456-a412-a0e4fd812cdc.png)
![10.0](https://user-images.githubusercontent.com/52240714/230784962-09311007-f4cd-4d05-8531-900ea68d43a1.png)
Both numbers appear on both sides, I just don't have a screenshot of both on the same side…

**Comment by MaxVerevkin** [comment]
@dorsiflexion this should be fixed in #1858, can you test it?

**Comment by dorsiflexion** [comment]
I've now been testing it for maybe 3 hours and have not yet seen the bar move. If I see it move I know this bug just occured and I most likely wouldn't miss that – which means it seems fixed so far.

But l'd say let me test (i. e. use) for another day or two.

**Comment by dorsiflexion** [comment]
Yep, I haven't seen it again so far. Seems fixed to me. Thanks a lot!

**Comment by dorsiflexion** [comment]
I don't think this is globally fixed. I just saw `1000KB`, when there's also `1.0MB`. I was too slow to screenshot the first one, I'm 100% sure though.
The config for that part is: `format = " ^icon_net_down $speed_down.eng(prefix:K, w:3) ^icon_net_up $speed_up.eng(prefix:K, w:3) "`
