### ISSUE TITLE
Support Mullvad in vpn widget

### ISSUE THREAD

**Issue by totikom** [greshake/i3status-rust#1867]
Right now vpn widget supports only Nordvpn, but it should be trivial to adapt it's code to Mullvad.
I've started working on it and hopefully create a PR today or tomorrow.

**Comment by totikom** [comment]
I've found that  cb994547 seems to break vpn widget entirely (at least for disconnected state). I'll try to fix it for both Mullvad (WIP) and NordVPN drivers.

**Comment by MaxVerevkin** [comment]
@totikom thanks for reporting! If you find a way to fix it, please submit the fix in a separate PR from the feature one.
