### ISSUE TITLE
The codepoints for material-nf will have to move before nerd-fonts 3.0.0

### ISSUE THREAD

**Issue by tkapias** [greshake/i3status-rust#1869]
Nerd-Fonts 2.3.3 fixed a lot of things.

[In the latest release](https://github.com/ryanoasis/nerd-fonts/releases/tag/v2.3.3) they announced that Material Design Icons were moved to new codepoints and that the old ones would be delete when 3.0.0 will be released.

Please check the old codepoints that you were using in material-nf and prepare for it.

**Comment by MaxVerevkin** [comment]
We are ready :) #1728

**Comment by tkapias** [comment]
Nice.

Sorry too, I searched in the Issues a little but not the Pull Requests.
