### ISSUE TITLE
net: 802.11ac frequency should be displayed as 5Ghz

### ISSUE THREAD

**Issue by farwayer** [greshake/i3status-rust#1879]
In previous versions it was correct but now it is showed as `6GHz`

**Comment by MaxVerevkin** [comment]
What is the output of `iw dev <your device> link | grep freq ` on your system?

**Comment by farwayer** [comment]
5540

According to wiki (know it's not the best source):
- 5 GHz channels are from 5030 to 5990 (802.11a/h/j/n/ac/ax)
- 6 GHz are from 5945 to 7125 (802.11ax and 802.11be)

So the is small overlap at the end of 5Ghz range. it's better to use RxMode/TxMode to find the frequency range or show frequency unrounded

**Comment by farwayer** [comment]
also note that I wrote the entire range of channels, not the center frequencies

**Comment by MaxVerevkin** [comment]
> In previous versions it was correct

I assume it was `5.5`, which you can have by setting the width to 3: `$frequency.eng(w:3)`.

**Comment by MaxVerevkin** [comment]
>     * 5 GHz channels are from 5030 to 5990 (802.11a/h/j/n/ac/ax)
> 
>     * 6 GHz are from 5945 to 7125 (802.11ax and 802.11be)

Hm, I suppose we can add a new placeholder which maps the frequency from actual value to this "conventional name", such as `2.4`, `5`, `6`, etc.

**Comment by farwayer** [comment]
Hm... maybe frequency should be displayed fully by default and 'conventional name' added. Good idea. It is much more useful to know the operating mode, (2.4, 5 or 6) than a certain frequency.

Anyway `$frequency.eng(w:1)` resolved my issue for now thanks!
