### ISSUE TITLE
weather block: invalid type map expected variant identifier

### ISSUE THREAD

**Issue by ubuntupunk** [greshake/i3status-rust#1887]
not sure why this is happening, I have the following config:

```
[[block]]
block = "weather"
format = " $icon $weather ($location) $temp, $wind m/s $direction "
[[block.service]]
name = "openweathermap"
api_key = "mykey"
city_id = "3369157"
place = "Cape Town"
coordinates = ["18.4241", -33,92584]
units = "metric"
```

version: i3status-rs
v0.31.0

**Comment by MaxVerevkin** [comment]
> `[[block.service]]`

This should be `[block.service]`. The error message is pretty weird though.

> `coordinates = ["18.4241", -33,92584]`

`coordinates = ["18.4241", "-33,92584"]`
