### ISSUE TITLE
Improved non-rotating music block

### ISSUE THREAD

**Issue by jgbyrne** [greshake/i3status-rust#189]
I have written a new music block (`static_music`) that is very similar to the existing `music` except it uses `TextWidget` not `RotatingTextWidget` and is a little smarter in how it trims text to fit within a max width. More precisely - it will trim from both the artist and the title in proportion to their lengths, to try and show the most information possible. Is this something you are interested in pulling into the main repository?

To avoid too much code duplication between the original and my new music block, I have moved much of the D-Bus interface logic into a backend module (`mbackend`) and some of the other common logic into a `utils` module.

My fork: https://github.com/jgbyrne/i3status-rust/tree/master/src/blocks/music

**Comment by atheriel** [comment]
I believe @greshake is the authority on this block, but FWIW I'm a fan of this idea.

**Comment by ammgws** [comment]
@jgbyrne Thanks for your work on this. I ended up implementing it into the current music block with a config option.
