### ISSUE TITLE
feat: retry policy on `external_ip` block

### ISSUE THREAD

**Issue by hgigas** [greshake/i3status-rust#1891]
https://github.com/greshake/i3status-rust/blob/49499c1ca624228c4b9e88b62b36cd0fa5e2dce5/src/blocks/external_ip.rs#L230

In my case the message "Failed to request current location" appears longer than the ip. Maybe basic 3 retries...

**Comment by MaxVerevkin** [comment]
I  don't understand this issue. It already retries after `error_interval`.

**Comment by hgigas** [comment]
Actual:
1. Fetch ip fails
2. Display error message
3. After `error_interval` seconds retry

Suggestion:
1. Fetch ip fails
2. Don't display anything and retry, for example, 3 times
3. If fails display error message
4. After `error_interval` seconds retry

With unstable internet connections there are occasional failures, then error message displays, but if you retry surely it will work

**Comment by MaxVerevkin** [comment]
I see. Perhaps the same effect cat be achieved by increasing the request timeout? Currently it is hardcoded to 10 seconds: https://github.com/greshake/i3status-rust/blob/00a08b5ebdaeb322392a62baf39ec2648762d405/src/lib.rs#L39

**Comment by hgigas** [comment]
Usually the request is lost no matter how long you wait.

Another solution could be allow `error_interval` less than `1`... I will set `0.3` in my case.

**Comment by hgigas** [comment]
It is difficult to test because it depends on the state of the network that I cannot control but it seems that the behavior has improved. I have tried it for a few minutes

**Comment by hgigas** [comment]
Thank you a lot :-)
