### ISSUE TITLE
Icon theme not being applied on status try icons, also issue with right click menu on tray icons

### ISSUE THREAD

**Issue by Hikandy** [greshake/i3status-rust#1894]
For some reason the icon theme papirus isn't getting applied on the status tray icons, where if I try waybar its getting applied and also its getting applied system wide. 

When I right click on the icons to get the menu for example nm-applet, it just outright doesn't appear at all. And when i try another application say telegram, it appears but right in the middle of the screen as a floating window.

I'm currently using sway (latest stable release) and archlinux with kernel 6.3

**Comment by MaxVerevkin** [comment]
The tray is controlled by `swaybar`, not `i3status-rust`. There is nothing we can do.
