### ISSUE TITLE
net block no connection

### ISSUE THREAD

**Issue by okhsunrog** [greshake/i3status-rust#1895]
Net block shows no connection when IVPN connection is active. (shows "x" sign)

my config is 
[[block]]
block = "net"
device = "^[ewu]"
format = " $icon {$ssid $signal_strength| $device} "

it's supposed to show connections when I have wifi (wlan0), ethernet (eth1 or eth0) or usb tethering from android device (usb0). works as I expect it to work, breaks every time I enable IVPN connection. it shows my connection back when I disable ivpn

**Comment by MaxVerevkin** [comment]
Probably related: #1866 #1846

**Comment by MaxVerevkin** [comment]
Please test #1903
