### ISSUE TITLE
Unable to override the colors for battery block

### ISSUE THREAD

**Issue by Hikandy** [greshake/i3status-rust#1897]
This is my current config

[[block]]
block = "battery"
format = " $icon $percentage $power $time "
[block.color_overrides]
idle_fg = "#000000"
idle_bg = "#abcdef"

OR EVEN IN THIS

[[block]]
block = "battery"
format = " $icon $percentage $power $time "
[[block.color_overrides]]
idle_fg = "#000000"
idle_bg = "#abcdef"

but when I do this, the block just doesn't work and gives me this
![screenshot_2023-05-09-210512](https://github.com/greshake/i3status-rust/assets/86432041/c972f6a8-d3c8-4635-8539-e7840d5df649)

Not sure what I'm doing wrong

**Comment by bim9262** [comment]
Try `[block.theme_overrides]` instead of `[block.color_overrides]`.

**Comment by MaxVerevkin** [comment]
By the way, you can click on the block to see full error message.
