### ISSUE TITLE
Icon "volume" not found.

### ISSUE THREAD

**Issue by ubuntupunk** [greshake/i3status-rust#1899]
Error in sound, Icon "volume" not found. 
I have tried material and awesome4
```
[icons]
icons = "material"

...

[[block]]
block = "sound"
[[block.click]]
button = "left"
cmd = "pavucontrol"
```

```
fc-list | grep material

/usr/share/fonts/woff/material-design-iconfont/MaterialIcons-Regulat.woff2: Material Icons:style=Regular

```

**Comment by GladOSkar** [comment]
Did you run `install.sh` after updating? Check `~/.local/share/i3status-rust/icons/material.toml` if there's a `volume` key in there. If not, it's outdated.

**Comment by ubuntupunk** [comment]
If I check `~/.local/share/i3status-rust/icons/material.toml `

```
volume_empty = "\ue04e" # volume_mute
volume_full = "\ue050" # volume_up
volume_half = "\ue04d" # volume_down
volume_muted = "\ue04f" # volume_off
microphone_full = "\ue029" # mic
microphone_half = "\ue029" # mic
microphone_empty = "\ue02a" # mic_none
microphone_muted = "\ue02b" # mic_off
```
Not sure where install.sh file is, I installed via cargo?

**Comment by MaxVerevkin** [comment]
Unfortunately, `cargo` is unable to install runtime files such as icons and themes. These files are left there from some previous installation. You need to clone the repo and either copy-paste the files from `fils/` to `~/.local/share/i3stauts-rust/` or run `install.sh`. We should probably state in the README that installation via `cargo` is unsupported.
