### ISSUE TITLE
sound: support wildcards in mappings

### ISSUE THREAD

**Issue by ptrcnull** [greshake/i3status-rust#1902]
some of audio devices have very long names with serial numbers in them - for example, `alsa_output.usb-Apple__Inc._USB-C_to_3.5mm_Headphone_Jack_Adapter_DWH2041023VL1MQAH-00.analog-stereo`

in other cases, there's multiple HDMI outputs and the actual one changes with every reboot, with the device name being `alsa_output.pci-0000_01_00.1.hdmi-stereo-extra<number>`

with a wildcard, user could specify one name for all usb audio devices or all HDMI outputs

**Comment by bim9262** [comment]
Wildcards are already supported for example `alsa_output\.pci-0000_01_00\.1\.hdmi-stereo-extra.*` should work. This feature has been enabled by default since `0.31.0`

**Comment by ptrcnull** [comment]
oh, i didn't realize this got added recently, sorry :sweat_smile:
