### ISSUE TITLE
Weird symbols in the bar

### ISSUE THREAD

**Issue by Konglomneshued** [greshake/i3status-rust#1913]
### I'm not sure what these are:
![image](https://github.com/greshake/i3status-rust/assets/94726665/2aa0df68-ba13-4cc5-822b-587c18030103)

### My config:
```
[theme]
theme = "plain"

[icons]
icons = "none"

[[block]]
block = "cpu"

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = " $icon root: $available.eng(w:2) "

[[block]]
block = "memory"
format = " $icon $mem_total_used_percents.eng(w:2) "
format_alt = " $icon_swap $swap_used_percents.eng(w:2) "

[[block]]
block = "sound"
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "time"
interval = 5
format = " $timestamp.datetime(f:'%a %d/%m %R') "
```

**Comment by bim9262** [comment]
Those are icons, but it looks like you aren't using a font with the correct symbols. Check your i3/sway config for the font you're using.

**Comment by MaxVerevkin** [comment]
> [icons]
> icons = "none"

Did you reload your bar?

**Comment by Konglomneshued** [comment]
> > [icons]
> > icons = "none"
> 
> Did you reload your bar?

Oh, thank you.  I was trying to reload i3.

**Comment by MaxVerevkin** [comment]
By the way, you can reload `i3status-rs` in-place with SIGUSR2 signal.
