### ISSUE TITLE
Player doesn't update properly when dash present in player name

### ISSUE THREAD

**Issue by DucNg** [greshake/i3status-rust#1914]
Player is only detected when restarting i3status-rs and the playing item isn't updated when player name contains a dash in it's name. Could it be link to the `busctl --user list | grep "org.mpris.MediaPlayer2." | cut -d '  ' -f1` not working properly in this case?

Steps to reproduce:

1. Add a music block
2. Play something on a player containing a dash in it's mpris name (eg: https://github.com/DucNg/fip-player)
3. Player doesn't appear in the list (even when right clicking)
4. Restart i3status-rs
5. Player detected and working
6. Quit player
7. Restart player
8. Playing item isn't properly updated

Sorry I don't code in Rust so it's hard to debug by myself, can someone take a look?

**Comment by MaxVerevkin** [comment]
This is a bug in one of our dependencies, which results in unexpected behavior when `-` is used is a bus name. Reported in https://github.com/dbus2/zbus/issues/382.
