### ISSUE TITLE
music block not picking up player/interface

### ISSUE THREAD

**Issue by asegarra** [greshake/i3status-rust#1920]
Just updated to the latest 0.31.8 and music block is no longer picking up songs when using the 'player' or 'interface_name_excludes' config options. e.g. Setting player to ["spotify"] and it is not picking up the current song unless I reload the bar then it's picked up until I close spotify and reopen it.

**Comment by MaxVerevkin** [comment]
Was 0.31.7 working as expected?

**Comment by badmoves** [comment]
Yes it was.

**Comment by asegarra** [comment]
Yes it was.

**Comment by MaxVerevkin** [comment]
Can you share the output of

```
busctl --user monitor --match "type='signal',interface='org.freedesktop.DBus',member='NameOwnerChanged',arg0namespace='org.mpris.MediaPlayer2'"
```
when you start spotify?

**Comment by asegarra** [comment]
I just noticed, it's picking up spotify on a fresh load of the bar, but if I close and reopen spotify it's not picked up. 

Here is the output when I open spotify:

```
Monitoring bus message stream.
‣ Type=signal  Endian=l  Flags=1  Version=1 Cookie=18  Timestamp="Fri 2023-06-30 19:37:29.502773 UTC"
  Sender=org.freedesktop.DBus  Path=/org/freedesktop/DBus  Interface=org.freedesktop.DBus  Member=NameOwnerChanged
  MESSAGE "sss" {
          STRING "org.mpris.MediaPlayer2.spotify";
          STRING "";
          STRING ":1.207";
  };
```

**Comment by MaxVerevkin** [comment]
Does it happen only with spotify?

> it's picking up spotify on a fresh load of the bar, but if I close and reopen spotify it's not picked up

This sounds so similar to #1914...

**Comment by asegarra** [comment]
Can't explain it but I just upgraded again to retest this with another player and lo and behold I can't reproduce it anymore. Don't know what's different now because I even rebooted before and consistently had the behavior I described.  And yes, it sounds pretty much like 1914 except without the dashes in the name. My apologies about this.

**Comment by asegarra** [comment]
ah sorry this is happening to me again, same thing as originally described and in https://github.com/greshake/i3status-rust/issues/1914. Happens all mpris2 players I tried. I'm using the player option so it only picks up specific inputs. If I don't use this option and just let it pick up everything there's no issue.

**Comment by asegarra** [comment]
ah sorry this is happening to me again, same thing as originally described and in https://github.com/greshake/i3status-rust/issues/1914. Happens all mpris2 players I tried. I'm using the player option so it only picks up specific inputs. If I don't use this option and just let it pick up everything there's no issue.

what I have found is that I can reproduce this only after I open chromium(xwayland) and have it take a mpris entry by playing something e.g. youtube. After that if I close spotify it won't pick up again unless I reboot the bar. It continues to behave this way until i close chromium.

**Comment by MaxVerevkin** [comment]
Dose the value of `$avail` not change too?

**Comment by MaxVerevkin** [comment]
> chromium(xwayland) 

is the xwayland part relevant? Does it not happen when you enable native Wayland support?

**Comment by asegarra** [comment]
Sorry it's not relevant, switched chromium to wayland to make sure, and to add to what I said I found I have to have firefox, chromium and spotify open along with the player option for this to happen. 

$avail goes from 1 to not rendering the block if I have nothing open or it's picking up the player.

**Comment by asegarra** [comment]
Tried a couple of other players and looks like it happens as long as I have 3 of them in mpris.

**Comment by MaxVerevkin** [comment]
Hm, I'll add a few debug log prints later

**Comment by MaxVerevkin** [comment]
Can you run `RUST_LOG=music=debug cargo r >/dev/null` on latest master and share the output?

**Comment by asegarra** [comment]
```
    Running `target/debug/i3status-rs`
[2023-07-04T17:35:49Z DEBUG music] available players:
[2023-07-04T17:36:10Z DEBUG music] available players:
[2023-07-04T17:36:10Z DEBUG music] available players:
[2023-07-04T17:36:24Z DEBUG music] new player org.mpris.MediaPlayer2.spotify owned by :1.38
```

**Comment by MaxVerevkin** [comment]
That's it? Normally a log sequence should end with a list of available players.

**Comment by asegarra** [comment]
yeah thats with the players option in the music block with only spotify.

**Comment by MaxVerevkin** [comment]
Okay, I added a few more prints, can you try now?

**Comment by asegarra** [comment]
```
   Finished dev [unoptimized + debuginfo] target(s) in 0.06s
     Running `target/debug/i3status-rs`
[2023-07-04T21:05:49Z DEBUG music] available players: []
[2023-07-04T21:05:54Z DEBUG music] new player org.mpris.MediaPlayer2.spotify owned by :1.217
[2023-07-04T21:05:54Z DEBUG music] creating Player for org.mpris.MediaPlayer2.spotify
[2023-07-04T21:05:54Z DEBUG music] querying player info
```

**Comment by MaxVerevkin** [comment]
Huh, so it gets stuck at `querying player info`. Since it started to happen with v0.31.8, which basically just updated `zbus`, our dbus dependency, it looks like an upstream bug. I'll try to look into it later.

**Comment by asegarra** [comment]
thanks, i appreciate it. Let me know if you need anything else from me.

**Comment by MaxVerevkin** [comment]
Can you try it now?

**Comment by asegarra** [comment]
I'm away from my main machine running Arch but have a similar setup on my laptop running Fedora 38 and I can't reproduce it with the latest git, but I've found it also works fine without the latest commit. It seems whatever the issue is it's specific to Arch. I'll get back to my computer in a couple of days and I can retest there if still required.

**Comment by asegarra** [comment]
Hi, sorry about the late update. Not sure what update fixed this, but I can no longer forcibly reproduce this anymore. So I believe this is fixed! Thanks!.
