### ISSUE TITLE
crates release permissions

### ISSUE THREAD

**Issue by bim9262** [greshake/i3status-rust#1927]
@cfsmp3  @MaxVerevkin

Can we add the other github maintainers as owners of the crate so we can cut new versions too?
I'm not sure if it's something that we purposefully decided to do or not.

**Comment by MaxVerevkin** [comment]
Each release I'm thinking about creating a new crates-io account and setting up github actions to publish releases automatically. Haven't done it yet... In the mean time, I've sent you an invitation.
