### ISSUE TITLE
mpdris2 and i3status-rust

### ISSUE THREAD

**Issue by maximyurevich** [greshake/i3status-rust#1929]
After login mpdris2 interface not updatable without mod + r in i3

**Comment by bim9262** [comment]
Can you tell us more about what your setup is?
Are you using i3 or sway? How are you launching i3/sway (from a tty or a login manager)? Which init system are you using? There's a lot of variables that could cause this.

**Comment by maximyurevich** [comment]
> Can you tell us more about what your setup is? Are you using i3 or sway? How are you launching i3/sway (from a tty or a login manager)? Which init system are you using? There's a lot of variables that could cause this.

update to mpdris2-rs solve this issue
