### ISSUE TITLE
error with reading memory usage

### ISSUE THREAD

**Issue by ahumblescientist** [greshake/i3status-rust#1930]
here is what i3status-rust outputs:
![2023-08-05_23-32](https://github.com/greshake/i3status-rust/assets/138120547/b09ae97e-c507-484a-aa61-e0163666182e)

sudo ps_mem ouput:
![2023-08-05_23-33ps](https://github.com/greshake/i3status-rust/assets/138120547/98f5e270-7979-4803-9158-0dc72596849f)
(sorry for bad english)

**Comment by ammgws** [comment]
Hmm, that percentage seems pretty sus. Thought we had fixed memory calcs a while back.

Do you use ZFS?

**Comment by ahumblescientist** [comment]
> Hmm, that percentage seems pretty sus. Thought we had fixed memory calcs a while back.
> 
> Do you use ZFS?

nope

**Comment by bim9262** [comment]
@ahumblescientist does the value in your status bar match the output of `free -g`?
On my computer `free -g` and `ps_mem` report different amounts of used memory. I'm pretty sure `ps_mem` just doesn't count everything.

**Comment by ahumblescientist** [comment]
> @ahumblescientist does the value in your status bar match the output of `free -g`? On my computer `free -g` and `ps_mem` report different amounts of used memory. I'm pretty sure `ps_mem` just doesn't count everything.

no, it says used 2GB, unlike i3status-rs which says that the used is 12GB

**Comment by ammgws** [comment]
What does htop show?

**Comment by bim9262** [comment]
Can you share the format you are using for the memory block?

**Comment by bim9262** [comment]
So you are showing how much is available, not how much is being used

**Comment by ahumblescientist** [comment]
@bim9262 
this is the dumbest i have ever felt to be honest, i rlly didnt notice that

**Comment by bim9262** [comment]
Haha no worries, glad we got it sorted out

**Comment by ammgws** [comment]
Possible cause of confusion could be that the percentage shown in the default format string is the total used %.

Perhaps should change

`$mem_avail.eng(prefix:M)/$mem_total.eng(prefix:M)($mem_total_used_percents.eng(w:2))`

to

`$mem_avail.eng(prefix:M)/$mem_total.eng(prefix:M)($mem_avail_percents.eng(w:2))`

?

**Comment by bim9262** [comment]
I think that `used/total(used%)` would be a better default. :man_shrugging:

**Comment by ahumblescientist** [comment]
@ammgws 
yes the avail percent works, but the used dosent work, it outputs 97% used even tho im only using 3GB of 16GB, i was intending to use the avail from the start anyway

**Comment by qrockz** [comment]
I think my **total mem usage output** is also **wrong** calculated:
```
free -g
               total        used        free      shared  buff/cache   available
Mem:              31          11           4           0          15          18
Swap:              1           0           1
```

![window4](https://github.com/greshake/i3status-rust/assets/56853194/45ecd061-b01d-484e-a920-1707680a31cc)
![window](https://github.com/greshake/i3status-rust/assets/56853194/fb02c78e-8565-47e6-a5c8-40ec53b15ec8)
![htop](https://github.com/greshake/i3status-rust/assets/56853194/265e3b0a-dd65-4313-955e-90bc5a29d030)

```
[[block]]
block = "memory"
format = " $icon $mem_total_used_percents.eng(w:2) "
format_alt = " $icon_swap $swap_used_percents.eng(w:2) "
```

```
cat /etc/os-release
NAME="Linux Mint"
VERSION="21.1 (Vera)"
ID=linuxmint
ID_LIKE="ubuntu debian"
PRETTY_NAME="Linux Mint 21.1"
VERSION_ID="21.1"
HOME_URL="https://www.linuxmint.com/"
SUPPORT_URL="https://forums.linuxmint.com/"
BUG_REPORT_URL="http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/"
PRIVACY_POLICY_URL="https://www.linuxmint.com/"
VERSION_CODENAME=vera
UBUNTU_CODENAME=jammy
```
```
~/.cargo/bin/i3status-rs -V
i3status-rs 0.32.2 (commit 69b38430 2023-10-18)
```
