### ISSUE TITLE
pacman block's click to update doesn't work

### ISSUE THREAD

**Issue by c02y** [greshake/i3status-rust#1945]
```
[[block.click]]
button = "right"
update = true
```
of pacman block doesn't work, I see no network activity, and the number of pacman block is not updated.

But if I reload i3status bar using shortcut such as `bindsym $mod+Ctrl+Shift+r exec --no-startup-id pkill -USR2 i3status-rs`, the number of pacman block will be updated as expected. I have noticed this issue in multiple recent i3status-rust versions.

The whole pacman block's config:
```
[[block]]
block = "pacman"
# sync db weekly
interval = 604800
format = " $icon$pacman.eng(w:1)/$aur.eng(w:1)"
format_up_to_date = ""
aur_command = "yaru -Qua"
[[block.click]]
button = "right"
update = true

```

Currently:
i3-wm 4.22-4
i3status-rust 0.32.1-1

**Comment by MaxVerevkin** [comment]
Should be fixed!
