### ISSUE TITLE
packages: add `ignore_updates_regex`

### ISSUE THREAD

**Issue by MaxVerevkin** [greshake/i3status-rust#1958]
We already have `warning_updates_regex` and `critical_updates_regex`. A new option can be added to filter the list of outdated packages.

- [x] Apt (#1967)
- [ ] Dnf
- [ ] Pacman

**Comment by bim9262** [comment]
For pacman wouldn't you just want to ignore the package in pacman.conf? What would be the benefit of ignoring it in the status bar, but actually updating it when you go to update your system?

I imagine other package managers have similar configs that allow packages to be ignored.

**Comment by MaxVerevkin** [comment]
I have some `-git` packages installed from `chaotic-aur` which are updated multiple times a day. I do want to keep them up-to-date, but in context of status bar, these packages generate a lot of noise.

**Comment by zheltikov** [comment]
Hello @MaxVerevkin !
I've opened a pull request to add this `ignore_updates_regex` option to blocks/apt: #1967
Please have a look at it :)
