### ISSUE TITLE
Alternative calendar support in time block

### ISSUE THREAD

**Issue by HKalbasi** [greshake/i3status-rust#1966]
There are many calendars other than the Gregorian calendar that are used in the world. For example, the ecmascript and web platform support [19 of them](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/Locale/getCalendars#supported_calendar_types). Would you accept a PR that add support for these calendars in the time block (or a new block) using the [icu4x](https://github.com/unicode-org/icu4x) crate?

**Comment by MaxVerevkin** [comment]
> Would you accept a PR that add support for these calendars in the time block

Yes :)
