### ISSUE TITLE
memory usage isn't calculated correctly

### ISSUE THREAD

**Issue by qrockz** [greshake/i3status-rust#1971]
I think my **total mem usage output** is **wrong** calculated:
```
free -g
               total        used        free      shared  buff/cache   available
Mem:              31          11           4           0          15          18
Swap:              1           0           1
```
![htop](https://github.com/greshake/i3status-rust/assets/56853194/265e3b0a-dd65-4313-955e-90bc5a29d030)

![window4](https://github.com/greshake/i3status-rust/assets/56853194/45ecd061-b01d-484e-a920-1707680a31cc)
![window](https://github.com/greshake/i3status-rust/assets/56853194/fb02c78e-8565-47e6-a5c8-40ec53b15ec8)

```
[[block]]
block = "memory"
format = " $icon $mem_total_used_percents.eng(w:2) "
format_alt = " $icon_swap $swap_used_percents.eng(w:2) "
```

```
cat /etc/os-release
NAME="Linux Mint"
VERSION="21.1 (Vera)"
ID=linuxmint
ID_LIKE="ubuntu debian"
PRETTY_NAME="Linux Mint 21.1"
VERSION_ID="21.1"
HOME_URL="https://www.linuxmint.com/"
SUPPORT_URL="https://forums.linuxmint.com/"
BUG_REPORT_URL="http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/"
PRIVACY_POLICY_URL="https://www.linuxmint.com/"
VERSION_CODENAME=vera
UBUNTU_CODENAME=jammy
```
```
~/.cargo/bin/i3status-rs -V
i3status-rs 0.32.2 (commit 69b38430 2023-10-18)
```

**Comment by bim9262** [comment]
You probably want to use `$mem_used_percents`, not `$mem_total_used_percents`

| Placeholder               | Value |
|--------|--------|
| `mem_used`                | Memory used, excluding cached memory and buffers; same as htop's green bar| 
| `mem_total_used`          | mem_total - mem_free|
| `mem_total`               | Total physical ram available|
| `mem_free`                | Free memory not yet used by the kernel or userspace (in general you should use mem_avail)|
