### ISSUE TITLE
Add a way to trigger refresh of the bar

### ISSUE THREAD

**Issue by quite** [greshake/i3status-rust#1979]
It would be nice if there was some way to trigger an immediate refresh of the bar (or block). Imagine a custom block which shows something, with a click action that changes the state of that something. Refreshing the bar or block immediately would be nice, while still keeping the same default refresh interval (seconds).

**Comment by MaxVerevkin** [comment]
There already is :) You can update the entire bar with `SIGUSR1` signal (mentioned in the readme). Also, each block has a `signal = n` property (mentioned [here](https://docs.rs/i3status-rs/latest/i3status_rs/blocks/index.html)) which lets you update a specific block using `SIGRTMIN+n`.

> Imagine a custom block which shows something, with a click action that changes the state of that something

In this specific case, you can set `update = true` in your click handler to update the block when clicking. If the output depends on the changed state, also set `sync = true`:

```toml
[[block.click]]
button = "left"
update = true
sync = true
cmd = "..."
```

**Comment by quite** [comment]
Oh, thanks a lot. I found it in the README now. Sorry for the noise.
