### ISSUE TITLE
Feature request: Weather data using NOAA service

### ISSUE THREAD

**Issue by psibi** [greshake/i3status-rust#1980]
While using XMobar and later cnx status bar, I found weather plugin using NOAA very helpful. Unfortunately, it's missing in i3status-rust, which I currently want to use as I'm transitioning to Wayland.

Relevant code/doc of this weather plugin in these projects:

- https://codeberg.org/xmobar/xmobar/src/branch/master/src/Xmobar/Plugins/Monitors/Weather.hs#L167
- https://docs.rs/cnx-contrib/latest/cnx_contrib/widgets/weather/struct.Weather.html (I authored it for cnx)

The advantage compared to the existing weather plugins in i3status-rust is that you don't need to configure NOAA with an API key. All you need to do is figure out is station id and you are good to go.

If there is no objections, I can implement the same for this project. There is already a parser for it which I have written for cnx status bar: https://docs.rs/weathernoaa/latest/weathernoaa/weather/index.html (But it would need some changes to reuse reqwest client etc).

**Comment by MaxVerevkin** [comment]
> The advantage compared to the existing weather plugins in i3status-rust is that you don't need to configure NOAA with an API key.

FYI, you don't need an API key for met.no

**Comment by psibi** [comment]
Thanks, using met.no solves it for me.
