### ISSUE TITLE
Tea timer done_cmd not run when using i3's "mode hide"

### ISSUE THREAD

**Issue by harfqaf** [greshake/i3status-rust#1996]
If bar is hidden using "mode hide", the tea_timer `done_cmd` doesn't run immediately when the timer ends. It only runs after I hold Mod4 to display the bar.

`
i3status-rs 0.32.3 (commit 93c1face 2024-02-07)`

**Comment by MaxVerevkin** [comment]
This is i3bar suspending the process for power saving. Try running i3status-rs with `--never-stop` flag.
