### ISSUE TITLE
docs.rs build fails

### ISSUE THREAD

**Issue by MaxVerevkin** [greshake/i3status-rust#2004]
See https://docs.rs/crate/i3status-rs/latest and https://docs.rs/crate/i3status-rs/0.33.0/builds/1132023

**Comment by bim9262** [comment]
Looks like pipewire has the same problem. See: https://docs.rs/crate/pipewire/0.8.0 and https://docs.rs/crate/pipewire/0.8.0/builds/1117588
Looks like dependencies can be added to the docs building process per: https://docs.rs/about/builds#missing-dependencies

**Comment by MaxVerevkin** [comment]
We can also not enable the pipewire feature when building docs, this would not affect the documentation, right? That would probably we way simpler.

**Comment by bim9262** [comment]
I think that only the blocks that are feature gated would be effected. So the privacy block wouldn't be altered by removing the pipewire feature.
