### ISSUE TITLE
Theme no longer being applied in swaybar after update

### ISSUE THREAD

**Issue by analyticmind** [greshake/i3status-rust#2011]
OS: Arch Linux 6.7.6-arch1-1
DE: Swayfx 0.3.2

Updated Arch today, and on reboot I noticed that the status section of Swaybar was themed differently from the rest of the bar. It should be semi-transparent with blur, but instead has a black background with the wrong separator symbol. Changing the separator symbol in Sway's config does nothing: the vertical lines do not change. Every other configuration of the bar (font, colors, height, etc.) works fine. Uninstalled and re-installed i3status-rs but no change. Reverted back to Py3status, and the correct theming was restored, which leads me to think it's an issue with i3status-rs. Any idea on what may be causing this?

![20240225_10h17m59s_grim](https://github.com/greshake/i3status-rust/assets/65921732/f0adf017-7e37-44e4-852c-2c27a3291458)

**Comment by MaxVerevkin** [comment]
Share your `i3status-rs` version and config.

**Comment by analyticmind** [comment]
Sure thing.

i3status-rs version: 0.33.0

i3status-rs config:

```
[icons]

[[block]]
block = "music"
format =" {$play $combo.str(max_w:25) |} "
player = "cmus"

[[block]]
block = "keyboard_layout"
driver= "sway"
sway_kb_identifier = "3141:28694:SONiX_USB_DEVICE_Keyboard"
[block.mappings]
"English (US)" = "us"
"Spanish (N/A)" = "es"

[[block]]
block = "sound"
format = " $icon {$volume.eng(hide_unit:true) |}"
show_volume_when_muted = true
[block.icons_overrides]
volume = "󰵪 "
volume_muted = " 󱎘 "

[[block]]
block = "net"
format = " $icon $speed_down"
[block.icons_overrides]
net_wired = "󰈀 "

[[block]]
block = "time"
interval = 5
format = " $timestamp.datetime(f:'%a, %b %-d  %-I:%M %p') "

[[block]]
block = "custom"
format = " $text.pango-str() "
command = "echo '{\"text\": \"\"}'"
json = true
```

**Comment by MaxVerevkin** [comment]
Ah, this is because  #1992 was fixed recently. You should set the theme to whichever theme you like. Like

```toml
[theme]
theme = "native"
```

**Comment by analyticmind** [comment]
Yup! That did the trick! So simple. Thanks!
