### ISSUE TITLE
Wrong icons in sound block

### ISSUE THREAD

**Issue by Ergus** [greshake/i3status-rust#2015]
Hi: 
I have been using the sounds block with this very simple config:

```
[[block]]
block = "sound"
step_width = 5
headphones_indicator = true
merge_with_next = true
#format = " $icon $output_name{ $volume|}"
[[block.click]]
button = "left"
cmd = "alacritty -e pulsemixer"

[[block]]
block = "sound"
step_width = 5
device_kind = "source"
```
But the "source" icons is wrong, it looks like a luggage: 

![image](https://github.com/greshake/i3status-rust/assets/6975176/916d26a4-6b44-446e-9966-9d9ec0c2b08c)

But also when I connect the headphone I don't get any result from `headphones_indicator = true`.

**Comment by bim9262** [comment]
Which icons have are have you set in your i3status-rs config? What font are you using in your i3/sway config for the bar?

**Comment by Ergus** [comment]
> Which icons have are have you set in your i3status-rs config? What font are you using in your i3/sway config for the bar?

Hi:

Very thanks for the quick reply

```
[theme]
theme = "plain"
[theme.overrides]
idle_fg = "#ffffff"

[icons]
icons = "awesome6"
```

and 

```
font pango:DejaVu Sans Mono, FontAwesome 9
```

**Comment by bim9262** [comment]
Are you sure that that's the name of the FontAwesome font and not something like `Font Awesome 6 Free`

Check with:
```shell
fc-list | grep -i awesome
```

**Comment by Ergus** [comment]
> Are you sure that that's the name of the FontAwesome font and not something like `Font Awesome 6 Free`
> 
> Check with:
> 
> ```shell
> fc-list | grep -i awesome
> ```

It looks like the issue is that I have two fonts in my system: `FontAwesome 6 Free` and `FontAwesome 6 Brands` and somehow `i3status-rust` was using the second one.

**Comment by bim9262** [comment]
Glad you got it sorted out then!
