### ISSUE TITLE
huge number of pacman packages to update shown in bar instead of 0

### ISSUE THREAD

**Issue by bluehood** [greshake/i3status-rust#202]
Screenshot:
![image](https://user-images.githubusercontent.com/10999034/40890880-1e09d520-677d-11e8-8008-a3e614319e42.png)

**Comment by atheriel** [comment]
This should be fixed as of #192. Are you using a recent version?

**Comment by bluehood** [comment]
Indeed updating fixes the issue. Thank you for the quick reply and sorry for the noise!
