### ISSUE TITLE
.Xresources color definition import?

### ISSUE THREAD

**Issue by jkorinth** [greshake/i3status-rust#2029]
If it isn't possible yet, I think it would be great to be able to use `.Xresources` color definitions [like i3 does](https://i3wm.org/docs/userguide.html#xresources). Otherwise I'd appreciated being pointed in the right direction! :-)

**Comment by MaxVerevkin** [comment]
See https://github.com/greshake/i3status-rust/issues/304#issuecomment-439988257.

**Comment by jkorinth** [comment]
I'm not sure #304 was suggesting the same thing; I meant simple support for hex rgb definitions in `~/.Xresources`. Please have a look at #2044, this is what I'm using atm.
