### ISSUE TITLE
Music block only shows music icon

### ISSUE THREAD

**Issue by ZJaume** [greshake/i3status-rust#204]
Music block does not display the marquee or play icon with any player when music is playing. I have tried with vlc, mpd, mpc, ncmpcpp and rhythmbox commands but never shown. I'm using i3status-rs with sway.
```
[theme]
name = "slick"
[theme.overrides]
idle_bg = "#303030"
idle_fg = "#C6C6C6"
info_bg = "#A83334"
info_fg = "#C6C6C6"
good_fg = "#C6C6C6"
warning_fg = "#C6C6C6"
critical_fg = "#C6C6C6"
[icons]
name = "awesome"

[[block]]
block = "music"
player = "vlc"
marquee = true
max_width = 20
buttons = ["play"]

[[block]]
block = "disk_space"
path = "/"
alias = "root"
info_type = "available"
unit = "GB"
interval = 60
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m} {5m}"

[[block]]
block = "net"
device = "wlp4s0"
ssid = true
interval = 3

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 60
format = "%d-%m-%y %R"
```

**Comment by devnoname120** [comment]
Note that this is likely a regression since it worked in b16a2c2b5b137f538f0992cd5553c83955257a3a.

Someone should do a `git bissect` to find out exactly which commit broke it.

**Comment by devnoname120** [comment]
There seems to be the same issue for the battery block:
![image](https://user-images.githubusercontent.com/2824100/41509188-8e914cd2-7250-11e8-91f3-605a2af63b65.png)

```
[[block]]
block = "battery"
interval = 1
show = "both"
```

**Comment by atheriel** [comment]
@devnoname120 That's intended, and only occurs when the battery is fully charged.

**Comment by nakulj** [comment]
I can still reproduce this.

> Someone should do a `git bisect` to find out exactly which commit broke it.

@devnoname120 for me it looked like b13e5214b54c6c1934e71b48b37f9fdbf8237404.

**Comment by devasmith** [comment]
I have this issue running i3status-rs version 0.13.1 with sway on Fedora 31. 
I've tried using both settings below with no result. 
```
[[block]]
block = "music"
buttons = ["play", "next"]` and 

[[block]]
block = "music"
player = "spotify"                                                                                                
buttons = ["play", "next"]
```

**Comment by atheriel** [comment]
@devasmith This is due to #563 and has been fixed in master.

**Comment by devasmith** [comment]
> @devasmith This is due to #563 and has been fixed in master.

Thank you! It works again after I installed from master branch.

**Comment by jkaiser-ioki** [comment]
when can we expect a release with this fix?

**Comment by ammgws** [comment]
It will probably be a while especially with this whole Corona thing going on. There's really only one active maintainer. I tried contacting the repo owner to get added as an additional maintainer last month but haven't heard anything yet.

**Comment by ammgws** [comment]
@atheriel I just found that email and replied to it. Sorry about not checking it sooner.

**Comment by jkaiser-ioki** [comment]
@atheriel @ammgws Thanks for the update, I've switched to the git master version for now, so don't feel pressured under the current circumstances. It's a really cool status line, btw, so kudos :-)
