### ISSUE TITLE
keyboard_layout span colors

### ISSUE THREAD

**Issue by nnovikov** [greshake/i3status-rust#2055]
Hello!
Is it possible to use span colors in keyboard_layout mapping? 
Like this:
```
[[block]]
block = "keyboard_layout"
driver = "kbddbus"
format = " $layout "
[block.mappings]
"Russian (N/A)" = "<span color='#131313'>ru</span>"
"English (US)" = "en"
```
In current i3status-rs tags escaped and passed to status bar as text.

**Comment by MaxVerevkin** [comment]
Can you try `format = " $layout.pango-str() "`?

**Comment by nnovikov** [comment]
It's works! Thanks.
