### ISSUE TITLE
Replace starter separator?

### ISSUE THREAD

**Issue by CarterSnich** [greshake/i3status-rust#2066]
Is there no way to replace starter separator? Although, there's a way for the ending separator.

**Comment by bim9262** [comment]
That's correct, there isn't a way to do that currently.

**Comment by bhorsujal** [comment]
I would like to work on this issue.
Can I get some head start, as I am new to this project?

**Comment by bim9262** [comment]
Take a look at where `end_separator` is used: https://github.com/search?q=repo%3Agreshake%2Fi3status-rust%20end_separator&type=code. All of those files will need to be updated to add a `start_separator`

**Comment by siddarth2810** [comment]
hii, I was just wondering whether `prev_last_bg` which gets changed in the loop could cause any issue while adding the start separator. 

![screenshot-20241013-121115Z-all](https://github.com/user-attachments/assets/1b303f7f-b6fa-4308-9355-cf2f849ce14a)
