### ISSUE TITLE
custom block: support text formatting

### ISSUE THREAD

**Issue by scampi** [greshake/i3status-rust#207]
It doesn't seem possible to render [colored text](http://tldp.org/HOWTO/Bash-Prompt-HOWTO/x329.html) coming from a custom block.
I tried but I get something like ![2018-06-20-122505_101x38_scrot](https://user-images.githubusercontent.com/795879/41653010-1748b39a-7485-11e8-8671-9ab913a98cdc.png).

**Comment by atheriel** [comment]
I'm pretty sure that i3 does not implement terminal escape sequences in its bar. To be sure that I understand correctly, are you asking that we parse these sequences an turn them into colour commands?

**Comment by scampi** [comment]
The use case would be to allow to set the colour of some part of the text, in order to better distinguish the different sections.
If setting a colour cannot be done, maybe being able to set some text in bold/italic/... would be sufficient.

If that is something that people would like to have, I'd be willing to propose a PR ;o)

**Comment by scampi** [comment]
@atheriel in https://github.com/enkore/i3pystatus you can have colored pieces of text so my original request should be possible :)

![2018-06-22-114824_185x43_scrot](https://user-images.githubusercontent.com/795879/41770424-6fb5e17c-7612-11e8-8971-9aa2a86195db.png)

**Comment by atheriel** [comment]
OK, so it's not possible under the [i3bar protocol](https://i3wm.org/docs/i3bar-protocol.html) to set the colour of individual slices of text, which I think is what you were originally getting at.

However, you *can* set the `color` field for whole blocks, which is what's going on with `i3pystatus` in your screenshot. I've wanted to make this possible for a long time (along with allowing for customization of other fields directly, such as border and background colour). But if you take a look at how things are currently implemented, that would be difficult without adding support on a block-by-block basis.

If you are interested in implementing parts of this stuff I would be happy to help.

**Comment by scampi** [comment]
You can use the `markup` parameter, and when set to `pango` you can [format](https://developer.gnome.org/pango/stable/PangoMarkupFormat.html) the text as you see fit.

For example, below is a screenshot of the example from the pango page that I prefixed to `full_text` content in `src/widgets/text.rs`:

![2018-06-24-220625_279x30_scrot](https://user-images.githubusercontent.com/795879/41823147-1a88d82c-77fb-11e8-9ec7-4977ddbd5450.png)

Sure I can help! Please open an issue describing what you think should be done first ;o)

**Comment by atheriel** [comment]
Whoops, I had never realized that was possible. I do think you could make a case for a `markup = true` configuration parameter for custom blocks.

**Comment by scampi** [comment]
Ok i'll try to propose something for that.

> But if you take a look at how things are currently implemented, that would be difficult without adding support on a block-by-block basis.

This felt like you had some larger work in mind, but adding the markup option narrows it down :)

**Comment by ammgws** [comment]
I believe this was solved by https://github.com/greshake/i3status-rust/pull/346
