### ISSUE TITLE
Fonts not recognized

### ISSUE THREAD

**Issue by bezze** [greshake/i3status-rust#209]
I've installed ttf-font-awesome-4 from the AUR yet my bar looks weird. It seems like the arrow thingies between blocks are not being recongnized properly.

![2018-06-25-140944_1360x768_scrot](https://user-images.githubusercontent.com/13110990/41865332-1ace19ae-7883-11e8-88ac-6c863a92762c.png)

Am I doing something wrong? Any clues?

**Comment by atheriel** [comment]
See if some of the discussion/suggestions in #130 work for you.

**Comment by yaymukund** [comment]
I experience the same issue on sway, version 0.9. I can't post a screenshot bc i don't have swaygrab working yet (xD), but it looks just like bezze's -- no separators, and weird glyphs around (in my case) the battery bar. It's possibly a bad interaction between the time block and the block before it.

**Comment by yaymukund** [comment]
![screenshot-2018-06-28-09-06-38](https://user-images.githubusercontent.com/590450/42022204-942d46ca-7ab4-11e8-9d73-515759a224d4.png)

Solved it by installing powerline. Apparently, it is a strict dependency rather than being optional.

**Comment by droslean** [comment]
Same issue here, 
Installing powerline doesn't seem to solve the problem.

**Comment by bezze** [comment]
Hey, just wanted to let you know. I suspect this is not awesome-font related nor i3status-rust related. I think this has something to do with utf-8 at a system level. If I enter the symbols manually using their [codes](http://astronautweb.co/snippet/font-awesome/) I can see every Awesome symbol. Furthermore, the problematic symbols are from the U+E000 to U+E0FF series, particularly the U+E0B2. Yet some unicode symbols appear correctly, for example, the U+AC00 to U+ACFF. Here's a sample.

![2018-06-28-184823_1360x768_scrot](https://user-images.githubusercontent.com/13110990/42062483-1227cccc-7b04-11e8-8826-40fbb5e3955a.png)

Please confirm if this is your case. My problem seems to be distro related (Arch Linux), so I'll seek help over there. If anyone has any suggestions I'm all ears.

**Comment by yaymukund** [comment]
@bezze It's very possible I have my terminal setup incorrectly, but *none* of those symbols work for me in terminal. I'm running, oh `termite v13` on arch with `ttf-font-awesome-4 4.7.0-5`, `powerline-common 2.6-1`, and `powerline-fonts 2.6-1`.

**Comment by droslean** [comment]
After installing powerline-fonts, just refreshing i3 is not working. Reboot is required.
After reboot, everything worked fine. :)

**Comment by bezze** [comment]
Ok, this was fixed by @droslean suggestion. Installing **powerline-fonts** and rebooting did the trick.

note: I actually had powerline-common and powerline packages installed, but not the fonts one. All of them are in the Arch Linux community repo. Is this package a dependency I missed?

btw, HUGE thanks guys
