### ISSUE TITLE
Allow for themes and icons to be defined in a file

### ISSUE THREAD

**Issue by svmnotn** [greshake/i3status-rust#21]
This way we can avoid having to recompile every single time we want to test color or icon changes.
Changing the themes in a file seems more useful than the icons, but the code shouldn't be too different

**Comment by greshake** [comment]
Alright, hit me with a pull request. I'm busy for the next week, but 'll help you review the PR..

**Comment by greshake** [comment]
Fixed in https://github.com/greshake/i3status-rust/pull/22
