### ISSUE TITLE
Optional blocks/discard errors

### ISSUE THREAD

**Issue by HugoBelotDeloro** [greshake/i3status-rust#2112]
Hello, I have an external AMD GPU, which means I plug it to my laptop while at home.  
When plugged, the module works perfectly fine, the GPU is properly detected.
When I am on the move however, there is no attached GPU, and thus the bar displays an error.  
What I would like is to simply hide the block automatically when there is an error, or maybe at least display an info block like "no GPU".  

I am a very new user to I3status-rust, but I can imagine adding a common property to all blocks like `optional = true` which would make the block discard errors without reporting them and simply not display.  
Maybe you could push it a bit further and allow for example `optional = "net"` to specify dependencies, so that a block like weather or IP that relies on external services simply disappears when there is no access instead of reporting errors.

**Comment by MaxVerevkin** [comment]
> What I would like is to simply hide the block automatically when there is an erro

You can do this!

```toml
error_format = ""
```

**Comment by HugoBelotDeloro** [comment]
Oh, I do note that the block is actually removed and not just empty (as in two separators side-by-side), so it is actually perfect for my use case, thanks a lot!
