### ISSUE TITLE
Compile error on cargo install

### ISSUE THREAD

**Issue by samuelallan72** [greshake/i3status-rust#2118]
```
$ cargo install --git "https://github.com/greshake/i3status-rust.git" i3status-rs
...
error[E0432]: unresolved import `sunrise`330/333: zbus, i3status-rs
   --> src/blocks/weather.rs:149:5
    |
149 | use sunrise::{SolarDay, SolarEvent};
    |     ^^^^^^^ use of undeclared crate or module `sunrise`

For more information about this error, try `rustc --explain E0432`.
error: could not compile `i3status-rs` (lib) due to 1 previous error
error: failed to compile `i3status-rs v0.33.2 (https://github.com/greshake/i3status-rust.git#9f52b653)`, intermediate artifacts can be found at `/tmp/cargo-installhQLIoc`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.
```

It appears to be related to https://github.com/greshake/i3status-rust/pull/2028 and how sunrise-next has `sunrise` as the lib name, but `sunrise_next` as the crate name. `cargo build` in the repository succeeds, but `cargo install --path .` fails. But, if I change that line to `use sunrise_next::{SolarDay, SolarEvent};`, it compiles successfully with `cargo install --path .`, but fails with `cargo build`. :thinking: 

Maybe it's more of a problem with the sunrise-next crate?

**Comment by MaxVerevkin** [comment]
The issue is with the `sunrise_next` crate, which changed its name from `sunrise` to `sunrise_next` in a patch release. Install with `--locked` flag to "fix" it.

**Comment by MaxVerevkin** [comment]
Also note (from the readme):

> NOTE: Installation via cargo is not supported.
