### ISSUE TITLE
Battery mode + docking station.

### ISSUE THREAD

**Issue by droslean** [greshake/i3status-rust#212]
The battery is not changing in charging mode when using a docking station.

So current situation is that when you put a laptop in a docking station, the state does not change and
it stacks in the same percentage without even increment the battery (because of charging).

**Comment by droslean** [comment]
There is a chance that the issue is related with i3 itself and not with i3status-rust bar. 
I am keep investigating.

**Comment by atheriel** [comment]
I'm having some difficulty understanding what you mean here. Can you perhaps provide a screenshot?

**Comment by droslean** [comment]
When you use docking station instead of a charger, the battery is not changing in "charging" mode.

**Comment by atheriel** [comment]
What does the file `/sys/class/power_supply/BAT0/status` contain when you are charging with a charger versus charging with a dock?

**Comment by droslean** [comment]
Seems the issue was that it was reading the wrong battery. I am closing the issue.
