### ISSUE TITLE
Plugins?

### ISSUE THREAD

**Issue by bobthemighty** [greshake/i3status-rust#216]
I know this is a contentious subject in the Rust community, but is it worth considering a plugin system for the project?

I've opened a WIP PR for adding notmuch support to a new block, but to get it merged I'll have to rewrite the block to shell out to the notmuch program. 

I'm happy enough to do so, but it seems that the project will remain quite limited in its scope if new blocks can only invoke functionality by exec'ing another program and parsing the string output. If that's a design limitation then it seems that i3status-rust is, for the most part, using rust as a scripting language.

**Comment by atheriel** [comment]
I'm not quite sure I understand what you mean here. Do you want to be able to load out-of-tree blocks as Rust dylibs?

There has been some discussion of a plugin system before. Mostly what came out of it is that we're quite happy to maintain many blocks in-tree. So if you're considering writing new functionality as a plugin, we'd almost certainly be happy to have it as part of the project itself, especially in the near term. We accept new blocks fairly regularly!

**Comment by greshake** [comment]
We explicitly don't want a scripting language or anything similar that adds a huge overhead to the program. I don't see how this in any way implies that we use Rust as a scripting language. Having the blocks compiled and written in Rust ensures that we can provide the best possible performance for the provided blocks; if anyone wants to quickly make a block, they may use the custom-block feature. If they want to publish that block or access more advanced features, they have to learn Rust and write it.

**Comment by greshake** [comment]
The only reason I started this project is that I was in stunned by the huge memory and CPU footprint of custom status bars written in Python (and similar).
