### ISSUE TITLE
custom block ony runs once?

### ISSUE THREAD

**Issue by sharethewisdom** [greshake/i3status-rust#218]
The command of this custom block repeats only after I refresh the bar.

```
[[block]]
block = "custom"
command = "if xclip -o -selection clipboard &>/dev/null; then echo -n 'clip'; else echo -n 'noclip'; fi"
on_click = "xsel -bc"
interval = 1
```
 I thought this might have been because I tried to access the X clipboard when it may not have been available yet. But even when appending something like `sleep 3` I still only get "noclip" in spite of the presence of string on the clipboard selection, unless I refresh the bar (sway reload command).

Am I doing something wrong?

**Comment by sharethewisdom** [comment]
Indeed you may close the issue. 

Since opening this issue, I've found that the bar sometimes stops refreshing after waking from hibernation or sleep. I'm not sure yet when it happens. I'm not sure if this has anything to do with it: I run physlock from a script to lock the virtual terminal in resume@.service.

**Comment by atheriel** [comment]
I'll close the issue, but please let us know if you find that the resolution of your issue may be helpful to other users of this project!
