### ISSUE TITLE
Calculate the capacity from multiple batteries.

### ISSUE THREAD

**Issue by droslean** [greshake/i3status-rust#220]
With more batteries all the calculations are wrong. 
We should summarise the capacity from all the batteries and output the percentage to the bar.

In the configuration, we would be able to specify more batteries there, instead of getting the default BAT0.
Which in most cases the default battery is not BAT0

**Comment by GladOSkar** [comment]
I think it should be an option, so you can choose if you want the batteries displayed separately or as one.

**Comment by droslean** [comment]
In which cases you need to check the batteries seperatly?

**Comment by GladOSkar** [comment]
For example if one of the batteries is your UPS or if you have a hot-swappable battery you want to put into an external charger when it's empty

**Comment by atheriel** [comment]
There was an attempt to support multiple batteries in #170, but it fell apart. At the moment we make very simple calculations for capacity and (dis)charge time, but I recently refactored the internal implementation to separate battery devices from the block itself, so it's quite possible to write code that accounts for multiple batteries when estimating these values. I would also like to see a more sophisticated estimate of (dis)charge time in the future -- surely there are models out there.

Unfortunately, we're somewhat stymied by the fact that the battery block only expects a single device, and I'm skeptical there are enough users with multiple batteries to justify breaking compatibility with everyone else's config. At the moment, I think that one possible way forward is to write a new block that uses the same underlying device type but allows for more idiosyncratic setups. Unfortunately, I don't personally have a second battery, so I'm not the best person to bang out an implementation.

**Comment by GladOSkar** [comment]
@atheriel I assume that refactor is why you haven't commented on my PR yet. I can look into time estimation and multiple batteries some more in mid-august.

**Comment by atheriel** [comment]
Nope, that just fell off my radar. Sorry!

**Comment by atheriel** [comment]
This should now be possible (after #356) by setting `device = "DisplayDevice"`. I don't have a second battery; can someone confirm this?

**Comment by droslean** [comment]
@atheriel Nope. #356 , Is not related.

**Comment by atheriel** [comment]
@droslean Can you explain why? The Upower docs point to it doing exactly what you've asked for here -- or is that not what happens in practice?

**Comment by droslean** [comment]
@atheriel Sry I was wrong. The #356 it actually solves this problem!!!

/close

**Comment by atheriel** [comment]
Ah, I'm glad to hear that. Credit to @frececroka for finding a solution.
