### ISSUE TITLE
Improve accuracy of estimated time for the battery block

### ISSUE THREAD

**Issue by atheriel** [greshake/i3status-rust#221]
As discussed in #214, we could likely provide more accurate estimates of remaining time for the battery block. #220 is related but might require a different category of solution.

**Comment by droslean** [comment]
An idea should be to be able to add a block in the status.toml with the option of multiple batteries, with another option -> merge=true/false

Example:
[[block]]
block = "battery"
interval = 10
show = "both"
device = [ "BAT0", "BAT1" ]
merge = true

and of course there is always the option to add another battery in another block.

Merge mode should get the summary of the capacity of the given batteries and calculate the percentage of the status.

**Comment by GladOSkar** [comment]
Yes, this seems like the logical way to do it

**Comment by atheriel** [comment]
I actually consider this to have been fulfilled by support for Upower in #252, and discussion of time estimation for multiple batteries should probably occur in those PRs/issues.
