### ISSUE TITLE
Unable to get fontawesome icons working

### ISSUE THREAD

**Issue by Svenito** [greshake/i3status-rust#23]
Just installed i3status-rust on my ubuntu box and am unable to get the awesome fonts working. I have installed the fontawesome ttf, but I am unable to see the correct icons. I get strange glyphs instead.

**Comment by greshake** [comment]
Not an issue to be fixed from this side. This is a configuration/setup error depending on your setup. I'd try to give you a hint if you give me some useful information, but otherwise I'm closing this issue.

**Comment by greshake** [comment]
If you want help, give me some more info:
- general OS setup
- i3 config
- i3status-rust config
- `$ fc-list`

**Comment by greshake** [comment]
In general, this program just outputs fixed unicode symbols, which are always the same independent from your setup, that is why I'm sure it is no issue of this project. The i3bar then select system font to render those symbols. The issue must be in your i3 config or font setup.

**Comment by Svenito** [comment]
Yes, I understand that from looking at the source, but I am failing to see what I am doing wrong, so I was hoping to get some help here.

System:
* Ubuntu: 16.04
* i3: 4.13

i3 config: https://gist.github.com/Svenito/3cfa7becd2dd1ad85b9648ea8fc0375b
i3status-rust config: 
```
[                                                                               
  {"block": "disk_space", "path": "/", "alias": "/", "type": "available", "unit": "GB", "interval": 20},
  {"block": "memory", "type":"memory", "format_mem":"{Mup}%", "format_swap":"{SUp}%"},
  {"block": "cpu", "interval": 1},                                              
  {"block": "load", "interval": 1, "format": "{1m}"},                           
  {"block": "music", "player": "clementine", "buttons": ["play", "next"]},      
  {"block": "time", "interval": 60, "format": "%a %d/%m %R"}                    
]    
```
[fonts.txt](https://github.com/greshake/i3status-rust/files/1028791/fonts.txt)

Let me know if you need anything else

**Comment by greshake** [comment]
Yep, found the issue. You don't specify your font in the "bar" block of your config. i3status can't choose the font for you, you have to specify it for i3bar manually. Look at the README, there is an example of the bar section from my personal config, hope that fixes it. Closing now.

**Comment by Svenito** [comment]
ah ok will try that, thanks

**Comment by greshake** [comment]
Working now?

**Comment by Svenito** [comment]
Yes thanks. I was under the impression that if you specify `awesome` as the icons it would automatically set the font somewhere. My mistake.

All clear now. Thanks for the help!

**Comment by greshake** [comment]
Alright, I added a **Note** in the README to avoid further confusion.
