### ISSUE TITLE
block backlight doesn't works [resolved] do not use i3status-rust AUR, use i3status-rust-git

### ISSUE THREAD

**Issue by jerome-diver** [greshake/i3status-rust#230]
i3status-rust installed from archlinux AUR repo version=0.9.0-1
*but version 0.9.0r508.gad5a44f-1 (i3status-rust-git) works*
add it inside toml config file just break the bar

**Comment by atheriel** [comment]
Yes, the backlight block is only available in newer versions. I'll close this, since you seem to have resolved it on your own, but you can reopen it if I've misunderstood.
