### ISSUE TITLE
Question regarding net block up/down icon size

### ISSUE THREAD

**Issue by ammgws** [greshake/i3status-rust#238]
Are the up/down icons meant to be so small?
![image](https://user-images.githubusercontent.com/20397027/44155990-c2473b78-a0e9-11e8-8584-1f928b168245.png)

Info:

- 4.17.14-arch1-1-ARCH
- sway version 0.15.2
- i3status-rust-git 0.9.0.r514.g2ec4cbb-1 (from AUR)

```sh
> cat ~/.config/i3status-rust/config.toml | grep icons
icons = "awesome"
```

```sh
> cat ~/.config/sway/config | grep -A 10 bar
# ┃ Status bar
# ┗━━━━━━━━━━━━━━━━━━━━━━━━┛
# Read `man 5 sway-bar` for more information about this section.
bar {
    font pango:DejaVu Sans Mono, FontAwesome 10
    position top
    status_command i3status-rs $XDG_CONFIG_HOME/i3status-rust/config.toml
    colors {
        statusline #ffffff
        background #323232
        inactive_workspace #32323200 #32323200 #5c5c5c
    }
}
```

```sh
> fc-match FontAwesome
FontAwesome.otf: "FontAwesome" "Regular"
```

```sh
> trizen -Ss ttf-font-awesome-4
aur/ttf-font-awesome-4 4.7.0-5 [installed] [26+] [1.89%] [12 Jan 2018]
    100% free version of font awesome.
```

```sh
> trizen -Ss powerline-fonts
community/powerline-fonts 2.7-1 [installed]
    patched fonts for powerline
```

**Comment by atheriel** [comment]
No, I don't think they are supposed to be that small.

**Comment by atheriel** [comment]
... the amount of time we spend trying to debug font issues in this repo is concerning.

**Comment by uinput** [comment]
I can reproduce this on sway, but I don't have an i3 setup right now. Can someone confirm on i3?

**Comment by ammgws** [comment]
Still the same in i3.
![image](https://user-images.githubusercontent.com/20397027/44201412-1b440e00-a184-11e8-8d24-fe91d4262461.png)

```sh
> cat ~/.config/i3/config | grep -A 10 i3bar                                                                                                                             
# Start i3bar to display a workspace bar (plus the system information i3status finds out, if available)
bar {
  font pango:DejaVu Sans Mono, FontAwesome 10
  position top
  status_command i3status-rs $XDG_CONFIG_HOME/i3status-rust/config.toml
  colors {
    statusline #ffffff
    background #323232
    inactive_workspace #32323200 #32323200 #5c5c5c
  }
}
```

```sh
> trizen -Ss i3 | grep installed                                                                                                                                         
community/i3-gaps 4.15.0.1-2 [i3] [installed]
community/i3blocks 1.4-6 [i3] [installed]
community/i3lock 2.10-1 [i3] [installed]
community/i3status 2.12-1 [i3] [installed]
community/sway 0.15.2-2 [installed]
aur/i3status-rust-git 0.9.0.r514.g2ec4cbb-1 [installed: 0.9.0.r511.g346e5d8-1] [8+] [0.86%] [15 Aug 2018]
```

**Comment by ammgws** [comment]
Can anyone share a screenshot of how it should look?

**Comment by atheriel** [comment]
![screenshot](https://user-images.githubusercontent.com/1448326/45182146-7fd81300-b1ee-11e8-85f1-ddd506babb3b.png)

This is what mine looks like. Font is `pango:Iosevka, FontAwesome 9`. I'm running the 1.0-alpha of sway but it was the same before. Master branch of this project, but again it's been unchanged for ages. I'll dig into the font a bit more.

**Comment by atheriel** [comment]
```
$ pacaur -Ss ttf-font-awesome
community/ttf-font-awesome 5.2.0-1
    Iconic font designed for Bootstrap
aur/ttf-font-awesome-4 4.7.0-5 (28, 2.92) [installed]
    100% free version of font awesome.
```

**Comment by ammgws** [comment]
This is how mine looks with Iosevka. This is pretty ridiculous  haha
![image](https://user-images.githubusercontent.com/20397027/45189369-a1c7a900-b273-11e8-9b51-115d8f9ea814.png)

```
aur/ttf-iosevka 2.0.0-1
aur/ttf-font-awesome-4 4.7.0-5
```

**Comment by ammgws** [comment]
OK so have managed to fix the arrows by getting rid of DejaVu from the config.
(I also had `aur/nerd-fonts-complete 2.0.0-5` installed which I uninstalled at some point in between just in case.)

**Before**
`font pango:DejaVu Sans Mono, FontAwesome 12`
![image](https://user-images.githubusercontent.com/20397027/45217384-d886d900-b2de-11e8-899a-49f025d1343b.png)
**After**
`font pango:FontAwesome 12`
![image](https://user-images.githubusercontent.com/20397027/45217410-eb011280-b2de-11e8-950f-1d17bf262e43.png)

**Comment by atheriel** [comment]
Good detective work!
