### ISSUE TITLE
SSID with wpa_cli

### ISSUE THREAD

**Issue by concatime** [greshake/i3status-rust#247]
Hi. I want to display only my SSID, but without installing `iw`. I have wpa_cli, and with `wpa_cli status -iwlp3s0`, I'm able to get my ssid. Can you implement this as an alternate way if iw is absent?
Thank you.

**Comment by atheriel** [comment]
This seems like a reasonable request.

**Comment by ammgws** [comment]
@concatime Sorry for the delay but does #625 solve this for you?

**Comment by ammgws** [comment]
Confirmed it works.

Closing via #625

**Comment by concatime** [comment]
Sorry, I was quite busy. And to be honest with you, I’m currently using Waybar.
