### ISSUE TITLE
sigma character in front of blocks

### ISSUE THREAD

**Issue by hurrtz** [greshake/i3status-rust#255]
Hey,

I am pretty sure that this is my problem alone but as of yet I cannot figure out where this issue comes from and you are my first contact in this matter...

Before all the blocks there is a sigma character, in the color of the block. Do you by any chance have come across this and know how to solve it?

**Comment by ammgws** [comment]
It sounds like you don't have powerline fonts installed?

**Comment by hurrtz** [comment]
I'll be damned. You are correct, that was it. Thank you very much :)

**Comment by avronr** [comment]
I have the same issue on Debian 10 and I have the powerline fonts installed.

**Comment by bkayes** [comment]
I'm having this same issue on Ubuntu 20.04 and I have powerline fonts installed
