### ISSUE TITLE
Question regarding dbus events

### ISSUE THREAD

**Issue by ammgws** [greshake/i3status-rust#256]
I noticed that blocks using dbus such as [music](https://github.com/greshake/i3status-rust/blob/master/src/blocks/music.rs#L94-L100) seem to be listening for events by polling. However iirc you should be able to do this without polling, by subscribing to the desired signal. Does the dbus crate not support subscriptions, or is this something we can improve upon?

EDIT: or have I misinterpreted this code? Is that just a timeout?

**Comment by ammgws** [comment]
My bad. Looks ilke it does subscribe and that loop is just going through the events iterator

**Comment by atheriel** [comment]
Yeah, in my view the `dbus` crate has a very non-idiomatic feel to it, and it can be quite difficult to interpret the code without knowing a great deal about D-Bus.
