### ISSUE TITLE
Request: libmpv block?

### ISSUE THREAD

**Issue by sharethewisdom** [greshake/i3status-rust#259]
In issue #219 a few players were mentioned that use libmpv. As there are [quite a number](https://github.com/mpv-player/mpv/wiki/Applications-using-mpv) of widely adopted players using the libmpv API, I thought I'd ask if someone wants to add support for such a block and weather it is easily done.

**Comment by atheriel** [comment]
Related: [an `mpv` plugin adding MPRIS2 support](https://github.com/hoyon/mpv-mpris). I do not think this covers all `libmpv` users, but it should cover those using `mpv` itself.

**Comment by sharethewisdom** [comment]
cool, thanks!

**Comment by atheriel** [comment]
I'm going to close this as resolved for now, but it can be re-opened if we need further discussion of libmpv support.
