### ISSUE TITLE
Feature: tooltip?

### ISSUE THREAD

**Issue by sharethewisdom** [greshake/i3status-rust#260]
Maybe a `i3status-rust-gtk3` fork or branch (because of the added dependency) with block configuration for a tooltip could be interesting. A custom command could be triggered when hovering; or a simple string could be given.

**Comment by atheriel** [comment]
I don't think this is supported by the i3status protocol, so I don't think it's possible to implement. Not a bad idea, though!

**Comment by aloispichler** [comment]
The tray allows hovering…

**Comment by MaxVerevkin** [comment]
> The tray allows hovering…

Obviously the bar itself knows then it is being hovered and how to show tooltips.

The problem is that i3bar protocol provides neither hover events nor a mechanism to specify a tooltip.

Relevant i3 issue: github.com/i3/i3/issues/3972

**Comment by ammgws** [comment]
As Max mentioned, we are limited by the i3bar protocol: https://i3wm.org/docs/i3bar-protocol.html
