### ISSUE TITLE
"chan" crate is deprecated

### ISSUE THREAD

**Issue by ammgws** [greshake/i3status-rust#264]
Just saw that the [chan crate](https://crates.io/crates/chan) has been deprecated, and is now superseded by [crossbeam-channel](https://github.com/crossbeam-rs/crossbeam-channel).

On that note, what is the reason for using `chan` instead of [std::sync::mpsc](https://doc.rust-lang.org/std/sync/mpsc/struct.Sender.html)?

If there is no real reason not to use the standard library, we could port the code to use that and remove the dependency on `chan`. Otherwise, I guess we should move over to the new crate at some point?

**Comment by atheriel** [comment]
I've been curious about the use of `chan` for a while, but hadn't noticed it was deprecated. I believe only @greshake knows the reasoning behind the choice.

**Comment by ammgws** [comment]
I see everything has been updated to crossbeam so can close this now.

(Though the question still remains whether we can remove the dependency and use the std lib)
