### ISSUE TITLE
Caps Lock and Num Lock block

### ISSUE THREAD

**Issue by hanckmann** [greshake/i3status-rust#267]
(from issue 4)
I would be very interested in having a block showing the status of Caps Lock and Num Lock.
I will try to make this a pull request... but I am not yet on steroids with Rust :-)

I am trying to do this using info on these pages:

    https://github.com/erlepereira/x11-rs/blob/40f3cc218e53e89f4b5093b16348de3b7103a8bd/src/xlib.rs
    https://github.com/compenguy/clickrs/blob/master/src/inputsource.rs

**Comment by atheriel** [comment]
I'm supportive of this addition, but one (minor) thing to keep in mind is that we have many non-X.org users. I'm fine having an implementation that relies on X.org, but we may have to make it opt-in.

Alternatively, does anyone know if there is way to listen for keyboard events via D-Bus?

**Comment by crablab** [comment]
Apparently there is as described [here](https://stackoverflow.com/a/1906667). 

These seems a bit nasty as you're piping all the keyboard events to the status bar (keylogger anyone...) so I wonder if there might be a better solution.

I might look at making the X.org version at some point, if no-one else is.

**Comment by ammgws** [comment]
If polling is OK we could just get the state via /sys/class/leds/inputXX::capslock/brightness

**Comment by c02y** [comment]
I'm sorry, how can I config `keyboard_layout` block to show whether the Caps Lock or Num Lock is enabled?

**Comment by Celibistrial** [comment]
> I'm sorry, how can I config `keyboard_layout` block to show whether the Caps Lock or Num Lock is enabled?

Hey did you figure it out? 
😅 My laptops caps light recently died

**Comment by c02y** [comment]
> > I'm sorry, how can I config `keyboard_layout` block to show whether the Caps Lock or Num Lock is enabled?
> 
> Hey did you figure it out? 😅 My laptops caps light recently died

nope, I wrote config in i3/config file to notify-send a message when I press tab key instead.
