### ISSUE TITLE
nvidia gpu block: temperature field ignores style

### ISSUE THREAD

**Issue by fedario** [greshake/i3status-rust#278]
Hi there,

the temperature field of the nvidia gpu block seems to ignore the style set in the config.toml.
When the temperature is low it has a bright green background instead of the black background specified for all blocks.

**Comment by tim77** [comment]
Can confirm this. Here is screenshot with green indication, but when temperature rising up it have the same color as whole bar.
![DeepinScreenshot_select-area_20191110184612](https://user-images.githubusercontent.com/5614476/68547509-00923080-03eb-11ea-8d7b-88aec77f8203.png)

**Comment by atheriel** [comment]
I don't think this is a bug. The current implementation looks like this:

```rust
temperature_widget.set_state(match temp {
    0..=50 => State::Good,
    51..=70 => State::Idle,
    71..=75 => State::Info,
    76..=80 => State::Warning,
    _ => State::Critical,
});
```

That is, low temperatures are considered "good", not "idle". This is similar to how a full battery is marked "good". You can override this style in your config if you wish. I'm also open to making these threshold more configurable -- they seem pretty arbitrary to me at the moment.

**Comment by tim77** [comment]
IMHO if we swap Good <-> Idle it would look like it should. This what i mean, when temp >50C:
![DeepinScreenshot_select-area_20191111003459](https://user-images.githubusercontent.com/5614476/68552042-61396180-041b-11ea-9226-14c1cbee9a12.png)

**Comment by atheriel** [comment]
Yep, I'd be happy to take a PR switching them.

**Comment by ammgws** [comment]
@tim77 Could you please try #615?

**Comment by tim77** [comment]
> @tim77 Could you please try #615?

Missed message, will try today.

**Comment by tim77** [comment]
✅ https://github.com/greshake/i3status-rust/pull/615 definitely fixed this issue. Thanks a lot!
