### ISSUE TITLE
[block sound] Error when trying to adjust volume of input sound device

### ISSUE THREAD

**Issue by yw662** [greshake/i3status-rust#284]
config:
[[block]]
block = "sound"
name = "alsa_input.pci-xxxxxxxxxx"

when scroll up/down on this block, i3status-rs throw an error, saying 'volume unknown'

Actually I am not trying to adjust volume of a microphone, I put it there just to mute/unmute microphone, but this happened accidentally.

There should be an option to disable the scroll up/down action, or ignore errors.

**Comment by yw662** [comment]
and btw, it cannot mute a microphone :-)

**Comment by fedario** [comment]
Related: #277

**Comment by atheriel** [comment]
TLDR: If you're using the default PulseAudio driver, we don't currently support sources. You can see if this setup works correctly with `driver = "alsa"` if you'd like, though.

**Comment by atheriel** [comment]
Closing in favour of #277.
