### ISSUE TITLE
Configuration error: failed to deserialize block config invalid type string

### ISSUE THREAD

**Issue by frojnd** [greshake/i3status-rust#286]
```
Configuration error: failed to deserialize block config.
Cause: invalid type: string "BAT1", expected usize for key `device`
```

My relavant toml.conf

```
[[block]]
block = "battery"
device = "BAT1"
interval = 10
show = "percentage"
```

**Comment by frojnd** [comment]
i3status-rust version: 0.9.0-1 

Please advice. I kinda need battery status.

**Comment by atheriel** [comment]
This is not actually a bug -- the configuration format has changed in the last year. You could use `device = 1` if you need to use such an old version of the project, but I'd suggest updating to a more recent build. 

(We don't actually support version 0.9.)
