### ISSUE TITLE
Error in block 'weather': Unknown block!

### ISSUE THREAD

**Issue by frojnd** [greshake/i3status-rust#287]
It's failing for no particular reason:
```
{"version": 1, "click_events": true}
[[{"background":"#000000","color":"#dc322f","full_text":" Error in block 'weather': Unknown block! ","separator":false,"separator_block_width":0}]


Error in block 'weather': Unknown block!
```

Relavnt toml.conf code

> [[block]]
> block = "weather"
> format = "{weather} {temp}° {wind} km/s"
> #service = { name = "openweathermap", api_key = "abra123kadabra", city_id = "3196359", units = "metric" }

**Comment by atheriel** [comment]
Judging by your other issue (#286), you are running a very old build, which does not include the weather block.
