### ISSUE TITLE
problem with cargo rust

### ISSUE THREAD

**Issue by danieltomasz** [greshake/i3status-rust#288]
I dont know cargo/rust, when I try to build i3status from source I get  the following error
```
error: failed to parse lock file at: /home/daniel/i3status-rust/Cargo.lock

Caused by:
  package `libc 0.2.40 (registry+https://github.com/rust-lang/crates.io-index)` is specified as a dependency, but is missing from the package list

```

In June build was ok. I am not sure if the error is caused by i3status config or  my rust/cargo setup.
Please help :)

**Comment by atheriel** [comment]
Can you give your `rustc` and `cargo` versions?

**Comment by danieltomasz** [comment]
Hi, I have  `R v1.28.0`, after updating to the latest (together with cargo) problem disappear!
