### ISSUE TITLE
System tray uglyness

### ISSUE THREAD

**Issue by hanckmann** [greshake/i3status-rust#291]
Not sure if this an actual i3status-rust issue, but maybe you know a fix or can point me somewhere else.
The system tray is very ugly. It does not clean-up old icons properly, which makes reading the new icons difficult. I attached a screenshot to make clear what I mean.
![screenshot at 2018-10-17 12-14-37](https://user-images.githubusercontent.com/925657/47080333-03324e80-d208-11e8-9ba1-da9ea63278f0.png)

**Comment by GladOSkar** [comment]
This is definitely a problem with your distro/system, not with `i3status` or `i3bar`

**Comment by hanckmann** [comment]
hmm... any pointers on where to look?
Which application puts the system-tray area in the bar? Does it need something like a compositor (I guess not, and I am not running one)?

**Comment by GladOSkar** [comment]
I don't really know anything about trays in X, sorry.

**Comment by sebastianst** [comment]
I'm experiencing the same problem for a few weeks now (Arch). But I just recently switched to i3status-rs, so this is definitely not because of it.

**Comment by atheriel** [comment]
The appearance of application icons in the system tray should be controllable via the system icon themes, but I've never fooled around with this specifically under i3 or sway.

However, as @GladOSkar notes this is *far* beyond the scope of this project. There are plenty of theme-related resources for Linux out there if you go looking for them, though.
