### ISSUE TITLE
Errors handling! 

### ISSUE THREAD

**Issue by droslean** [greshake/i3status-rust#300]
There are problems with errors is that if there is any, the whole status bar breaks and displays only the error.

For example, in the `weather` block, I have recently experienced a strange error that after debugging I discover that my API expired (which was not true). I3status bar is not responsible for this, but it shouldn't break the whole bar.
Even the error was not clear to me: `Malformed JSON`.  see also #292 

## Suggestion:
I suggest in case of error, we should append an exclamation mark in the block that error appears. And after click on it, we should display the error in a small window.

**Comment by ammgws** [comment]
See #145 for previous (and ongoing) discussion about this

**Comment by droslean** [comment]
Closing..  Duplicated with #145
