### ISSUE TITLE
.Xresources colors in config file

### ISSUE THREAD

**Issue by drozdowsky** [greshake/i3status-rust#304]
Hello!
First of all great job, recently installed i3 and I come upon [pywal](https://github.com/dylanaraps/pywal) I think adding support for reading colors from .Xresources is nice to have feature. It will make i3status-rust more fitting with the whole desktop theme, right now I don't see any option to do this without writing custom script (or I am not aware of such things).
I think this can be solved in 3 ways:
- custom script
- i3status-rust reads .Xresources values ($ xrdb -query)
- i3 config can read .Xresources values so from there we can somehow pass values to i3status-rust config

I have no knowledge in rust programming so I can't contribute (if we talk about last two points, I will probably write python script for the first one)

**Comment by drozdowsky** [comment]
I make custom [script](https://github.com/drozdowsky/rc-files/blob/master/.i3/scripts/i3status-rust-colors.py) for anyone interested

**Comment by atheriel** [comment]
I don't think we intend to support reading colours from `xrdb`. And it's not clear that the `.Xresources` names could be transparently mapped to our existing (functional) names, either.

However, it's my hope that colours will one day be specified in a separate file, which could make writing these scripts easier.

I'm going to close this, but thanks for posting the link to your script -- that could indeed be very useful for users of the various `wal` programs!

**Comment by jkorinth** [comment]
> I don't think we intend to support reading colours from `xrdb`. And it's not clear that the `.Xresources` names could be transparently mapped to our existing (functional) names, either.

I was actually looking for a simple way to reference colors in `.Xresources` in theme overrides, so I created #2044. Maybe this would help you, too, @drozdowsky?
