### ISSUE TITLE
Music block ability to configure bus type

### ISSUE THREAD

**Issue by 318h7** [greshake/i3status-rust#306]
A feature request:
I would really love to have add the ability to set up the bus type to use in the music block.

When trying to use mopidy as a service, it fires the messages over the system bus. And the music block listens to the session bus.

I am new to rust, but looking at the source, it seems obvious, what needs to be done. I beleave I could handle it and would like to contribute.

**Comment by atheriel** [comment]
Is it possible to configure mopidy to use the session bus? I don't have an objection to implementing this feature, but using the system bus for a music service seems a little odd.

**Comment by 318h7** [comment]
Yes, that is what I am doung now. I run it in background, configured to use the session bus. It works perfectly fine with the bar.

I am not a linux guru, to be honest. Maybe you could explain in couple of words why it is a bad idea to use the system bus and we can close the issue?

**Comment by atheriel** [comment]
Oh, my understanding is that the session bus is attached to login sessions. Since a music player is presumably run by a user, not by the system, it would make sense to use their bus.
