### ISSUE TITLE
Can we have custom icons for custom blocks?

### ISSUE THREAD

**Issue by NullVoxPopuli** [greshake/i3status-rust#31]
I have a block that executes a script that finds my public ip address, and I'd like to add a globe icon to it or somethin.

**Comment by greshake** [comment]
You just need your block to emit the right unicode symbol for the font you are using. So, if you're using font awesome, just emit an icon from their cheatsheet: http://fontawesome.io/cheatsheet/
e.g. use the command "echo  `curl -s https://wtfismyip.com/text`"

**Comment by NullVoxPopuli** [comment]
thanks!

**Comment by NullVoxPopuli** [comment]
![2017-05-28-164456_1090x23_scrot](https://cloud.githubusercontent.com/assets/199018/26532040/fff20210-43c4-11e7-9a23-c76f9a3e87f6.png)

:-) 
Also, I got the background color to match. Thanks for your help!

**Comment by greshake** [comment]
If you have made a good matching theme, don't forget to add it to themes.rs and give me a pull request :)
