### ISSUE TITLE
Release on crates.io for easier Gentoo integration

### ISSUE THREAD

**Issue by lovesegfault** [greshake/i3status-rust#315]
On Gentoo, generating ebuilds for Rust applications is supposed to be done through [cargo-ebuild](https://github.com/cardoe/cargo-ebuild). I tried to do that for this package, but it seems to have failed due to it not being on crates.io itself.

Would you consider adding releases there as well?

**Comment by atheriel** [comment]
I didn't realize crates.io supported applications. In any case, this is unlikely to happen in the near future -- the version of this "crate" has been frozen for more than a year, despite ongoing development, and we mostly expect users to install from git master to get new features.

**Comment by ignatenkobrain** [comment]
So I see that there were few releases lately... is it time to reconsider this? @atheriel

**Comment by bluec0re** [comment]
Bump @ammgws (who created the latest releases)

**Comment by bluec0re** [comment]
Added some install instructions with cargo in #751
