### ISSUE TITLE
Keyboard layout indicator

### ISSUE THREAD

**Issue by jslby** [greshake/i3status-rust#319]
Hello. I want show in status bar current keyboard layout.
How i can do this?
I try this lib [https://github.com/nonpop/xkblayout-state](https://github.com/nonpop/xkblayout-state) and custom-block, but i can't do it.
Thx

**Comment by GladOSkar** [comment]
If you are using Xorg:

```
[[block]]
block = "custom"
command = "setxkbmap -query | grep layout | awk '{print $2}'"
interval = 10
```

Keep in mind this will not update immediately on layout changes but only every 10 seconds.

Hope i could help :)

**Comment by jslby** [comment]
I know about this opportunity. But I think that the use of the interval is not cool here.

**Comment by atheriel** [comment]
This is sort of related to #267. I think it is a good idea, especially if there is a way to do this via D-Bus.
