### ISSUE TITLE
How do I configure colors?

### ISSUE THREAD

**Issue by NullVoxPopuli** [greshake/i3status-rust#32]
In the readme, there are colors for each block. Right now, all I have is monochrome text.
![2017-05-28-152541_1056x26_scrot](https://cloud.githubusercontent.com/assets/199018/26531581/ecde2bbe-43b9-11e7-8b09-c08d1a9ac04b.png)

**Comment by greshake** [comment]
Colors are set based on theme and block state. Ramp your CPU usage up and you will see color. By default the bar is supposed to get out of your way. Colors only come into play to convey information, e.g. warn you of a critical system resource. Edit your theme to configure colors.

**Comment by NullVoxPopuli** [comment]
cool. I see: https://github.com/greshake/i3status-rust/blob/master/example_theme.json
how do I specify to use a custom theme.json?

**Comment by greshake** [comment]
Have you tried `$ i3status-rust --help`?

**Comment by greshake** [comment]
--theme <file> shoud work.

**Comment by NullVoxPopuli** [comment]
it worked. cool. I'm providing an absolute path to the theme json.
Nice.
And I keep forgetting that i3status-rust is a CLI bin as well.
