### ISSUE TITLE
Get API key from env. variable

### ISSUE THREAD

**Issue by yangmillstheory** [greshake/i3status-rust#320]
Thanks for the great project :). I version my dotfiles and I'm planning on using the Weather block, but you need to specify an API key in the .toml file, which risks checking the key into source control. 

Can we implement some way of pulling this information from the process environment?

**Comment by atheriel** [comment]
Sure, that would make sense. If anyone's willing to take it on I will happily review the PR, otherwise it might take a while to get to.

**Comment by fennifith** [comment]
@yangmillstheory I have no Rust experience either, but if you want a "different" solution (that works for other config files too) you could use something like [this script](https://gist.github.com/fennifith/4221a79ec5f39c21085fec4c41d7d160#file-gen-bintray-descriptor-sh) on your config file to format environment variables into it before i3 is started (this is what I'm doing - it allows me to get the network device for the "net" block from `iw dev` as well).

Of course, you still have to remember not to add the formatted file to VCS after the script has been run (maybe you could have it store the formatted version in a different location to avoid this?), but it makes it much easier to manage the configuration across multiple devices.

**Comment by atheriel** [comment]
@fennifith That's a clever example, thanks. We have a few issues filed around sharing configurations across machines, and that serves as a good workaround for many of them.

@yangmillstheory It shouldn't be too hard to get started with Rust, and you can build this project with Cargo. But it's not the most welcoming of languages, either.

Implementation-wise, you should be able to use [the standard library's support for environment variables](https://doc.rust-lang.org/std/env/fn.var.html). Here is how I would do it:

* Change the `api_key` from a `String` to an `Option<String>` in the `OpenWeatherMap` structure (in `src/blocks/weather.rs`). This will allow it to be missing/empty when parsing the configuration file.

* In the logic that reads the configuration (also in that file), check if the `api_key` is `None` and then look in the `OPENWEATHERMAP_API_KEY` environment variable. If both are missing, error out.

The actual tricky bit here will be handling `None` and `Err` correctly. It will end up being a 3-4 line change in the end, but that understates the work needed to get there.

**Comment by ammgws** [comment]
For privacy reasons I'd also want to apply this to `city_id`.

**Comment by atheriel** [comment]
Closed by #410.
