### ISSUE TITLE
Program icon not showing in the task bar

### ISSUE THREAD

**Issue by SachaNevsky** [greshake/i3status-rust#323]
So I have a few programs show up in the task bar, but some don't have a logo, and instead have a 🚫 icon, as can be seen [here](https://gyazo.com/3d28365b7dd34f5e5281f77fae004765).

**Comment by atheriel** [comment]
Program icons are not controlled by `i3status-rs`, they are controlled either by `i3` (via `i3bar`) or `sway` (via `swaybar`). As such, this is out of our control. However, if anyone has a suggested solution, feel free to post it in this thread.
