### ISSUE TITLE
Enable custom blocks to exclude themselves from the bar entirely

### ISSUE THREAD

**Issue by OddBloke** [greshake/i3status-rust#330]
I want to write a custom block that informs me of a (boolean) error state on my machine that only happens occasionally. As such, I don't want to sacrifice bar real estate to it when it's in a good state, which is 99% of the time.

It would be good if a custom block could express (via configuration) that an empty result means the block should be excluded from the bar entirely.

(At the moment, at least two spaces will be produced from ButtonWidget::update; one in the format string, and one as a default if an icon isn't specified.)

**Comment by OddBloke** [comment]
Even removing those two spaces in the code still leaves a separator character:

![image](https://user-images.githubusercontent.com/62736/52888716-d147df00-314a-11e9-9d3b-0def42447a61.png)

**Comment by OddBloke** [comment]
This is a dupe of #208

**Comment by ammgws** [comment]
Implemented in #860
