### ISSUE TITLE
Don't display blocks that partially overflow screen

### ISSUE THREAD

**Issue by OddBloke** [greshake/i3status-rust#341]
I have two monitors, one of which I use in portrait mode. I have blocks configured that take up ~2/3rd of my landscape monitor's bar, but they overflow on my portrait monitor, which looks messy (that text actually reads "162.7k"):

![messy](https://user-images.githubusercontent.com/62736/53495082-2f3ec580-3a6d-11e9-9893-ebb172b3b801.png)

It would be good if the block(s) that aren't going to be properly displayed weren't displayed at all.

**Comment by GladOSkar** [comment]
I think this is not possible via the i3bar protocol.

I think it is not possible to cut a status off in the i3bar config either.

But if you want your bar on the portrait monitor to show the workspaces but not the status, you can create 2 bars in your config and assign them to one monitor each, with the second one having no status command configured.

**Comment by OddBloke** [comment]
Thanks for the comment, @GladOSkar! I'll investigate doing just that.

**Comment by GladOSkar** [comment]
Actually, if you did that you could also have 2 instances of `i3status-rs` running with different config files :)

**Comment by OddBloke** [comment]
Good idea, thanks!
