### ISSUE TITLE
Getting a lot of `dyn Trait` errors

### ISSUE THREAD

**Issue by SamSaffron** [greshake/i3status-rust#347]
I am probably doing something silly here, but my install is totally blowing up with 100s of:

```
error[E0658]: `dyn Trait` syntax is unstable (see issue #44662)
    --> /home/sam/.cargo/registry/src/github.com-1ecc6299db9ec823/libpulse-binding-2.5.0/src/context/introspect.rs:1838:30
     |
1838 |         callback: Option<Box<dyn FnMut(bool) + 'static>>) -> Operation<dyn FnMut(bool)>
```

```
sam@arch ~ % rustc --version
rustc 1.26.1 (827013a31 2018-05-25)
```

**Comment by GladOSkar** [comment]
`1.26` is pretty old. Did you try with a current `rustc`?

**Comment by SamSaffron** [comment]
Oops.... going to close this @GladOSkar  and re-test on 1.33, for some reason I had ancient rust living in my home dir and it overrode what Arch was trying to install. 

Thanks so much for making this!

**Comment by GladOSkar** [comment]
No worries. Also i didn't make this :)

**Comment by atheriel** [comment]
@SamSaffron It's actually not a bad thing for us to know that we don't compile on year-old stable. I'd lost track of that myself. Thanks for reporting this.

**Comment by jlecour** [comment]
Hi, on Debian stable (9.8) we have Rust 1.24.1 and i3status-rust can't compile :/

**Comment by atheriel** [comment]
@jlecour Unfortunately we do not support releases that old at this time. You should be able to get an updated version of the compiler via `rustup`.

**Comment by jlecour** [comment]
@atheriel I would be very happy to try this, but I know nothing about `rustup` and ir doesn't seem to be installed by the `rustc` package on Debian.

**Comment by GladOSkar** [comment]
@jlecour As you can see on [rustup's homepage](https://rustup.rs/), it's usually installed via an install script. I would recommend uninstalling your systems rust packages first.
