### ISSUE TITLE
MPD support. 

### ISSUE THREAD

**Issue by oknozor** [greshake/i3status-rust#348]
Hello, 

I would really like to get Music player daemon working with the music block. Unfortunately it doesn't support the MediaPlayer2 interface.  

At first i tried to make my own custom block which called a little script rotating the song name every second. The problem is that the output get trimed so the width of the block is inconsistent on every call (is this intended?).  

So i'd like to implement a block for mpd. My question is shall i extend the current Music block behavior, which is tightly coupled with MediaPlayer2 or shall i rather make a new one?

**Comment by ammgws** [comment]
Sorry if I have misunderstood, but are you saying that when setting your config like below `mpd` doesn't work? I have `mpd` and `mpDris2` installed and running and the music block works fine (need mpDris2 for block to work)

![20190321_18h17m25s](https://user-images.githubusercontent.com/20397027/54742758-9b908d00-4c05-11e9-8e30-e5132858f2e1.png)

**Comment by oknozor** [comment]
Oh i did not knew about mpDris2, sorry. It might be worth it to add that to the music block documentation. Anyway it's working like a charm now. Thank you !

**Comment by atheriel** [comment]
Added to the docs at your suggestion. Thanks @ammgws -- I was not aware of `mpDris2`, either.

**Comment by nsirolli** [comment]
In case you want to avoid Python, there's a rust-based alternative to mpdris2:

https://github.com/szclsya/mpdris2-rs
