### ISSUE TITLE
`hide_missing` looks weird with alternating color scheme

### ISSUE THREAD

**Issue by GladOSkar** [greshake/i3status-rust#349]
When a block is hidden, it is not removed from the alternating color sequence.

![screenshot](https://user-images.githubusercontent.com/9497832/54833063-a4449a00-4cbd-11e9-956c-22c9acdd545f.png)

Ideally when a block is hidden, it should be removed.

**Comment by atheriel** [comment]
This might be tricky to fix, but it is for sure a bug. Alternating colours are handled in a very different place than the missing block code.

**Comment by GladOSkar** [comment]
@atheriel 

The easiest solution would imo be to not push empty blocks in `main.rs:180`.

The clean solution would of course be to offer blocks a way to remove themselves entirely, but that seems overly complicated and would probably break a few assumptions.

**Comment by GladOSkar** [comment]
@atheriel  The way to do it is probably yo tint the blocks after they have been rendered and not before. But that would of course require more computation because the tint is calculated on every update, not just when creating the blocks.

**Comment by ammgws** [comment]
If it's not that big of a computation then I think we should go for it
