### ISSUE TITLE
Clicking time block makes zombie processes with `on_click` option

### ISSUE THREAD

**Issue by xnuk** [greshake/i3status-rust#355]
### Configuration:
```
[[block]]
block = "time"
interval = 5
format = "%Y %-jth, %a, %-m/%d %R"
on_click = "gsimplecal"
```
[`gsimplecal`](https://github.com/dmedvinsky/gsimplecal) is a pop-up calendar program. When I click time block in `i3status-rs` then `gsimplecal` shows well, but after closing it (by Ctrl-w or Ctrl-q or whatever) it seems to make zombie processes, one zombie per each try. I don't think it's `gsimplecal`'s issue; manually running it in command line doesn't creates a zombie process.

### Maybe related code:
https://github.com/greshake/i3status-rust/blob/b3146bcbdbcca79fd1daba675205324284f90cbd/src/blocks/time.rs#L100-L108

**Comment by frececroka** [comment]
The fix is to wait for the created child to finish (see https://doc.rust-lang.org/std/process/struct.Child.html#method.wait). Looking through the code base, I saw that the sound block has the same problem.

I'll try to submit a fix.

**Comment by atheriel** [comment]
Nice detective work. :+1:
