### ISSUE TITLE
Multiple Separators [Feature Request]

### ISSUE THREAD

**Issue by Th3Whit3Wolf** [greshake/i3status-rust#363]
## Multiple Separators
In your documentation I couldn't find any documentation regard multiple separators which is unfortunate.

I would like to make something like this...
![img](https://i.redd.it/l7nduug3fcr21.png)

Is this something that you would like to pursue?

**Comment by atheriel** [comment]
There are some ways you can fiddle with the separator character (see [the wiki](https://github.com/greshake/i3status-rust/wiki/Theming-&-Icons)), but I don't think this kind of stuff is currently possible.

**Comment by GladOSkar** [comment]
@Th3Whit3Wolf I assume you would use [`powerline-extra-symbols`](https://github.com/ryanoasis/powerline-extra-symbols), and then set

```
[theme.overrides]
separator = "<separator char here>"
```

Finally, for the "double" separators i think you could just insert empty blocks using the `custom` block.

**Comment by Th3Whit3Wolf** [comment]
I see, I will try to implement this this weekend. If you would be interested I will send you a screenshot so that you could showcase as an example of what i3-status-rust is capable of.

**Comment by Th3Whit3Wolf** [comment]
I was unable to complete this task at this time.
