### ISSUE TITLE
[sway] Internal error in context 'util'

### ISSUE THREAD

**Issue by Sangeppato** [greshake/i3status-rust#364]
On sway, I get the following error when I try to use i3status-rust, with both the default configuration and a simpler one, I get the following [error](https://imgur.com/a/8nw3F2Z). The package was installed on Arch Linux with i3status-rust-git from the AUR, thanks

**Comment by atheriel** [comment]
Can you run the program directly in a terminal? It will print out a better error in that case. You can also use `RUST_BACKTRACE=1` to get more information.

**Comment by Sangeppato** [comment]
Actually I don't get any error running it from the shell... This actually makes me think that the problem is on the sway side

**Comment by atheriel** [comment]
Can you post the bar part of your Sway config?

**Comment by atheriel** [comment]
Closing this due to perceived inactivity. Feel free to reopen if you think there's something more to address.

**Comment by r3drock** [comment]
I get the exact same error, also with sway on arch linux. I compiled from source.
When ran in terminal:
```sh
~ ./i3status-rs $HOME/.config/sway/config.toml
{"version": 1, "click_events": true}
[[{"background":"#000000","color":"#dc322f","full_text":" Internal error in context 'util': failed to open file.\nCause: No such file or directory (os error 2) ","separator":false,"separator_block_width":0}]


Internal error in context 'util': failed to open file.
Cause: No such file or directory (os error 2)
```
But the program does not close after the error, it just halts.
So I don't know how to make a backtrace.

**Comment by r3drock** [comment]
I see my mistake now: I named my config config.toml and referenced it as status.toml in my sway config.
After fixing this it all works nicely.

**Comment by r3drock** [comment]
This error had been way easier to see for me, when the errormessage told me which file was missing.
I changed the error message to tell me which file was missing.

**Comment by atheriel** [comment]
I suppose it is obvious to us but not to a user that "failed to open file" can only mean "failed to open the config file", since the config file is the only file we actually open. We should indeed try to fix this.
