### ISSUE TITLE
Automatically keep Weather block location up-to-date

### ISSUE THREAD

**Issue by atheriel** [greshake/i3status-rust#367]
At the moment you need to hard-code your City ID to use the OpenWeatherMap API, so when you're traveling the weather information will obviously be incorrect.

As a possible solution, the `GeoClue2` program does provide [a D-Bus API](https://www.freedesktop.org/software/geoclue/docs/ref-dbus.html) for reporting/updating the user's location. Not everyone has GeoClue installed, but we could make use of it if present. The location information provided by GeoClue is in the form of longitude/latititude, which the OpenWeatherMap API [supports](https://openweathermap.org/current).

**Comment by GladOSkar** [comment]
Since the weather block needs an internet connection anyway - why not use a geolocation api that uses the IP?

**Comment by atheriel** [comment]
That's a much simpler solution. Is there a geolocation service with a decent reputation we could use?

**Comment by GladOSkar** [comment]
@atheriel I have not been able to find a service that does not require an API Key, which would add additional complexity...

**Comment by crablab** [comment]
https://ipapi.co provide 30,000 requests per month with no API key required :+1:
