### ISSUE TITLE
Temperature block colour ignoring threshold

### ISSUE THREAD

**Issue by cameronswinoga** [greshake/i3status-rust#378]
![i3status-rs-bug](https://user-images.githubusercontent.com/1660815/57466560-ec5c5380-724e-11e9-9aff-a1a44249bbb0.png)

As seen in the image, my thresholds are set and the temperature block is ignoring them and constantly at the red "critical" colour. This issue persists without custom thresholds and just the defaults.

**Comment by atheriel** [comment]
Are you actually using version 0.9 or are you building from master?

**Comment by cameronswinoga** [comment]
Ah sorry, I am building from master.

**Comment by cameronswinoga** [comment]
So I found the reason why this is happening. I printed out the temperatures that the block is retrieving from my hardware:
```
temperatures: [34, 41, 0, 33, 31, 29, 127, 38, 37, 37, 35]
min: 0
max: 127
avg: 40
```
So even through the text is displaying the average temperature, the minimum and maximum temperatures are erroneous measurements from `sensor`. The colouring of the block only takes into account the maximum temperature (127), therefore it will always display as the critical colour.

[There are temperature limits in place](https://github.com/greshake/i3status-rust/blob/c0dba4a2ffa20f484be2616d451f040533b4f33f/src/blocks/temperature.rs#L134), but they are set to the range [-100, 150] (not sure why these values). I think a reasonable solution would be to change these limits to be user-configurable, or perhaps just to [0, 127].

**Comment by atheriel** [comment]
The temperature lower bound does seem rather odd, I can't image normal hardware would operate at -100 C. But I do not believe we should attempt to detect fixes for potentially faulty hardware sensors -- that seems to me to belong firmly in the realm of `lm_sensors` itself.

**Comment by cameronswinoga** [comment]
Alright, that's a fair decision. I've been reading up on [lm-sensors configuration](http://www.lm-sensors.org/wiki/man/sensors.conf) and I see now how to correct for the faulty readings. At first glance as a user this definitely seems like a bug though, on account of how the `avg` is used for text but `max` is used for colour.

Could I add a small explanation to the temperature section blocks.md of how it pulls from lm-sensors? I (wrongly) assumed that i3status-rust was doing the temperature polling manually and for situations like this it helps a lot to have that transparency upfront, instead of digging through the source code.

**Comment by atheriel** [comment]
Yep, I'm quite happy to see additions to the block documentation for these ambiguities.
