### ISSUE TITLE
CPU usage bars

### ISSUE THREAD

**Issue by fbreitwieser** [greshake/i3status-rust#379]
Thanks a lot for i3status-rust, really like it!

In my previous bar configuration with another tool, I configured to have a small barplot for CPU utilization with a separate UTF block character for each core's CPU utlization.

E.g., on my 4-core laptop, it would show something like '▇▅▁▁' if the first two cores are in use and the last two cores aren't. [Additionally, it would color the blocks individually; e.g. the first block would be red in this example and the second one orange.]

i3status-rust uses UTF ramp characters so far for different levels of the blacklight and volume. What do you think about adding that functionality to the cpu module, especially with separate characters for each core? I could make a pull request. What do you think would be the best way to support it? E.g. with a format key?

**Comment by fbreitwieser** [comment]
I made an implementation that adds this kind of barchart. It adds a format option, and with `{barchart} {utilization}% {frequency}GHz` it shows the following:

![image](https://user-images.githubusercontent.com/516060/57661096-74c45680-75b7-11e9-8f34-d6a104193fa1.png)
![image](https://user-images.githubusercontent.com/516060/57661196-c53bb400-75b7-11e9-9aeb-ecbe75a73819.png)

I can submit a pull request after polishing up the code. To do that - Is there a good way to ask a FormatTemplate whether it has a key?

**Comment by atheriel** [comment]
This looks like a neat feature, we'd be happy to have your PR. `FormatTemplate` is a bit limited at the moment, unfortunately.

**Comment by fbreitwieser** [comment]
Cool, will submit it. Right now I have the following block in `update` to set `has_frequency` and `has_barchart`. I could put the functionality into a `FormatTemplate` method `pub fn has_vars(Vec<&'static str>) -> Vec<bool>`, or something like that:
 
```rust
impl Block for Cpu {
    fn update(&mut self) -> Result<Option<Duration>> {
        if self.first_update {
            let mut fmt = &self.format;
            loop {
                match fmt {
                    FormatTemplate::Var(ref s, ref next) => {
                        match &s as &str {
                            "{frequency}" => { self.has_frequency = true; },
                            "{barchart}" =>  { self.has_barchart = true; },
                            _ => {},
                        }
                        if let Some(fmt1) = next {
                            fmt = fmt1;
                        } else {
                            break;
                        }
                    }
                    FormatTemplate::Str(ref s, ref next) => {
                        if let Some(fmt1) = next {
                            fmt = fmt1;
                        } else {
                            break;
                        }
                    }
                }
            }
        }
        self.first_update = false;
        ...
    }
}
```
