### ISSUE TITLE
Man page

### ISSUE THREAD

**Issue by crozbo** [greshake/i3status-rust#380]
It will be nice to have terminal/offline help, man pages or just pure terminal commands for information's like in wiki pages. Listing available blocks, themes, and icons, blocks, blocks options, theme colors...

**Comment by atheriel** [comment]
Yes, I think having a `man` page would be a nice addition. It should be possible to produce one from the existing documentation via Pandoc, too.

**Comment by crablab** [comment]
I'm happy to look into this, but could you explain a little more about a) where the existing docs are b) how you intend to use Pandoc? (I use it solely for markdown/LaTeX conversion) @atheriel

**Comment by atheriel** [comment]
Pandoc can output the man page format, so we could render the existing `blocks.md` documentation as, say, the **CONFIGURATION** section of a man page pretty easily. There is some additional documentation on the wiki as well, although it is not maintained as well as the block documentation.

**Comment by crablab** [comment]
I have a draft PR #391 to do this. 

The man page is generate by the CI. How do we want to 'deploy' this or otherwise commit back to the repo?
