### ISSUE TITLE
Make network block's spacing consistent

### ISSUE THREAD

**Issue by B4rc1** [greshake/i3status-rust#381]
The network block is in its current state inconsistent in spacing. When the value changes from 10 to 100 for example all blocks to the left of it shift.

I am using FontAwesome and the gruvbox-dark theme.

**Comment by atheriel** [comment]
I believe we set some padding, but this is basically unavoidable unless you have a pretty narrow range of values and a fixed-width font. I'm not sure I consider it a bug.

**Comment by crablab** [comment]
I agree - this isn't a bug. If you want consistent spacing then you have to use a monospace typeface.
