### ISSUE TITLE
Wireless signal quality

### ISSUE THREAD

**Issue by BenFradet** [greshake/i3status-rust#387]
Is there a way to display the wireless signal quality similarly to what was done in i3status?

**Comment by atheriel** [comment]
There is no way to do that at present. If you can figure out how `i3status` does it we could possibly add it, though.

**Comment by BenFradet** [comment]
cool thanks I'll have a peek :+1:

**Comment by rht** [comment]
For reference, https://github.com/i3/i3status/blob/f791b4af3fd250c193c9a165e02305d138222c98/src/print_wireless_info.c#L121, then https://github.com/NetworkManager/NetworkManager/blob/master/src/platform/wifi/nm-wifi-utils-nl80211.c
