### ISSUE TITLE
weather block incorrectly treats missing field as malformed JSON

### ISSUE THREAD

**Issue by maciejjo** [greshake/i3status-rust#395]
Sometimes JSON from openweathermap is missing a field (in case of my location it is "deg" parameter of wind is not present when wind speed is low), which causes whole status to disappear, displaying "Error in block 'weather': Malformed JSON." According to thread on OWM support [1], response with some fields missing is valid and means that given characteristic was not measured.
I think that it would be better if missing field was just omitted in weather block format.

Also, maybe error in block could be displayed in the block itself rather than replacing the whole status? Now when the weather block throws BlockError, the whole status is gone and only the error is shown.

[1] https://openweathermap.desk.com/customer/portal/questions/16989445-how-to-treat-missing-json-fields-

**Comment by atheriel** [comment]
[It looks like](https://serde.rs/attr-default.html) we should be able to handle missing fields with `serde`.
