### ISSUE TITLE
Specify Temperature Device

### ISSUE THREAD

**Issue by ibrokemypie** [greshake/i3status-rust#398]
Currently it seems like temperature draws from all devices inlm_sensors, which isnt particularly useful if you want to see your average CPU temperature but its including your GPU temperature in the average, any chance you could add an option to specify which device to draw from?

**Comment by atheriel** [comment]
I believe `lm_sensors` supports filtering on the type of "chip", which would probably give you what you want. I'd be happy to see a `chip` parameter added to the configuration to support this.
