### ISSUE TITLE
Text interpreted as icons

### ISSUE THREAD

**Issue by tomberek** [greshake/i3status-rust#409]
Things like the day or WiFi SSID are interpreted with icons if they happen to have special words in them. Eg.

Sunday => 'Sun'day => <Sun icon>day

**Comment by ammgws** [comment]
@tomberek Is this specific to the SSID part of the `net` block or does it occur elsewhere too? I couldn't reproduce it by having "Sunday" in the `time` block for example.

**Comment by ammgws** [comment]
![image](https://user-images.githubusercontent.com/20397027/80815198-25cc6280-8c08-11ea-91c3-b79573703fdd.png)

I can't reproduce on sway. Using a virtual wireless device/AP with the SSID set to "Sunday", and it displays properly.
