### ISSUE TITLE
language_locale doesn't work with nixos

### ISSUE THREAD

**Issue by ezemtsov** [greshake/i3status-rust#416]
Locale is not shown correctly with both drivers setxkbmap and localebus

With localebus the block shows a list of configured locale (us,ru)
With setxkbmap the block shows one value staticly and no changes.

Currently I've configured it to work well with custom block
[[block]]
block = "custom"
command = "xkblayout-state print %s"
interval = 5

But could be nice to have it working properly with localebus

**Comment by atheriel** [comment]
How do you change your keyboard layout on NixOS?

Related: #404.

**Comment by ezemtsov** [comment]
Hi @atheriel 
Here's the code from my nixos config:
`      # Keyboard options
      layout = "us,ru";
      xkbOptions = "grp:caps_toggle";`

Here's response from setxkbmap -query:
`rules:      evdev
model:      pc104
layout:     us, ru
options:    grp:caps_toggle`

**Comment by sashomasho** [comment]
I've tried to implement something for exact this scenario and yesterday it was merged (thanks Aaron), so you may try the new driver kbbdbus if you have kbdd installed. 

I have it working with the following lines:
in i3/config:
exec_always setxkbmap -layout us,bg -option "grp:shifts_toggle" 
exec_always pkill kbdd; kbdd

modify keyboard_layout block configuration with:
driver = "kbddbus"

Probably you can skip the first line since you already have it configured somehow.

**Comment by ezemtsov** [comment]
@sashomasho I get error 'unknown variant "kbddbus" .. for key `driver`'
Version is 0.11.0. Also kbddbus variant is not documented. 
I'm I doing something wrong?

**Comment by sashomasho** [comment]
I don't think there has been a new release since it was merged, but you can build i3status-rust yourself from the master branch if you have rust toolchain on your system. 

I'll try to update the documentation, but the only thing you need is to set the block driver and install kbdd on your system.

**Comment by ammgws** [comment]
@ezemtsov Have you tried with the 0.12 release?

**Comment by ezemtsov** [comment]
@ammgws just tried kbdd version with 0.12 release. It works well, thanks!

**Comment by qezz** [comment]
I have the same issue on Ubuntu 18.04. I've been using `kbdd` for a while, it worked fine. But as I understand `kbdd` is limited to per-window keyboard layout management, which IMO is not very convenient to use.

Is there a way to use global keyboard layout? I didn't find anything related in kbdd repo.

**Comment by ezemtsov** [comment]
@qezz I ended up using https://github.com/xkbmon/xkbmon with a custom block.

For anyone else finding this issue, here's an example of i3status rust home-manager config:
```nix
    programs.i3status-rust.enable = true;
    programs.i3status-rust.bars.default = {
      blocks = [
        { block = "net"; format = " $icon {$signal_strength $ssid} "; }
        { block = "disk_space"; }
        { block = "sound"; }
        { block = "time"; interval = 60; }
        { block = "custom"; persistent = true; command = "${pkgs.xkbmon}/bin/xkbmon -u"; }
        { block = "battery"; }
      ];
  };
```
