### ISSUE TITLE
[archlinux] block backlight icon broken

### ISSUE THREAD

**Issue by yw662** [greshake/i3status-rust#417]
AUR package `ttf-font-awesome-4` seems does not have font for `U+1f311` to `U+1f314` (`U+1f315` is surprisingly usable, though), which breaks the icon of backlight.

I am not sure it is just for me or it is for everyone, though.

Maybe, could it use some other characters ?

**Comment by atheriel** [comment]
It's worth noting that you can manually override the icons, which might be a good band-aid in this case.

**Comment by elverskog** [comment]
Per overriding, can someone help with:
1) Is there an icon label/key for the backlight block. I don't see it in the table here https://github.com/greshake/i3status-rust/wiki/Theming-&-Icons
2) Also some help/documentation on how Unicode characters should be entered would be great. 
Is it like a traditional i3 status bar where one pastes the actual character in, like "key = ""?
Or does it want the "code"? For example the fa-sun-o character, FontAwesome4 lists "f185" on their site. Is that what the .toml file wants? Or does it want something with 6 characters like "00f185".
