### ISSUE TITLE
Battery block can't show UPower batteries without battery_ prefix

### ISSUE THREAD

**Issue by freswa** [greshake/i3status-rust#421]
Since #356 while using ```upower``` as ```driver``` anything but ```DisplayDevice``` in ```device``` is treated as a ```battery_``` suffix.
With the following list of batteries, I am not able to read the battery status of my mouse while using UPower
```
 ~ % upower --enumerate
/org/freedesktop/UPower/devices/line_power_AC
/org/freedesktop/UPower/devices/battery_BAT0
/org/freedesktop/UPower/devices/mouse_hidpp_battery_0
/org/freedesktop/UPower/devices/DisplayDevice
```

**Comment by atheriel** [comment]
This is a tricky issue. We use the `battery_` prefix so that the block can use the same device name as `sysfs`, but it's possible we could add more clever logic to support other devices. What does your mouse battery look like in `/sys/class/power_supply`?

**Comment by freswa** [comment]
It's ```hidpp_battery_1``` in ```/sys/class/power_supply```.

**Comment by atheriel** [comment]
Ah, that's unfortunate that it seems inconsistent. It should be possible to make the block first check for the device name exactly, and then fall back on inserting a `battery_` prefix, though.
