### ISSUE TITLE
blocks/sound: volume differs

### ISSUE THREAD

**Issue by rsteube** [greshake/i3status-rust#422]
On my machine the volume differs from alsamixer and volume applet (also won't go down to 0%) as discussed here: https://bbs.archlinux.org/viewtopic.php?pid=1114261#p1114261.
To get the correct volume i needed to use the `mapped-volume` option of amixer: https://github.com/rsteube/i3status-rust/commit/f56d6a15eb24c85a907c366fd8f25267351aae1e

Maybe add an option to activate this?

**Comment by atheriel** [comment]
This seems sensible. Would enabling it by default affect other users?

**Comment by rsteube** [comment]
Anyone that uses the AlsaAudioDevice backend (and not PulseAudio).
Can't say for sure but from what i'm reading about the `mapped-volume` option it seems rather to be the value that is desired. Especially since it is what is shown in alsamixer.

**Comment by ammgws** [comment]
Looks like this [was also an issue](https://github.com/vivien/i3blocks/pull/254) in i3blocks, and the solution was the same.

@rsteube how about submitting a PR?
