### ISSUE TITLE
Discussion: New block to support nordvpn (status, connecting, disconnecting)

### ISSUE THREAD

**Issue by whois-max** [greshake/i3status-rust#424]
Hey there,

i3status-rust is amazing, and I would love to contribute to this project. I am pretty new to rust, so I think this feature would not be too hard to implement.

Let me explain, what I would like to do:

I am a nordvpn user. A while ago the company published a nordvpn CLI client for linux. It is kind of basic, but I think it does everything that an ordinary user likes to use.

So, I plan to create a button which shows the status of nordvpn. The on_click event will connect/disconnect to the nordvpn features. An additional parameter can be the country in which the server should stand. 

Well, the README advises to first discuss new blocks. So, feel free to comment. I would like to add this feature to the collection of blocks and hope that it will help more people than just me.

Thanks for sharing your thoughts!
Max

**Comment by ammgws** [comment]
Have you tried using a `custom` block? It's what I'm using to display the status for a Wireguard connection with another provider.

**Comment by atheriel** [comment]
@ammgws Can you post an example of what your block looks like? It might help the discussion.

**Comment by ammgws** [comment]
I have my custom block running [this](https://github.com/ammgws/dotfiles/blob/master/fish/.config/fish/functions/check_vpn.fish) shell script which uses my VPN provider's API to determine if I'm connected or not and output some pango text to be displayed in the bar. (I'll probably stop using this once the net block gets wg support)

**Comment by coskunkut** [comment]
I use a toggle block for vpn connection and it is beautiful.

```
[[block]]
block = "toggle"
text = "VPN"
command_state = "~/.config/i3/vpn.sh status"
command_on = "~/.config/i3/vpn.sh toggle"
command_off = "~/.config/i3/vpn.sh toggle"
interval = 5
```

And `vpn.sh` is something like this.
```
#!/usr/bin/env bash

vpn="kut-dt"

if [[ "${1}" == "status" ]]; then
	if nmcli -t con show $vpn | grep -qi 'VPN connected'; then
		echo ""
	else
		echo ""
	fi

elif [[ "${1}" == "toggle" ]]; then
	if nmcli -t con show $vpn | grep -qi 'VPN connected'; then
		nmcli con down $vpn
		notify-send "VPN Down"
	else
		nmcli con up $vpn
		notify-send "VPN Active"
	fi
fi

```

**Comment by ammgws** [comment]
@whois-max Please re-open if the alternative methods mentioned above don't work for you.
