### ISSUE TITLE
MouseButton enum not working for others than LeftClick

### ISSUE THREAD

**Issue by Drogglbecher** [greshake/i3status-rust#43]
I want to implement scrolling features for xrand but it looks like all other buttons expect of LeftClick have no effect. For simplicity I changed the `... event.button == MouseButton::LeftClick...` in memory.rs:443 to `... event.button == MouseButton::RightClick...` but in the bar nothing happens when clicking the right button. 
Did I forgot something?

**Comment by greshake** [comment]
Some numbers were switched up, and if clicked with some unknown button the input handeling thread crashed. What you saw could have been either issue mixed up, just try again now, and thanks for pointing this out.
