### ISSUE TITLE
battery block: consider battery crate

### ISSUE THREAD

**Issue by matthiaskrgr** [greshake/i3status-rust#440]
There's a [battery crate](https://crates.io/crates/battery), and looking [the api](https://docs.rs/battery/0.7.4/battery/struct.Battery.html) it might be possible to simplify the battery block quite a bit.

**Comment by ohk2kt3t4** [comment]
Good find. Looks like it will introduce four new dependencies:
```
[dependencies]
cfg-if = "0.1"
num-traits = { version = "0.2", default_features = false }
uom = { version = "^0.23", features = ["autoconvert", "f32", "si"] }
[target.'cfg(target_os = "linux")'.dependencies]
lazycell = "1.2.1"
```

**Comment by travankor** [comment]
[It](https://github.com/svartalf/rust-battery/blob/master/battery/src/platform/linux/sysfs/source.rs#L250) won't solve #429, but maybe in a few months hopefully.

**Comment by atheriel** [comment]
Are there advantages other than simplicity? The current code seems to work pretty well.

**Comment by marc0der** [comment]
The current implementation is a bit brittle since it merely uses the textual output of `sensors`, making a lot of assumptions about the format of it's output. In fact, with the latest update of Manjaro on 2019-10-10 it has stopped working because the minimum temperature is always inferred as `0`.

**Comment by Fuzen-py** [comment]
Looking into this project a bit, this appears to solve #463 if this crate is used to fetch Bluetooth device battery. I do find this to be a step in the right direction regardless as this would open up more opportunities for cross-platform support as long as the status bar support i3-status format.

**Comment by atheriel** [comment]
Cross-platform support in this case being FreeBSD support (#296), I imagine? It's possible we'll get there someday but for now there is a mountain of Linux-specific code in this project.

> this appears to solve #463 if this crate is used to fetch Bluetooth device battery

I can't see support for Bluetooth (or UPower, for that matter) in the source of the crate, have I missed something?

**Comment by Fuzen-py** [comment]
> Cross-platform support in this case being FreeBSD support (#296), I imagine? It's possible we'll get there someday but for now there is a mountain of Linux-specific code in this project.

I wasn't referring to any specific platform, this crate, in general, would reduce some of the Linux specific code that exists. After some further investigation, the current feature set seems to be a step backwards as it only supports
> I can't see support for Bluetooth (or UPower, for that matter) in the source of the crate, have I missed something?

There is reference to UPower [here](https://github.com/svartalf/rust-battery/blob/08b2ad579d135dbe48d52ff31a35df307c173eb6/battery/src/platform/linux/sysfs/source.rs#L201), I appear to have been mistaken on it helping with #463 as it doesn't seem to support Bluetooth, I incorrectly assumed it supported such devices.

**Comment by wucke13** [comment]
The battery crate introduced some 0.5%~1% load on a similar project of mine, with an interval of 1 second. One should evaluate whether it can be used without this hit

**Comment by ammgws** [comment]
Closing until a more compelling case is made.
