### ISSUE TITLE
music block blank on fedora 30 with mpd and mpDris2

### ISSUE THREAD

**Issue by ibotty** [greshake/i3status-rust#441]
I can see useful traffic via dbus-monitor in session bus, e.g.

```
method call time=1568269972.557250 sender=:1.14285 -> destination=org.mpris.MediaPlayer2.mpd serial=318 path=/org/mpris/MediaPlayer2; interface=org.freedesktop.DBus.Properties; member=Get
   string "org.mpris.MediaPlayer2.Player"
   string "PlaybackStatus"
method return time=1568269972.559454 sender=:1.3 -> destination=:1.14285 serial=228159 reply_serial=318
   variant       string "Playing"
```

But unfortunately the music block is blank, it only displays the music icon.

Any Idea on what's wrong?

This is on `0.10.0` as well as on master as of today (2019-09-12: f90bc9874d060a24276c2808275f4068d30ba47b).

**Comment by ibotty** [comment]
Oh, and how come that the master version identifies as "0.9": `src/main.rs:66:        .version("0.9")`?

**Comment by rtxm** [comment]
Sometimes I have to restart the WM / i3status-rust after the music player starts playing.

**Comment by atheriel** [comment]
Can you confirm that this happens when you only have the one block?

**Comment by ibotty** [comment]
Unfortunately, restarting i3status-rs does not fix anything.

**Comment by ibotty** [comment]
I checked and if the music block is the only one, it exhibits the same problem.  Is there anything I can do to debug this issue?

**Comment by rtxm** [comment]
What's in your configuration file?

**Comment by ibotty** [comment]
``
theme = "solarized-dark"
icons = "awesome"

[[block]]
block = "music"
#player = "mpd"
buttons = ["prev", "play", "next"]
```

but it happens without buttons and with specified player.

**Comment by rtxm** [comment]
What's your pulseaudio version?

**Comment by ibotty** [comment]
I don't see how that's relevant, because the volume widget works and the music block does not use pulseaudio afaict.

Anyway: my Pulseaudio version is `pulseaudio-12.2-9.fc30.x86_64`.

**Comment by ibotty** [comment]
Sorry that sounded more harsh than intended.  I do guess it's not because of pulseaudio though.

**Comment by rtxm** [comment]
Sorry, you're right, I was thinking dbus but wrote pulseaudio, the "music" keyword effect maybe (already tired on Tuesday!)

**Comment by rtxm** [comment]
I don't know if it's relevant, but I don't have `dbus-broker` here.

**Comment by Rikorose** [comment]
I had the same problem. I installed it via the copr, mentioned in the readme. Compiling it from source however works for me.

**Comment by rtxm** [comment]
@ibotty Do you have Chrome or another MPRIS player open before you launch your mpd player?

Currently, the block detects the first active player and sticks with it until the player exits.  

Chrome/Chromium (and maybe Firefox?) is such a player and if I've been on a site with audio content before launching my favourite player, the music block won't display what the latter is playing.

**Comment by Rikorose** [comment]
I am not ibotty, but I will answer anyway.

I do not have any other player open. The compiled master version reliably finds the active spotify, the copr 0.11 version does not work however. Master and copr are sending the same dbus requests, as far as I can tell.

**Comment by ibotty** [comment]
I am, but I can tell that there is only one MPRIS player registered on dbus.

**Comment by atheriel** [comment]
@Rikorose The distro packaging (including COPR) is done by community members, so we can't really support them. Best if you can find a way to file an issue with the downstream maintainer in this case.

**Comment by atheriel** [comment]
Can folks try out #561 to see if it fixes this issue for them?
