### ISSUE TITLE
Feature request: show placeholders for empty workspaces

### ISSUE THREAD

**Issue by Ploppz** [greshake/i3status-rust#442]
My suggestion is to have an option to just show a sort of grayed-out desktop indicator on desktops that are empty. For example, say you have windows on desktops 1 and 8: then the status bar can show 1 and 8 just like now, but put 6 boxes between 1 and 8 and one to the right of 8, all of which are grayed out just to visualize the logical placement of the existing workspaces. Possibly with numbers as well.
I want this because it makes it easy to see which numbers are available for a new workspace, and it makes the horizontal position of a workspace in the status bar constant, which imo makes for easier management of workspaces.
I can give it a try if you agree, and if it's doable.
As for multiple monitors, I would personally only use this feature on my single-monitor setup and disable it for multi-monitor setups, so not sure how the behaviour should be there.

**Comment by atheriel** [comment]
This sounds reasonable, but would need an opt-in configuration option -- e.g. `show_empty = true`.

**Comment by ammgws** [comment]
AFAIK the workspace part of the bar is generated by i3bar/swaybar and not us. Please re-open if I'm wrong.
