### ISSUE TITLE
Support strip_workspace_numbers yes

### ISSUE THREAD

**Issue by technatica** [greshake/i3status-rust#444]
i3status allows the number to be stripped from workspace titles. Adding this parameter to the bar block with i3status-rust causes errors.

bar {
        # remove workspaces numbers
        strip_workspace_numbers yes
}

**Comment by atheriel** [comment]
Can you give some indication of the errors you see?

**Comment by technatica** [comment]
Ahhh, my bad. I put it in the color block. It works, thanks.
