### ISSUE TITLE
Releasing 0.11.0

### ISSUE THREAD

**Issue by atheriel** [greshake/i3status-rust#446]
Version `0.10.0` was tagged on July 14, over two months ago. We've got some nice new features and a few fixes in master since that time -- @greshake do you have any objection to me cutting `0.11.0` and writing some release notes? I was also able to build a `.deb` locally, which we could use to distribute binaries.

I think I'd prefer to see us release regularly rather than working towards specific milestones.

**Comment by greshake** [comment]
No, I'm fine with that. Thank you! :)

**Comment by atheriel** [comment]
Released. I attached a `.deb` file if anyone wants to try that out and report any issues with it.
