### ISSUE TITLE
Why backlight block monitors `brightness` not `actual_brightness`?

### ISSUE THREAD

**Issue by shunlir** [greshake/i3status-rust#447]
I happen to have a laptop, inotify can't get event from `/sys/class/backlight/brightness`, but `/sys/class/backlight/actual_brightness`, even through they both change when I change brightness through laptop shortcut keys.
Is it possible to make the filename to be monitored configurable?

**Comment by atheriel** [comment]
A couple questions:

1. What program are you using to change the brightness?
2. What kind of laptop?
3. Can you change the brightness by writing to the `brightness` file directly? (This may require elevated permissions.)

I don't believe that `inotify` is guaranteed to work with `sysfs` -- it just happens to work most of the time.

**Comment by shunlir** [comment]
@atheriel 
My answers:
1. The multi-media keys; or change `brightness` file in sysfs, the backlight of screen works well
2. Dell Inspiron 1420, with Nvidia GeForce 8400M GS, proprietary driver.
3. Yes. it works. however, MouseButton::WheelUp/Down doesn't work, no error messages (I'm not sure where to check error message).

I see `backlight` block use inotify to watch modification of `brightness` file (https://github.com/greshake/i3status-rust/blob/master/src/blocks/backlight.rs#L201)

**Comment by ammgws** [comment]
> Is it possible to make the filename to be monitored configurable?
>MouseButton::WheelUp/Down doesn't work, no error messages (I'm not sure where to check error message).

This could possibly be added, however it won't solve the issue of not being able to set the brightness itself.

**Comment by ammgws** [comment]
@shunlir Did you try this from our docs?

### Setting Brightness with the Mouse Wheel

The block allows for setting brightness with the mouse wheel. However, depending on how you installed i3status-rust, it may not have the appropriate permissions to modify these files, and will fail silently. To remedy this you can write a `udev` rule for your system (if you are comfortable doing so).

First, check that your user is a member of the "video" group using the `groups` command. Then add a rule in the `/etc/udev/rules.d/` directory containing the following, for example in `backlight.rules`:

```
ACTION=="add", SUBSYSTEM=="backlight", GROUP="video", MODE="0664"
```

This will allow the video group to modify all backlight devices. You will also need to restart for this rule to take effect.
