### ISSUE TITLE
Change colors block

### ISSUE THREAD

**Issue by lckrspirit** [greshake/i3status-rust#460]
Please tell me how to change the color of a single block? Is it possible to turn off the backlight of the blocks?
Thanks.

**Comment by lckrspirit** [comment]
I solved my problem by applying the information from the module- [Available theme overrides](https://github.com/greshake/i3status-rust/blob/master/themes.md)

**Comment by ammgws** [comment]
@lckrspirit FYI #947 may be of interest to you (for per-block colour customisation)
