### ISSUE TITLE
Provide a default config file paths

### ISSUE THREAD

**Issue by roipoussiere** [greshake/i3status-rust#465]
`i3status-rs` could look in default paths if no configuration file is given in CLI arguments.

Suggested paths:
- `.config/i3status-rs/config.toml`
- `$XDG_CONFIG_HOME/i3status-rs/config.toml`
- `.i3status-rs.toml`

**Comment by atheriel** [comment]
I'm supportive of this, although I think `i3status-rust` would be preferred over `i3status-rs`. Reading from `$XDG_CONFIG_HOME` is actually implemented in #366, and could be integrated into the CLI pretty easily.

However, it is possible that @greshake had a reason at the time for requiring that the path is explicitly passed to the CLI, and he may object.
