### ISSUE TITLE
status line Does not cover the i3 bar fully.

### ISSUE THREAD

**Issue by ReductoAdAbsurdum** [greshake/i3status-rust#471]
I have : 
theme = "gruvbox-dark"
icons = "awesome"
but the status bar does not cover the i3bar fully...The background color for the bar is blueish and with  all of the themes except solarized-light I can see a thin blue line on top of the status bar.

**Comment by GladOSkar** [comment]
This is implemented this way in `i3` and `i3status-rust` has no control over it.

`i3` does not intend to make this configurable: https://github.com/i3/i3/issues/2358

Here's Airblader's patch for `i3` that removes the pixel lines: https://gist.github.com/Airblader/72d6a03d05c111d33ad4

Cheers :)

**Comment by atheriel** [comment]
@GladOSkar is correct, this is beyond our ability to control unfortunately.
