### ISSUE TITLE
Not all blocks display a background color.

### ISSUE THREAD

**Issue by HugoForrat** [greshake/i3status-rust#482]
Hello,

There seems to be a problem with the displaying of colors since only two of my blocks have a background color.

![i3rust1](https://user-images.githubusercontent.com/43822304/70742083-0f873e00-1d1d-11ea-9314-c5a2908c3467.png)

I use i3 on Arch Linux.
If it is relevant, I have built i3status-rust myself.

The problem probably isn't related to the theme since I have tried with another one and without any, and the same blocks are colored.

![i3rust2](https://user-images.githubusercontent.com/43822304/70742084-0f873e00-1d1d-11ea-868e-e5fee8301ee9.png)
![i3rust3](https://user-images.githubusercontent.com/43822304/70742085-101fd480-1d1d-11ea-8a99-e69263072792.png)

Here is the "bar block" of my i3 config file, pretty much the same as the one in the README.md.

```
bar {
	# status_command i3status
	font pango:DejaVu Sans Mono, FontAwesome 9
    position top
    status_command /home/hugo/.bin/i3status-rs /home/hugo/.config/i3/i3status-rs.toml
    colors {
		separator #666666
		background #222222
		statusline #dddddd
		focused_workspace #0088CC #0088CC #ffffff
		active_workspace #333333 #333333 #ffffff
		inactive_workspace #333333 #333333 #888888
		urgent_workspace #2f343a #900000 #ffffff
    }
}
```

I have tried to comment out the `colors` block inside, but this doesn't seem to change anything.

And here is my i3status-rust config file.
```

theme = "solarized-dark"
icons = "awesome"

[[block]]
block = "backlight"
device = "intel_backlight"

[[block]]
block = "battery"
interval = 10
format = "{percentage}% {time}"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "xrandr"
icons = true
interval = 2

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"
```

Thanks for your help.

**Comment by GladOSkar** [comment]
This is intentional.

In most themes by default, only blocks that want to actively announce information are colored. In your case those are your root partition is low on space and your battery is full.

Whenever one of the other blocks has something to say, it will become colorful, for example for high CPU usage.

What were you expecting? I'm curious.

**Comment by HugoForrat** [comment]
Ah yes indeed, I'm sorry for misunderstanding. I've actually noticed the high CPU usage after posting this.

I guess I was expecting something like what's shown in the screenshot in the README with more contrast between blocks.

Thanks for your response.

**Comment by ammgws** [comment]
@HugoForrat FYI with #947 you will be able to define colours on a per-block basis

**Comment by HugoForrat** [comment]
> @HugoForrat FYI with #947 you will be able to define colours on a per-block basis

Oh that's nice, thanks for the work, hope this will be merged !
