### ISSUE TITLE
[Questions] how to add another bar without workspaces and align blocks

### ISSUE THREAD

**Issue by templis** [greshake/i3status-rust#495]
I want to have a second top bar, but without the workspaces.
How can I manage this?

My second question points to block alignment. I would like to have Date/Time in my top bar in the middle instead of the right corner. Is there any workaround to align those blocks?

**Comment by atheriel** [comment]
Neither of these is in the scope of this project, unfortunately.

1. You are limited by [the bar positions that i3 supports](https://i3wm.org/docs/userguide.html#i3bar_position), so I don't think it is possible to have two bars.

2. "In the middle" positioning of the kind you are imagining is not possible under the i3 bar protocol.

**Comment by templis** [comment]
>     1. You are limited by [the bar positions that i3 supports](https://i3wm.org/docs/userguide.html#i3bar_position), so I don't think it is possible to have two bars.

but I already have two bars. :) 
I only want to have my top bar without the workspace block.
But it's okay, i can also use another bar for my top bar.

>     2. "In the middle" positioning of the kind you are imagining is not possible under the i3 bar protocol.
from your posted link:

>  align
> 
>     Align text on the center, right or left (default) of the block, when the minimum width of the latter, specified by the min_width key, is not reached.

**Comment by atheriel** [comment]
> I only want to have my top bar without the workspace block.

Your original question was not so clear -- I assumed "second top bar" meant that you wanted two top bars. There does [seem to be](https://i3wm.org/docs/userguide.html#_workspace_buttons) support for turning off workspace buttons in i3, if that's what you're after. Nothing special from us, though.

And FWIW, you've misinterpreted the `align` parameter: it refers to alignment within blocks, not on the bar itself.

**Comment by templis** [comment]
> Your original question was not so clear -- I assumed "second top bar" meant that you wanted two top bars. There does seem to be support for turning off workspace buttons in i3, if that's what you're after. Nothing special from us, though.

Thank you for pointing me to this.
I've added to my top bar:
`tray_output none`
`workspace_buttons no`
now it does what it should do

> And FWIW, you've misinterpreted the align parameter: it refers to alignment within blocks, not on the bar itself.

I initally wanted to have my clock in the middle of the top bar but now I've added some more inforamtions to that top bar so there is anyways no place in the middle - so I'm fine with a right aligned clock. :)

Whish you a happy new year and thank you for pointing me to the right links.
