### ISSUE TITLE
Music pauses when going full-screen

### ISSUE THREAD

**Issue by WhoMeNope** [greshake/i3status-rust#503]
Using the music block like this:
```
[[block]]
block = "music"
on_collapsed_click = "spotify"
```
After clicking on it to launch `spotify` and starting music playback, 
going full-screen in i3 will cause it to pause music/freeze.

I reckon this is caused because spotify is lauched as a child process of i3status-rust, and going full-screen suspends both processes.

Launching spotify by other means, avoids this issue, but loses the convenience of the single interface for music control.

---

```
$ i3status-rs --version
i3status-rs 0.12.0
```

**Comment by atheriel** [comment]
I'm not sure we can actually fix this... what about using `exec spotify` instead?

**Comment by ammgws** [comment]
Seems related:
https://github.com/i3/i3/issues/3242

**Comment by WhoMeNope** [comment]
@ammgws Yeah that seems to explain it.

Tried out `nohup spotify` and `exec spotify`, the spotify process gets stopped regardless when going full-screen.

I guess that i3 needs to be modified for this, and there is not really anything to be done from here.

**Comment by ammgws** [comment]
Please re-open if there's anything we can do on our side

**Comment by ammgws** [comment]
@WhoMeNope #701 might fix this for you. Let me know if you can give it a go.
