### ISSUE TITLE
Any reason this wouldn't work outside of sway and i3?

### ISSUE THREAD

**Issue by Th3Whit3Wolf** [greshake/i3status-rust#514]
I see in your documentation that you officially support i3 and sway but is it possible to run it on other tiling window managers? I'm attempting to get it work on [leftwm](https://github.com/leftwm/leftwm), a really neat window manager written in rust, and I am having some issues.

**Comment by ammgws** [comment]
It needs to support the i3bar protocol. All this bar does is output JSON which i3/sway process into a bar.

**Comment by Th3Whit3Wolf** [comment]
Oh I see, bummer.
