### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by avronr** [greshake/i3status-rust#537]
Executed:
```shell
cargo build --release
```

and got this error:
```shell
error:` expected one of `!` or `::`, found `std`
 --> src/themes.rs:1:6
  |
1 | xuse std::str::FromStr;
  |      ^^^ expected one of `!` or `::` here

error: aborting due to previous error

error: could not compile `i3status-rs`.
```

**Comment by ammgws** [comment]
Rust 2018 edition?

**Comment by avronr** [comment]
Installed using the script from the rust website.
```shell
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
```

**Comment by ammgws** [comment]
What version is it?

For example the [CI builds](https://travis-ci.org/greshake/i3status-rust/builds/643760069?utm_source=github_status&utm_medium=notification ) that are passing at the moment are running:

```
$ rustc --version
rustc 1.40.0 (73528e339 2019-12-16)

$ rustup --version
rustup 1.21.1 (7832b2ebe 2019-12-20)

$ cargo --version
cargo 1.40.0 (bc8e4c8be 2019-11-22)
```

I have the same versions installed on my system (Arch) and don't experience any build errors either.

**Comment by atheriel** [comment]
Feel free to reopen if you can find the source of the issue.
