### ISSUE TITLE
Intel GPU monitoring block?

### ISSUE THREAD

**Issue by kflak** [greshake/i3status-rust#542]
Hi,

Thanks for a great status bar! I was wondering if somebody has created a block for intel GPU monitoring?

**Comment by atheriel** [comment]
No, I don't think anything like that is available. What kind of block did you have in mind?

**Comment by kflak** [comment]
I'm thinking of a block that would pipe the output of `intel_gpu_top` into the status bar...

**Comment by ammgws** [comment]
Does the custom block not work for that?

**Comment by kflak** [comment]
Ah, didn't notice that one before! This is the command that would (theoretically) do the trick:
```
[[block]]
block = "custom"
command = "intel_gpu_top -l | awk '{print $8}'"
interval = 1
```
However, the intel_gpt_top needs to be run as root, so I am not getting any output. Is there a way around these kinds of issues?

**Comment by ammgws** [comment]
Perhaps you could try adding an entry for it to the sudoers file?

**Comment by kflak** [comment]
Looks like that should do the trick! I'll give it a go as soon as I have a bit more time and (hopefully) close this issue.

**Comment by kflak** [comment]
So, I tried putting my user into the sudoers file, but I still get the error `Failed to initialize PMU! (Permission denied)`, which I guess is far beyond the scope of i3status-rust! Of course, I'm very happy if someone has a solution for this, but I'll take this elsewhere and see what I can figure out! In the meantime, closing this issue.

**Comment by ammgws** [comment]
https://askubuntu.com/questions/159007/how-do-i-run-specific-sudo-commands-without-a-password

Is what you tried something like in the answer to that question?

**Comment by kflak** [comment]
I was following this tip: [https://www.atrixnet.com/allow-an-unprivileged-user-to-run-a-certain-command-with-sudo/](https://www.atrixnet.com/allow-an-unprivileged-user-to-run-a-certain-command-with-sudo/), and added 
```
<user> ALL=(ALL) NOPASSWD: /usr/bin/intel_gpu_top
```
to my sudoers file, below %wheel. Still no joy. Seems like the intel_gpu_top is calling some system function that needs root priviliges....

**Comment by atheriel** [comment]
I've often thought that little examples like this could be added to the Custom block documentation to inspire others.
