### ISSUE TITLE
Execute command on external signal

### ISSUE THREAD

**Issue by teldra** [greshake/i3status-rust#543]
Is it possible to manipulate, "schedule", a block from the outside, like i3blocks[1] and I just overlooked it?
If it is not possible, I think, this is something like a feature request. :)

[1] https://github.com/vivien/i3blocks#signal

**Comment by GladOSkar** [comment]
Related to IPC/Signalling: #77

**Comment by ammgws** [comment]
Closing in favour of #77

**Comment by ammgws** [comment]
@teldra FYI this was implemented via #822

**Comment by teldra** [comment]
@ammgws thank you!
