### ISSUE TITLE
Pulseaudio configuration profile gets out of sync with audio control block

### ISSUE THREAD

**Issue by mankinskin** [greshake/i3status-rust#547]
I am not sure when and where this happens, but often when I come back to my computer after a break (without hibernating, but usually the screen is turned off) the audio control block can not control the volume anymore. I have to open pavucontrol-qt and switch my sound card's configuration profile to something else and back again so that the audio control can control volume again.

My OS is Manjaro Linux. This happens both with my external as with my laptop's internal sound card.

**Comment by ammgws** [comment]
How many screens do you have? Lately I've found that pulseaudio is switching the default sink to one of my HDMI monitors that has speakers (which I don't use), so I keep having to switch it back. Have been meaning to look into it but doubt it has anything to do with i3status

**Comment by mankinskin** [comment]
> How many screens do you have?

I do have an external screen connected with a MiniDisplayport, but that doesn't have any speakers. Although I have also found this occurs frequently when I unplug this screen or when it wakes up from standby. This may aswell be connected to the horrible display management system Linux has. I will try to find out whether the external screen does indeed cause the issue.

**Comment by atheriel** [comment]
I occasionally see this issue under Sway on Manjaro as well, and handle it in the same way. However, I'm almost certain it is not a bug in this particular project, because other things (including my volume hotkeys) break as well.

**Comment by mankinskin** [comment]
Oh I havent even noticed that but you are right, right now I am having the issue and my volume hotkeys don't work aswell. It seems to be something in with pulseaudio I am guessing..
