### ISSUE TITLE
Consider integrating with rust-psutil

### ISSUE THREAD

**Issue by cjbassi** [greshake/i3status-rust#549]
I recently became a maintainer of [rust-psutil](https://github.com/rust-psutil/rust-psutil), and I've been working on polishing it up, and I think it could be a win-win if we use rust-psutil for some of the data fetching. I wouldn't mind opening up some pull requests for doing so. It could clean up some of the i3status code and it could open up the door to better cross-platform support like here: https://github.com/greshake/i3status-rust/issues/296.

**Comment by atheriel** [comment]
My general line on this has been that we should look to external crates if it gives us more features or fewer bugs than the existing implementation, which might be the case here. I'm also cautious about adding crates that introduce a substantial number of transitive dependencies.

**Comment by cjbassi** [comment]
As far as dependencies go, rust-psutil doesn't really have too many and some of its dependencies overlap with i3status-rust.

**Comment by ammgws** [comment]
I see it would also solve issues such as [this](https://github.com/greshake/i3status-rust/issues/749), though it relies on a separate optional crate for that.

Anyway it would be easier to consider this if there was actual code (PR) to look at, so someone please give it a go .
