### ISSUE TITLE
Establish a policy of bumping dependencies as part of the release process

### ISSUE THREAD

**Issue by atheriel** [greshake/i3status-rust#551]
In the past it has been extremely unclear when we should update the versions of dependent crates in our lockfile. I originally proposed a "policy" for dependencies in #272, which now appears in our `CONTRIBUTING.md` file. However, I now think this policy may need an amendment with respect to bumping versions.

As @tim77 pointed out (in #483), Fedora packages are expected to use the latest versions of dependent crates, and other packagers (including @rotty  in #540) have voiced similar concerns. I don't feel amazing about this, especially since one of the virtues of Rust's extremely strict semantic versioning is that package versions carry actual meaning, and don't need to be updated "just because" -- but it's not friendly or fair to fight with downstream packagers about it.

Going forward, I still don't think it's a good idea to bump dependencies at totally random intervals (or whenever we happen to receive a PR doing so). So: I propose that we start bumping dependencies **as part of the release process**, which gives us a precise time and place to do so, and should ease the burden on downstream packagers (who will be dealing with releases, for the most part).

To achieve this, I think we can (1) update `CONTRIBUTING.md` to explain that dependencies are bumped by maintainers as part of the release process to prevent drive-by PRs; and (2) actually remember to bump them when cutting releases.

cc @ammgws, curious to hear your thoughts on this.

**Comment by atheriel** [comment]
I'm also happy to put out a `0.13.1` release with fresh dependencies if that makes sense.

**Comment by atheriel** [comment]
Version `0.13.1` has been released (from the `0.13.x-release` branch) with fresh dependencies and `CONTRIBUTING.md` has been updated.

I rebased and merged the dependency work in #540 by @rotty into the `0.13.x-release` branch and cherry-picked it into `master` as well, for consistency.

**Comment by ammgws** [comment]
I guess it was inevitable given how many times it was requested. Seems like we have +30 more dependencies now though - I'll have a look later when not on mobile to see how that's come about.
