### ISSUE TITLE
Add some tests to Travis CI

### ISSUE THREAD

**Issue by ammgws** [greshake/i3status-rust#555]
Is there a trivial way to run the compiled binary against a simple test config after a successful build?

**Comment by atheriel** [comment]
It should be possible with `--exit-on-error`, yes.

**Comment by ammgws** [comment]
Though if there is no error it would keep running wouldn't it?

**Comment by atheriel** [comment]
Oh, right.

**Comment by atheriel** [comment]
We could maybe add a `--oneshot` mode to render the blocks exactly once.

**Comment by ammgws** [comment]
Or perhaps this could be done using `cargo test`, that way it could be used locally too. There is some discussion [here](https://users.rust-lang.org/t/how-do-you-test-binaries-not-libraries/9554/11) that might shed some light on how to do it.
