### ISSUE TITLE
Migrate to the v0.7 dbus-rs API

### ISSUE THREAD

**Issue by atheriel** [greshake/i3status-rust#557]
As described here: https://github.com/diwic/dbus-rs/blob/master/dbus/changes-in-0.7.md

**Comment by ammgws** [comment]
TODO:
- [ ] KeyboardLayout block
- [ ] NetworkManager block
- [ ] Bluetooth block
- [ ] Music block
- [ ] Battery block
- [ ] Backlight block
- [ ] IBus block
- [x] CustomDBus block
- [x] KDEConnect block

**Comment by ammgws** [comment]
Async branch has now been merged into master (still some work to do before release is possible though), and we are now using the `zbus` crate instead.
