### ISSUE TITLE
Invalid file name in power_supply

### ISSUE THREAD

**Issue by Peltoche** [greshake/i3status-rust#56]
# Config
An Archlinux with a Linux kernel V4.11.7-1

# Issue
The battery block try to open files named `charge_full` and `charge_now` from the `/sys/class/power_supply/BAT{nb}` forlder but with my pc config the files are named `energy_full` and `energy_now`.

Do any other archlinux user have this issue?

# Solution
I changed manually the values and everything work well.

I will propose a PR later with a clean way to do it without creating breaking changes.

**Comment by greshake** [comment]
Thanks for the proper description here, but you could have found https://github.com/greshake/i3status-rust/issues/16 too :) Great if you want to take care of that issue, it was discussed there before

**Comment by Peltoche** [comment]
arf... my bad. 

So it's closed.
