### ISSUE TITLE
Music block not working since last update 

### ISSUE THREAD

**Issue by marzzzello** [greshake/i3status-rust#563]
On the latest release 0.13.1 the music block does not show the song name/artist anymore.
On 0.12.0 it is working normally.
The 0.13.0 release got skipped in AUR but I tested it manually and it is still working there too.
So probably https://github.com/greshake/i3status-rust/commit/03f3549014f070323da257680f0ddd345e842507  is the cause.

**Comment by atheriel** [comment]
I don't have any testing set up for the music block -- can anyone else chime in to confirm this?

**Comment by QDesjardin** [comment]
Music block is blank for me too.

**Comment by atheriel** [comment]
Does #561 solve this issue for you?

**Comment by marzzzello** [comment]
Yes, fixed now
