### ISSUE TITLE
NVIDIA GPU Block - Fixed Utilization Width

### ISSUE THREAD

**Issue by TheJP** [greshake/i3status-rust#564]
I noticed that the gpu utilization does not have a prefixed 0. It is therefore moving blocks that are to the left of it when switching between the 0-9 and 10-99 ranges.

I propose to make it two digits wide by default so it matches the CPU utilization: https://github.com/TheJP/i3status-rust/commit/a72fd8ddf0bb38c823160915f0ed97e70457af58

**Comment by atheriel** [comment]
Sounds good, I'm happy to accept that patch.
