### ISSUE TITLE
[Feature Request] Ability to include other config files

### ISSUE THREAD

**Issue by gjabell** [greshake/i3status-rust#567]
It would be nice to be able to break up the configuration file into multiple files and include them in the main configuration. This would allow having a main config as well as device-specific config files (ie one with a battery block for a laptop, or one with an ethernet block for a desktop).

**Comment by atheriel** [comment]
This sounds like a nice idea, but [there are no plans to support this in the TOML spec](https://github.com/toml-lang/toml/issues/397), and I don't think we will take on the implementation work ourselves. You might have to use a preprocessor (or `cat`) instead.

**Comment by gjabell** [comment]
Ok, thanks for the rationale!
