### ISSUE TITLE
Feature: Hide blocks with missing resources

### ISSUE THREAD

**Issue by shazow** [greshake/i3status-rust#568]
I'm trying to create some shared configuration setup between multiple devices. Sometimes a battery is available, sometimes it's not. Sometimes there is a wifi device, sometimes it's an ethernet device, etc.

By default, the i3status-rust aborts when a block's resource is missing. Would be nice to be able to override a block to hide when the resource is missing (e.g. have the battery block be skipped if there's no battery available).

Related to https://github.com/greshake/i3status-rust/issues/567

Happy to take a crack at it, let me know if there's any objections.

**Comment by wucke13** [comment]
I absolutely support this. I started writing my own rust program for an i3/sway status bar and this was the first thing I took care of. Once I found out about i3status-rust, I was quite surprised to find out that the config is not easily shareable!

**Comment by shazow** [comment]
I haven't had a chance to give it a try lately, so if anyone wants to beat me to it please go ahead. :)

**Comment by wucke13** [comment]
Where in the code would one have to ignore the error?
Would it be feasible to output the error message to stderr, and all other blocks to stdout, instead of only putting the error message and nothing else?

**Comment by ammgws** [comment]
Closing this as the battery block and net block both support hiding the block when the specified device is missing.

If this support is required for another block then please re-open/create another issue.
