### ISSUE TITLE
Powerline separator overriden by main font

### ISSUE THREAD

**Issue by rsolvang** [greshake/i3status-rust#572]
I have tried several fonts (Noto Sans, Inter) as my main font for i3/i3bar that has another symbol defined for the same unicode character () as the Powerline font uses. It seems that the main font is used instead of the Powerline font – _if_ the main font has a character defined for the same unicode symbol. Maybe it's possible to give priority to the Powerline font for this one symbol?

When i use Dejavu, the right symbol is shown (although to small).

This is the -symbol as defined by the Inter font:
![Skjermbilde tatt 2020-02-23 kl 22-31](https://user-images.githubusercontent.com/1956027/75120492-85e4dc80-568c-11ea-9023-dc978f5d751d.png)
When using Inter as my main font, the same symbol is shown in the bar:
![Skjermbilde tatt 2020-02-23 kl 22-30](https://user-images.githubusercontent.com/1956027/75120512-a14fe780-568c-11ea-9a14-641cfc27245e.png)

**Comment by ammgws** [comment]
All we do is output i3/swaybar compatible JSON, the font stuff is handled by i3/swaybar. Don't think there is anything we can do here...
