### ISSUE TITLE
Add horizontal progress-bar style formats

### ISSUE THREAD

**Issue by arlopurcell** [greshake/i3status-rust#577]
There are a number of blocks which could use something like a progress bar to display some kind of a percentage rather than a numerical value. In particular i think the following blocks could use this option

- battery (format placeholder)
- cpu (format placeholder)
- disk_space (new show_bar boolean config)
- memory (format placeholders like "Mupb", "SUpb", etc.)
- net (new signal_strength_bar boolean config)
- sound (new bar boolean option)

The progress bar itself could use [unicode block elements](https://en.wikipedia.org/wiki/Block_Elements) to give pretty good resolution, looking like this:
![image](https://user-images.githubusercontent.com/8958229/76001534-d9e09400-5eca-11ea-9cab-d285ac72ab44.png)

**Comment by ammgws** [comment]
Looks like this can be closed now :)
