### ISSUE TITLE
Strange graphics artifacts at the end of each block

### ISSUE THREAD

**Issue by RaitoBezarius** [greshake/i3status-rust#579]
Since some upgrade of my system on Archlinux, I'm seeing those strange glyphs (?) at the end of most of my blocks.

I never saw them before, so I suppose it is some separator and some upgrade broke some fonts.

Any idea?
![DeepinScreenshot_select-area_20200308003344](https://user-images.githubusercontent.com/314564/76153967-98bbd000-60d4-11ea-829c-b1c0e5d168a2.png)

**Comment by GladOSkar** [comment]
My first idea would be to reinstall your Powerline fonts

**Comment by RaitoBezarius** [comment]
Already done and I'm using:
https://aur.archlinux.org/packages/nerd-fonts-complete/ which I think is
pretty much complete…

**Comment by GladOSkar** [comment]
Huh honestly no idea then

**Comment by atheriel** [comment]
What does your i3/sway config for `bar.font` look like?

**Comment by RaitoBezarius** [comment]
```
bar {
    font pango:DejaVu Sans Mono, FontAwesome 10
    position top
    workspace_buttons no
    status_command i3status-rs ~/.config/i3status-rs/config-top.toml
    colors {
        separator #666666
        background #222222
        statusline #dddddd
        focused_workspace #0088CC #0088CC #ffffff
        active_workspace #333333 #333333 #ffffff
        inactive_workspace #333333 #333333 #888888
        urgent_workspace #2f343a #900000 #ffffff
    }
}
```

For example.

**Comment by ammgws** [comment]
@RaitoBezarius Are you still getting this?

**Comment by RaitoBezarius** [comment]
@ammgws I don't see it anymore

**Comment by ammgws** [comment]
Good to hear. I will close this for now as the only thing we can control with respect to fonts is which icon we choose to use in the JSON output. Please re-open if it happens again so we can try find out why regardless.
