### ISSUE TITLE
[bluetooth] Hide block if not connected

### ISSUE THREAD

**Issue by Rikorose** [greshake/i3status-rust#583]
Thanks for your project!

It would be nice, if there would be an option to hide the bluetooth block if the specified device is not connected.

**Comment by ammgws** [comment]
Something like how the net block behaves?

**Comment by Rikorose** [comment]
Yes that would an option, I guess.

It would be also nice, if we could provide the MAC of the bluetooth controller instead of the device to connect to. This simplifies it a lot when having multiple bluetooth devices.

**Comment by ammgws** [comment]
OK I'll see what I can do. I don't have Bluetooth so I'll ping you for testing when I have something :construction_worker:

**Comment by ammgws** [comment]
@Rikorose @taziden @AkechiShiro Can you try the new `hdie_disconnected` config option added in #858?

**Comment by AkechiShiro** [comment]
It is working to hide the Bluetooth block when `hide_disconnected = true` inside the toml configuration.

When the headset is connected the block shows up as expected, I can confirm that it works as expected.

If I encounter an issue I will comment here again but I think this is working fine now, nice little upgrade thanks.
