### ISSUE TITLE
Battery block shows wrong information

### ISSUE THREAD

**Issue by droslean** [greshake/i3status-rust#586]
My current situation:
BAT0 = 5%
BAT = 73%

Block 
```
[[block]]
block = "battery"
interval = 10
format = "{percentage}% {time}"
```
shows 5%

block:
```
[[block]]
block = "battery"
interval = 10
upower = true
device = "DisplayDevice"
format = "{percentage}%"
```
shows 35% (??????????????)

**Comment by ammgws** [comment]
So `upower -d` shows 5% and 73%?

Also `upower = true` will be deprecated at some stage, use `driver = upower` instead.

**Comment by droslean** [comment]
Thanks @ammgws.

**Comment by ammgws** [comment]
Oh, did that actually solve the issue?

**Comment by droslean** [comment]
Yes. Do we have to update any docs?

**Comment by droslean** [comment]
For the record:
```
[[block]]
block = "battery"
interval = 10
driver = "upower"
device = "DisplayDevice"
format = "{percentage}%"
```

works just fine.

**Comment by ammgws** [comment]
> Yes. Do we have to update any docs?

The deprecation notice is in the docs and the example config uses `driver` so there's not much else to do apart from actually removing it from the code.
