### ISSUE TITLE
Why is bitrate not available for wired devices?

### ISSUE THREAD

**Issue by indradhanush** [greshake/i3status-rust#587]
I tried to set `bitrate = true` on an ethernet device and got the following error:

```Bitrate is only available for connected wireless devices.```

The code in question seems to be here:

https://github.com/greshake/i3status-rust/blob/4049a6a5a91bee026e1cf175476a0f7217b6e2ab/src/blocks/net.rs#L246-L250

Any specific reason why bitrate is not available for connected wired devices? I haven't played with Rust before, but won't mind taking a dig at fixing this if it is technically feasible.

**Comment by ammgws** [comment]
It's using `iw` to get the bitrate which is a command only for wireless services, right? If you have a way to get the info for wired devices via `ip` or whatever then I don't see why it couldn't be added.

**Comment by indradhanush** [comment]
@ammgws Thank you for the response. I checked with `ethtool` and `dmesg` on my system and it shows the speed:

```
$ ethtool enp0s31f6 | grep Speed     
Cannot get wake-on-lan settings: Operation not permitted
	Speed: 100Mb/s
$ dmesg | grep 'enp0s31f6.*Up' | tail -n 1
[269307.165323] e1000e: enp0s31f6 NIC Link is Up 100 Mbps Full Duplex, Flow Control: Rx/Tx
```

`ethtool` is not natively available on Linux and needs to be installed. While the `dmesg` approach feels more hackier. What do you suggest could be the better approach?

**Comment by ammgws** [comment]
Probably ethtool since I don't think there's a guarantee it be in dmesg

**Comment by indradhanush** [comment]
@ammgws I would expect it to be in `dmesg` if the device successfully connects. Any reason why it might not be there? :thinking:

**Comment by ammgws** [comment]
I was thinking in case the dmesg log gets rotated, though I'm not sure how often that would occur in every use.

**Comment by indradhanush** [comment]
You're right on this one. On second thoughts `dmesg` won't always guarantee that the last entry has the "Up" keyword with the speed is the current one, for eg: if the connection got disconnected. `ethtool` sounds like the better approach.

**Comment by ammgws** [comment]
Can you check out #612?
