### ISSUE TITLE
fakeroot required for pacman block

### ISSUE THREAD

**Issue by PicoJr** [greshake/i3status-rust#592]
Hello,

The pacman block is always indicating "system is up to date" on my fresh Arch install.

After some investigation it appears that the pacman block relies on `fakeroot` (which wasn't installed on my machine).

Maybe it would be worth mentioning that `fakeroot` is required by the pacman block ?

IMO the following snippet is a bit misleading: I understand that if `fakeroot` is not found
 on the system, the pacman block will report 0 update...

https://github.com/greshake/i3status-rust/blob/4049a6a5a91bee026e1cf175476a0f7217b6e2ab/src/blocks/pacman.rs#L116-L119

I'm not too sure about this check: 

https://github.com/greshake/i3status-rust/blob/4049a6a5a91bee026e1cf175476a0f7217b6e2ab/src/blocks/pacman.rs#L103-L106

`type` does not have a `-P` option, maybe it should be `type -p fakeroot` instead?

What do you think?

Thanks for this project =)

**Comment by ammgws** [comment]
I guess it could be documented and the block changed to error out if it's not installed.

You're right about `type` not having `-P`, at least in `sh`/`bash` on Arch. Incidentally, `fish shell`'s type does have -P. Could be changed to `which` instead?

**Comment by PicoJr** [comment]
My bad, you are right: @ammgws 

I ran the command in my zsh shell...

```
# zsh
❯ type -P fakeroot
type: bad option: -P
```

```
sh-5.0$ type -h
sh: type: -h: invalid option
type: usage: type [-afptP] name [name ...]
```

**Comment by flying7eleven** [comment]
Wouldn't it be a feasable option to always use the ```-p``` (lower-case) option? That works just fine in ```bash``` as well as ```zsh```. Based on the documentation the result would be an empty string if the command could not be found (which is what the code checks anyway).

**Comment by flying7eleven** [comment]
Nvm. I forgot that everything will be ran through ```sh``` so the capital ```-P``` is not an issue. Sorry

**Comment by ammgws** [comment]
@PicoJr Do you plan on contributing this some time? https://github.com/PicoJr/i3status-rust/commit/0a11691e1af937ff4fbab6a68e01c257518e495e#diff-2c6af12f9d4ff45f3dc7a0bbdc275de9 Since it solves this issue
