### ISSUE TITLE
Update to Font Awesome 5

### ISSUE THREAD

**Issue by carloabelli** [greshake/i3status-rust#598]
There was some discussion of this in #130, but that issue is closed and cluttered with workarounds. Additionally the [pango issue](https://github.com/greshake/i3status-rust/issues/130#issuecomment-455540786) that was causing a lot of the hexboxes has now been [fixed](https://gitlab.gnome.org/GNOME/pango/-/merge_requests/67). Here is a list of icons to change for Font Awesome 5 with possible alternatives:

Icons that have to be updated:
  - `cpu`:
    - [tachometer-alt](https://fontawesome.com/icons/tachometer-alt?style=solid)
    - [microchip](https://fontawesome.com/icons/microchip?style=solid)
  - `volume_muted`
    - [volume-mute](https://fontawesome.com/icons/volume-mute?style=solid) (see #517)

Icons that could be updated:
  - `net_up`
    - [upload](https://fontawesome.com/icons/upload?style=solid)
    - [file-upload](https://fontawesome.com/icons/file-upload?style=solid)
    - [cloud-upload-alt](https://fontawesome.com/icons/cloud-upload-alt?style=solid)
    - [long-arrow-alt-up](https://fontawesome.com/icons/long-arrow-alt-up?style=solid)
  - `net_down`
    - [download](https://fontawesome.com/icons/download?style=solid)
    - [file-download](https://fontawesome.com/icons/file-download?style=solid)
    - [cloud-download-alt](https://fontawesome.com/icons/cloud-download-alt?style=solid)
    - [long-arrow-alt-down](https://fontawesome.com/icons/long-arrow-alt-down?style=solid)
  - `net_wired`
    - [ethernet](https://fontawesome.com/icons/ethernet?style=solid)
    - [network-wired](https://fontawesome.com/icons/network-wired?style=solid)
  - `ping`
    - [exchange-alt](https://fontawesome.com/icons/exchange-alt?style=solid)
    - [arrows-alt-h](https://fontawesome.com/icons/arrows-alt-h?style=solid)
    - [redo](https://fontawesome.com/icons/redo?style=solid)
    - [undo](https://fontawesome.com/icons/undo?style=solid)
    - [sync](https://fontawesome.com/icons/sync?style=solid)
    - [table-tennis](https://fontawesome.com/icons/table-tennis?style=solid)
  - `uptime`
    - [stopwatch](https://fontawesome.com/icons/stopwatch?style=solid)
    - [hourglass](https://fontawesome.com/icons/hourglass?style=solid)
  - `memory_mem`
    - [memory](https://fontawesome.com/icons/memory?style=solid)

Icons that are emojis (were these ever included in font awesome?):
  - `backlight*`
    - [lightbulb](https://fontawesome.com/icons/lightbulb?style=solid) combined with some sort of bar?
  - `pomodoro`
    - [business-time](https://fontawesome.com/icons/business-time?style=solid)
    - [user-clock](https://fontawesome.com/icons/user-clock?style=solid)
    - [stopwatch](https://fontawesome.com/icons/stopwatch?style=solid)
    - [hourglass](https://fontawesome.com/icons/hourglass?style=solid)

**Comment by ammgws** [comment]
What's the availability of Font Awesome 5 like on Ubuntu and the like? Ideally would like to avoid bug reports coming in from users of those distros where there isn't an easy installable package available.

**Comment by carloabelli** [comment]
@ammgws 

Looks like it's version 5 on both Ubuntu and Debian:
https://packages.ubuntu.com/eoan/fonts-font-awesome
https://packages.debian.org/buster/fonts-font-awesome

**Comment by ammgws** [comment]
Ubuntu 18.04LTS seems to still be on the 4.7 version.

**Comment by carloabelli** [comment]
Okay so in that case it would probably be best to create a new icon set for font awesome 5. Any thoughts on the updated icons?

**Comment by atheriel** [comment]
New LTS for Ubuntu is out this week, so it's not unreasonable to be thinking of this change soon. Thanks for all of your work collecting together the changes!

**Comment by ammgws** [comment]
> Any thoughts on the updated icons?

This is what I think

cpu: tachometer-alt (1. seems more CPU-like to me rather than the chip icon, 2. the chip icon is already used for memory (assuming we dont change it), 3. same as the icon used in FA4)

volume_muted: volume-mute

net_up: upload (I hate the current icons as they show so small for me)
net_down: download

net_wired: network-wired

ping: exchange-alt

uptime: stopwatch

memory: keep the current icon

**Comment by carloabelli** [comment]
> This is what I think

I agree with these.

> memory: keep the current icon

Personally I prefer the memory icon, but consistency is not a bad thing and overriding icons in the config is simple.

I'll update my other pull request to include these changes.

**Comment by carloabelli** [comment]
@ammgws Sorry I was busy and just now saw this. Looks like there were two small bugs, so here's a PR with the fixes.
