### ISSUE TITLE
Display usage% per CPU core in the cpu block

### ISSUE THREAD

**Issue by grim7reaper** [greshake/i3status-rust#603]
Hello,

I'm currently moving from XMonad/xmobar to i3 and I'm trying to have a status bar similar to what I had with xmobar.
I've managed to get almost all I needed with your cool project here :slightly_smiling_face: , but I'm still missing a few features.

Regarding the block `cpu` I'm missing two things:
1. the ability to display the utilization of each core in %. IIUC, the `{utilization}` format only gives a global average.
2. ideally, the color would be applied to each % indivually, according to the threshold.

In picture, here is what I'm trying to get:

![cpu](https://user-images.githubusercontent.com/6479907/80019889-80fba800-84d8-11ea-9c77-8887de332d25.png)

I've had a quick look at `src/blocks/cpu.rs` and I think that the first point should be easy to do because we already fetch the info for `{barchart}`: we "simply" have to display it differently.
I can probably provide up with a PR for that :wink:

The second point (independant color inside a single block), looks trickier with the current implementation :confused:

**Comment by ammgws** [comment]
Give it a go and see what you can come up with

**Comment by grim7reaper** [comment]
Ok, I'll give it a try :slightly_smiling_face: 
I'll let the color issue aside for now: it seems related to `widget.rs` and may have a wider impact.
Anyway, it can be addressed later.

Should I go with:
- a new format, I'll need to find a good name for it (`{utilizations}` sounds way too similar to the existing one)
- a new bool in the block config that would toggle "show average/show all" for the existing format `{utilization}`
?
