### ISSUE TITLE
Music block doesn't show title/artist info with mpd+mpDris2

### ISSUE THREAD

**Issue by grim7reaper** [greshake/i3status-rust#604]
Hi,

I've noticed that the music block seems to be somewhat broken with mpd+mpDris2: I can see the music icon but no text (neither title nor artist).

Looking at the output of `dbus-monitor` I can see `i3status-rs` querying and getting the info back, but nothing is displayed :confused:

FWIW, I did some testing and:
- v0.13.1: broken
- v0.13.0: works like a charm 

I've had a quick look at the diff between the two tags, and it's very small. Likely culprit would be the update of the dbus dependency (to be confirmed though, that's just a guess).

Feel free to ask if you need more details from me to help you troubleshoot this issue :slightly_smiling_face:

**Comment by ammgws** [comment]
Is it broken on git master too?

A similar issue (with another music program) came up a couple of days ago and that solved the issue for them: https://github.com/greshake/i3status-rust/issues/589

**Comment by grim7reaper** [comment]
Ho, it's working on master indeed!

I think I've tested on master actually, but weirdly enough the the master branch `-V` returns `i3status-rs 0.13.0`, hence my confusion.

To sum up:
- `tags/v0.13.0`: works
- `tags/v0.13.1`: doesn't work
- `master`: work
