### ISSUE TITLE
Fail to compile on Debian docker image

### ISSUE THREAD

**Issue by eleidan** [greshake/i3status-rust#61]
It seems we miss some dependencies here. This is crucial for future packaging.
The result of my try inside a docker container:
```
error: failed to run custom build command for `dbus v0.5.3`
process didn't exit successfully: `/home/phantom/app/target/release/build/dbus-d1ec11d4d82de6d9/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error(PkgConfig(Failure { command: "\"pkg-config\" \"--libs\" \"--cflags\" \"dbus-1 >= 1.6\"", output: Output { status: ExitStatus(ExitStatus(256)), stdout: "", stderr: "Package dbus-1 was not found in the pkg-config search path.\nPerhaps you should add the directory containing `dbus-1.pc\'\nto the PKG_CONFIG_PATH environment variable\nNo package \'dbus-1\' found\n" } }), State { next_error: None })', /checkout/src/libcore/result.rs:860
note: Run with `RUST_BACKTRACE=1` for a backtrace.

warning: build failed, waiting for other jobs to finish...
error: build failed

```

**Comment by svmnotn** [comment]
The ReadMe says it has only been tested with Arch, and most Arch configurations use systemd which depends on `dbus`, perhaps we should write the `dbus` requirement on the ReadMe.

**Comment by greshake** [comment]
Yea it requires the libdbus-dev lib. Some dependencies are eonly related to a single block, and I haven't really figured out how to elegantly use conditional compilation for people not wanting those dependencies. I know how to implement it, but not how to make it easily usable.

**Comment by svmnotn** [comment]
They would have to compile it with different feature flags, something like `cargo build --music` or `cargo build --no-default-features --music` depending on it is organised, sadly I don't think there are any better ergonomics for optional configurations of dependencies as of yet. Well, maybe looking up which libs are and dynamically loading them but... that is a mess I don't think anyone wants to go down into.
