### ISSUE TITLE
sway: empty horizontal space

### ISSUE THREAD

**Issue by travankor** [greshake/i3status-rust#620]
Minor nitpick: On sway, there is wasted horizontal space about a ~1 pixel tall on both the top and bottom edge of swaybar. This seems to happen at different swaybar sizes, unless you crop swaybar to be smaller than the font size (which is a bad idea generally).

![swaybar](https://user-images.githubusercontent.com/38744110/80476453-b2e29380-894a-11ea-89e9-f18418fd0668.png)

**Comment by ammgws** [comment]
Are you sure that's not just a sway issue? All we do is output i3/swaybar compatible JSON - you can check the output in your terminal.

**Comment by travankor** [comment]
Good point -- This can't be from i3status-rust.
