### ISSUE TITLE
Weather bar curl error

### ISSUE THREAD

**Issue by crisidev** [greshake/i3status-rust#621]
Hello folks, 
I have started seeing consistently an error in the weather bar:

```
Error in block 'weather': Unexpected curl output curl: unknown --write-out variable: 'stderr'
```

I am on ubuntu with curl version 7.58.0-2ubuntu3.8 and i3status-rs is compiled from today's master.

Interestingly enough, If I run curl manually with `--write-out 'stderr'` it works fine..

**Comment by sashomasho** [comment]
Can you try with the following?

> curl --silent -m 1 "http://api.openweathermap.org/data/2.5/weather?id=726050&appid=API_KEY&units=metric" --write-out "%{stderr} %{http_code}"

**Comment by ammgws** [comment]
Your curl version is too old. `stderr` var was added in curl 7.63

https://github.com/curl/curl/commit/e431daf013ea04cb1a988a2009d820224ef5fb79

**Comment by crisidev** [comment]
I am on 18.04, but I had an old pinned package, totally my fault. This can be closed. Sorry about that.
