### ISSUE TITLE
Add a `workspaces` block

### ISSUE THREAD

**Issue by mox-mox** [greshake/i3status-rust#624]
Feature-request: would it be hard to create a block that shows workspaces?
My rationale is that I would like to have the workspaces in the same style as the rest of the bar. But currently, that would mean I'd have to get swaybar to support the same theming as i3-status which it AFAIK does not.

If there is a chance to get such a block merged, I might try to implement it myself.

**Comment by atheriel** [comment]
It's certainly possible if you can find a way to do it through i3's [IPC mechanism](https://i3wm.org/docs/ipc.html), which is how the focused block window works today. Sway supports the same interface.

**Comment by atheriel** [comment]
To add: yes, we would probably support adding such a block, although I think it's also worth proposing a design for what it would show before fulling implementing it.

**Comment by mox-mox** [comment]
Well, it would show a button for each workspace as received from the sway ipc event.
If you click a button, it takes you to the pertaining workspace. If a workspace has the 'urgent' status it is highlighted. Really, about the same as what swaybar does.
If this works well, I might also create a block to show the mode to be able to completely replace that bit of swaybar as well.

**Comment by ammgws** [comment]
Possibly of interest: https://github.com/i3/i3/issues/3818

**Comment by mox-mox** [comment]
Hmm, I got to admit, after my request to allow blocks on the left side of the bar crashed and burned, I more or less lost interest in this.
But now, I'm excited to continue on this. Nice! And thanks for the heads up!

**Comment by ammgws** [comment]
What request was that again?

**Comment by mox-mox** [comment]
Small update: I'm not yet finished, but it is going forward when I find some time and by now it is mostly working.
Can't wait till i3/i3#3818 is implemented :)

**Comment by ammgws** [comment]
The other day I noticed waybar has a workspaces block, it might be of reference.

**Comment by mox-mox** [comment]
Yes, that might help to get the ordering right when some workspaces have a number and some don't. The rest works.

**Comment by ammgws** [comment]
Do you have something ready to share yet?

**Comment by mox-mox** [comment]
Hi sorry for the long time to respond. Yes, I have something to share: https://github.com/mox-mox/i3status-rust/tree/workspaces_block
Effectively that is the code I created in June, then more-or-less abandoned but ported to work with the current i3status-rust framework.

**Comment by ammgws** [comment]
As mentioned in #980 I think this can be done once i3/i3#4311is merged, it is just a matter of time.
