### ISSUE TITLE
[FR] Weather block: make it possible to configure by city/country instead of city_id

### ISSUE THREAD

**Issue by kflak** [greshake/i3status-rust#632]
Hi,

Been tinkering around a bit with the openweather-api, and it would be great to be able to fill in 
```
city = "Pärnu"
country = "Estonia"
```
instead of city_id. This would make it easier to update my location as I travel around (post-COVID, of course...)
Turns out this is possible by running a different curl command than the one in `blocks/weather.rs`:
```
curl 'api.openweathermap.org/data/2.5/weather?q=Pärnu,estonia&appid=<app_id>'
```

I am sure there are issues with this that I haven't quite anticipated, but would be neat if it were possible :-)

**Comment by ammgws** [comment]
Generally we try to avoid breaking existing configs, so I guess this could be separate to the existing city_id. So you either need to specify `city_id`, or specify both `city` and `country`, or maybe just one parameter using a TOML array.

**Comment by kflak** [comment]
Yes, of course! Sorry about the sloppy wording above. It would obviously have to be an additional option....

**Comment by kflak** [comment]
Conveniently, all these ways of specifying country work in the call to openweathermap:
Estonia, estonia, EE. So these calls seem to be equivalent:
```
curl 'api.openweathermap.org/data/2.5/weather?q=Pärnu,estonia&appid=<app_id>'
curl 'api.openweathermap.org/data/2.5/weather?q=Pärnu,Estonia&appid=<app_id>'
curl 'api.openweathermap.org/data/2.5/weather?q=Pärnu,EE&appid=<app_id>'
```

**Comment by ammgws** [comment]
I started working on this but then realised:

>  API responds with a list of results that match a searching word. 

vs

> API responds with exact result. 

for city_id.

Maybe we could just take the first result if there are multiple?

**Comment by kflak** [comment]
If you want to get fancy you could maybe do an automatic retrieval of gps coordinates based on some ip location service and feed openweathermap the exact location...? This is in fact my ideal use case, but not entirely sure how to pull it off. My Rust skills are not yet very advanced, unfortunately.

**Comment by ammgws** [comment]
Hmm, an "auto" feature would be more involved. Perhaps another time.

For now, could you give #635 a go?

**Comment by kflak** [comment]
Yup, seems to work fine! Really appreciate the option for setting the place as an environment variable as well, then I can run something like this script to get my current location occasionally:
```
#!/bin/bash

city=$(curl ipinfo.io/city)
country=$(curl ipinfo.io/country)
echo $city $country
```
Probably very suboptimal :-)

**Comment by kflak** [comment]
Furthermore,  I just have to say that you guys are super responsive about everything! Very impressed by the work you are putting into this project.

**Comment by ammgws** [comment]
Sounds like #367 is what you want

**Comment by kflak** [comment]
Very interesting, thanks for the tip!
