### ISSUE TITLE
Turned off network adapter results in error message

### ISSUE THREAD

**Issue by gabm** [greshake/i3status-rust#633]
When i turn of the wifi via software `wifi off`, then I get an error:

Error in block 'net': failed to read /sys/class/net/wlp0s20f3/carrier

I can't seem to read that pseudo-file manually, so its not really i3status-rusts fault. But: what can I do?

I found this: https://unix.stackexchange.com/questions/252002/help-testing-special-file-in-sys-class-net

**Comment by ammgws** [comment]
Ok so looks like that file is unreadable when the interface is disabled. I just pushed a fix - please see if it works for you.

**Comment by gabm** [comment]
That seems to work. thank you for the fast fix!
