### ISSUE TITLE
Using `actual_brightness` breaks backlight block

### ISSUE THREAD

**Issue by Celti** [greshake/i3status-rust#642]
My laptop's backlight driver is `amdgpu`; commit 15b7b7d to use `actual_brightness` instead of `brightness` forces the block to always display brightness 100%, and will set the brightness to 100% when trying to set the brightness via scrolling.

The cause of this is very obvious:
```
❯ rg . /sys/class/backlight/amdgpu_bl0/*brightness
/sys/class/backlight/amdgpu_bl0/actual_brightness:65535
/sys/class/backlight/amdgpu_bl0/brightness:255
/sys/class/backlight/amdgpu_bl0/max_brightness:255
```
`actual_brightness` is on a _completely_ different scale from `max_brightness` — even if I set the brightness to zero, `actual` is still 771, over three times the `max`!

Since `brightness` and `max_brightness` are driver values that are guaranteed to be consistent with each other, and `actual_brightness` is a hardware value that does not necessarily make guarantees about anything, can we please go back to using `brightness`, or at least make it configurable?

**Comment by ammgws** [comment]
[Looks like](https://github.com/polybar/polybar/blob/068bf5a311725bfef66b1f9d30be2ac5c0df59eb/src/modules/backlight.cpp#L50-L54) it's specific to amdgpu:

> amdgpu drivers set the actual_brightness in a different scale than [0, max_brightness]
> The only sensible way is to use the 'brightness' file instead

Wonder if it's easier to make it configurable in case there are others apart from amdgpu that behave the same

**Comment by ammgws** [comment]
Try with master
