### ISSUE TITLE
Pango error - unescaped blocks/net command output

### ISSUE THREAD

**Issue by dunrix** [greshake/i3status-rust#644]
When SSID name contains regular non-alphanumeric characters like `&`, widget output fails with following error being logged:

> (process:183221): Pango-WARNING **: 09:27:14.559: pango_layout_set_markup_with_accel: Error on line 1: Entity did not end with a semicolon; most likely you used an ampersand character without intending to start an entity ? escape ampersand as \&amp\;

It seems output of external commands is not handled properly (ie. escaped) before sent to i3bar.

Affected lines for `blocks/net`:
https://github.com/greshake/i3status-rust/blob/2efa54c39fa56613ecfe77b34a7cb248bc783de0/src/blocks/net.rs#L170

https://github.com/greshake/i3status-rust/blob/2efa54c39fa56613ecfe77b34a7cb248bc783de0/src/blocks/net.rs#L184

The quick fix for `net` would be straightforward, ie. do escaping of returned string but I'd suggest do it in a more general way, like some helper function for safe processing external command calls and their output.

**Comment by ammgws** [comment]
Something like this?

![image](https://user-images.githubusercontent.com/20397027/81310770-81db2f00-90bf-11ea-8c76-26a007d2edee.png)

There are errors galore in sway's output but the bar itself appears to be working for me. Or at least it was reacting to the network going up and down. I can only test with a virtual wifi adapter so testing is kinda limited.

Does the bar crash for you?

**Comment by ammgws** [comment]
However this is implemented in our code, these are the chars that have to be escaped:

```
  <  to &lt;
  >  to &gt;
  &  to &amp;
  '  to &#39;
```

**Comment by dunrix** [comment]
@ammgws No, the bar does not crash but SSID string is not displayed and quoted error starts appear in `.xsession-errors` log.

Tested with two access points, one constituting ID with alphanumeric chars only, the second with ampersand in between (like "*Laurel&Hardy*"). The issue exists only in the second case.

**Comment by ammgws** [comment]
OK so it doesn't display at all on i3, while it does on sway.

Need to come up with a function that escapes these for us.

**Comment by dunrix** [comment]
Yep, I'm running with `i3`.

Didn't found where the special characters get escaped in `i3status-rust` code.

**Comment by ammgws** [comment]
I just realised I came across this error before in another block: https://github.com/greshake/i3status-rust/pull/518.

We don't escape anything at the moment. We need to write a function that escapes those characters listed above and then use it here: https://github.com/greshake/i3status-rust/blob/d6efae28e53d41d9f2909918a03b4223cc42f994/src/widgets/button.rs#L50, and anywhere else that has `"markup": "pango"`.

**Comment by ammgws** [comment]
I'll get around to it in a couple hours

**Comment by ammgws** [comment]
It's fixed for me now. Please re-open if not for you.

**Comment by dunrix** [comment]
> It's fixed for me now. Please re-open if not for you.

Works for me. Thanks!

**Comment by matclab** [comment]
I'm not sure, but I have the impression tha escaping does defeat the purpose of pango markup or did I miss something.
For example, I have the following conf:
```
[[block]]
block = "time"
interval = 60
format = "%a %d/%m <b>%R</b>"
```
Before, the hour:minute  part of the time widget was displayed as bold, but now I see the markup in the widget.
Shouldn't the escaping only be done for each widget when the user has no control of the data (for example ssid).

**Comment by ammgws** [comment]
Hmm I'm on mobile atm so a bit limited but I suspect it's because you don't have pango set in your i3/swaybar font config. IIRC pango output is enabled for all blocks that use the TextWidget, so it's likely you'd see unformatted pango in other blocks as well. If enabling pango in your config isn't an option then will need to think about this...

**Comment by ammgws** [comment]
Sorry I misread your comment. So your pango formatting was actually broken by this. I'll look into this tonight hopefully!

**Comment by ammgws** [comment]
> Shouldn't the escaping only be done for each widget when the user has no control of the data (for example ssid).

Indeed. I'll push a fix today or tomorrow.

**Comment by matclab** [comment]
Thanks !

**Comment by Donatzsky** [comment]
Seems like this issue hasn't been fully resolved. At least not for custom blocks.


```shell
#!/bin/sh

## Fails - Empty
echo "{\"text\":\"1 &\"}"
## Works
echo "{\"text\":\"2 &amp;\"}"

## Fails - Empty
echo "1 &"
## Works
echo "2 &amp;"


## Works
echo "{\"text\":\"1 >\"}"
## Works
echo "{\"text\":\"2 &gt;\"}"

## Works
echo "1 >"
## Works
echo "2 &gt;"


## Fails - Empty
echo "{\"text\":\"1 <\"}"
## Works
echo "{\"text\":\"2 &lt;\"}"

## Fails - Empty
echo "1 <"
## Works
echo "2 &lt;"


## Works
echo "{\"text\":\"1 '\"}"
## Works
echo "{\"text\":\"2 &#39;\"}"

## Works
echo "1 '"
## Works
echo "2 &#39;"
```
