### ISSUE TITLE
Next release: 0.14.0 ready?

### ISSUE THREAD

**Issue by PicoJr** [greshake/i3status-rust#652]
Already >190 commits :rocket: to master since last release (0.13.1).

* 0.11.0 -> 0.12.0 = 55 commits
* 0.12.0 -> 0.13.0/1 = 60 commits
* 0.13.0/1 -> 0.14.0? = ~200 commits

It sounds next release will be quite dense (many new features + fixes) :partying_face:.

What is left to do before `master` can be considered as a stable release candidate?

Thanks for the great work =)

**Comment by ammgws** [comment]
The delay of the next release is just due to the maintainers being busy with life. @atheriel has been handling releases for a while now, so I might defer to him for now.

**Comment by PicoJr** [comment]
It's what I thought, it was just in case some help was required in order to prepare the next release.

I'm happily recompiling from sources for now =)
