### ISSUE TITLE
Add per widget wide/narrow switching behavior 

### ISSUE THREAD

**Issue by matclab** [greshake/i3status-rust#676]
My bar is quite full and some time has not enough space to display everything.

Thus, it would be useful to enable switching between a full width widget and between a narrower widget (with less information).
For example, the net block may display IP addresses only in the wide mode.
The time block may have two format string, on for the wide mode and on for the narrow mode.
…

I propose using the right or middle mouse button to switch between mode.

What do you think about this proposal ?

**Comment by ammgws** [comment]
Haha, I just thought of this tonight as well. The i3bar JSON schema actually has a field called `short_text` which is used for this exact situation. I was going to test it out with a random block to see if/how it works. For reference we only use the `full_text` field at the moment:

https://i3wm.org/docs/i3bar-protocol.html
> full_text
> 
>     The full_text will be displayed by i3bar on the status line. This is the only required key. If full_text is an empty string, the block will be skipped.
> 
> short_text
> 
>     Where appropriate, the short_text (string) entry should also be provided. It will be used in case the status line needs to be shortened because it uses more space than your screen provides. For example, when displaying an IPv6 address, the prefix is usually (!) more relevant than the suffix, because the latter stays constant when using autoconf, while the prefix changes. When displaying the date, the time is more important than the date (it is more likely that you know which day it is than what time it is).

**Comment by travankor** [comment]
Some blocks already have a collapsed mode that can be collapesed or expanded on click. I wonder how this approach compares to short_text?

**Comment by matclab** [comment]
Oh ! I didn't used any of this block (music & temperature), so I didn't know.
I guess it is the same feature which just as to be ported to other blocks… 
I'll submit a PR using the same terminology.

**Comment by ammgws** [comment]
Let's investigate `short_text` first, since it means collapsing would be done automatically, and would free up a click action for the blocks. Some blocks might already be using all clicks, or might in the future (such as the `custom` block), for other functionality.

**Comment by matclab** [comment]
Ok. But as a user, I'd like to be able to switch back to `full_text` in order to see masked information ("what is my IP, what is the date?") if possible (if I have not mapped the click to other functionality in the configuration or if the block has not already mapped all clicks).
I may give a try, but with no promise about delivery :-) 
@ammgws do not hesitate to give a try !

**Comment by GladOSkar** [comment]
I agree that some sort of hybrid would be most desirable - Both automatic (when screen width is reached) and manual (on click) truncation/shortening. No idea how that would be possible though.

**Comment by ammgws** [comment]
We could set `short_text` where possible and then let i3/sway do it's thing to automatically shorten the bar. Then where possible add an `on_click` to blocks that changes `short_text` back to `full_text` and vice versa when clicked. I guess using right click would be the most safe option, but I think there are some blocks that already use left and right.

**Comment by eater** [comment]
I just came here to request the same enhancement. Can it be implemented for every type of block, not just Custom? Music is the one that takes up the most space on my bar, and I'd like to be able to collapse it with a click, especially when I'm not playing music.

**Comment by ammgws** [comment]
The PR for the Custom block allows i3bar/swaybar to automatically shorten the bar when the output is too long; there is no click action for the user to manually collapse the block. The same thing (`short_text`) could be implemented for other blocks, but it would be different to what you're requesting.

**Comment by matclab** [comment]
In #703 I added some examples of short_text management where blocks may provide a mean to set a short_text in addition to the default full_text, and consecutive middle click on a block switch from `Default` (display of short/long managed by i3bar) to `Short` (display only short_text) and then to `Full` (display only full_text) and the back to `Default`.

It works well, but may be a bit disturbing as the user as no clue in which mode it is and moreover it may affect other block display (for example switching a long block to `Short` will give enough room so i3bar will now display full_text to all other block that were displayed as short). 
It indeed seems that i3bar displays all blocks as *short* as soon as the bar is too wide (even if switching only one block to *short* would be enough).

Do you have any thought about it? Does it bother you? Does it looks good as is?

**Comment by matclab** [comment]
closed in favor of #1205
