### ISSUE TITLE
Where are the themes located?

### ISSUE THREAD

**Issue by andersfylling** [greshake/i3status-rust#686]
I read the wiki, the themes markdown, the man pages for this project. But I can't figure out where the themes are installed.

I also noticed that changing the theme, seem to do nothing. My XDG_CONFIG_HOME environment variable is not set, and I don't have a .Xresources file in my home folder.

**Comment by ammgws** [comment]
```
pub fn from_file(file: &str) -> Option<Theme> {

let full_path = Path::new(file);

let xdg_path = util::xdg_config_home()

.join("i3status-rust/themes")

.join(file);

let share_path = Path::new(util::USR_SHARE_PATH).join("themes").join(file);
```

If you're looking for the default theme files I don't think we have exposed all of them yet, but according to the above they should be in /use/... However they will only be there if whoever packaged i3status-rust for your distro actually copied the example theme files to /usr/...

**Comment by ammgws** [comment]
However if you're content with the themes that come with i3status-rust, you change the theme like this in your config:
_ 

[theme]
name = "slick"

Is that not working? It doesn't depend on any external files as those themes are all built into the source code.

**Comment by andersfylling** [comment]
Interesting. Cause I do not have the path `/usr/share/i3status-rust`. Nothing i3 related in `/usr/share` at all actually.

It does seem like this has just been me not being able to notice the color change from the themes I compared. So I'll close this :sweat_smile: 

Changing it from "modern" to "slick", does yield a slightly brighter colour. The reason I brought this up is because I tried to get transparency working.

```
bar {
    output DP-4
    i3bar_command i3bar --transparency
    font pango:DejaVu Sans Mono, FontAwesome 12
    position top
    status_command i3status-rs ~/.config/i3/status.toml
    colors {
        separator #666666
        background #22222244
        statusline #dddddd
        focused_workspace #0088CC #0088CC #ffffff
        active_workspace #333333 #333333 #ffffff
        inactive_workspace #333333 #333333 #888888
        urgent_workspace #2f343a #900000 #ffffff
    }
    height 25
}
```

**Comment by ammgws** [comment]
>  I do not have the path /usr/share/i3status-rust.

How did you install i3status-rust? If you pulled from GitHub and built it yourself, it's up to you to make the folder and copy the appropriate files there (even though there's not much point in doing that). Usually whoever packages i3status-rust for your distro would setup the install script so that it copies the files there.

Anyway for switching between the premade themes you don't need to think about the theme files so you can ignore it for now :)

**Comment by andersfylling** [comment]
thank you. I used AUR. the package is named "i3status-rust-git". I noticed there were almost 300 new commits, so I wanted to avoid the previous version as I felt it could perhaps be outdated.

**Comment by ammgws** [comment]
> AUR. the package is named "i3status-rust-git".

Something like the linked line would need to be added to the PKGBUILD for the themes located [here](https://github.com/greshake/i3status-rust/tree/master/example/theme) (at the moment there is only one example theme in there):

https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=i3status-rust-git#n46
