### ISSUE TITLE
Hide (music) block when inactive

### ISSUE THREAD

**Issue by rubdos** [greshake/i3status-rust#69]
Would it be possible to hide the music block when music is inactive/stopped? Takes a lot of space on my 1366x768 display... :/

This may be a good feature for other blocks too; not sure there.

**Comment by greshake** [comment]
It does hide when your music program communicates correctly. But, afaik, Spotify doesn't signal program exit correctly (maybe I just misread some interface docs) and so might others. I'll implement a periodic check if the music program is still alive, and if not collapse the block.

**Comment by greshake** [comment]
I already implemented the feature in my first implementation of the music block : Due to a bug it got stuck when you're not using the marquee feature. Now it hides correctly with marquee disabled.

**Comment by rubdos** [comment]
> I already implemented the feature in my first implementation of the music block 😄 Due to a bug it got stuck when you're not using the marquee feature. Now it hides correctly with marquee disabled.

Thanks! Problem here probably is that I'm on MPD, and as MPD is a daemon, it's always running. Sometimes, it's just that the music is stopped/playlist is empty, and such it's not very useful to have it around.

But you know what; it's probably more useful [to use systemd socket activation](https://www.musicpd.org/doc/user/systemd_socket.html) here, such that MPD starts on use. Still have to find a way to kill it when not in use though :P thanks!

**Comment by rubdos** [comment]
Oh wait, that of course doesn't work. i3status connects to that socket, and so activates mpd.

Would it be possible to check for an empty playlist or something like that?

**Comment by greshake** [comment]
Hmm. That totally depends on what data MPD provides over its dbus interface. I wanted to keep the features used at a minimum to increase compatibility.. But, as far as I can tell from your post, MPD actually provides empty metadata when there is no current track, right? At least that is what Spotify does on startup. And there is a case currently where empty-string metadata is displayed as just `|` which is probably what you're seeing. Guessing here. I will make the block interpret that the same as an unavailable player, but I don't think there is more I can do without making this an MPD specific change, which I'd like to avoid.

**Comment by greshake** [comment]
Can't tell if this works for you, just try it :)

**Comment by rubdos** [comment]
Seems to do it man, thanks again! :D
