### ISSUE TITLE
[net block] add `format` option

### ISSUE THREAD

**Issue by ammgws** [greshake/i3status-rust#692]
As mentioned here https://github.com/greshake/i3status-rust/issues/237#issuecomment-570277470

**Comment by gurditsbedi** [comment]
I read the mentioned comment (and thread), not much able to understand, what config option are we trying to change here? Any list of proposed config options ?

**Comment by ammgws** [comment]
Basically instead of having a million options like "ipv6", "ssid" etc, we just have one called "format" that can be set by the user to a string such as "{my IP: {ip}, connected to {ssid}". Check out the docs for examples of other blocks that have a format string

**Comment by gurditsbedi** [comment]
Got the thing here, I think I will be able to do this task.

So the following options will stay out of the format string:
`device`
`interval`
`hide_missing`
`hide_inactive`

I don't think these will be able to become a part of the format string
so these will be out also? Any alternative idea about putting them inside?
`speed_min_unit`
`speed_digits`

Rest of all the options listed in blocks.md will go to become placeholder's in
the format string.

What do you say?

**Comment by ammgws** [comment]
Yep that's what I was going for. Regarding speed_digits/min_unit, if you can figure out a way to do it then sure otherwise I don't have any ideas at the moment.

Also we might need to keep around the old ones and list them as deprecated. There's another block that does that, forgot which one.

**Comment by gurditsbedi** [comment]
Hi, I was working on the issue. So, I am having difficulty to figure out that how should I manage both the legacy option formatting and new format option based formatting.

Should I opt for a "rule based" checking of the options in the config provided by the user? and accordingly modify the format string or is their a better way to do it.

**Comment by gurditsbedi** [comment]
I think I have found a way out. I would request to look at [my commits](https://github.com/gurditsbedi/i3status-rust/commits/dev-net-block-fmt-one). This is a rough work. Let me know if there is a better way out.

If everything is fine. I am thinking of doing the following.
1. I will be convert the all the variable `Widgets` in the Net Struct into `string` and display the whole output as a `ButtonWidget`. This will create another issue of handling the icons.
2. Create an `icon` option to show/hide all the icons used in the block.

**Comment by gurditsbedi** [comment]
I also experimented in the following way. 
```rust
enum ButtonOrGraphWidget {
    ButtonWidget(ButtonWidget),
    GraphWidget(GraphWidget),
}

impl ButtonOrGraphWidget {
    fn set_icon(&mut self, name: &str) {
        match self {
            ButtonWidget => (self as ButtonWidget).set_icon(name),
            GraphWidget => (self as GraphWidget).set_icon(name),
        }
    }

    fn set_text(self, name: &str) {
        match self {
            ButtonWidget => (self as ButtonWidget).set_text(name),
        }
    }
}
```

But this creates another type of errors (Trait stuff) which I am not currently good at.
```
error[E0605]: non-primitive cast: `blocks::net::ButtonOrGraphWidget` as `widgets::button::ButtonWidget`
   --> src/blocks/net.rs:373:29
    |
373 |             ButtonWidget => (self as ButtonWidget).set_text(name),
    |                             ^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: an `as` expression can only be used to convert between primitive types. Consider using the `From` trait

error[E0277]: the trait bound `blocks::net::ButtonOrGraphWidget: widget::I3BarWidget` is not satisfied
   --> src/blocks/net.rs:960:18
    |
960 |             vec![&self.network]
    |                  ^^^^^^^^^^^^^ the trait `widget::I3BarWidget` is not implemented for `blocks::net::ButtonOrGraphWidget`
    |
    = note: required for the cast to the object type `dyn widget::I3BarWidget`
```

This way of doing, seems good to me if the errors can be mitigated.

What do you say?
