### ISSUE TITLE
Error in block 'focused_window': failed to acquire connect to IPC

### ISSUE THREAD

**Issue by gurditsbedi** [greshake/i3status-rust#705]
Versions:
i3 version: 4.14.1 (2017-09-24)
OS: Ubuntu 18.04 Kernel 4.15
i3status-rs version: 0.13.0

Just used the 'install from source' instruction. The 'title' says it all.

**Comment by ammgws** [comment]
Possibly the same as this comment: https://github.com/greshake/i3status-rust/pull/667#issuecomment-631238476

If I3SOCK isn't set in your environment can you try setting it before launching i3status-rust?

In the meantime I'll look into fixing this upstream.

**Comment by ammgws** [comment]
@gurditsbedi This has been fixed upstream, please rebuild and try again.
