### ISSUE TITLE
speedtest block: possible improvements to speed format?

### ISSUE THREAD

**Issue by ammgws** [greshake/i3status-rust#706]
From https://github.com/greshake/i3status-rust/pull/704#issuecomment-633022351
> I wonder if (the net block speed formatting) could be adapted into the speedtest block as well, because the formatting of that one annoys me to the point that i always patch it before updating i3status-rs... But the values are obtained in a very different way there

These are the values `speedtest-cli` outputs and i3status-rs then extracts and displays as-is:

```
>speedtest-cli --simple
Ping: 17.058 ms
Download: 977.85 Mbit/s
Upload: 876.94 Mbit/s

>speedtest-cli --simple --bytes
Ping: 16.492 ms
Download: 91.13 Mbyte/s
Upload: 98.73 Mbyte/s
```

@GladOSkar I'll see what we can do

**Comment by GladOSkar** [comment]
`i3status-rs` _does_ actually parse the output values into floats, but they're already magnitude adjusted. So i suppose one could either

1. Convert the value into the raw value (in bits/bytes) and use the net formatter or
2. Just provide an option to set the amount of decimals

**Comment by ammgws** [comment]
I was thinking about going with 1)

Also can change the command to use `speedtest-cli --json` which gives the results back in bits/s and also some other fields that could possibly be added as format qualifiers if someone wanted them.

**Comment by GladOSkar** [comment]
Oh neat i didn't know about that. Seems very reasonable

**Comment by GladOSkar** [comment]
I wonder if this could be adapted to work on all numerical values, not just data rates. Because honestly i don't need to know my ping down to microseconds either...
