### ISSUE TITLE
Varlink support

### ISSUE THREAD

**Issue by notramo** [greshake/i3status-rust#708]
Varlink is simple API that is similar in functionality to DBus (in some aspects), but doesn't require running a server, and can be used easily from any language without using additional libraries (only a JSON generator/parser is needed).
https://varlink.org/
This could be similar to the **Custom DBus** block.
https://github.com/varlink/rust
Also, it should be able to provide click/scroll events via a Varlink API.

**Comment by ammgws** [comment]
I had a quick look.

The varlink crate only adds 4 new dependencies from what I can see, and that might be able to be lowered if they implement a feature flag to disable the Windows stuff, so it might be acceptable.

There seems to be a [CLI](https://github.com/varlink/libvarlink) tool to interface with varlink, but from your "without using additional libraries" comment above it seems there's another way to send messages to the varlink that would be running in the hypothetical CustomVarlink block?

Have you used the protocol before?

**Comment by notramo** [comment]
> can be used easily from any language without using additional libraries

If you don't need all the features it can be used from shell with [`jq`](https://stedolan.github.io/jq/), so you can avoid the Varlink CLI tool dependency for your script. Obviously, using the CLI tool is much simpler and shorter if your script is more advanced.
This applies to very high-level languages, e.g. [Crystal](https://crystal-lang.org/), where JSON is included in the standard library, so if you use only few Varlink APIs, you can go without adding more dependencies.

**Comment by ammgws** [comment]
Isn't jq for parsing json? I meant to ask how you would interact with the CustomVarlink block from a shell script, given this:

> Varlink can be implemented on any connection-oriented transport.The most common example are streaming sockets, but it can also be implemented on kernel special files like device nodes or encapsulated in other protocols, like HTTP, GSS-API or SASL.

**Comment by ammgws** [comment]
Closing due to lack of response. Please re-open otherwise.
