### ISSUE TITLE
Use ACPI command for battery information.

### ISSUE THREAD

**Issue by linuxunil** [greshake/i3status-rust#71]
Wouldn't it be easier to implement things like time left and less configuration for batteries if you used a command like 'acpi -bi' and stripped the out put for just the information you need?  I would work on a block doing this but rust still confuses me.

**Comment by greshake** [comment]
Yes, it would be significantly easier. But executing commands and starting processes is a very expensive operation, especially if we can get the information directly from the kernel. This project aims to use minimal resources, and adding a dependency and significant overhead is not something we should do when there is a direct kernel interface available. We can calculate time remaining directly using the current_now property, but if we implement this we must account for differences in the interface based on battery model.

**Comment by linuxunil** [comment]
I was looking at ease of maintaining and portability, but your point makes sense.  I have looked at how powertop does it (there source is on github) and seems like there should be a library for this somewhere.
