### ISSUE TITLE
xrandr block: brightness control uses colour and not hardware brightness

### ISSUE THREAD

**Issue by ammgws** [greshake/i3status-rust#713]
The brightness control works fine (not considering the fact that it uses color and not hardware brightness), and clicking the block changes the display the brightness control acts on.

_Originally posted by @2ico in https://github.com/greshake/i3status-rust/issues/709#issuecomment-636107271_

Also https://github.com/greshake/i3status-rust/issues/92

**Comment by GladOSkar** [comment]
Isn't this sufficiently covered by the `backlight` block?

**Comment by ammgws** [comment]
Yes, so it seems redundant to add its functionality here. However I don't use either block so maybe some people just want to do everything from one block?

**Comment by 2ico** [comment]
I think xrandr.rs should run something like
```xbacklight -set {}```
instead of 
```xrandr --output {} --brightness {}```

**Comment by ammgws** [comment]
@2ico What's the reasoning behind that? Does it make it use the hardware brightness?
