### ISSUE TITLE
Specifying colors (theme) for each block

### ISSUE THREAD

**Issue by oschoudhury** [greshake/i3status-rust#72]
At the moment my upper bar looks pretty 'boring' as it is all one colour. I would love to specify alternating colours or colours on individual block basis.

**Comment by greshake** [comment]
Could be a feature, but keep in mind that the blocks don't control the color themselves- they may only report a 'state', e.g. critical, good, idle and warning, which is then used to determine the color based on the theme. I have two propositions:
1. Specify an `alternating_tint` property in the theme, which is then applied as an additive color tint to alternating blocks (e.g. when the color is  RGB 0,10,10 and the tint is 0,0,10 then the resulting color is 0,10,10).
2. Allow the user to override all possible state colors for each block. While being the most flexible solution, this entails significant implementation effort and a lot of effort to configure on the user's side. Also, themes created this way can hardly be shared or implemented as a fixed theme independent from the specific configuration of blocks.

**Comment by oschoudhury** [comment]
I would be happy with option 1, I just want to see the individual blocks immediately in one go ;)

**Comment by greshake** [comment]
Check out the current implementation, certainly still needs improvement but some of the functionality is there

**Comment by oschoudhury** [comment]
I first thought it wasn't working but overriding the alternating tint works fine. May I recommend that you use the base02/base2 colours (http://ethanschoonover.com/solarized) or one of the other colours for solarized dark? Thanks for the quick solution, this is looking a lot better now!

**Comment by jLuca** [comment]
@greshake I would happy with option 2. I think that will be an appealing features for many users, to be able to customize the look of the bar as they want. What about implementing a property for each block where you can specify the theme of that block through a JSON/TOML file?
example: I set the standard theme solarized-dark for the bar and the I override some block themes throught the property of the block. User would only download the themes they want (.JSON) and add theme in the .TOML configuration file

**Comment by Tintin512** [comment]
@LuchiLucs Were you successful in applying specific colors to each of the blocks? And would you mind telling me how's it possible actually ?

**Comment by Tintin512** [comment]
And I guess there's already a way to do since the picture in the given project shows us every block has it's own colorscheme

**Comment by LuchiLucs** [comment]
@Tintin512 I don't think so. I haven't been using it in a while.

**Comment by atheriel** [comment]
@Lucienya The colours in the image are due to the various states of each block with one of the default colour schemes; they are not set individually. It is not currently possible to customize the colour scheme of individual blocks via the configuration file.

This issue is pretty stale, so I'm going to close it for now.

**Comment by ammgws** [comment]
@oschoudhury, @LuchiLucs, @Lucienya, @cljoly  If you're still using i3status-rust then perhaps #947 may be of interest.

**Comment by cljoly** [comment]
That’s awesome, thanks @ammgws!

**Comment by aleb** [comment]
For example:
```
[[block]]
block = "sound"
headphones_indicator = true
[block.theme_overrides]
idle_fg = "#ff0000ff"
idle_bg = "#000000ff"
```
