### ISSUE TITLE
Is it a good idea to release more often

### ISSUE THREAD

**Issue by ryzokuken** [greshake/i3status-rust#720]
I noticed that a substantial amount of changes have been made to the project since the last release. I wonder if it's a good idea to make releases more often, since the `i3status-rust` package on AUR lags far behind the `master` branch on `i3status-rust-git`.

**Comment by ammgws** [comment]
See https://github.com/greshake/i3status-rust/issues/652

I guess if it still doesn't happen then I will look into it.

**Comment by ammgws** [comment]
I just started writing the release notes

**Comment by ryzokuken** [comment]
@ammgws perfect! Thanks a ton.

**Comment by ammgws** [comment]
Done

**Comment by atheriel** [comment]
@ammgws I tried to get into the habit of releasing about once every 3 months, time permitting, although the project is a bit more active now. A known, regular release schedule takes some pressure off requests like this and gives everyone clarity on how long they'll need to wait for downstream packages to update.

Congratulations on the release!
