### ISSUE TITLE
Add ability to customise number formatting when using `format` strings

### ISSUE THREAD

**Issue by ammgws** [greshake/i3status-rust#724]
> I was also wondering if decimal control could be integrated into the format string.
> 
> When thinking about things like the `net` or the `speedtest` block, it would be neat to be able to define the precision separately for the different displayed values. Ideally the syntax would allow to define all 3 arguments of the `format_speed()` function added in #704 / #707, like for example
> 
> `Free: {free:3:G:B}` for `Free: 21.9GB`
> 
> or
> 
> `Uplink: {up:2:M:b}/s` for `Uplink: 50Mb/s`
> 

_Originally posted by @GladOSkar in https://github.com/greshake/i3status-rust/pull/714#issuecomment-639379159_

**Comment by GladOSkar** [comment]
I would like to work on this but really don't have the time currently, so if somebody else wants to i don't mind

**Comment by ammgws** [comment]
Covered by #1108
