### ISSUE TITLE
Document top-level options

### ISSUE THREAD

**Issue by ryzokuken** [greshake/i3status-rust#726]
I just realized that there's a top level option called "scrolling" which is pretty nifty if you're on a laptop device. I believe it makes sense to document all top-level options somewhere, probably in the wiki or README.

**Comment by ammgws** [comment]
Hmm there doesn't seem to be a good place to add this. Perhaps we need to add a Configuration section to the README which explains the basic config format including top-level options then links out to the blocks.md and themes.md for the other.

**Comment by ryzokuken** [comment]
Thanks!
