### ISSUE TITLE
Time module does not respect locale

### ISSUE THREAD

**Issue by oschoudhury** [greshake/i3status-rust#73]
I use a different time locale with setting `LC_TIME` in `/etc/locale.conf`. The status bar is ignoring this and showing the day of the week and the name of the month (`%A` and `%B` options) in English while the same formatting options in my terminal does not show it in English.

I looked at your code, but as I am not that familiar with Rust, I cannot tell if the problem is in your code or if the problem is upstream in that `chrono` does not provide this option. If the latter is the case, please excuse for me raising the problem here and feel free to close it.

**Comment by greshake** [comment]
Well, all the formatting is done by the `chrono` crate, and I have't given much thought to locales so far. Maybe you can investigate whether this is a missing feature/bug in chrono/bug in the time block?

**Comment by oschoudhury** [comment]
I forgot to answer here. It seems like it should be able by combining the `chrono` crate with the `locale` crate, the problem is however that on [rust-locale](https://github.com/rust-locale/rust-locale) it says "This version is mostly useless. Major rewrite is pending for version 0.3.".

So I guess that for the moment it is a "won't fix" situation.

**Comment by ammgws** [comment]
Let's keep an eye on this: https://github.com/chronotope/chrono/issues/199

**Comment by ammgws** [comment]
FYI Chrono now supports localisation (https://github.com/chronotope/chrono/pull/453)

We still have to get LC_TIME ourselves though. Or add another option to the time block to specify the locale.

**Comment by cecton** [comment]
https://crates.io/crates/locale_config maybe this could be useful?

**Comment by ammgws** [comment]
@oschoudhury This should be fixed in #863. For now you'll have to manually specify your locale in the config but in the future it could be made to retrieve your system LC_TIME by default.
