### ISSUE TITLE
Configurable text for CPU, battery, brightness

### ISSUE THREAD

**Issue by notramo** [greshake/i3status-rust#736]
Currently, the CPU block prepends `CPU` to the text, the battery block prepends `FULL`, the brightness `BRIGHT`, etc.
This should be configurable with format strings

**Comment by ammgws** [comment]
Are you using the "none" theme? For the time being you can at least override the text by overriding the icons in your config file.

**Comment by notramo** [comment]
Yes, I am using `none`, and it works with override.

**Comment by ammgws** [comment]
OK, so this is solved?

**Comment by notramo** [comment]
Yes, but mentioning it in the docs would be useful for others.

**Comment by ammgws** [comment]
https://github.com/greshake/i3status-rust/blob/master/themes.md

**Comment by notramo** [comment]
Where does it mention that these texts are actually icons (if I choose `none` icon set, I expect no icons, so I guessed these are labels or something).

**Comment by ammgws** [comment]
Perhaps the name is a bit misleading, but we can't change that now. Can add a note to the docs though. PRs welcome.
