### ISSUE TITLE
Is this taskbar configured in Rust?

### ISSUE THREAD

**Issue by Joe23232** [greshake/i3status-rust#739]
Hi is this taskbar configured in Rust?

**Comment by ammgws** [comment]
The config file is in TOML

**Comment by Joe23232** [comment]
Ah I see, is it really customisable as awesomeWM?

**Comment by ammgws** [comment]
Isn't that a window compositor? You might have the wrong repo. This project generates JSON for use with i3bar/swaybar.

**Comment by Joe23232** [comment]
Oh sorry my mistake.
