### ISSUE TITLE
Battery indicicator claims very bold times

### ISSUE THREAD

**Issue by wucke13** [greshake/i3status-rust#745]
Once my battery is almost charged up, a quite huge number appears:

![2020-06-16_10:23:37](https://user-images.githubusercontent.com/20400405/84750601-c493ff00-afbb-11ea-8190-4f0ea943b7b5.png)

I'm not sure this is correct. I guess it seems to be the integer part of (2^(64)-1)/60. So probably something overflows/get's stuck in u64 max.

This is on `i3status-rs 0.14.0`

**Comment by ammgws** [comment]
@Thra11 seems related to your PR?

**Comment by Thra11** [comment]
Can you try to determine which method it's using to determine the time to full? Which of the following exist in `/sys/class/power_supply/<your battery identifier>`?
time_to_empty
time_to_full
energy_full
charge_full
energy_now
charge_now
power_now
current_now

**Comment by Thra11** [comment]
It is possible that the charging current backs off as it approaches 100%. Can you confirm that, if left for a while, it does eventually charge up to 100%?

**Comment by wucke13** [comment]
+ /sys/class/power_supply/BAT0:
   + alarm
   + capacity
   + capacity_level
   + charge_start_threshold
   + charge_stop_threshold
   + cycle_count
   + device -> ../../../PNP0C0A:00
   + energy_full
   + energy_full_design
   + energy_now
   + hwmon1
   + manufacturer
   + model_name
   + power
   + power_now
   + present
   + serial_number
   + status
   + subsystem -> ../../../../../../../../../class/power_supply
   + technology
   + type
   + uevent
   + voltage_min_design
   + voltage_now
+ /sys/class/power_supply/BAT1:
   + alarm
   + capacity
   + capacity_level
   + charge_start_threshold
   + charge_stop_threshold
   + cycle_count
   + device -> ../../../PNP0C0A:01
   + energy_full
   + energy_full_design
   + energy_now
   + hwmon3
   + manufacturer
   + model_name
   + power
   + power_now
   + present
   + serial_number
   + status
   + subsystem -> ../../../../../../../../../class/power_supply
   + technology
   + type
   + uevent
   + voltage_min_design
   + voltage_now

> Can you confirm that, if left for a while, it does eventually charge up to 100%?

Yes, indeed.

**Comment by Thra11** [comment]
So based on what properties are present, it should be taking
```
full = energy_full
fill = energy_now
usage = power_now
```
then doing `((full - fill) / usage) * 60.0` (±some unwrapping and casting). Are you able to get it into the bug state and read out the values of `energy_full`, `energy_now` and `power_now`?

**Comment by atheriel** [comment]
A quick fix for this (which has shown up in the past) would be to check of whether the differences are smaller than some tiny value before attempting any division.

**Comment by wucke13** [comment]
Funnily I wasn't able to reproduce this in the meantime. I don't know why. I will report back when I get the info, @Thra11 . Shall I close the issue, or let it open?

**Comment by ammgws** [comment]
Please leave it open

**Comment by ammgws** [comment]
Unless I have misunderstood then #912 should resolve this for now.
