### ISSUE TITLE
Missing font requirement: PowerlineSymbols

### ISSUE THREAD

**Issue by progandy** [greshake/i3status-rust#75]
The built-in themes `slick`, `solarized-dark`, and `modern` use a powerline symbol as the separator. This character is not part of FontAwesome, but requires the installation of the font [PowerlineSymbols](https://github.com/powerline/powerline/tree/develop/font).
On Arch Linux, it is available in the package `powerline-fonts`

**Comment by jLuca** [comment]
Confirmed, installing the `powerline-fonts `resolved this issue.
Here are two comparison screenshots, before and after the package installation:
[before](http://imgur.com/a/JRL3c)
[after](http://imgur.com/a/FyrRE)

**Comment by greshake** [comment]
Thanks for pointing that out, don't know how noone else noticed before :D Will add some remarks in the README as soon as I can, if you guys want you can open a PR with changes to the README.

**Comment by greshake** [comment]
Happy with these changes?

**Comment by jLuca** [comment]
Yes, I would be happy to help with PR and edit the README file or add some documentation but I am new to linux and github, so I have so many things I need to learn first and I am always busy. Maybe in the future I will contribute a bit ^^
