### ISSUE TITLE
block idea: show output configuration

### ISSUE THREAD

**Issue by colemickens** [greshake/i3status-rust#762]
Hi I have a custom block that shows this:

`| DP-1(1.0) HEADLESS-1(1.0) | `

to show the active outputs and their current scale factor.

It might be nice to have something like this built in.

**Comment by ammgws** [comment]
Can you share your custom block? Want to see if this could be done by enhancing the xrandr block.

**Comment by colemickens** [comment]
I'm using Wayland and have since moved to Waybar, sorry I can't supply that config. It was `swaymsg -t get_outputs | jq` mangled.

**Comment by ammgws** [comment]
Just saw that now. No worries.

**Comment by ammgws** [comment]
Looks like it was this anyway:
```sh
#!/usr/bin/env bash
set -euo pipefail
set -x

alloutputs="$(swaymsg -t get_outputs)"

outputnames="$(printf "${alloutputs}" | jq -r '.[] | select(.active == true).name')"

result=""
while read -r out; do
  scale="$(swaymsg -t get_outputs | jq ".[] | select(.name==\"${out}\").scale")"
  printf -v scale "%.01f" "${scale}"
  result="${result}${out}(${scale}) "
done < <(echo "${outputnames}")

printf "%s" "${result} "
```

**Comment by ammgws** [comment]
Does waybar have a native block that does what you mentioned in the OP?

**Comment by colemickens** [comment]
Heh, good find.

>Does waybar have a native block that does what you mentioned in the OP?

I don't think so. I just looked again, albeit not the world's most thorough look.
