### ISSUE TITLE
Specify background for tray icons

### ISSUE THREAD

**Issue by Alexeyan** [greshake/i3status-rust#763]
Hi. I would like to request the feature to specify the background color for tray icons. 
The current way just uses the same color as with the empty space between the workspaces and the blocks. 
Since I use a white theme during the day and for example my network manager applet icon is white, i would like to give it a dark background manually. 

As far as I can tell none of the theme overrides change the background of the tray icons.

Best regards, 
Alex

**Comment by ammgws** [comment]
Do you mean the network manager block icon? We don't control the tray. That would be i3/sway if anything
