### ISSUE TITLE
i3status-rust AUR link leads ot 404

### ISSUE THREAD

**Issue by maximeplante** [greshake/i3status-rust#764]
https://aur.archlinux.org/packages/i3status-rust/ leads to a 404.
https://aur.archlinux.org/packages/i3status-rust-git/ is fine, however.

**Comment by ammgws** [comment]
I guess whoever was maintaining it deleted it?

**Comment by maximeplante** [comment]
I thought you were the maintainers of that package. Please ignore then.

**Comment by ammgws** [comment]
It was adopted into the official Arch community repo hence being removed from the AUR: https://git.archlinux.org/svntogit/community.git/commit/trunk?h=packages/i3status-rust&id=64a77db3d268622e35d2ce68f1c0b8e0b175c496

I'll update our README

**Comment by maximeplante** [comment]
Thanks for the update!
