### ISSUE TITLE
net block shows speeds regardless of config

### ISSUE THREAD

**Issue by ammgws** [greshake/i3status-rust#766]
> After updating my current config shows fields that it didn't before. Even though i have set
> 
> ```
> [[block]]
> block = "net"
> device = "ppp0"
> hide_inactive = true
> hide_missing = true
> interval = 10
> speed_up = false
> speed_down = false
> ip = false
> 
> [[block]]
> block = "net"
> device = "eno1"
> hide_inactive = true
> hide_missing = true
> interval = 10
> speed_up = false
> speed_down = false
> ip = false
> 
> [[block]]
> block = "net"
> device = "wlp2s0"
> signal_strength = true
> interval = 10
> speed_up = false
> speed_down = false
> ip = false
> ```
> 
> The blocks show some speeds:
> ![image](https://user-images.githubusercontent.com/9497832/86793146-78445800-c06b-11ea-9dc9-1b02dbf876c0.png)
> 
> This is probably unintended and should be fixed?
> 
> _Originally posted by @GladOSkar in https://github.com/greshake/i3status-rust/issues/467#issuecomment-654886404_

**Comment by ammgws** [comment]
Hmm I can't seem to reproduce with just:
```
[[block]]
block = "net"
speed_up = false
speed_down = false
```

**Comment by GladOSkar** [comment]
I just had a look again. When i change `format` back to:

```
[[block]]
block = "net"
device = "eno1"
speed_up = false
speed_down = false
```
It shows the speed again:

![Peek 2020-07-07 16-16](https://user-images.githubusercontent.com/9497832/86794866-446a3200-c06d-11ea-97ab-2388ce1f099b.gif)

**Comment by GladOSkar** [comment]
When i unset `device` as well. I built from the `master` i _just_ pulled.

**Comment by ammgws** [comment]
Actually my bad, I was testing on another branch. Able to repro now.

@gurditsbedi  Are you able to have a look?

**Comment by gabm** [comment]
I have the same... running on Arch: 0.14.1.r1225.gc9d5f3e-1,that means I'm on this commit and the problem exists: https://github.com/greshake/i3status-rust/commit/c9d5f3e710ac5ade11956012672591ffc33e9f71

**Comment by gurditsbedi** [comment]
Confirming the issue. Will send a fix soon.

**Comment by ammgws** [comment]
Closing via #767 

Tested fine for me, please re-open if anyone still has issues.

**Comment by GladOSkar** [comment]
Works. Thanks!
