### ISSUE TITLE
Reloading block on keypress

### ISSUE THREAD

**Issue by arnegoeteyn** [greshake/i3status-rust#77]
Is it possible to make a block reload by pressing a key? Like when I would press my mediakey to increase volume the volume block would immediately reload and show the correct output? So I would put something like this in my i3config

`bindsym mediakey reload volumeblock && amixer sset Master 5%+`

**Comment by GladOSkar** [comment]
i3blocks provides this by having a "signal" option for each block, updting that block when the process receives that signal. i do not know how hard this is to implement.

**Comment by greshake** [comment]
the custom block currently doens't allow that, but you could look at a workaround: Set the custom block to read from a hidden file every second or so, and then write into the file with:
`bindsym mediakey echo 'test' > .hidden`

**Comment by lausek** [comment]
I was also looking for a solution to this problem recently. 

What about establishing a separate IPC channel that dispatches updates to each block? This should be a bit more resource-friendly dann polling it from a file, right?

**Comment by atheriel** [comment]
Slightly off-topic, but the volume block should already update automatically if you do this, although I did rate limit the refresh so it might not be totally instantaneous. Is that not what you observe?

**Comment by atheriel** [comment]
Sorry, I should clarify: `bindsym mediakey amixer sset Master 5%+` should trigger an update.

**Comment by ammgws** [comment]
#426 uses DBus, once I get around to putting the server code inside the block itself then it could be a viable solution

**Comment by ammgws** [comment]
> i3blocks provides this by having a "signal" option for each block, updting that block when the process receives that signal. i do not know how hard this is to implement.

Probably need the nix crate to implement this first: https://github.com/nix-rust/nix/issues/1143

**Comment by ammgws** [comment]
This should be covered by #822.
