### ISSUE TITLE
Align blocks to the left, or center

### ISSUE THREAD

**Issue by 7596ff** [greshake/i3status-rust#774]
I would like to have the current window block on the left side of the bar. Could this be a configuration option for all blocks?

**Comment by GladOSkar** [comment]
Unfortunately this is not possible within the [`i3bar` protocol](https://i3wm.org/docs/i3bar-protocol.html).

See #239

**Comment by NickLarsenNZ** [comment]
Could it be possible with a divider block that takes up remaining space? Or is the problem with the i3bar protocol is that there is no width information?
