### ISSUE TITLE
No ssid in net block shown

### ISSUE THREAD

**Issue by martinbrylski** [greshake/i3status-rust#782]
Hi,
I'm using this config for my net block.
```
[[block]]
block = "net"
device = "wlp0s20f3"
format = "{ssid} {signal_strength} {speed_down} {speed_up}"
```
iw and ip are installed, I'm using latest Manjaro with uptodate packages and this aur: i3status-rust-git (0.14.1.r1254.g4127fdb-1)
The device name matches the one in `ip addr`.

The icon is shown, but no ssid or signal, bitrate or anything else. It worked before the introduction of the format config.

Any suggestions whats wrong here?

**Comment by ammgws** [comment]
What happens if you remove the format string completely?

**Comment by martinbrylski** [comment]
With the latest build it seems to work properly again :-D perfect

**Comment by ammgws** [comment]
OK, hopefully it's not a fluke!
