### ISSUE TITLE
Usage without i3

### ISSUE THREAD

**Issue by fdietze** [greshake/i3status-rust#79]
Hi, is it possible to use `i3status-rust` without i3? I would like to play with this bar but am not using i3 myself. I would be fine running i3bar, but not using i3 - if that's even possible.

**Comment by OneMoreByte** [comment]
I use it with sway. I imagine you could use it with other things as long as it can run an i3bar. [Although I think they plan to make it more general in the future?](https://github.com/greshake/i3status-rust/issues/7)

**Comment by greshake** [comment]
As @OneMoreByte pointed out, there are already plans to make this program compatible with other bar-rendering programs. But currently it only works with i3bar and any wm that can use i3bar- I'll close this issue as a duplicate :)
