### ISSUE TITLE
music block does not reset title on MPRIS closed

### ISSUE THREAD

**Issue by P4Cu** [greshake/i3status-rust#791]
So it looks like music block does not listen or react to unregister of DBus service and it does not remove the tile of playing song.
This should be easy to fix.

I might have a look but for now lets mark it as unassigned.

**Comment by ammgws** [comment]
Also IIRC the whole DBus code for the music block is pretty inefficient. It subscribes to changes and when it gets one it makes another DBus call to get the new info, however that info is already available in the signal that was sent out in the first place.

**Comment by ammgws** [comment]
@P4Cu Does #874 solve your issue? I don't really have a way to test it as I can't reproduce your issue with any of my players.
