### ISSUE TITLE
kdeconnect block: battery percentage can overflow

### ISSUE THREAD

**Issue by ammgws** [greshake/i3status-rust#794]
![20200806_20h33m42s](https://user-images.githubusercontent.com/20397027/89531698-9e584600-d82b-11ea-9256-860bd34f16f9.png)

kdeconnect is returning -1 for whatever reason, but we aren't handling it properly.

**Comment by Stunkymonkey** [comment]
Could you explain what `-1` means? fully charged? empty?

**Comment by GladOSkar** [comment]
We don't know, that'd be something to research. Presumably something like "no value available"

**Comment by GladOSkar** [comment]
Looking at the [`kdeconnect` battery plugin doc](https://invent.kde.org/network/kdeconnect-kde/-/blob/master/plugins/battery/README) this isn't supposed to happen.

Looking at the [code](https://invent.kde.org/network/kdeconnect-kde/-/blob/master/plugins/battery/batteryplugin.cpp#L123), it appears to be sent whenever the device sends a packet with no charge information. It's probably irrelevant to us why this happens, might be a bug, might be a special packet that only has other information.

We should probably either ignore it until a reasonable value occurs or show a fault (e.g. `x`)

**Comment by ammgws** [comment]
There's two places where we get the charge info. Once upon first startup on the block, and then whenever a signal is received. If we assume that the former is way more rarer to occur than the latter, then we can get away with just changing the signal message handler to ignore any values <0. If we want to handle both cases then we would have to go with the `x` method described above which would need some more code changes (currently the charge is stored as an int, so would need to change that). Or maybe could keep storing it as an int and add logic to display an `x` at the very end in the update function where it generates the status bar string to show.
