### ISSUE TITLE
keyboard block: support for multiple xbkcomp layouts (active highlighting)

### ISSUE THREAD

**Issue by workflow** [greshake/i3status-rust#798]
I'm using an `xkbmap` config with 3 different layouts (comma-separated) and xkbcomp's usual way of switching layouts.

![image](https://user-images.githubusercontent.com/1276854/89712250-43a52280-d9c2-11ea-9be8-b1cb8e179ecf.png)

...so that `Win+Space` toggles between the `us`, `de` and `ua` layouts.

The `keyboard` block show the overall layout correctly:

![image](https://user-images.githubusercontent.com/1276854/89712254-53bd0200-d9c2-11ea-9470-0ad6733fe550.png)

...but it would be amazing to highlight the currently active one!

**Comment by ammgws** [comment]
Which keyboard block driver are you using?

**Comment by workflow** [comment]
Thanks for the link!

> Which keyboard block driver are you using?
Currently `localebus`, but happy to use any that will work.

I tested https://github.com/nonpop/xkblayout-state and it works, so that would be one option to explore.

**Comment by ammgws** [comment]
I take it you are in i3 and not sway?

**Comment by workflow** [comment]
> I take it you are using i3 and not sway?

i3 aye

**Comment by ivankovnatsky** [comment]
i had the same issue, while using localebus, showing almost exact same layouts: us,ua. 

switching to kbdd driver resolved the issue for me, it just showing up the current active layout.

**Comment by ammgws** [comment]
That's good to hear. I will go ahead and close this since I cannot think of any good ways to implement it for `localebus` driver. I believe it should also work for the `sway` driver as well.
