### ISSUE TITLE
[Low Prio] Add source documentation

### ISSUE THREAD

**Issue by jheyens** [greshake/i3status-rust#8]
The source code does not have a lot of `rustdoc` compatible documentation.
I added `#![warn(missing_docs)]`, to speed this up a bit. 

Nobody likes warnings on build! :-)

**Comment by XYunknown** [comment]
Worked so hard to remove the warnings, now I can hardly scroll over them in my shell, please at least remove the compiler warning flag in main and add it where it is really needed (block.rs, icons.rs, themes.rs, widget.rs)

**Comment by atheriel** [comment]
This is pretty stale, so I'm closing it for now. Please open new issues for documentation-related problems.
