### ISSUE TITLE
nvidia_gpu block: add format string because spaces between the widgets are too large

### ISSUE THREAD

**Issue by DCsunset** [greshake/i3status-rust#800]
Now many blocks support format string.
It would be great if the nvidia_gpu block also supports it.

If there's no plan to implement it currently, I could submit a PR in a few days :)

**Comment by ammgws** [comment]
See here: https://github.com/greshake/i3status-rust/pull/754

Feel free to submit a PR :)

**Comment by DCsunset** [comment]
After looking into the code, I found it hard to add the format string because the block consists of widgets, some of which could be clicked, and I haven't come up with any idea how to add it.

I originally came up with this issue because the spaces between the widgets are too large (each widget has both a leading space and a trailing space). Maybe I could try to add a property `inline` to the widget to remove the leading space when used in the same block. Does it make sense?

**Comment by ammgws** [comment]
> I originally came up with this issue because the spaces between the widgets are too large (each widget has both a leading space and a trailing space).

I believe this is an issue with the music block as well (IIRC related discussion here https://github.com/greshake/i3status-rust/issues/468).

> add a property inline to the widget to remove the leading space when used in the same block.

Hmm, perhaps this is the only way forward?

**Comment by DCsunset** [comment]
I think so because the widget inside a block should behave differently from the whole block.
Maybe I could submit a PR for it?

**Comment by ammgws** [comment]
Yeah it would be easier to proceed if there's some code to look at/test.

**Comment by DCsunset** [comment]
I have submitted a PR to resolve this issue. I hope it could be helpful.
