### ISSUE TITLE
Investigate if can use serde_json to get ip address instead of sed

### ISSUE THREAD

**Issue by ammgws** [greshake/i3status-rust#812]
Originally done in #513 but had to revert due to a bug in Debian Buster's `ip` implementation. However since then there has been a new release of Buster (10.5) so perhaps it has been fixed...

Ref: https://github.com/greshake/i3status-rust/pull/513#commitcomment-39226333

**Comment by ammgws** [comment]
@hlmtre Assuming you've upgraded to 10.5, do you still get the empty object at the start of the array as you mentioned in https://github.com/greshake/i3status-rust/pull/513#commitcomment-39226333?

**Comment by hlmtre** [comment]
I have submitted a simple workaround in a [pull request](https://github.com/greshake/i3status-rust/pull/825).
