### ISSUE TITLE
net block (nor any other for that matter) should not include "cruft" in format specifiers

### ISSUE THREAD

**Issue by Dieterbe** [greshake/i3status-rust#814]
I noticed that a net block with `format = "{ssid}"` results in the text "SSID: actual-ssid-here"
i believe this is due to `get_iw_ssid` using the full regex match rather than the first group
(`    static ref IW_SSID_REGEX: Regex = Regex::new("SSID: ([[:alnum:]]+)").unwrap();`)

it looks similar for a bunch of the other defined regexes.

note that if you're so inclined, you can always use
```
format = "SSID: {ssid}"
```

so i suggest to only put the actual ssid in `{ssid}` etc. does that make sense? i might have time to file a PR for this over the next few weeks

**Comment by ammgws** [comment]
Yeah that shouldn't be happening. Looking forward to the PR
