### ISSUE TITLE
Signal need for update to custom (or all) blocks

### ISSUE THREAD

**Issue by Gelox** [greshake/i3status-rust#819]
Sometimes you want to write event-driven custom blocks rather than blocks that poll. Let's for example say that I want to write a custom volume block, but I only want to update it when I change my volume rather than updating every X seconds.
As far as I can tell this is currently impossible, if not please let me know how to accomplish this.

I'm willing to take a look at creating this feature if it's not available currently but it seems to me that there are two important aspects that should be discussed by the community before embarking.

1) How to signal to i3status-rs that an update for some block should happen? i3blocks uses SIGKILL signals in order to signal, this comes with the negatives of a strange interface as well as the application needing to handle SIGKILL signals in an abnormal manner.
The other option that seems possible to me is to have some CLI like feature where you can call i3status-rs --signal <num> or something like this. This would require some seemingly frustrating work in implementing a server-like listener for i3status-rs but likely makes for a better interface.
Is there a feature that makes signal sending a piece of cake already implemented? Does anyone in the community have any better suggestions for attack vectors?

2) Should this be an option available to all blocks or just the custom one? I don't see a direct problem with it being given to every block, but there might be an issue in collisions with built-in update intervals. I'd suggest this feature would be limited to custom blocks initially.

Thanks! :)

**Comment by ammgws** [comment]
Depending on what you actually want to do the Custom DBus block could achieve what you want.

As for the questions:
1. SIGRT might be the best bet (see https://github.com/vivien/i3blocks#signal) so you can pinpoint updates to a specific block. See previous discussion here: https://github.com/greshake/i3status-rust/issues/77 and https://github.com/greshake/i3status-rust/issues/302. 

2. I think it would be nice to work out a solution that can be applied to any block, but Custom block would be a good start.

**Comment by ammgws** [comment]
Closed via #822, thanks for working on it!
