### ISSUE TITLE
nvidia_gpu block: hybrid graphics compability

### ISSUE THREAD

**Issue by DarkWeird** [greshake/i3status-rust#826]
`nvidia_gpu `block dont work on notebooks properly:

When nvidia card not using - nvidia-smi returns: 
`NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.` (return code: 9)

When nvidia card using - nvidia-smi returns as expected.

If disable nvidia card during `i3status-rs` - It failing all status string.

Suggestion:
hide block/disable output to block(Like a unconnected WLAN) when nvidia-smi cannot connect to dirver.

**Comment by DarkWeird** [comment]
You can use `optirun <program>`, `primusrun <program>`  or start `X` server with enabled nvidia driver.
Also it can be bbswitch kernel module...
See https://wiki.archlinux.org/index.php/Bumblebee

I don't know what really enabling nvidia driver.
(I guess bbswitch have kind of IPC mechanism)

I did use `optirun glxgears`.
While this program running - block works.

I am using Sway + swaybar.

This problem reproducing on X with enabled integrated graphics(intel) and disabled nvidia.

**Comment by GladOSkar** [comment]
> How is the card turned on/off in the first place?

@ammgws to expand on DarkWeird's answer - This happens using Nvidia's `optimus` technology for dynamically switching between graphics adapters, usually Intel HD to nvidia and back. The standard linux tool for this is `bumblebee`, but linux support is a little flaky at times.

But essentially it's definitely possible for a Nvidia card to be disabled or enabled at runtime, so this request definitely makes sense

**Comment by ammgws** [comment]
Can we just check the return code, and if it's 9 as in the OP then show the card as unavailable similar to the WiFi block, otherwise error the block.

**Comment by ammgws** [comment]
To answer my own question, yes:

> RETURN VALUE
>        Return code reflects whether the operation succeeded or failed and what was the reason of failure.
> 
>        •      Return code 0 - Success
> 
>        •      Return code 2 - A supplied argument or flag is invalid
> 
>        •      Return code 3 - The requested operation is not available on target device
> 
>        •      Return code 4 - The current user does not have permission to access this device or perform this operation
> 
>        •      Return code 6 - A query to find an object was unsuccessful
> 
>        •      Return code 8 - A device's external power cables are not properly attached
> 
>        •      Return code 9 - NVIDIA driver is not loaded
> 
>        •      Return code 10 - NVIDIA Kernel detected an interrupt issue with a GPU
> 
>        •      Return code 12 - NVML Shared Library couldn't be found or loaded
> 
>        •      Return code 13 - Local version of NVML doesn't implement this function
> 
>        •      Return code 14 - infoROM is corrupted
> 
>        •      Return code 15 - The GPU has fallen off the bus or has otherwise become inaccessible
> 
>        •      Return code 255 - Other error or internal driver error occurred

**Comment by ammgws** [comment]
@DarkWeird Can you test #846? I don't have a nvidia GPU so my testing is limited.

**Comment by ammgws** [comment]
Ended up testing with a mock script and it worked fine.

**Comment by DarkWeird** [comment]
@ammgws 

Sorry for late response.

Yeah, it works fine! Thx!

**Comment by ammgws** [comment]
Good to know!
