### ISSUE TITLE
block using high cpu with high temperature

### ISSUE THREAD

**Issue by muralikodali** [greshake/i3status-rust#827]
I have added a block to show the status of current keyboard ( whether in insert mode or normal mod ).

I have added a block as shown below :  

[[block]]
block = "custom"
command = "cat ~/.cache/xkb-curr-$DISPLAY"
interval = 0.5

the content of ~/.cache/xkb-curr-$DISPLAY ( INS for insert mode or NOR for normal mode ) is produced by a script attached below. when i run this block , temperature is raising from 45C to 60C and CPU usage is going up and down.

[xkb_swapper.zip](https://github.com/greshake/i3status-rust/files/5209642/xkb_swapper.zip)

**Comment by ammgws** [comment]
What happens if you change the interval to 1? Or 5?

**Comment by muralikodali** [comment]
I have tried the block at interval of 1 and 5.

- interval at 1, temperature raised from normal 58C
- interval at 5, temperature raised up to 42C to 47C

high temperature is accompanied by high cpu usage up to 42% for a single thread

**Comment by muralikodali** [comment]
script is taken from the url given below.

[https://cedaei.com/posts/vim-like-layer-for-xorg-wayland/](url)

xkb_swapper.sh :  
```
#!/bin/bash
# Usage: xkb_swapper.sh [layout_name]

function set_layout() {
	echo "Setting layout to $1"
	if [[ -v WAYLAND_DISPLAY ]]; then
		swaymsg input '*' xkb_file ~/.xkb/"$1".xkb
	else
		xkbcomp ~/.xkb/"$1".xkb "$DISPLAY"
	fi
	echo "$1" > ~/.cache/xkb-curr-"$DISPLAY"
}
layouts=(INS NOR)
current_layout=$(cat ~/.cache/xkb-curr-"$DISPLAY" || echo "")

if [[ $1 != "" ]]; then
	set_layout "$1"
	exit
fi
if [[ $current_layout == "" ]]; then
	echo "No current layout found!"
	set_layout "${layouts[0]}"
fi

i=0
while [[ $i -lt ${#layouts[@]} ]]; do
	if [[ $current_layout == "${layouts[$i]}" ]]; then
		new_idx="$((i+1))"
		if [[ $new_idx -eq ${#layouts[@]} ]]; then
			set_layout "${layouts[0]}"
		else
			set_layout "${layouts[$new_idx]}"
		fi
		exit
	fi
	((i++))
done

echo "Current Layout doesn't exist!"
set_layout "${layouts[0]}"
```

**Comment by ammgws** [comment]
Can you check your CPU usage details? Which processes are busy etc.

**Comment by muralikodali** [comment]
i'm attaching screenshots taken from htop with one image taken before starting the xkb process and one image taken after starting xkb process using i3status-rust.

![cpu_pre](https://user-images.githubusercontent.com/11482766/95208974-6c516900-0807-11eb-830b-4e3907029da5.png)

![cpu_post](https://user-images.githubusercontent.com/11482766/95209020-7c694880-0807-11eb-8a9a-7f5c05cb2bea.png)

**Comment by ammgws** [comment]
I think there's something weird going on in your fish config file. Your block config should only be running and consuming the output of `cat`, yet your process tree shows some perl stuff being spawned by fish. I happen to use fish as well, so I might be able to spot something if you show me your fish config.

![image](https://user-images.githubusercontent.com/20397027/95766791-bf875800-0cee-11eb-9908-bc1e3cc494b1.png)

**Comment by muralikodali** [comment]
fish config file attached.

[config.zip](https://github.com/greshake/i3status-rust/files/5369478/config.zip)

**Comment by ammgws** [comment]
Sorry could you please paste it in a gist or something? Dealing with unknown zip files is kind of... fishy 😅

**Comment by muralikodali** [comment]
uploaded config.fish content to gist as sugggested by you.

[config.fish](https://gist.github.com/9738bed15642f7bc491ef824c45fff9b)

**Comment by ammgws** [comment]
This line looks like the culprit:
```fish
. /home/zenova/projects/perl/perl5/perlbrew/etc/perlbrew.fish
```

Can you try changing it to the following?
```fish
if status is-interactive
    . /home/zenova/projects/perl/perl5/perlbrew/etc/perlbrew.fish
end
```

I'll close this issue for now but feel free to continue discussion.

**Comment by muralikodali** [comment]
Your suggestion has helped to some extent. it is consuming less cpu than before. but temperature still raises to 58 to 60 Celsius once i uncomment the relevant block. Even after completely commenting perlbrew.fish line, there is a small change in cpu load and temperature. It shows there is some other issue involved in the problem.

perlbrew version: App::perlbrew/0.86
fish, version 3.1.2

**Comment by ammgws** [comment]
Can you check htop again?

**Comment by muralikodali** [comment]
![cpuload_20201013](https://user-images.githubusercontent.com/11482766/95873225-5276cf80-0d8d-11eb-9904-8f1fcb0a1cd9.png)

**Comment by ammgws** [comment]
I still think there's something else fishy in your config. There's probably more things you should be guarding behind `is-interactive`.

Anyway I just added a new option `shell` to the Custom block in #861. To rule out fish, try `shell = "sh"` in your config and see if you still get high CPU usage.

**Comment by muralikodali** [comment]
thanks for giving a straight solution. changing the shell in the block may be useful in  some other cases also, which i am hoping from the beginning. 

now the process is consuming very less cpu and problem is completely gone.

**Comment by ammgws** [comment]
I think you should still look into your fish config though
