### ISSUE TITLE
pacman block always displays 0 

### ISSUE THREAD

**Issue by Brod8362** [greshake/i3status-rust#834]
Pacman block always displays 0 for `{count}` or `{pacman}`. The aur command works fine.
I got it to display 4 once when I first set it up, but ever since then it just displays 0.
Fakeroot **is** installed.

My config:
```
[theme]
name = "slick"

[icons]
name = "awesome"

[[block]]
block = "focused_window"
max_width= 99


[[block]]
block = "pacman"
interval = 300
format = "{pacman}/{aur}"
aur_command = "yay -Qua"
critical_updates_regex = "(linux |linux-lts|linux-zen)"

[[block]]
block = "music"
player = "mpd"
marquee=false
smart_trim=false
buttons = ["prev","play","next"]

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "battery"
#driver = "upower"
format = "{percentage}% ({time}) {power}W" 
device="BAT0"

[[block]]
block = "battery"
#driver = "upower"
format = "{percentage}% ({time}) {power}W"
device="BAT1"

[[block]]
block = "sound"
```

![image](https://user-images.githubusercontent.com/38388134/94313269-054cce00-ff44-11ea-8a44-510af52fe1ef.png)

**Comment by ammgws** [comment]
Does it work if you remove the critical_updates_regex?

**Comment by Brod8362** [comment]
Yeah, seems so, though I tried that before and I'm pretty sure it didn't work.

**Comment by ammgws** [comment]
Can't reproduce so far. Can you try running `fakeroot -- pacman -Sy --dbpath /tmp/checkup-db-yourusername/` and after that run and show the output of `fakeroot pacman -Qu --dbpath /tmp/checkup-db-yourusename/`? That is the command i3status-rs runs to get the update count.

If you have the CHECKUPDATES_DB env var set on your system then substitute that dir instead of /tmp/checkup-db-yourusername.

**Comment by Brod8362** [comment]
![image](https://user-images.githubusercontent.com/38388134/94700244-dbf3bf80-0300-11eb-8b80-f053c246c2a8.png)

Here you go. I find it unusual that `critical_updates_regex` can break it, I don't have any updates at the moment so I can't test it right now, but once I get some updates later I'm going to re-add the regex and see if it's still broken. Ever since I removed `critical_update_regex` it's been working fine.

**Comment by ammgws** [comment]
I have the exact same `critical_updates_regex` as you but haven't encountered this yet. When it happens next run those two commands again. If there are updates then the second command should list the package names.

**Comment by Brod8362** [comment]
Got some updates, added back in the `critical_updates_regex` and it's working properly now. Not sure what happened before, but I'll mark this as closed.
