### ISSUE TITLE
Backlight block - awesome icons flipped

### ISSUE THREAD

**Issue by karthink** [greshake/i3status-rust#845]
The font-awesome icons used to indicate backlight brightness are flipped, with the darkest "moon phase" corresponding to the brightest setting:

![2020-10-05-124636_122x26_scrot](https://user-images.githubusercontent.com/8607532/95113946-cfa8a180-0708-11eb-9a04-d9849e1cd02d.png)
![2020-10-05-124704_107x27_scrot](https://user-images.githubusercontent.com/8607532/95113997-e0f1ae00-0708-11eb-8b16-8f13fa7eb928.png)
![2020-10-05-124730_89x26_scrot](https://user-images.githubusercontent.com/8607532/95114034-ef3fca00-0708-11eb-9754-5708833952cd.png)
![2020-10-05-124746_84x26_scrot](https://user-images.githubusercontent.com/8607532/95114060-f961c880-0708-11eb-9f3a-502997c141f9.png)

I am not sure if this is intentional. Seems to me the progression should be flipped. I am using `ttf-font-awesome` version `5.14.0-1` from the Arch repos.

**Comment by ammgws** [comment]
See #573
