### ISSUE TITLE
Screen freeze on i3status-rust update

### ISSUE THREAD

**Issue by Nukesor** [greshake/i3status-rust#853]
Hi everyone :)

I started using i3status-rust a few weeks ago.
Around the same time, I noticed that my screen began to stutter from time to time.

The stutter was very frequent and it would result in me writing and the screen
updating about a second later all the time.

![Peek 2020-10-12 16-19](https://user-images.githubusercontent.com/3322822/95757113-fdf92480-0ca6-11eb-9c79-245e0dd66dc5.gif)

It turns out, this stutter always happens, whenever a module in i3status-rust updates and the bar is redrawn.

I'm not sure what could be the cause of this, but I would be happy to help debugging.

Current setup:

- i3status 2.13
- Arch Linux 5.8.14
- Multi monitor setup (3 screens)

Config:
```
theme = "modern"
icons = "awesome5"

[[block]]
block = "disk_space"
path = "/"
alias = "root:"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "custom"
command = '~/.config/i3/scripts/netinfo'

[[block]]
block = "memory"
display_type = "memory"
format_mem = "Mem: {Mup}%"
clickable = false

[[block]]
block = "cpu"
format = "{barchart} {utilization}%"
interval = 5
info = 80
warning = 90
critical = 95

[[block]]
block = "hueshift"
step = 50
hue_shifter = "redshift"

[[block]]
block = "battery"
device = "BAT0"
driver = "sysfs"
allow_missing = true
hide_missing = true
format = "Bat0: {percentage}% {time}"

[[block]]
block = "battery"
device = "BAT1"
driver = "sysfs"
allow_missing = true
hide_missing = true
format = "Bat1: {percentage}% {time}"

[[block]]
block = "music"
player = "spotify"
max_width = 15
marquee = true
marquee_interval = 10
marquee_speed = 0.25
buttons = ["prev", "play", "next"]

[[block]]
block = "sound"
step_width = 2

[[block]]
block = "custom"
cycle = ["~/.bin/keyboard-layout en", "~/.bin/keyboard-layout de"]
json = true

[[block]]
block = "time"
format = "%a %d-%m-%y %T"
interval = 5
```

**Comment by ammgws** [comment]
What status bar generator did you use before i3status-rust? I take it that it had no issues?

For further debugging it would be best to reduce down your config to the bare minimum that reproduces the issue. I'd start with removing your custom blocks one by one to see if they are the culprit.

**Comment by Nukesor** [comment]
I used py3status before switching to `i3status-rust`

**Comment by ammgws** [comment]
Did you manage to come up with a bare minimum config?

**Comment by Nukesor** [comment]
Hey, sorry for not responding sooner. I didn't have a chance to debug this, since it only happens on my laptop at work and I've been working at my desktop at home for the last week, which a lot faster.

Since our City just reached a critical threshold, I'll probably continue to work at home for a few weeks.
Maybe I can reproduce this issue with my SO's Notebook in the meantime.

I'll report back as soon as I get a chance to do this :)

**Comment by Nukesor** [comment]
Closing for now until, I get the chance to reproduce :)
