### ISSUE TITLE
Allow themes to be provided as a text file (launch option?)

### ISSUE THREAD

**Issue by SapiensAnatis** [greshake/i3status-rust#86]
I'm currently making a few changes to the default theme and it's kind of irritating how I have to recompile the entire project just to see how a slightly different colour looks (which takes around 50 seconds for me). 

It would be nice if I could instead work in a text file and just restart the bar with that as an argument.

I understand if parsing the text file to implement a Theme object could be a lot of work, then this may not be worth it.

**Comment by svmnotn** [comment]
@SapiensAnatis you can override themes in your config file

**Comment by svmnotn** [comment]
take a look at [example-themes.toml](https://github.com/greshake/i3status-rust/blob/master/example_theme.toml) and it's icon counterpart to see how to do it.
