### ISSUE TITLE
Better README, or perhaps enabling the Wiki feature

### ISSUE THREAD

**Issue by svmnotn** [greshake/i3status-rust#87]
Currently the README involves a lot of scrolling since it doesn't have a table of contents, however that table would add more scrolling... I think enabling the wiki would be better. However I think no matter which choice we take, we need the following:

- [ ] Table of Contents for all available blocks.
- [x] How to override themes/icons (this should be stated somewhere to avoid things like #86, unless I misunderstood that issue).
- [ ] A set format for blocks to follow, currently that is just sort of maintained by copy paste but it isn't specified anywhere as to how the documentation of a new block should be when adding one.
- [ ] Requirements for themes, and/or more importantly icon sets.

This list is just a quick take on what is missing, if anyone has anything to add I'll expand the list.

**Comment by greshake** [comment]
Yea I agree.. Moving things to the Wiki should be rather simple, I'll have a look soon. Point 2 has already been kind of adressed in https://github.com/greshake/i3status-rust/pull/57.

**Comment by svmnotn** [comment]
yes, however that adds it to the readme so it should also be on the wiki

**Comment by greshake** [comment]
Most of the stuff has been moved into the wiki, we still need a table of contents for the blocks to give a quick overview.

**Comment by svmnotn** [comment]
The table of contents for the blocks can go as part of the sidebar, so something like:

```markdown
# I3status-rust
- [How to develop a new block](Development)
- [How to: Theming and Icons](Theming-&-Icons)
- Available blocks:
  - [Time]()
```
.... etc

This should make it easier to find blocks as they would be in the sidebar

**Comment by svmnotn** [comment]
I just noticed on #90 ... I can't edit the bit that contains the documentation of the block so that it is updated, since that is a WIP, it doesn't matter but when adding a new block it will be a slight issue. Maybe we should say that the documentation for a block should be on top of the block struct? That would make it a simple copy/paste.

**Comment by atheriel** [comment]
I think the discussion in this issue is pretty stale at this point. If there are still outstanding concerns, can they be filed separately?
