### ISSUE TITLE
new release?

### ISSUE THREAD

**Issue by flokli** [greshake/i3status-rust#879]
I really enjoy using i3status-rust!

One question though: Would it be possible to craft a new release?

I started using `allow_missing` and `hide_missing` to be able to share my configuration with my laptop and workstation, but this hasn't made it into an official release yet.

**Comment by flokli** [comment]
Hmm, in fact, this doesn't seem to work on latest master (2f70c5755d7245af95740ed028965e542c4b1a73) either:

```
Oct 19 11:00:55 tp xsession[14552]: Configuration error: Failed to deserialize block config..
Oct 19 11:00:55 tp xsession[14552]: Cause: unknown field `allow_missing`, expected one of `interval`, `device`, `show`, `format`, `upower`, `driver`, `good`, `info`, `warning`, `critical`
```

**Comment by ammgws** [comment]
New release might come soon, but no guarantees yet.

Are you sure you're running the correct binary?
```sh
git clone https://github.com/greshake/i3status-rust
cd i3status-rust
cargo run
```

**Comment by flokli** [comment]
Indeed I was running an older binary there, sorry for the noise.

Confirmed this works with latest master, looking forward for a release :-)
