### ISSUE TITLE
music block icon missing

### ISSUE THREAD

**Issue by ammgws** [greshake/i3status-rust#889]
PS my collapsed block looks like this. perhaps i'm missing an icon or something? (all other icons work fine though, see full bar below)
![music](https://user-images.githubusercontent.com/20774/96735792-989ee500-13c4-11eb-9e03-e820142f0bcc.png)
![bar](https://user-images.githubusercontent.com/20774/96735944-c1bf7580-13c4-11eb-908f-7e058d0416c8.png)

_Originally posted by @Dieterbe in https://github.com/greshake/i3status-rust/issues/808#issuecomment-713627847_

**Comment by ammgws** [comment]
@Dieterbe 
What's your config file look like?

**Comment by Dieterbe** [comment]
[status-rust-dark.txt](https://github.com/greshake/i3status-rust/files/5416726/status-rust-dark.txt)
thanks @ammgws !

**Comment by ammgws** [comment]
I'm also using `awesome5` but mine displays fine. How about your i3bar config? I'm using sway but it should be the same:
```toml
bar {
    font pango:DejaVu Sans Mono, FontAwesome 10
    status_command i3status-rs
...
}
```

**Comment by Dieterbe** [comment]
```
bar {
    font pango:DejaVu Sans Mono, FontAwesome 10
    position top
    status_command /home/dieter/code/i3status-rust/target/release/i3status-rs .i3/status-rust-dark.toml
    colors {
        separator #666666
        background #222222
        statusline #dddddd
        focused_workspace #0088CC #0088CC #ffffff
        active_workspace #333333 #333333 #ffffff
        inactive_workspace #333333 #333333 #888888
        urgent_workspace #2f343a #900000 #ffffff
    }
}

```

**Comment by ammgws** [comment]
It shouldn't make a difference but what happens if you try copy pasting the below into your config? (removing your existing icons line)

```toml
[icons]
name = "awesome5"
[icons.overrides]
music = "   "
```

**Comment by Dieterbe** [comment]
it makes no difference indeed. but look at how it renders in chromium and then how it renders when i copy paste the text from the browser to my editor/terminal (vim+termite) :/
looks like i have an issue that goes well beyond i3status-rust. (quite annoying because i recently spent almost a day getting my font setup fixed so that it displays icons properly.. or so i thought. if i recall correctly it turned out the only thing i really had to do was [define a fallback font](https://wiki.archlinux.org/index.php/Font_configuration#Force_emoji_font)) 
 
![icons](https://user-images.githubusercontent.com/20774/96740616-aacf5200-13c9-11eb-9212-9eb4ee994dca.png)

**Comment by Dieterbe** [comment]
i notice the font section in the readme. this looks like it may indicate a problem
```
$ fc-match FontAwesome
DejaVuSans.ttf: "DejaVu Sans" "Book" # <--- shouldn't this say fontawesome instead of dejavu?
$  fc-list | grep -i awesome
/usr/share/fonts/TTF/fa-brands-400.ttf: Font Awesome 5 Brands,Font Awesome 5 Brands Regular:style=Regular
/usr/share/fonts/TTF/fa-solid-900.ttf: Font Awesome 5 Free,Font Awesome 5 Free Solid:style=Solid
/usr/share/fonts/TTF/fa-regular-400.ttf: Font Awesome 5 Free,Font Awesome 5 Free Regular:style=Regular

```

**Comment by Dieterbe** [comment]
hooray, changing my i3 bar config to say
```
    font pango:DejaVu Sans Mono, Font Awesome 5 Free
```
fixes the icon in my status bar.

**Comment by moghwan** [comment]
> It shouldn't make a difference but what happens if you try copy pasting the below into your config? (removing your existing icons line)
> 
> ```toml
> [icons]
> name = "awesome5"
> [icons.overrides]
> music = "   "
> ```

this worked well by specifying a custom icon from font-awesome, with both "awesome" and "awesome5"
