### ISSUE TITLE
equal amount of whitespaces as seperators in a single block

### ISSUE THREAD

**Issue by Stunkymonkey** [greshake/i3status-rust#900]
when using mono spaced fonts this catches my eye

some blocks have more spaces, then needed:

- wifi but no ethernet
![Screenshot-2020-10-24_005148](https://user-images.githubusercontent.com/1315818/97060269-1f092180-1593-11eb-9ccc-ba89ad4f1f0b.png)
- battery if fully charged
![Screenshot-2020-10-24_005121](https://user-images.githubusercontent.com/1315818/97060255-144e8c80-1593-11eb-9075-e46f5b0b4722.png)
- when connecting ethernet and wifi there is some weird spacing inbetween

is this intentional? I expect that is was programmed this way, because it was easy.

It would be more pleasing if the spacing is even on both sides.

I cloud help implementing a fix, but first I want some feedback and suggestions on how to do it or maybe why not to do it.

**Comment by ammgws** [comment]
I doubt it's intentional to have uneven spacing. Can you post your actual config?

**Comment by Stunkymonkey** [comment]
https://pastebin.com/x14cjkGe

**Comment by ammgws** [comment]
So for the battery block your config is `"{percentage}%<space>{time}"` and here in one of the cases `time` is set to an empty string:

https://github.com/greshake/i3status-rust/blob/db9b567e31f497b3a35f25451b7286a31f5e6e59/src/blocks/battery.rs#L726-L732

Which means the output turns into `"{percentage}%<space>"`.

One way to fix it might be to include the space in `{time}` itself so you can set your config to `"{percentage}%{time}"`, but it would introduce an extra space for people who still have their configs set to `"{percentage}%<space>{time}"`...

**Comment by Stunkymonkey** [comment]
maybe we could have a regex searching for more then two spaces and replace it with a single space?

**Comment by Stunkymonkey** [comment]
this would then have some bad behavior if the user has a format string `{percentage}%<space><space>{time}`

**Comment by Stunkymonkey** [comment]
> include the space in {time}

would prevent people to not have any space at all. Maybe that is something users want.

**Comment by ammgws** [comment]
As you can see from the links below fixing spacing has been an on going battle, and likely the issues left now are not trivial to solve. For blocks that use format strings perhaps each format specifier such as `time` etc could each have a format string itself such as `{time_format}` but things might get out of hand

https://github.com/greshake/i3status-rust/pull/866
https://github.com/greshake/i3status-rust/pull/894
https://github.com/greshake/i3status-rust/issues/468
https://github.com/greshake/i3status-rust/issues/381
https://github.com/greshake/i3status-rust/issues/498
https://github.com/greshake/i3status-rust/pull/870
https://github.com/greshake/i3status-rust/issues/884
https://github.com/greshake/i3status-rust/issues/800

**Comment by ammgws** [comment]
> > include the space in {time}
> 
> would prevent people to not have any space at all. Maybe that is something users want.

Might possibly be the only way to go.

**Comment by Stunkymonkey** [comment]
what about an integer-option to deduplicate the whitespace (at start and end (sufficient for even spacing, but inner is ignored)) to a fixed amount of spaces? doing this for all blocks?

**Comment by Stunkymonkey** [comment]
I thought about this some time. I think the best solution is to include the "space" in e.g. `{time}` itself. Like you suggested.

Additionally I would like to add the option to define the "included space", so that maybe someone wants to have double space/tab/... he could do that.

All solutions to reformat after formatting the string are kind of shitty from my point of view.

This way the uneven spacing would be solved, but this would introduce breaking changes (only visual). I think introducing them now is painful yes, but doing so in in some years (after 1.0) would be worse.

If I implement this nicely, would the PR be welcomed?

**Comment by Stunkymonkey** [comment]
with this PR every block I am using works fine except `networkmanager`.

**Comment by Stunkymonkey** [comment]
# 923 now fixes all blocks I am using

**Comment by ammgws** [comment]
Closed via #923 

Create a new issue for any other ones
