### ISSUE TITLE
Taskwarrior block filter is overly restrictive

### ISSUE THREAD

**Issue by matt-snider** [greshake/i3status-rust#905]
The current implementation of the taskwarrior block only allows specifying a filter of the form `+tag1 +tag2 +tag3 ...` which does not allow for negating tags (`-tag1`), or specifying `or` instead of the implicit `and` ( `+tag1 +tag2 or +tag2`). An example of a query I'd like to do would be `+PENDING +OVERDUE or +DUETODAY`. Unless I have missed something, this isn't possible.

For reference, here is a minimal configuration:

```toml
[[block]]
block = "taskwarrior"
filter_tags = ["tag1", "tag2"]
```

The cause of the restrictiveness is that the block already prepends the `+`: 

```rust
fn tags_to_filter(tags: &[String]) -> String {
    tags.iter()
        .map(|element| format!("+{}", element))
        .collect::<Vec<String>>()
        .join(" ")
}
```

This seems unnecessary because the effort for the user to specify `+` themselves is negligible, and it reduces the block's flexibility significantly.

I have two different ideas for how we could improve the block:

1. Prefix with `+` only if the tag does not already start with `+` or `-`  
    * Allows more complex queries, but still does not allow for specifying `or` 
    * Is backward compatible and a minimal change in the code
2. Allow specifying a `filter` string instead of `filter_tags` which is passed to the `task` command as is
    * Is very flexible
    * Allows an easy to switch from `filter_tags` to `filter`
    * Is more work for users to change - we could deprecate the option initially, and simply convert `filter_tags` to `filter` at the parse stage using the existing `tags_to_filter()` function.

I would be grateful to get some feedback from those who have worked on and use this block - @flying7eleven @HPrivakos @jubnzv let me know what you think

**Comment by flying7eleven** [comment]
The implementation - as it is right now - was due to my own use-case. Additionally I wanted to keep it as simple as possible for the user. I can completely understand that this is not flexible enough for everyone. I would go for the second option since even the backward-compatibility can be easily achieved with your posted approach. 👍🏻

**Comment by matt-snider** [comment]
@flying7eleven Thanks for the feedback. I'll give it a shot! :-)

**Comment by ammgws** [comment]
Closed via @1008
