### ISSUE TITLE
New block for calendar events

### ISSUE THREAD

**Issue by theamma** [greshake/i3status-rust#919]
I just implemented a block that displays the amount of current calendar events. It uses [_khal_](https://github.com/pimutils/khal) as his backend. I thought it could be of use for others as well, thus, I tried to push the branch (in preparation of a PR) and got this: _remote: Permission to greshake/i3status-rust.git denied to theamma._ Sorry for all beginner's mistakes - I am doing this for the first time. Thanks.

**Comment by ammgws** [comment]
You need to push it to your cloned repo instead
