### ISSUE TITLE
change brightness control from xrandr to sysfs

### ISSUE THREAD

**Issue by etrombly** [greshake/i3status-rust#92]
xrandr changes the brightness of the display using gamma rather than changing the brightness in hardware, so it doesn't really save much power. Using /sys/class/backlight/ directly would require a udev rule for a regular user, but saves a lot more power. Not sure if this would be better as an entirely separate block, or an option.

**Comment by greshake** [comment]
I'm not familiar with the interface and how easy it will be to make this compatible with a lot of screens.. But of course using the interface would be much preferred

**Comment by etrombly** [comment]
It supports multiple displays, the names aren't as nice though. They'll be along the lines of acpi_video0, and intel_backlight. It also has the edid, so you can parse out the actual display name if it reports it correctly, but that's probably too long.

**Comment by mirh** [comment]
Just for the records, xrandr *can* change "hardware brightness". It's just that it's called backlight in there (in the drivers that support this property to begin with)

**Comment by ammgws** [comment]
@mirh Do you mean the `--brightness` option can change hardware brightness depending on the user's hardware? Or is there another option specifically for changing hardware brightness? I couldn't find one.

**Comment by mirh** [comment]
No, brightness is just a hacky software solution, end. 
I meant the `backlight` property. 
https://unix.stackexchange.com/questions/61256/how-to-change-lcd-intensivity-brightness

**Comment by ammgws** [comment]
Hmm those are some weird ranges. We could add an option to the xrandr block to make it use this method, just need to parse out the ranges I guess.

```sh
xrandr --verbose
Screen 0: ...
    BACKLIGHT: 268 
        range: (0, 852)
    Backlight: 268 
        range: (0, 852)
```

**Comment by mirh** [comment]
Or there should also be xbacklight I guess.
