### ISSUE TITLE
Change alternating tint start point

### ISSUE THREAD

**Issue by ammgws** [greshake/i3status-rust#925]
I wonder if it would make more sense to do the alternating from right to left than from left to right, since the right is basically the anchor of the status bar.

Currently, whenever a network device shows up or disappears on my system, the alternating color stays the same on the left of that block and flips on the right. I'd rather have it the other way around

_Originally posted by @GladOSkar in https://github.com/greshake/i3status-rust/pull/924#issuecomment-725403106_

**Comment by ammgws** [comment]
I guess it makes sense since the bar itself is filled from right to left. Only problem is that the blocks are ordered left-to-right in the JSON output so we need to reverse the order to calculate the tints and then reverse it again to print the blocks.

**Comment by GladOSkar** [comment]
Yeah seems a bit clunky to implement. I always found it confusing that the first block in the config was the leftmost and not the rightmost one on the bar, but that can't be changed anymore.

Still, i'll have a look

**Comment by GladOSkar** [comment]
I played around with it and have a solution in #927. A review would be appreciated :)
