### ISSUE TITLE
Keyboard layout block: re-add variant

### ISSUE THREAD

**Issue by ammgws** [greshake/i3status-rust#935]
Any way to get this to show again? I switch variants but not the layout. In my case br-qwerty and br-dvorak

_Originally posted by @Henriquelay in https://github.com/greshake/i3status-rust/issues/458#issuecomment-728205857_

**Comment by ammgws** [comment]
@Henriquelay we could add another specifier for the `format` string which shows the variant. The question is how do reliably get that info (I haven't used X in years so have forgotten details). Can you submit a PR?

**Comment by Henriquelay** [comment]
I will try my best.
I have never contributed in projects like this, so I will take my time.
Any insights outside of CONTRIBUTING.md ?

**Comment by ammgws** [comment]
It should be a fairly straight forward change. You can open a PR and mark it as a draft so we can figure it out as you go.

By the way which `driver` are you using: "setxkbmap", "localebus", or "kbddbus"?

**Comment by Henriquelay** [comment]
localebus

**Comment by ammgws** [comment]
I'm confused then since according to that PR you commented on, the variant was only ever shown when using the `kbddbus` driver. For `localebus` all we are doing is grabbing the layout from the `X11Layout` property, but since the DBus interface also exposes the variant with the `X11Variant` property, this should be trivial to implement for the `localebus` driver.

**Comment by ammgws** [comment]
Try #940

**Comment by Henriquelay** [comment]
Sorry, I didn't express myself well and also initially misunderstood #458. I meant to display currently active layout and variant. #940 currently just show all my layouts and variants, as a static string.
I previously used Cinnamon, and [it has this functionality](https://github.com/linuxmint/cinnamon/tree/2499b0920ddbc86692f89cb54777486005add497/files/usr/share/cinnamon/applets/keyboard%40cinnamon.org), I wanted to replicate in i3.
