### ISSUE TITLE
Pango escaping broken for custom blocks.

### ISSUE THREAD

**Issue by ammgws** [greshake/i3status-rust#936]
Seems like this issue hasn't been fully resolved. At least not for custom blocks.

```shell
#!/bin/sh

## Fails - Empty
echo "{\"text\":\"1 &\"}"
## Works
echo "{\"text\":\"2 &amp;\"}"

## Fails - Empty
echo "1 &"
## Works
echo "2 &amp;"


## Works
echo "{\"text\":\"1 >\"}"
## Works
echo "{\"text\":\"2 &gt;\"}"

## Works
echo "1 >"
## Works
echo "2 &gt;"


## Fails - Empty
echo "{\"text\":\"1 <\"}"
## Works
echo "{\"text\":\"2 &lt;\"}"

## Fails - Empty
echo "1 <"
## Works
echo "2 &lt;"


## Works
echo "{\"text\":\"1 '\"}"
## Works
echo "{\"text\":\"2 &#39;\"}"

## Works
echo "1 '"
## Works
echo "2 &#39;"
```

_Originally posted by @Donatzsky in https://github.com/greshake/i3status-rust/issues/644#issuecomment-728127484_

**Comment by ammgws** [comment]
IIRC if we pango escape the output then it will break pango formatting. Looks like the solution is either to have you manually escape the characters yourself or add a `pango=false` option that enables pango escaping for the output text.

**Comment by Donatzsky** [comment]
Adding a `pango=false` option would be a good idea, I think. That would probably handle the vast majority of cases.
If you want to use Pango, you can then do the escaping yourself.

```shell
#!/bin/sh

function PangoEscape {
	_string=$1
	_string=${_string//"&"/"&amp;"}
	_string=${_string//"'"/"&#39;"}
	_string=${_string//'"'/'\"'}
	_string=${_string//'<'/'&lt;'}
	_string=${_string//'>'/'&gt;'}

	echo "$_string"
}
```

**Comment by ammgws** [comment]
Sound good to you @matclab? (Your previous comments: https://github.com/greshake/i3status-rust/issues/644#issuecomment-626990284)

**Comment by matclab** [comment]
Yes, a `pango=false` option looks good to me. Thanks for asking.

**Comment by ammgws** [comment]
Actually this isn't just specific to the custom block, is it? I think any block where you can use a `format` string then this same thing could occur...
