### ISSUE TITLE
can't display CURRENT cpu temperature

### ISSUE THREAD

**Issue by becomeacoder** [greshake/i3status-rust#941]
Hi,greshake,Thanks for your working on i3status-rust,it's greate.
There is one little problem,
i3status-rust can't show the current cpu temperature,
although I using "custom" to work it out,
but lack of  color supporting,and eats a little more resource.
can you provide a new {cpu} to show the current cpu temperature?
Thanks in advance!

**Comment by ammgws** [comment]
Did you get the "chip" and "inputs" options? Post your config.

**Comment by becomeacoder** [comment]
[[block]]
block = "temperature"
collapsed = false
interval = 3
chip = "*-isa-*"
inputs = ["temp1"]







Just found a bug,inputs = ["CPUTIN","SYSTIN"] won't work,
inputs = ["temp1"] works.

So I go back to read the doc,
1)    chip = "*-isa-*"  and  inputs = ["temp1"] will filter out all but CPU temperature,right?
2)    and  the avg is about all different sensors at the same time,not about  a same sensor at different time,am i right?

**Comment by ammgws** [comment]
Run the command "sensors" to see what values you need for "chip" and "inputs"

I'm not too sure what the issue is to be honest

**Comment by becomeacoder** [comment]
[[block]]
block = "temperature"
collapsed = false
interval = 3
chip = "*-isa-*"
inputs = ["temp1"]
format = "{min}°C"




This config works fine on my laptop.
The problem is the input value,some how  inputs = ["CPUTIN", "SYSTIN"] can't be recognize.

**Comment by ammgws** [comment]
Can you paste here the output of the sensors command?

**Comment by becomeacoder** [comment]
thinkpad-isa-0000
Adapter: ISA adapter
fan1:        2712 RPM
temp1:        +53.0°C  
temp2:        +40.0°C  
temp3:        +39.0°C  
temp4:         -1.0°C  
temp5:            N/A  
temp6:            N/A  
temp7:            N/A  
temp8:            N/A  
temp9:        +41.0°C  
temp10:       +44.0°C  
temp11:       +48.0°C  
temp12:           N/A  
temp13:           N/A  
temp14:           N/A  
temp15:           N/A  
temp16:           N/A  

acpitz-acpi-0
Adapter: ACPI interface
temp1:        +53.0°C  (crit = +127.0°C)
temp2:        +50.0°C  (crit = +100.0°C)

**Comment by ammgws** [comment]
Well there you go, that explains why "CPUTIN" or "SYSTIN" didn't work for you: your system doesn't have (show?) them. You can only choose from whats in that list for your block config.
