### ISSUE TITLE
Problem with icons

### ISSUE THREAD

**Issue by holoGDM** [greshake/i3status-rust#948]
I saw this ticket https://github.com/greshake/i3status-rust/issues/130 and try different things from there to solve my problem but still my status is looking like that:

![image](https://user-images.githubusercontent.com/29735778/100258531-79f1b800-2f47-11eb-92e1-73c8a5771717.png)

my present config (i tried combination of all settings awesome, awesome5 and material)

```
theme = "solarized-dark"
icons = "material"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"
```

My bar config:

```
ar {
	i3bar_command i3bar
	status_command i3status-rs $HOME/.config/i3/i3status-rs-config.toml
	position top

## please set your primary output first. Example: 'xrandr --output eDP1 --primary'
	tray_output primary
#	tray_output DisplayPort-0

	bindsym button4 nop
	bindsym button5 nop
	font pango: DejaVu Sans Mono, Font Awesome 5 Free, Material Icons
	strip_workspace_numbers yes

    colors {
        background #222D31
        statusline #F9FAF9
        separator  #454947

#                      border  backgr. text
        focused_workspace  #F9FAF9 #16a085 #292F34
        active_workspace   #595B5B #353836 #FDF6E3
        inactive_workspace #595B5B #222D31 #EEE8D5
        binding_mode       #16a085 #2C2C2C #F9FAF9
        urgent_workspace   #16a085 #FDF6E3 #E5201D
    }
}
```

i was trying with:
```
font pango:DejaVu Sans Mono, FontAwesome 12
```
too and icon "awesome" in settings but still that same

My installed fonts:

```
 ~  .config  i3  master  ✎  +  $  fc-list | grep Awesome
/usr/share/fonts/TTF/fa-brands-400.ttf: Font Awesome 5 Brands,Font Awesome 5 Brands Regular:style=Regular
/usr/share/fonts/OTF/Font Awesome 5 Brands-Regular-400.otf: Font Awesome 5 Brands,Font Awesome 5 Brands Regular:style=Regular
/usr/share/fonts/awesome-terminal-fonts/fontawesome-regular.ttf: FontAwesome:style=Regular
/usr/share/fonts/OTF/Font Awesome 5 Free-Regular-400.otf: Font Awesome 5 Free,Font Awesome 5 Free Regular:style=Regular
/usr/share/fonts/TTF/fa-solid-900.ttf: Font Awesome 5 Free,Font Awesome 5 Free Solid:style=Solid
/usr/share/fonts/TTF/fa-regular-400.ttf: Font Awesome 5 Free,Font Awesome 5 Free Regular:style=Regular
/usr/share/fonts/OTF/Font Awesome 5 Free-Solid-900.otf: Font Awesome 5 Free,Font Awesome 5 Free Solid:style=Solid
 ~  .config  i3  master  ✎  +  $  
```

```
 ~  .config  i3  master  ✎  +  $  fc-list | grep Material
/home/holo/.local/share/fonts/MaterialIcons-Regular-for-inline.ttf: Material Icons:style=Regular
 ~  .config  i3  master  ✎  +  $  
```
Am i missed something? I have powerlinefonts installed too:

community/powerline-fonts 2.8.1-1 [installed]
    patched fonts for powerline

**Comment by holoGDM** [comment]
Today icons started working but instead i do not have "arrows" (i have but not such like they should be):

![image](https://user-images.githubusercontent.com/29735778/100360890-d1506080-2ff9-11eb-8851-187e46b2ac40.png)

**Comment by ammgws** [comment]
What changed between then and now for the icons to suddenly start working?
Also what distro are you using?
What does it look like when you run it inside a terminal?

(I'll close this since it's not an actual issue with i3status-rust but feel free to continue discussion)

**Comment by holoGDM** [comment]
Hello, sorry i didnt saw Your reply. I do not know what changed probably some fonts loaded after boot (but i made fc-cache udpate when i installed new fonts). Right now i have problem with separators which are like on screen. After change to other sign they are small or half hidden behind bar.

**Comment by shahriar0247** [comment]
just close this, becaue it doesnt have an answer
