### ISSUE TITLE
Wrong label of "volume_muted" in "none" icon set

### ISSUE THREAD

**Issue by usaoc** [greshake/i3status-rust#951]
Should be `" VOL MUTED "` instead.

https://github.com/greshake/i3status-rust/blob/e45b9c6d2d8d945a6df1c55128c4db523c6d682c/src/icons.rs#L64

**Comment by ammgws** [comment]
Thanks! Fixed here: https://github.com/greshake/i3status-rust/commit/a4bc0d7a1e2bb6217bb19c18cbc3ae1b2c4f98f8
