### ISSUE TITLE
Configuration parse error

### ISSUE THREAD

**Issue by GrayJack** [greshake/i3status-rust#952]
Today I updated to the latest master and a configuration error started to come up:

```
Configuration error: failed to parse TOML from file contents.
Cause: invalid type: map, expected a string for key `theme` at line 139 column 1
```

My [config](https://up1.secretalgorithm.com/#55rkQW6Cy-N0aVqfTEiUrg) for reference.

I didn't found a break change in the commit logs, so I thought it was all ok to update. Do you know the reason for the error?

**Comment by ammgws** [comment]
What version were you using previously? I just tried with an old release (v0.13.1) and I got something similar:

```sh
{"version": 1, "click_events": true}
[[{"background":"#000000","color":"#dc322f","full_text":" Configuration error: failed to parse TOML from file contents.\nCause: cannot find specified icons for key `icons` at line 139 column 1 ","separator":false,"separator_block_width":0}]


Configuration error: failed to parse TOML from file contents.
Cause: cannot find specified icons for key `icons` at line 139 column 1
```

**Comment by ammgws** [comment]
Actually I think that's too old a release. I'll try bisecting

**Comment by ammgws** [comment]
OK looks like it was #938

**Comment by GrayJack** [comment]
> What version were you using previously? I just tried with an old release (v0.13.1) and I got something similar:

It was a build of about 2.5 weeks 

> OK looks like it was #938

Yeah, the build was certainly older than 11 days ago where this PR was merged

**Comment by ammgws** [comment]
This is the line that trips it: `alternating_tint_fg = "#111111"`

I'll find out what's going on

**Comment by GladOSkar** [comment]
I removed the `alternating_tint_fg` since it wasn't implemented anywhere (ie. didn't actually tint the text). @ammgws re-added it as a dummy option. Let us know if you'd actually want it to tint the text, then i'll add that :)

**Comment by GrayJack** [comment]
Yeah, I used it before when it made difference, but I didn't notice that it was not having the same effect, I'll remove it from my config

**Comment by ammgws** [comment]
I ended up re-adding it properly to keep the old behaviour.

**Comment by foxhoundsk** [comment]
Hmm.. I got a similar issue on version 0.22.0. By running `i3status-rs` directly, I got:
```
{"version": 1, "click_events": true}
[
[{"full_text":" Error: failed to parse TOML from file contents (Cause: unknown field `theme`, expected one of `name`, `file`, `overrides` for key `theme` at line 41 column 1) ","color":"#DC322FFF","background":"#000000FF","name":"0","instance":"0","separator":false,"separator_block_width":0,"markup":"pango"}],


Wrapped("failed to parse TOML from file contents", Error { inner: ErrorInner { kind: Custom, line: Some(40), col: 0, at: Some(646), message: "unknown field `theme`, expected one of `name`, `file`, `overrides`", key: ["theme"] } })
```

And the config in use is the [example config](https://github.com/greshake/i3status-rust/blob/26763bc0e023808fb756601fd38a735dc391b825/examples/config.toml).

Any thoughts? Thanks!

**Comment by ammgws** [comment]
The example config you linked is for v0.3
