### ISSUE TITLE
Add a calendar icon to icons.rs

### ISSUE THREAD

**Issue by theamma** [greshake/i3status-rust#956]
Would it be possible to add a calendar icon to icons.rs? I need this for a custom [block](https://github.com/theamma/i3status-custom-pim) and it's probably not that uncommon and thus useful for others also.

"calendar" => " CAL ",
"calendar" => " \u{f073} ",

Would it be okay to create a pull request for this?

**Comment by ammgws** [comment]
I guess it's harmless enough...

Go for it
