### ISSUE TITLE
[feature request] left-align option for blocks

### ISSUE THREAD

**Issue by ngortheone** [greshake/i3status-rust#970]
It would be awesome to be able to put some blocks on the left.
Idea taken from Waybar: 
![waybar screenshot](https://raw.githubusercontent.com/alexays/waybar/master/preview-2.png)

**Comment by ammgws** [comment]
As far as I know this isn't possible, and if I recall correctly i3 rejected a proposal to allow it. https://github.com/greshake/i3status-rust/issues/774
