### ISSUE TITLE
Hide Pacman if up to date?

### ISSUE THREAD

**Issue by JP-Ellis** [greshake/i3status-rust#971]
Is there an option to hide the pacman block if the system is up to date?  If not, this could be a useful addition.

**Comment by ammgws** [comment]
I'd accept a PR for that

**Comment by ammgws** [comment]
Does #971 do the trick for you?

**Comment by GladOSkar** [comment]
> Does #971 do the trick for you?

I presume you mean #982 :)

**Comment by ammgws** [comment]
![image](https://user-images.githubusercontent.com/20397027/102353481-74d6d480-3fec-11eb-8bcd-cfd1a6d671db.png)
