### ISSUE TITLE
Battery info broken in the latest version of kdeconnect

### ISSUE THREAD

**Issue by ammgws** [greshake/i3status-rust#974]
D-Bus structure changed: https://github.com/KDE/kdeconnect-kde/commit/f90d6a019ff288c4a16f91c2d7baa617ce793077

**Comment by 12ian34** [comment]
thank you for working on this

**Comment by ammgws** [comment]
What distro are you on?

**Comment by 12ian34** [comment]
@ammgws 5.10.14-arch1-1

**Comment by ammgws** [comment]
Thought so. I guess a lot of people will still be on the older versions on other distros so need to figure out how to support both.

**Comment by 12ian34** [comment]
@ammgws I'm just glad this issue is being tracked. I didn't even know about kdeconnect until reading about it in the docs here!
