### ISSUE TITLE
Volume Inidicator Broken for pipewire-pulse

### ISSUE THREAD

**Issue by carloabelli** [greshake/i3status-rust#976]
I was experimenting with using pipewire as a replacement for pulseaudio (specifically the `pipewire-pulse` package on Arch Linux). 

When using the pipewire pulseaudio server, the volume indicator seems to be stuck at `00%`. This is despite the fact that pavucontrol reports the correct volume and sound does play.

Not sure if there is an issue here or upstream with libpulse/libpulse_binding and haven't had time yet to investigate, but since pavucontrol can correctly get the volume it seems that there should be a way to support pipewire-pulse as well.

Note that pipewire-pulse is still experimental, so this is unlikely to affect many users, but still figured it was worth investigating.

**Comment by murlakatamenka** [comment]
I'm using Arch's `pipewire-pulse` too and it works fine for me (my scripts work, so does `pavucontrol`, Wine games etc).

I have this in the config:

```toml
[[block]]
block = "sound"
driver = "auto"
```
+ device names mappings. `i3status` works the same as with Pulse Audio in my case, no issues.

**Comment by carloabelli** [comment]
Huh strange. I specified `driver = "auto"`, reloaded and it worked, I removed `driver = "auto"` (since it should be the default anyways) and it worked. Maybe it just needed to be reloaded? I'll see if I can find a more specific way to reproduce this and reopen if I can.

**Comment by carloabelli** [comment]
Looks like this happens pretty consistently on reboot for me. A reload of sway (reloads i3status-rs) fixes the issue. My guess is that i3status-rs starts up before `pulseaudio-pulse` is ready. Not sure if it is worth adding a check for this case here, so I'm going to leave this closed.

**Comment by rumpelsepp** [comment]
Can confirm this.

**Comment by ammgws** [comment]
I don't think it's our fault so may be worth reporting to the pulse crate is it hasn't been already
