### ISSUE TITLE
Automatically determine default route for the network interface

### ISSUE THREAD

**Issue by BourgondAries** [greshake/i3status-rust#977]
There's a bandwidth monitor in i3blocks's contribs called `bandwidth3` that determines the default route and uses that to gather information. Before making any commits, I'd like to discuss this.

The main usage of this is for sharing the same config on multiple computers with different network configurations. Instead of making an entry for each of these systems it would be much preferable to have just one.

**Comment by ammgws** [comment]
bandwidth3:
> Note that the interface will be guessed using ip route but it can also be specified using the $IFACE property

Don't we already do this?
https://github.com/greshake/i3status-rust/blob/4d8f98a04a7d4be74995a54d6b2522f8ba896eb3/src/blocks/net.rs#L92-L104

**Comment by ammgws** [comment]
Looks like the docs were out of date

**Comment by BourgondAries** [comment]
Thank you!
