### ISSUE TITLE
Don't fail if no backlight device is available

### ISSUE THREAD

**Issue by marzzzello** [greshake/i3status-rust#978]
Related to #568  
If there is no device under `/sys/class/backlight` and there is no device specified in the block, then the bar should not fail.
Instead the block should be hidden.

```toml
[[block]]
block = "backlight"
```

**Comment by ammgws** [comment]
Is this purely so you can share the same config between, for example, a laptop and a desktop? Or are there cases when the backlight is actually unavailable?

**Comment by marzzzello** [comment]
Yes, needed for shared config. I don't know of cases where the backlight device disappears

**Comment by ammgws** [comment]
I think I would accept a PR for that, though it might not be trivial to implement.

**Comment by PremiumUsername** [comment]
> Is this purely so you can share the same config between, for example, a laptop and a desktop? Or are there cases when the backlight is actually unavailable?

There are such user cases: 

If you have a portable monitor, and you use the driver for ddc in order to enable brightness control it's very convenient to use the brightness block to control the brightness for that monitor when it is connected.

**Comment by ammgws** [comment]
@marzzzello What does `actual_brightness` report for your case?

Need to figure out the best way to make this possible.

**Comment by marzzzello** [comment]
> @marzzzello What does `actual_brightness` report for your case?

It goes from 0 (black screen) to 1515 (100%)

**Comment by ammgws** [comment]
Sorry I meant in the case when the backlight/monitor is absent.

**Comment by marzzzello** [comment]
How should I test that? My monitor is integrated in the laptop

**Comment by ammgws** [comment]
Actually don't worry, I mixed up your case with the other one in this thread. Your issue is due to sharing configs with another PC that doesn't have a backlight.

**Comment by ammgws** [comment]
Does this still happen with master (v0.30)?

**Comment by MaxVerevkin** [comment]
> Instead the block should be hidden.

This is possible:

```toml
[[block]]
block = "backlight"
error_format = ""
```
