### ISSUE TITLE
block idea: Fifo/Local Messages

### ISSUE THREAD

**Issue by BourgondAries** [greshake/i3status-rust#979]
A block that shows any line sent to a fifo.

Use-case: When changing i3's pane mode (tabbed/horizontal/vertical/stacked), I normally send a message using `notify-send` just as a little feedback mechanism, however, this overlaps completely with the (top) i3bar and is rather ugly. It would be better if this kind of feedback were integrated into i3status-rust.

Solution: Instead just echo a line into a local fifo and show it integrated into `i3status-rust` for a user-defined amount of time, or keep it around (depending on the block config).

**Comment by GladOSkar** [comment]
Wouldn't this be very easy with a custom block? Just write your message to a temp file and cat it in the custom block, optionally send a signal to reload immediately. Or use a custom dbus block which is probably even easier

**Comment by BourgondAries** [comment]
@GladOSkar it's a bit of bookkeeping to use a custom block, for instance, clearing the block 3 seconds after the last update becomes a bit of work. You'd need some kind of scheduler such that if 2 notifies happen in short succession, that the first doesn't clear the second. Also requires a script to notify and send a signal for updating.

By having a dedicated block, this is all made easier for the user, it's as simple as `echo Hey > /tmp/myfifo`.

**Comment by GladOSkar** [comment]
Sounds like the custom dbus block would be perfect for that

**Comment by BourgondAries** [comment]
> Sounds like the [custom dbus](https://github.com/greshake/i3status-rust/blob/master/blocks.md#custom-dbus) block would be perfect for that:
> 
> ```
> [[block]]
> block = "custom_dbus"
> name = "MyDBus"
> ```
> 
> `qdbus i3.status.rs /MyDBus i3.status.rs.SetStatus Hey`

That looks useful, is there any easy way to clear this based on time, without potentially clearing right after a new message has been set?

**Comment by GladOSkar** [comment]
Nah i can only think of

```
qdbus i3.status.rs /MyDBus i3.status.rs.SetStatus Hey
sleep 3
qdbus i3.status.rs /MyDBus i3.status.rs.SetStatus There
```

**Comment by ammgws** [comment]
Hmm would a new config for the custom blocks be useful?

i.e. "clear_timeout" or something which will clear the output of the block after x seconds.

Combined with the hide when empty option it could allow the block to act as an adhoc notification

**Comment by ammgws** [comment]
Or maybe the timeout could be specified via the existing JSON option. That way you could customise it on the fly.

**Comment by BourgondAries** [comment]
@ammgws might be best to leave configurable whether we want the json msg to specify a per-message timeout or having a block-wide timeout.

**Comment by ammgws** [comment]
@BourgondAries I think #1329 should cover your use-case, what do you think?

**Comment by BourgondAries** [comment]
@ammgws seems reasonable. I'll close this as I have a solution (just run a script periodically from crontab and read it every hour or so in i3status).
