### ISSUE TITLE
CustomDBus block icon and state args should be optional

### ISSUE THREAD

**Issue by ammgws** [greshake/i3status-rust#983]
The docs say they are optional but if you try to set just the text you will encounter an error:

```sh
>busctl --user call i3.status.rs /test i3.status.rs SetStatus sss just-some-text
Too few parameters for signature.
```

Need to check whether D-Bus actually allows optional paramters, and if so then update the block so that it can do it that way. Otherwise need to update the docs to make them all required.

**Comment by diegodorado** [comment]
You can make the call as
`busctl --user call i3.status.rs /test i3.status.rs SetStatus s just-some-text` and it works

**Comment by ammgws** [comment]
D'oh! That was pretty obvious.

Thanks!
