### ISSUE TITLE
Processes spawned by xrandr block on brightness updates are not cleaned up properly

### ISSUE THREAD

**Issue by CyanoKobalamyne** [greshake/i3status-rust#988]
After I change the brightness by scrolling on the block, many new `xrandr` processes are spawned. They seem to be zombies ("Z" notation in `ps`/`top`/`htop`).

**Comment by ammgws** [comment]
Should be fixed if you make a similar change:

https://github.com/greshake/i3status-rust/commit/75204ed5fdeee85170dc0fed35e7851716753285

Need to go through and check if there are any other places left that need fixing.

**Comment by ammgws** [comment]
Also you wouldn't happen to also experience https://github.com/greshake/i3status-rust/issues/668?

**Comment by ammgws** [comment]
Can you try #990? I don't have an X system to test with.

**Comment by CyanoKobalamyne** [comment]
I haven't noticed any performance degradation like those mentioned in #668. (I'm also on Arch btw.)

I just checked out #990 and it fixed the issue!
