### ISSUE TITLE
Extremely High CPU usage when using the music block + mpd

### ISSUE THREAD

**Issue by michaelmrose** [greshake/i3status-rust#989]
I'm running the current up to date version of project trident which is 99% Void Linux with i3wm. I installed i3status-rust 0.14.2_1 via xbps-install. I experienced no problems running the example config but noticed an issue after creating my own config. Very specifically the xorg process would slowly grow in average CPU usage until it consumed most of the systems resources. The issue is neither immediate nor consistent. It takes around 20 minutes to become disruptive but can be seen spiking prior to that. Eventually getting to the point where it spikes to 100% of cpu and then stays there for minutes making it very difficult to use the computer.

 I first killed everything nonessential one at a time. Having almost nothing running in the background but i3wm itself and system services. The problem immediately terminated when killing i3status-rs. Thereafter I narrowed it down to my music block with the following config.

    '''[[block]]
    block = "music"
    player = "mpd"
    buttons = ["prev", "play", "next"]
    smart_trim = true
    dynamic_width = true
    max_width = 80'''

Disabling this and using a custom block to get the status via mpc and updating with a signal totally avoids the issue.Interestingly this is evident even if mpd isn't running.

**Comment by ammgws** [comment]
Can you try 0.14.3?

#906 made some improvements that may have fixed your issue.

If it still occurs with 0.14.3 then strace may be useful to see what the process is actually doing.

**Comment by michaelmrose** [comment]
As of version i3status-rs 0.14.3 (commit 2b63bcd 2020-12-23) This is no longer an issue

**Comment by ammgws** [comment]
Awesome!

**Comment by michaelmrose** [comment]
Thank you for your prompt and friendly response and for your software. I find it easy to configure and a pleasure to use.
