### ISSUE TITLE
Net block not displaying extended characters of SSID correctly.

### ISSUE THREAD

**Issue by mkvarnst** [greshake/i3status-rust#999]
Hi.
I have noticed that the net block does not display the extended characters from my SSID as I would expect it. 

I have a SSID that contains extended characters:
`GULAHUSETS VÄNNER`
but the net block displays it like:
`GULAHUSETS V\xc3\x84N`

If I switch to the Network Manager it displays the SSID correctly.
Please see the attached screenshots for comparison.

Net:
![2021-01-06-net_module_utf8](https://user-images.githubusercontent.com/1787840/103750558-45bdec80-5007-11eb-966f-0ff56b9ba98b.png)

NetworkManager:
![2021-01-06-networkmanager_module_utf8](https://user-images.githubusercontent.com/1787840/103751090-0ba11a80-5008-11eb-9b4a-419630ed398f.png)

Any idea on where I should start looking?

**Comment by ammgws** [comment]
https://github.com/greshake/i3status-rust/pull/995 ?

**Comment by mkvarnst** [comment]
Yes.  Didn't see that one.  Sorry about that.
